	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, GRAY, GREEN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, RED, WATER, WATER, ROOF, ROOF, ROOF, ROOF, GRAY
	tilepal 1, GRAY, GRAY, GRAY, ROOF, RED, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, ROOF, ROOF, ROOF, ROOF, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, RED, RED, RED
	tilepal 1, RED, ROOF, ROOF, ROOF, ROOF, ROOF, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, RED, RED, RED, WATER, WATER, WATER, RED
	tilepal 1, RED, RED, ROOF, RED, RED, ROOF, RED, RED
	tilepal 1, RED, ROOF, ROOF, RED, RED, RED, ROOF, ROOF
	tilepal 1, RED, RED, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
