	tilepal 0, GRAY, BROWN, GRAY, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 0, WATER, BROWN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, GRAY, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, RED, RED, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, RED, WATER, WATER
	tilepal 1, RED, RED, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, BROWN, BROWN, BROWN, GRAY, WATER, WATER
	tilepal 1, RED, RED, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, GRAY, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
