	tilepal 0, GRAY, GRAY, WATER, WATER, RED, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, GRAY, WATER, WATER, RED, BROWN, BROWN, WATER
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, WATER, WATER
	tilepal 0, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, WATER, WATER, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GRAY, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, RED, RED

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, BROWN, BROWN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, BROWN, BROWN, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, RED, RED, RED, RED, RED, WATER, WATER
	tilepal 1, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
