	tilepal 0, GRAY, GRAY, GREEN, GREEN, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GREEN, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, WATER, WATER
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, WATER, GREEN, GREEN, WATER, BROWN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, RED, RED, YELLOW, YELLOW, WATER, WATER, BROWN, BROWN
	tilepal 1, WATER, WATER, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, RED, RED, YELLOW, YELLOW, WATER, WATER, BROWN, BROWN
	tilepal 1, WATER, WATER, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 1, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
