	tilepal 0, GRAY, BROWN, BROWN, RED, YELLOW, GREEN, BROWN, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, WATER, GREEN, BROWN, BROWN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, YELLOW, BROWN, GRAY, BROWN, YELLOW, YELLOW, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GRAY, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, YELLOW
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, BROWN, BROWN, RED
	tilepal 1, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, WATER, GREEN, BROWN, BROWN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, YELLOW, BROWN, GRAY, BROWN, YELLOW, YELLOW, GRAY
	tilepal 0, GRAY, BROWN, BROWN, GRAY, GREEN, GREEN, GREEN, WATER
	tilepal 0, GREEN, GREEN, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY
