	tilepal 0, GRAY, WATER, ROOF, ROOF, RED, RED, RED, RED
	tilepal 0, WATER, WATER, ROOF, ROOF, RED, RED, WATER, WATER
	tilepal 0, WATER, WATER, ROOF, ROOF, RED, RED, RED, RED
	tilepal 0, WATER, WATER, ROOF, ROOF, RED, RED, WATER, WATER
	tilepal 0, GRAY, GREEN, GREEN, GRAY, ROOF, GRAY, RED, RED
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, RED, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, RED, RED, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, BROWN, BROWN, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN

rept 8
	db $ff
endr

	tilepal 1, RED, RED, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
