	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, RED, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, RED, RED, GRAY, GRAY, WATER, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, ROOF, ROOF, GRAY, GRAY, YELLOW, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 0, GREEN, ROOF, ROOF, WATER, WATER, GREEN, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, YELLOW, YELLOW, WATER, WATER, BROWN, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, YELLOW, YELLOW, GRAY, GRAY, BROWN, YELLOW, YELLOW

rept 16
	db $ff
endr

	tilepal 1, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
