	tilepal 0, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, GREEN, GREEN, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, ROOF, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
