	tilepal 0, GRAY, BROWN, BROWN, RED, RED, RED, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, RED, RED, RED, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, BROWN, RED, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY, RED, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, RED, RED, ROOF, ROOF, GRAY, GRAY, GREEN, WATER
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, RED, RED, YELLOW, YELLOW, GRAY, GRAY, WATER, ROOF
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
