	tilepal 0, GRAY, WATER, GREEN, GREEN, GREEN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, RED, RED, RED, GRAY, BROWN, GREEN, GREEN
	tilepal 0, RED, RED, ROOF, GREEN, GREEN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, RED, RED, RED, GRAY, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, WATER, WATER, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GREEN, GREEN, RED, RED, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, TEXT, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
