	tilepal 0, GRAY, WATER, GREEN, GREEN, GREEN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, GRAY, BROWN, GREEN, GREEN
	tilepal 0, RED, RED, GREEN, GREEN, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, GRAY, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, WATER, WATER, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, RED, RED, TEXT, RED
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT, TEXT
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
