	tilepal 0, ROOF, GREEN, GREEN, RED, GREEN, GREEN, GREEN, BROWN
	tilepal 0, BROWN, YELLOW, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GREEN, RED, WATER, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, ROOF
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal 0, WATER, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN

rept 8
	db $ff
endr

	tilepal 1, GREEN, ROOF, ROOF, GREEN, GREEN, ROOF, ROOF, GREEN
	tilepal 1, YELLOW, ROOF, ROOF, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED
	tilepal 1, GREEN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, GREEN, BROWN, BROWN, BROWN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
