	tilepal 0, ROOF, GREEN, GREEN, RED, GRAY, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, GREEN, GREEN, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, YELLOW, BROWN, BROWN
	tilepal 0, GREEN, GREEN, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, WATER, GREEN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, BROWN, GRAY, BROWN, BROWN
	tilepal 0, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GREEN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GREEN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, GREEN, BROWN, BROWN, GREEN, ROOF, BROWN, BROWN, ROOF
