	tilepal 0, GRAY, GRAY, BROWN, RED, BROWN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, RED, RED, GREEN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, RED, BROWN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GREEN, RED, RED, GREEN, GRAY, RED, RED
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, GREEN, BROWN, RED, RED
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, RED, RED
	tilepal 0, RED, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, WATER, ROOF, ROOF, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, YELLOW, RED, YELLOW, RED, GREEN, GREEN, BROWN, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, YELLOW, RED, YELLOW, RED, GREEN, GREEN, BROWN, ROOF
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, YELLOW, RED, YELLOW, RED, WATER, WATER, RED, RED
	tilepal 1, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, RED, RED, YELLOW, YELLOW, WATER, WATER, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, RED, RED, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
