	tilepal 0, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GREEN, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, WATER, WATER
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, WATER, GREEN, GREEN, WATER, BROWN, BROWN, GRAY, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, RED, RED, YELLOW, YELLOW, WATER, WATER, BROWN, BROWN
	tilepal 0, WATER, WATER, GREEN, GREEN, RED, RED, RED, RED

rept 8
	db $ff
endr

	tilepal 1, RED, RED, YELLOW, YELLOW, WATER, WATER, BROWN, BROWN
	tilepal 1, WATER, WATER, GREEN, GREEN, RED, RED, RED, RED
	tilepal 1, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, RED, RED, GREEN, GREEN, BROWN
	tilepal 1, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, BROWN, RED, RED, GREEN, GREEN, ROOF
