	tilepal 0, ROOF, GREEN, GREEN, GREEN, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GREEN, GREEN, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GREEN, GREEN, YELLOW, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, RED, RED, RED, RED, RED
	tilepal 0, BROWN, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, RED, RED, RED, ROOF, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN

rept 8
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, ROOF, RED, ROOF, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, WATER, WATER, WATER, ROOF, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, RED, GRAY, GRAY, RED, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, ROOF
