	tilepal 0, GRAY, GRAY, GRAY, RED, RED, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, GRAY, GRAY, RED, RED, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, GRAY, GRAY, RED, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
	tilepal 1, WATER, WATER, WATER, RED, RED, RED, BROWN, BROWN
	tilepal 1, BROWN, GRAY, BROWN, BROWN