	tilepal 0, GRAY, BROWN, WATER, WATER, RED, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, WATER, WATER, RED, BROWN, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, RED, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, YELLOW, GRAY, BROWN, BROWN, BROWN, BROWN, RED, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, RED, RED, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, TEXT
	tilepal 1, GRAY, GRAY, GRAY
