	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, BROWN, BROWN, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, WATER, WATER, ROOF, ROOF, WATER, WATER, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, WATER, WATER, ROOF, ROOF, GRAY, GRAY, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, WATER, GRAY, GRAY, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, GREEN
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
