	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, RED, GRAY, BROWN
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, GRAY, BROWN
	tilepal 0, GRAY, RED, GRAY, RED, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, RED, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, ROOF, BROWN, WATER, WATER, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED
	tilepal 0, ROOF, BROWN, BROWN, ROOF, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, WATER, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, RED, RED, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, GREEN, GREEN, ROOF, ROOF, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, ROOF, ROOF
	tilepal 1, RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, RED, ROOF, ROOF
	tilepal 1, ROOF, RED, ROOF, RED, ROOF, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
