	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, RED, GRAY, BROWN
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, GRAY, BROWN
	tilepal 0, GRAY, GREEN, GRAY, BROWN, BROWN, ROOF, GREEN, GREEN
	tilepal 0, BROWN, BROWN, RED, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, GRAY, GRAY, BROWN, WATER, WATER, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, GRAY, BROWN, BROWN, GRAY, RED, RED, RED, RED
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, RED, RED, RED, RED
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, BROWN, BROWN, GREEN
