	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, RED, GRAY, BROWN
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, GRAY, BROWN
	tilepal 0, GRAY, GREEN, GRAY, BROWN, BROWN, YELLOW, GREEN, GREEN
	tilepal 0, BROWN, BROWN, RED, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN
	tilepal 0, BROWN, BROWN, WATER, WATER, BROWN, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, BROWN, WATER, WATER, BROWN, YELLOW, YELLOW, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, WATER, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED

rept 8
	db $ff
endr

	tilepal 1, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED
	tilepal 1, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, YELLOW
	tilepal 1, YELLOW, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, YELLOW
	tilepal 1, YELLOW, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
