	tilepal 0, ROOF, GREEN, GRAY, RED, GRAY, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, YELLOW, WATER, WATER
	tilepal 0, ROOF, ROOF, ROOF, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED
	tilepal 0, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED
	tilepal 0, RED, RED, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, WATER, WATER, RED
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, YELLOW
	tilepal 0, YELLOW, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal_skip
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, YELLOW
	tilepal 1, YELLOW, GREEN, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, GREEN, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER
