	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, BROWN, BROWN, GRAY
	tilepal 0, BROWN, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, RED, WATER, BROWN, BROWN, GRAY
	tilepal 0, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, YELLOW, GREEN, GREEN
	tilepal 0, GRAY, ROOF, ROOF, ROOF, ROOF, BROWN, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, BROWN, BROWN, BROWN, ROOF, ROOF, BROWN, BROWN
	tilepal 0, GRAY, ROOF, ROOF, ROOF, ROOF, BROWN, GRAY, GRAY
	tilepal 0, GRAY, WATER, GRAY, GRAY, ROOF, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY
	tilepal 1, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, ROOF, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
