	tilepal 0, GRAY, WATER, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, WATER, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, WATER, WATER, ROOF, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, WATER, WATER, WATER, WATER, RED, BROWN, BROWN, GRAY
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, ROOF, GREEN, GREEN, GREEN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, ROOF, ROOF, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
