	tilepal 0, ROOF, BROWN, ROOF, WATER, RED, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, RED, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, WATER, WATER, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, RED, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, YELLOW, RED, BROWN, BROWN
	tilepal 0, BROWN, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, BROWN, BROWN
	tilepal 0, BROWN, RED, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
