	tilepal 0, ROOF, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, WATER, RED, GRAY, GRAY, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, RED, ROOF, ROOF, GRAY, YELLOW
	tilepal 0, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 0, WATER, WATER, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, GREEN, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, YELLOW, YELLOW, YELLOW, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, RED, RED, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GRAY
	tilepal 1, GRAY, GREEN, GREEN, RED, RED, WATER, WATER, WATER
	tilepal 1, GRAY, GRAY, GRAY, YELLOW, YELLOW, YELLOW, ROOF, GRAY
	tilepal 1, GRAY, GRAY, WATER, GRAY, GRAY, ROOF, YELLOW, WATER
	tilepal 1, GRAY, GRAY, GRAY, RED, RED, RED, RED, RED
	tilepal 1, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, RED, RED, RED, ROOF, RED, RED, RED
	tilepal 1, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, WATER, WATER, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, WATER, GRAY, WATER, WATER, WATER, ROOF
