	tilepal 0, GRAY, BROWN, BROWN, BROWN, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 0, ROOF, GREEN, GREEN, GREEN, RED, RED, GRAY, GRAY

rept 8
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, GREEN, GREEN, GREEN, RED, RED, GRAY, GRAY
	tilepal 1, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF
