	tilepal 0, ROOF, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, RED, RED, WATER, ROOF
	tilepal 0, RED, WATER, ROOF, WATER, WATER, WATER, RED, RED
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, RED, WATER, WATER, WATER
	tilepal 0, RED, RED, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, RED, WATER, GRAY, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, RED, RED
	tilepal 0, YELLOW, YELLOW, WATER, WATER, GRAY, RED, RED, GRAY
	tilepal 0, RED, RED, WATER, WATER, WATER, WATER, RED, RED
	tilepal 0, YELLOW, YELLOW, WATER, WATER, GRAY, GRAY, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, WATER, RED, RED, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, WATER

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, RED, RED, GRAY, GRAY, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, WATER, RED, WATER, ROOF, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
