	tilepal 0, GRAY, ROOF, RED, RED, RED, RED, WATER, WATER
	tilepal 0, RED, RED, RED, GRAY, RED, RED, RED, RED
	tilepal 0, RED, ROOF, RED, RED, RED, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, RED, RED, WATER, WATER, RED, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, RED, RED, RED, RED
	tilepal 0, RED, RED, WATER, WATER, GRAY, GRAY, WATER, GRAY
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, RED, RED, GRAY
	tilepal 0, RED, RED, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED
	tilepal 0, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, GREEN, GREEN, BROWN, BROWN, ROOF, RED, WATER, WATER
	tilepal 1, RED, RED, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 1, GREEN, GREEN, BROWN, BROWN, ROOF, GRAY, WATER, WATER
	tilepal 1, RED, RED, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, RED, RED, RED, WATER
	tilepal 1, WATER, RED, ROOF, ROOF, WATER, WATER, WATER, WATER
	tilepal 1, BROWN, BROWN, GRAY, GRAY, GRAY, RED, RED, GRAY
	tilepal 1, GRAY, ROOF, ROOF, ROOF, GRAY, GRAY, RED, GRAY
