	tilepal 0, GRAY, ROOF, ROOF, WATER, WATER, RED, RED, RED
	tilepal 0, WATER, WATER, RED, RED, YELLOW, YELLOW, WATER, WATER
	tilepal 0, WATER, ROOF, ROOF, WATER, WATER, RED, RED, RED
	tilepal 0, WATER, WATER, RED, RED, YELLOW, YELLOW, WATER, WATER
	tilepal 0, RED, GRAY, GRAY, RED, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 0, RED, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, GRAY, WATER, WATER, WATER, GRAY, RED, RED, GRAY
	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, RED, GRAY

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, RED, RED, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, GREEN, GREEN
	tilepal 1, GRAY, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, ROOF, WATER, WATER, WATER, WATER, ROOF, BROWN, BROWN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
