	tilepal 0, ROOF, WATER, WATER, GRAY, GRAY, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, ROOF, ROOF, RED, RED, RED, GRAY
	tilepal 0, ROOF, WATER, WATER, ROOF, WATER, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, ROOF, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, RED, ROOF, ROOF, ROOF
	tilepal 0, ROOF, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN

rept 8
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, GRAY, GRAY, ROOF, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GRAY, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GRAY, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, RED, RED, ROOF, ROOF, RED, RED
