	tilepal 0, GRAY, RED, RED, WATER, WATER, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, WATER, RED, WATER, WATER, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, ROOF, ROOF, GRAY, GRAY, BROWN, GRAY, GRAY, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, GRAY, GRAY, BROWN
	tilepal 0, BROWN, GRAY, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 8
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, RED, YELLOW, YELLOW, RED
	tilepal 1, ROOF, RED, RED, ROOF, GRAY, GRAY, GRAY, GRAY
