	tilepal 0, TEXT, GRAY, RED, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, RED, WATER, WATER, RED, RED
	tilepal 0, GRAY, GRAY, RED, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, GRAY, GRAY, BROWN, BROWN, TEXT
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, GRAY, GRAY, TEXT
