	tilepal 0, GRAY, GRAY, WATER, WATER, WATER, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, WATER, WATER, WATER, WATER, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, RED, BROWN
	tilepal 0, BROWN, ROOF, ROOF, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, RED, BROWN
	tilepal 0, BROWN, ROOF, ROOF
