; GetCGBLayout arguments (see engine/gfx/cgb_layouts.asm)
	const_def
	const CGB_RAM
	const CGB_BATTLE_GRAYSCALE
	const CGB_BATTLE_COLORS
	const CGB_POKEGEAR_PALS
	const CGB_SUMMARY_SCREEN_HP_PALS
	const CGB_POKEDEX
	const CGB_POKEDEX_PREPARE_ONLY
	const CGB_SLOT_MACHINE
	const CGB_PLAIN
	const CGB_MAPPALS
	const CGB_PARTY_MENU
	const CGB_EVOLUTION
	const CGB_MOVE_LIST
	const CGB_BUYMENU_PALS
	const CGB_PACKPALS
	const CGB_TRAINER_CARD
	const CGB_TRAINER_CARD_2
	const CGB_TRAINER_CARD_3
	const CGB_BILLS_PC
	const CGB_UNOWN_PUZZLE
	const CGB_GAMEFREAK_LOGO
	const CGB_TRADE_TUBE
	const CGB_INTRO_PALS
	const CGB_INTRO_GENDER_PALS
	const CGB_PLAYER_OR_MON_FRONTPIC_PALS
	const CGB_TRAINER_OR_MON_FRONTPIC_PALS
	const CGB_JUDGE_SYSTEM
	const CGB_NAMING_SCREEN
	const CGB_WRITE_MAIL
	const CGB_READ_MAIL
	const CGB_FLY_MAP
	const CGB_NEW_DIPLOMA
DEF NUM_CGB_LAYOUTS EQU const_value
