	const_def

	const ENGINE_RADIO_CARD ; $0
	const ENGINE_MAP_CARD
	const ENGINE_PHONE_CARD
	const ENGINE_EXPN_CARD
	const ENGINE_POKEGEAR

	const ENGINE_DAYCARE_MAN_HAS_EGG
	const ENGINE_DAYCARE_MAN_HAS_MON
	const ENGINE_DAYCARE_LADY_HAS_MON

	const ENGINE_MOM_SAVING_MONEY ; $8
	const ENGINE_DST

	const ENGINE_POKEDEX
	const ENGINE_UNOWN_DEX
	const ENGINE_POKERUS
	const ENGINE_ROCKET_SIGNAL_ON_CH20
	const ENGINE_CREDITS_SKIP
	const ENGINE_BUG_CONTEST_ON
	const ENGINE_ROCKETS_IN_RADIO_TOWER ; $10
	const ENGINE_SAFARI_GAME
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_SEEN_SHAMOUTI_ISLAND
	const ENGINE_BIKE_SHOP_CALL_ENABLED
	const ENGINE_GIVE_POKERUS
	const ENGINE_EXORCISED_LAV_RADIO_TOWER
	const ENGINE_ROCKETS_IN_MAHOGANY

	const ENGINE_STRENGTH_ACTIVE ; $18
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL
	const ENGINE_AUTOSURF_ACTIVE
	const ENGINE_ROCK_SMASH_ACTIVE
	const ENGINE_HEADBUTT_ACTIVE
	const ENGINE_AUTOWHIRLPOOL_ACTIVE
	const ENGINE_AUTOWATERFALL_ACTIVE
	const ENGINE_AUTOCUT_ACTIVE ; $20

	const ENGINE_ZEPHYRBADGE
	const ENGINE_HIVEBADGE
	const ENGINE_PLAINBADGE
	const ENGINE_FOGBADGE
	const ENGINE_MINERALBADGE
	const ENGINE_STORMBADGE
	const ENGINE_GLACIERBADGE
	const ENGINE_RISINGBADGE ; $28

	const ENGINE_BOULDERBADGE
	const ENGINE_CASCADEBADGE
	const ENGINE_THUNDERBADGE
	const ENGINE_RAINBOWBADGE
	const ENGINE_MARSHBADGE
	const ENGINE_SOULBADGE
	const ENGINE_VOLCANOBADGE
	const ENGINE_EARTHBADGE ; $30

	const ENGINE_UNLOCKED_UNOWNS_1
	const ENGINE_UNLOCKED_UNOWNS_2
	const ENGINE_UNLOCKED_UNOWNS_3
	const ENGINE_UNLOCKED_UNOWNS_4
	const ENGINE_UNLOCKED_UNOWNS_5
	const ENGINE_UNLOCKED_UNOWNS_6
	const ENGINE_UNLOCKED_UNOWNS_7
	const ENGINE_UNLOCKED_UNOWNS_8 ; $38

	const ENGINE_FLYPOINT_PLAYERS_HOUSE
	const ENGINE_FLYPOINT_PALLET
	const ENGINE_FLYPOINT_VIRIDIAN
	const ENGINE_FLYPOINT_PEWTER
	const ENGINE_FLYPOINT_MT_MOON
	const ENGINE_FLYPOINT_CERULEAN
	const ENGINE_FLYPOINT_CERULEAN_CAPE
	const ENGINE_FLYPOINT_ROCK_TUNNEL ; $40
	const ENGINE_FLYPOINT_VERMILION
	const ENGINE_FLYPOINT_LAVENDER
	const ENGINE_FLYPOINT_SAFFRON
	const ENGINE_FLYPOINT_CELADON
	const ENGINE_FLYPOINT_FUCHSIA
	const ENGINE_FLYPOINT_CINNABAR
	const ENGINE_FLYPOINT_INDIGO_PLATEAU
	const ENGINE_FLYPOINT_NEW_BARK ; $48
	const ENGINE_FLYPOINT_CHERRYGROVE
	const ENGINE_FLYPOINT_VIOLET
	const ENGINE_FLYPOINT_UNION_CAVE
	const ENGINE_FLYPOINT_AZALEA
	const ENGINE_FLYPOINT_CIANWOOD
	const ENGINE_FLYPOINT_GOLDENROD
	const ENGINE_FLYPOINT_OLIVINE
	const ENGINE_FLYPOINT_ECRUTEAK ; $50
	const ENGINE_FLYPOINT_MAHOGANY
	const ENGINE_FLYPOINT_YELLOW_FOREST
	const ENGINE_FLYPOINT_LAKE_OF_RAGE
	const ENGINE_FLYPOINT_BLACKTHORN
	const ENGINE_FLYPOINT_SILVER_CAVE

	const ENGINE_LUCKY_NUMBER_SHOW

	const ENGINE_KURT_MAKING_BALLS
	const ENGINE_DAILY_BUG_CONTEST ; $58
	const ENGINE_SPECIAL_WILDDATA
	const ENGINE_VALERIE_MORNING_WALK
	const ENGINE_DAILY_UNUSED_1
	const ENGINE_SHUCKIE_GIVEN
	const ENGINE_GOLDENROD_UNDERGROUND_MERCHANT_CLOSED
	const ENGINE_FOUGHT_IN_TRAINER_HALL_TODAY

	const ENGINE_GYM_LEADER_REMATCH_1
	const ENGINE_GYM_LEADER_REMATCH_2 ; $60
	const ENGINE_GYM_LEADER_REMATCH_3
	const ENGINE_DAILY_PHOTOGRAPH
	const ENGINE_DAILY_SHRINE_VISIT
	const ENGINE_DAILY_MYSTERY_GIFT
	const ENGINE_RED_IN_MOUNT_SILVER
	const ENGINE_LEAF_IN_NAVEL_ROCK

	const ENGINE_BOUGHT_LEFTOVERS
	const ENGINE_TOOK_HYPER_TEST ; $68
	const ENGINE_CHERYL_DONE_TODAY
	const ENGINE_RILEY_DONE_TODAY
	const ENGINE_BUCK_DONE_TODAY
	const ENGINE_MARLEY_DONE_TODAY
	const ENGINE_MIRA_DONE_TODAY
	const ENGINE_ANABEL_DONE_TODAY

	const ENGINE_SEASHORE_SHELL_BELL
	const ENGINE_SHAMOUTI_RESTAURANT_CHALLENGE ; $70
	const ENGINE_FOUGHT_PSYCHIC_INVER
	const ENGINE_BOUGHT_MOOMOO_MILK
	const ENGINE_CHANGED_TRENDY_PHRASE
	const ENGINE_ALL_HIDDEN_GROTTOES
	const ENGINE_DAILY_UNUSED_2
	const ENGINE_DAILY_UNUSED_3

	const ENGINE_MT_MOON_SQUARE_CLEFAIRY
	const ENGINE_UNION_CAVE_LAPRAS ; $78
	const ENGINE_GOLDENROD_UNDERGROUND_GOT_HAIRCUT
	const ENGINE_GOLDENROD_MALL_5F_HAPPINESS_EVENT
	const ENGINE_TEA_IN_BLUES_HOUSE
	const ENGINE_INDIGO_PLATEAU_RIVAL_FIGHT
	const ENGINE_INDIGO_PLATEAU_LYRA_FIGHT
	const ENGINE_BUENAS_PASSWORD

	const ENGINE_BUENAS_PASSWORD_2
	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON ; $80

	const ENGINE_GAME_TIMER_PAUSE

	const ENGINE_PLAYER_IS_FEMALE

	const ENGINE_HAVE_EXAMINED_GS_BALL
	const ENGINE_HAVE_SILPHSCOPE2
	const ENGINE_HAVE_SHINY_CHARM

	const ENGINE_JACK
	const ENGINE_HUEY
	const ENGINE_GAVEN ; $88
	const ENGINE_BETH
	const ENGINE_JOSE
	const ENGINE_REENA
	const ENGINE_JOEY
	const ENGINE_WADE
	const ENGINE_RALPH
	const ENGINE_LIZ
	const ENGINE_ANTHONY ; $90
	const ENGINE_TODD
	const ENGINE_GINA
	const ENGINE_ARNIE
	const ENGINE_ALAN
	const ENGINE_DANA
	const ENGINE_CHAD
	const ENGINE_TULLY
	const ENGINE_BRENT ; $98
	const ENGINE_TIFFANY
	const ENGINE_VANCE
	const ENGINE_WILTON
	const ENGINE_PARRY
	const ENGINE_ERIN

	const ENGINE_BEVERLY_HAS_NUGGET
	const ENGINE_JOSE_HAS_STAR_PIECE
	const ENGINE_WADE_HAS_ITEM ; $a0
	const ENGINE_GINA_HAS_LEAF_STONE
	const ENGINE_ALAN_HAS_FIRE_STONE
	const ENGINE_DANA_HAS_THUNDERSTONE
	const ENGINE_DEREK_HAS_NUGGET
	const ENGINE_TULLY_HAS_WATER_STONE
	const ENGINE_TIFFANY_HAS_PINK_BOW
	const ENGINE_WILTON_HAS_ITEM

	const ENGINE_JACK_MONDAY_MORNING ; $a8
	const ENGINE_HUEY_WEDNESDAY_NIGHT
	const ENGINE_GAVEN_THURSDAY_MORNING
	const ENGINE_BETH_FRIDAY_AFTERNOON
	const ENGINE_JOSE_SATURDAY_NIGHT
	const ENGINE_REENA_SUNDAY_MORNING
	const ENGINE_JOEY_MONDAY_AFTERNOON
	const ENGINE_WADE_TUESDAY_NIGHT
	const ENGINE_RALPH_WEDNESDAY_MORNING ; $b0
	const ENGINE_LIZ_THURSDAY_AFTERNOON
	const ENGINE_ANTHONY_FRIDAY_NIGHT
	const ENGINE_TODD_SATURDAY_MORNING
	const ENGINE_GINA_SUNDAY_AFTERNOON
	const ENGINE_ARNIE_TUESDAY_MORNING
	const ENGINE_ALAN_WEDNESDAY_AFTERNOON
	const ENGINE_DANA_THURSDAY_NIGHT
	const ENGINE_CHAD_FRIDAY_MORNING ; $b8
	const ENGINE_TULLY_SUNDAY_NIGHT
	const ENGINE_BRENT_MONDAY_MORNING
	const ENGINE_TIFFANY_TUESDAY_AFTERNOON
	const ENGINE_VANCE_WEDNESDAY_NIGHT
	const ENGINE_WILTON_THRUSDAY_MORNING
	const ENGINE_PARRY_FRIDAY_AFTERNOON
	const ENGINE_ERIN_SATURDAY_NIGHT

	const ENGINE_KRIS_IN_CABLE_CLUB ; $c0

	const ENGINE_DUNSPARCE_SWARM
	const ENGINE_YANMA_SWARM

	const ENGINE_READ_FALKNER_JOURNAL
	const ENGINE_READ_BUGSY_JOURNAL
	const ENGINE_READ_WHITNEY_JOURNAL
	const ENGINE_READ_MORTY_JOURNAL
	const ENGINE_READ_CHUCK_JOURNAL
	const ENGINE_READ_JASMINE_JOURNAL ; $c8
	const ENGINE_READ_PRYCE_JOURNAL
	const ENGINE_READ_CLAIR_JOURNAL

	const ENGINE_READ_BROCK_JOURNAL
	const ENGINE_READ_MISTY_JOURNAL
	const ENGINE_READ_LT_SURGE_JOURNAL
	const ENGINE_READ_ERIKA_JOURNAL
	const ENGINE_READ_JANINE_JOURNAL
	const ENGINE_READ_SABRINA_JOURNAL ; $d0
	const ENGINE_READ_BLAINE_JOURNAL
	const ENGINE_READ_BLUE_JOURNAL

	const ENGINE_READ_WILL_JOURNAL
	const ENGINE_READ_KOGA_JOURNAL
	const ENGINE_READ_BRUNO_JOURNAL
	const ENGINE_READ_KAREN_JOURNAL
	const ENGINE_READ_LANCE_JOURNAL
	const ENGINE_READ_RED_JOURNAL ; $d8
	const ENGINE_READ_GREEN_JOURNAL
	const ENGINE_READ_PROF_OAK_JOURNAL

	const ENGINE_READ_PROF_ELM_JOURNAL
	const ENGINE_READ_PROF_IVY_JOURNAL
	const ENGINE_READ_PROF_WESTWOOD_JOURNAL
	const ENGINE_READ_GIOVANNI_JOURNAL
	const ENGINE_READ_LORELEI_JOURNAL
	const ENGINE_READ_AGATHA_JOURNAL ; $e0
	const ENGINE_READ_BILL_JOURNAL
	const ENGINE_READ_KURT_JOURNAL

	const ENGINE_READ_MR_FUJI_JOURNAL

	const ENGINE_JUDGE_MACHINE

NUM_ENGINE_FLAGS EQU const_value
