	const_def
	const NO_ITEM      ; 00

	const POKE_BALL    ; 01
	const GREAT_BALL   ; 02
	const ULTRA_BALL   ; 03
	const MASTER_BALL  ; 04

	const SAFARI_BALL  ; 05

	const LEVEL_BALL   ; 06
	const LURE_BALL    ; 07
	const MOON_BALL    ; 08
	const FRIEND_BALL  ; 09
	const FAST_BALL    ; 0a
	const HEAVY_BALL   ; 0b
	const LOVE_BALL    ; 0c

	const PARK_BALL    ; 0d

	const REPEAT_BALL  ; 0e
	const TIMER_BALL   ; 0f
	const NEST_BALL    ; 10
	const NET_BALL     ; 11
	const DIVE_BALL    ; 12
	const LUXURY_BALL  ; 13
	const HEAL_BALL    ; 14
	const QUICK_BALL   ; 15
	const DUSK_BALL    ; 16
	const PREMIER_BALL ; 17
	const CHERISH_BALL ; 18

	const POTION       ; 19
	const SUPER_POTION ; 1a
	const HYPER_POTION ; 1b
	const MAX_POTION   ; 1c

	const ANTIDOTE     ; 1d
	const BURN_HEAL    ; 1e
	const PARALYZEHEAL ; 1f
	const AWAKENING    ; 20
	const ICE_HEAL     ; 21
	const FULL_HEAL    ; 22
	const FULL_RESTORE ; 23

	const REVIVE       ; 24
	const MAX_REVIVE   ; 25

	const ETHER        ; 26
	const MAX_ETHER    ; 27
	const ELIXIR       ; 28
	const MAX_ELIXIR   ; 29

	const HP_UP        ; 2a
	const PROTEIN      ; 2b
	const IRON         ; 2c
	const CARBOS       ; 2d
	const CALCIUM      ; 2e
	const ZINC         ; 2f
	const RARE_CANDY   ; 30
	const PP_UP        ; 31
	const PP_MAX       ; 32

	const FRESH_WATER  ; 33
	const SODA_POP     ; 34
	const LEMONADE     ; 35
	const MOOMOO_MILK  ; 36
	const RAGECANDYBAR ; 37

	const SACRED_ASH   ; 38
	const ENERGYPOWDER ; 39
	const ENERGY_ROOT  ; 3a
	const HEAL_POWDER  ; 3b
	const REVIVAL_HERB ; 3c

	const X_ATTACK     ; 3d
	const X_DEFEND     ; 3e
	const X_SPEED      ; 3f
	const X_SPCL_ATK   ; 40
	const X_SPCL_DEF   ; 41
	const X_ACCURACY   ; 42
	const DIRE_HIT     ; 43
	const GUARD_SPEC   ; 44

	const REPEL        ; 45
	const SUPER_REPEL  ; 46
	const MAX_REPEL    ; 47
	const ESCAPE_ROPE  ; 48
	const POKE_DOLL    ; 49

	const ABILITY_CAP  ; 4a

	const LEAF_STONE   ; 4b
	const FIRE_STONE   ; 4c
	const WATER_STONE  ; 4d
	const THUNDERSTONE ; 4e
	const MOON_STONE   ; 4f
	const SUN_STONE    ; 50
	const DUSK_STONE   ; 51
	const SHINY_STONE  ; 52
	const ICE_STONE    ; 53
	const EVERSTONE    ; 54

	const BICYCLE      ; 55
	const OLD_ROD      ; 56
	const GOOD_ROD     ; 57
	const SUPER_ROD    ; 58
	const COIN_CASE    ; 59
	const ITEMFINDER   ; 5a
	const EXP_SHARE    ; 5b
	const MYSTERY_EGG  ; 5c
	const SQUIRTBOTTLE ; 5d
	const SECRETPOTION ; 5e
	const RED_SCALE    ; 5f
	const CARD_KEY     ; 60
	const BASEMENT_KEY ; 61
	const S_S_TICKET   ; 62
	const PASS         ; 63
	const MACHINE_PART ; 64
	const LOST_ITEM    ; 65
	const RAINBOW_WING ; 66
	const SILVER_WING  ; 67
	const CLEAR_BELL   ; 68
	const GS_BALL      ; 69
	const BLUE_CARD    ; 6a
	const ORANGETICKET ; 6b
	const MYSTICTICKET ; 6c
	const OLD_SEA_MAP  ; 6d
	const SHINY_CHARM  ; 6e
	const OVAL_CHARM   ; 6f
	const SILPHSCOPE2  ; 70
	const APRICORN_BOX ; 71

	const TERU_SAMA    ; 72

	const CHERI_BERRY  ; 73
	const CHESTO_BERRY ; 74
	const PECHA_BERRY  ; 75
	const RAWST_BERRY  ; 76
	const ASPEAR_BERRY ; 77
	const LEPPA_BERRY  ; 78
	const ORAN_BERRY   ; 79
	const PERSIM_BERRY ; 7a
	const LUM_BERRY    ; 7b
	const SITRUS_BERRY ; 7c
	const FIGY_BERRY   ; 7d
	const LIECHI_BERRY ; 7e
	const GANLON_BERRY ; 7f
	const SALAC_BERRY  ; 80
	const PETAYA_BERRY ; 81
	const APICOT_BERRY ; 82
	const JABOCA_BERRY ; 83
	const ROWAP_BERRY  ; 84
	const KEE_BERRY    ; 85
	const MARANGABERRY ; 86

	const PEWTERCRUNCH ; 87

	const SILK_SCARF   ; 88
	const BLACK_BELT   ; 89
	const SHARP_BEAK   ; 8a
	const POISON_BARB  ; 8b
	const SOFT_SAND    ; 8c
	const HARD_STONE   ; 8d
	const SILVERPOWDER ; 8e
	const SPELL_TAG    ; 8f
	const METAL_COAT   ; 90
	const CHARCOAL     ; 91
	const MYSTIC_WATER ; 92
	const MIRACLE_SEED ; 93
	const MAGNET       ; 94
	const TWISTEDSPOON ; 95
	const NEVERMELTICE ; 96
	const DRAGON_FANG  ; 97
	const BLACKGLASSES ; 98
	const PINK_BOW     ; 99

	const BRIGHTPOWDER ; 9a
	const SCOPE_LENS   ; 9b
	const QUICK_CLAW   ; 9c
	const KINGS_ROCK   ; 9d
	const FOCUS_BAND   ; 9e
	const LEFTOVERS    ; 9f
	const LUCKY_EGG    ; a0
	const AMULET_COIN  ; a1
	const CLEANSE_TAG  ; a2
	const SMOKE_BALL   ; a3
	const BERSERK_GENE ; a4

	const LIGHT_BALL   ; a5
	const STICK        ; a6
	const THICK_CLUB   ; a7
	const LUCKY_PUNCH  ; a8
	const METAL_POWDER ; a9
	const QUICK_POWDER ; aa
	const ARMOR_SUIT   ; ab

	const AIR_BALLOON  ; ac
	const ASSAULT_VEST ; ad
	const BIG_ROOT     ; ae
	const BINDING_BAND ; af
	const DESTINY_KNOT ; b0
	const EVIOLITE     ; b1
	const EXPERT_BELT  ; b2
	const FOCUS_SASH   ; b3
	const GRIP_CLAW    ; b4
	const LIFE_ORB     ; b5
	const LIGHT_CLAY   ; b6
	const METRONOME_I  ; b7
	const MUSCLE_BAND  ; b8
	const PROTECT_PADS ; b9
	const ROCKY_HELMET ; ba
	const SAFE_GOGGLES ; bb
	const SHED_SHELL   ; bc
	const SHELL_BELL   ; bd
	const SOOTHE_BELL  ; be
	const WEAK_POLICY  ; bf
	const WIDE_LENS    ; c0
	const WISE_GLASSES ; c1
	const ZOOM_LENS    ; c2

	const MENTAL_HERB  ; c3
	const POWER_HERB   ; c4
	const WHITE_HERB   ; c5

	const DAMP_ROCK    ; c6
	const HEAT_ROCK    ; c7
	const SMOOTH_ROCK  ; c8
	const ICY_ROCK     ; c9

	const CHOICE_BAND  ; ca
	const CHOICE_SCARF ; cb
	const CHOICE_SPECS ; cc

	const FLAME_ORB    ; cd
	const TOXIC_ORB    ; ce
	const BLACK_SLUDGE ; cf

	const MACHO_BRACE  ; d0
	const POWER_WEIGHT ; d1
	const POWER_BRACER ; d2
	const POWER_BELT   ; d3
	const POWER_LENS   ; d4
	const POWER_BAND   ; d5
	const POWER_ANKLET ; d6

	const DRAGON_SCALE ; d7
	const UP_GRADE     ; d8
	const DUBIOUS_DISC ; d9
	const PROTECTOR    ; da
	const ELECTIRIZER  ; db
	const MAGMARIZER   ; dc
	const RAZOR_FANG   ; dd
	const RAZOR_CLAW   ; de
	const ODD_SOUVENIR ; df

	const NUGGET       ; e0
	const BIG_NUGGET   ; e1
	const TINYMUSHROOM ; e2
	const BIG_MUSHROOM ; e3
	const BALMMUSHROOM ; e4
	const PEARL        ; e5
	const BIG_PEARL    ; e6
	const PEARL_STRING ; e7
	const STARDUST     ; e8
	const STAR_PIECE   ; e9
	const BRICK_PIECE  ; ea
	const RARE_BONE    ; eb
	const SILVER_LEAF  ; ec
	const GOLD_LEAF    ; ed
	const SLOWPOKETAIL ; ee
	const BOTTLE_CAP   ; ef

	const HELIX_FOSSIL ; f0
	const DOME_FOSSIL  ; f1
	const OLD_AMBER    ; f2

	const MULCH        ; f3
	const SWEET_HONEY  ; f4

	const FLOWER_MAIL  ; f5
	const SURF_MAIL    ; f6
	const LITEBLUEMAIL ; f7
	const PORTRAITMAIL ; f8
	const LOVELY_MAIL  ; f9
	const EON_MAIL     ; fa
	const MORPH_MAIL   ; fb
	const BLUESKY_MAIL ; fc
	const MUSIC_MAIL   ; fd
	const MIRAGE_MAIL  ; fe

	const ITEM_FROM_MEM ; ff

; See data/items/name_order.asm
	const_def
	const NAM_NO_ITEM      ; 00
	const NAM_ABILITY_CAP  ; 01
	const NAM_AIR_BALLOON  ; 02
	const NAM_AMULET_COIN  ; 03
	const NAM_ANTIDOTE     ; 04
	const NAM_APICOT_BERRY ; 05
	const NAM_APRICORN_BOX ; 06
	const NAM_ARMOR_SUIT   ; 07
	const NAM_ASPEAR_BERRY ; 08
	const NAM_ASSAULT_VEST ; 09
	const NAM_AWAKENING    ; 0a
	const NAM_BALMMUSHROOM ; 0b
	const NAM_BASEMENT_KEY ; 0c
	const NAM_BERSERK_GENE ; 0d
	const NAM_BICYCLE      ; 0e
	const NAM_BIG_MUSHROOM ; 0f
	const NAM_BIG_NUGGET   ; 10
	const NAM_BIG_PEARL    ; 11
	const NAM_BIG_ROOT     ; 12
	const NAM_BINDING_BAND ; 13
	const NAM_BLACK_BELT   ; 14
	const NAM_BLACK_SLUDGE ; 15
	const NAM_BLACKGLASSES ; 16
	const NAM_BLUE_CARD    ; 17
	const NAM_BLUESKY_MAIL ; 18
	const NAM_BOTTLE_CAP   ; 19
	const NAM_BRICK_PIECE  ; 1a
	const NAM_BRIGHTPOWDER ; 1b
	const NAM_BURN_HEAL    ; 1c
	const NAM_CALCIUM      ; 1d
	const NAM_CARBOS       ; 1e
	const NAM_CARD_KEY     ; 1f
	const NAM_CHARCOAL     ; 20
	const NAM_CHERI_BERRY  ; 21
	const NAM_CHERISH_BALL ; 22
	const NAM_CHESTO_BERRY ; 23
	const NAM_CHOICE_BAND  ; 24
	const NAM_CHOICE_SCARF ; 25
	const NAM_CHOICE_SPECS ; 26
	const NAM_CLEANSE_TAG  ; 27
	const NAM_CLEAR_BELL   ; 28
	const NAM_COIN_CASE    ; 29
	const NAM_DAMP_ROCK    ; 2a
	const NAM_DESTINY_KNOT ; 2b
	const NAM_DIRE_HIT     ; 2c
	const NAM_DIVE_BALL    ; 2d
	const NAM_DOME_FOSSIL  ; 2e
	const NAM_DRAGON_FANG  ; 2f
	const NAM_DRAGON_SCALE ; 30
	const NAM_DUBIOUS_DISC ; 31
	const NAM_DUSK_BALL    ; 32
	const NAM_DUSK_STONE   ; 33
	const NAM_ELECTIRIZER  ; 34
	const NAM_ELIXIR       ; 35
	const NAM_ENERGY_ROOT  ; 36
	const NAM_ENERGYPOWDER ; 37
	const NAM_EON_MAIL     ; 38
	const NAM_ESCAPE_ROPE  ; 39
	const NAM_ETHER        ; 3a
	const NAM_EVERSTONE    ; 3b
	const NAM_EVIOLITE     ; 3c
	const NAM_EXP_SHARE    ; 3d
	const NAM_EXPERT_BELT  ; 3e
	const NAM_FAST_BALL    ; 3f
	const NAM_FIGY_BERRY   ; 40
	const NAM_FIRE_STONE   ; 41
	const NAM_FLAME_ORB    ; 42
	const NAM_FLOWER_MAIL  ; 43
	const NAM_FOCUS_BAND   ; 44
	const NAM_FOCUS_SASH   ; 45
	const NAM_FRESH_WATER  ; 46
	const NAM_FRIEND_BALL  ; 47
	const NAM_FULL_HEAL    ; 48
	const NAM_FULL_RESTORE ; 49
	const NAM_GANLON_BERRY ; 4a
	const NAM_GOLD_LEAF    ; 4b
	const NAM_GOOD_ROD     ; 4c
	const NAM_GREAT_BALL   ; 4d
	const NAM_GRIP_CLAW    ; 4e
	const NAM_GS_BALL      ; 4f
	const NAM_GUARD_SPEC   ; 50
	const NAM_HARD_STONE   ; 51
	const NAM_HEAL_BALL    ; 52
	const NAM_HEAL_POWDER  ; 53
	const NAM_HEAT_ROCK    ; 54
	const NAM_HEAVY_BALL   ; 55
	const NAM_HELIX_FOSSIL ; 56
	const NAM_HP_UP        ; 57
	const NAM_HYPER_POTION ; 58
	const NAM_ICE_HEAL     ; 59
	const NAM_ICE_STONE    ; 5a
	const NAM_ICY_ROCK     ; 5b
	const NAM_IRON         ; 5c
	const NAM_ITEMFINDER   ; 5d
	const NAM_JABOCA_BERRY ; 5e
	const NAM_KEE_BERRY    ; 5f
	const NAM_KINGS_ROCK   ; 60
	const NAM_LEAF_STONE   ; 61
	const NAM_LEFTOVERS    ; 62
	const NAM_LEMONADE     ; 63
	const NAM_LEPPA_BERRY  ; 64
	const NAM_LEVEL_BALL   ; 65
	const NAM_LIECHI_BERRY ; 66
	const NAM_LIFE_ORB     ; 67
	const NAM_LIGHT_BALL   ; 68
	const NAM_LIGHT_CLAY   ; 69
	const NAM_LITEBLUEMAIL ; 6a
	const NAM_LOST_ITEM    ; 6b
	const NAM_LOVE_BALL    ; 6c
	const NAM_LOVELY_MAIL  ; 6d
	const NAM_LUCKY_EGG    ; 6e
	const NAM_LUCKY_PUNCH  ; 6f
	const NAM_LUM_BERRY    ; 70
	const NAM_LURE_BALL    ; 71
	const NAM_LUXURY_BALL  ; 72
	const NAM_MACHINE_PART ; 73
	const NAM_MACHO_BRACE  ; 74
	const NAM_MAGMARIZER   ; 75
	const NAM_MAGNET       ; 76
	const NAM_MARANGABERRY ; 77
	const NAM_MASTER_BALL  ; 78
	const NAM_MAX_ELIXIR   ; 79
	const NAM_MAX_ETHER    ; 7a
	const NAM_MAX_POTION   ; 7b
	const NAM_MAX_REPEL    ; 7c
	const NAM_MAX_REVIVE   ; 7d
	const NAM_MENTAL_HERB  ; 7e
	const NAM_METAL_COAT   ; 7f
	const NAM_METAL_POWDER ; 80
	const NAM_METRONOME_I  ; 81
	const NAM_MIRACLE_SEED ; 82
	const NAM_MIRAGE_MAIL  ; 83
	const NAM_MOOMOO_MILK  ; 84
	const NAM_MOON_BALL    ; 85
	const NAM_MOON_STONE   ; 86
	const NAM_MORPH_MAIL   ; 87
	const NAM_MULCH        ; 88
	const NAM_MUSCLE_BAND  ; 89
	const NAM_MUSIC_MAIL   ; 8a
	const NAM_MYSTERY_EGG  ; 8b
	const NAM_MYSTIC_WATER ; 8c
	const NAM_MYSTICTICKET ; 8d
	const NAM_NEST_BALL    ; 8e
	const NAM_NET_BALL     ; 8f
	const NAM_NEVERMELTICE ; 90
	const NAM_NUGGET       ; 91
	const NAM_ODD_SOUVENIR ; 92
	const NAM_OLD_AMBER    ; 93
	const NAM_OLD_ROD      ; 94
	const NAM_OLD_SEA_MAP  ; 95
	const NAM_ORAN_BERRY   ; 96
	const NAM_ORANGETICKET ; 97
	const NAM_OVAL_CHARM   ; 98
	const NAM_PARALYZEHEAL ; 99
	const NAM_PARK_BALL    ; 9a
	const NAM_PASS         ; 9b
	const NAM_PEARL        ; 9c
	const NAM_PEARL_STRING ; 9d
	const NAM_PECHA_BERRY  ; 9e
	const NAM_PERSIM_BERRY ; 9f
	const NAM_PETAYA_BERRY ; a0
	const NAM_PEWTERCRUNCH ; a1
	const NAM_PINK_BOW     ; a2
	const NAM_POISON_BARB  ; a3
	const NAM_POKE_BALL    ; a4
	const NAM_POKE_DOLL    ; a5
	const NAM_PORTRAITMAIL ; a6
	const NAM_POTION       ; a7
	const NAM_POWER_ANKLET ; a8
	const NAM_POWER_BAND   ; a9
	const NAM_POWER_BELT   ; aa
	const NAM_POWER_BRACER ; ab
	const NAM_POWER_HERB   ; ac
	const NAM_POWER_LENS   ; ad
	const NAM_POWER_WEIGHT ; ae
	const NAM_PP_MAX       ; af
	const NAM_PP_UP        ; b0
	const NAM_PREMIER_BALL ; b1
	const NAM_PROTECT_PADS ; b2
	const NAM_PROTECTOR    ; b3
	const NAM_PROTEIN      ; b4
	const NAM_QUICK_BALL   ; b5
	const NAM_QUICK_CLAW   ; b6
	const NAM_QUICK_POWDER ; b7
	const NAM_RAGECANDYBAR ; b8
	const NAM_RAINBOW_WING ; b9
	const NAM_RARE_BONE    ; ba
	const NAM_RARE_CANDY   ; bb
	const NAM_RAWST_BERRY  ; bc
	const NAM_RAZOR_CLAW   ; bd
	const NAM_RAZOR_FANG   ; be
	const NAM_RED_SCALE    ; bf
	const NAM_REPEAT_BALL  ; c0
	const NAM_REPEL        ; c1
	const NAM_REVIVAL_HERB ; c2
	const NAM_REVIVE       ; c3
	const NAM_ROCKY_HELMET ; c4
	const NAM_ROWAP_BERRY  ; c5
	const NAM_S_S_TICKET   ; c6
	const NAM_SACRED_ASH   ; c7
	const NAM_SAFARI_BALL  ; c8
	const NAM_SAFE_GOGGLES ; c9
	const NAM_SALAC_BERRY  ; ca
	const NAM_SCOPE_LENS   ; cb
	const NAM_SECRETPOTION ; cc
	const NAM_SHARP_BEAK   ; cd
	const NAM_SHED_SHELL   ; ce
	const NAM_SHELL_BELL   ; cf
	const NAM_SHINY_CHARM  ; d0
	const NAM_SHINY_STONE  ; d1
	const NAM_SILK_SCARF   ; d2
	const NAM_SILPHSCOPE2  ; d3
	const NAM_SILVER_LEAF  ; d4
	const NAM_SILVER_WING  ; d5
	const NAM_SILVERPOWDER ; d6
	const NAM_SITRUS_BERRY ; d7
	const NAM_SLOWPOKETAIL ; d8
	const NAM_SMOKE_BALL   ; d9
	const NAM_SMOOTH_ROCK  ; da
	const NAM_SODA_POP     ; db
	const NAM_SOFT_SAND    ; dc
	const NAM_SOOTHE_BELL  ; dd
	const NAM_SPELL_TAG    ; de
	const NAM_SQUIRTBOTTLE ; df
	const NAM_STAR_PIECE   ; e0
	const NAM_STARDUST     ; e1
	const NAM_STICK        ; e2
	const NAM_SUN_STONE    ; e3
	const NAM_SUPER_POTION ; e4
	const NAM_SUPER_REPEL  ; e5
	const NAM_SUPER_ROD    ; e6
	const NAM_SURF_MAIL    ; e7
	const NAM_SWEET_HONEY  ; e8
	const NAM_TERU_SAMA    ; e9
	const NAM_THICK_CLUB   ; ea
	const NAM_THUNDERSTONE ; eb
	const NAM_TIMER_BALL   ; ec
	const NAM_TINYMUSHROOM ; ed
	const NAM_TOXIC_ORB    ; ee
	const NAM_TWISTEDSPOON ; ef
	const NAM_ULTRA_BALL   ; f0
	const NAM_UP_GRADE     ; f1
	const NAM_WATER_STONE  ; f2
	const NAM_WEAK_POLICY  ; f3
	const NAM_WIDE_LENS    ; f4
	const NAM_WISE_GLASSES ; f5
	const NAM_WHITE_HERB   ; f6
	const NAM_X_ACCURACY   ; f7
	const NAM_X_ATTACK     ; f8
	const NAM_X_DEFEND     ; f9
	const NAM_X_SPCL_ATK   ; fa
	const NAM_X_SPCL_DEF   ; fb
	const NAM_X_SPEED      ; fc
	const NAM_ZINC         ; fd
	const NAM_ZOOM_LENS    ; fe

; APRICORN_BOX contents
	const_def 1
	const RED_APRICORN ; 1
	const BLU_APRICORN ; 2
	const YLW_APRICORN ; 3
	const GRN_APRICORN ; 4
	const WHT_APRICORN ; 5
	const BLK_APRICORN ; 6
	const PNK_APRICORN ; 7
NUM_APRICORNS EQU const_value +- 1
