	const_def
	const NO_ITEM      ; 00

	const POKE_BALL    ; 01
	const GREAT_BALL   ; 02
	const ULTRA_BALL   ; 03
	const MASTER_BALL  ; 04

	const SAFARI_BALL  ; 05

	const LEVEL_BALL   ; 06
	const LURE_BALL    ; 07
	const MOON_BALL    ; 08
	const FRIEND_BALL  ; 09
	const FAST_BALL    ; 0a
	const HEAVY_BALL   ; 0b
	const LOVE_BALL    ; 0c

	const PARK_BALL    ; 0d

	const REPEAT_BALL  ; 0e
	const TIMER_BALL   ; 0f
	const NEST_BALL    ; 10
	const NET_BALL     ; 11
	const DIVE_BALL    ; 12
	const LUXURY_BALL  ; 13
	const HEAL_BALL    ; 14
	const QUICK_BALL   ; 15
	const DUSK_BALL    ; 16
	const DREAM_BALL   ; 17
	const PREMIER_BALL ; 18
	const CHERISH_BALL ; 19

	const POTION       ; 1a
	const SUPER_POTION ; 1b
	const HYPER_POTION ; 1c
	const MAX_POTION   ; 1d

	const ANTIDOTE     ; 1e
	const BURN_HEAL    ; 1f
	const PARALYZEHEAL ; 20
	const AWAKENING    ; 21
	const ICE_HEAL     ; 22
	const FULL_HEAL    ; 23
	const FULL_RESTORE ; 24

	const REVIVE       ; 25
	const MAX_REVIVE   ; 26

	const ETHER        ; 27
	const MAX_ETHER    ; 28
	const ELIXIR       ; 29
	const MAX_ELIXIR   ; 2a

	const HP_UP        ; 2b
	const PROTEIN      ; 2c
	const IRON         ; 2d
	const CARBOS       ; 2e
	const CALCIUM      ; 2f
	const ZINC         ; 30
	const RARE_CANDY   ; 31
	const PP_UP        ; 32
	const PP_MAX       ; 33

	const FRESH_WATER  ; 34
	const SODA_POP     ; 35
	const LEMONADE     ; 36
	const MOOMOO_MILK  ; 37
	const RAGECANDYBAR ; 38
	const PEWTERCRUNCH ; 39

	const SACRED_ASH   ; 3a
	const ENERGYPOWDER ; 3b
	const ENERGY_ROOT  ; 3c
	const HEAL_POWDER  ; 3d
	const REVIVAL_HERB ; 3e

	const X_ATTACK     ; 3f
	const X_DEFEND     ; 40
	const X_SPEED      ; 41
	const X_SPCL_ATK   ; 42
	const X_SPCL_DEF   ; 43
	const X_ACCURACY   ; 44
	const DIRE_HIT     ; 45
	const GUARD_SPEC   ; 46

	const REPEL        ; 47
	const SUPER_REPEL  ; 48
	const MAX_REPEL    ; 49
	const ESCAPE_ROPE  ; 4a
	const POKE_DOLL    ; 4b

	const ABILITY_CAP  ; 4c

	const LEAF_STONE   ; 4d
	const FIRE_STONE   ; 4e
	const WATER_STONE  ; 4f
	const THUNDERSTONE ; 50
	const MOON_STONE   ; 51
	const SUN_STONE    ; 52
	const DUSK_STONE   ; 53
	const SHINY_STONE  ; 54
	const ICE_STONE    ; 55
	const EVERSTONE    ; 56

	const EXP_SHARE    ; 57

	const CHERI_BERRY  ; 58
	const CHESTO_BERRY ; 59
	const PECHA_BERRY  ; 5a
	const RAWST_BERRY  ; 5b
	const ASPEAR_BERRY ; 5c
	const LEPPA_BERRY  ; 5d
	const ORAN_BERRY   ; 5e
	const PERSIM_BERRY ; 5f
	const LUM_BERRY    ; 60
	const SITRUS_BERRY ; 61
	const FIGY_BERRY   ; 62
	const LIECHI_BERRY ; 63
	const GANLON_BERRY ; 64
	const SALAC_BERRY  ; 65
	const PETAYA_BERRY ; 66
	const APICOT_BERRY ; 67
	const JABOCA_BERRY ; 68
	const ROWAP_BERRY  ; 69
	const KEE_BERRY    ; 6a
	const MARANGABERRY ; 6b

	const BERRY_JUICE  ; 6c

	const SILK_SCARF   ; 6d
	const BLACK_BELT   ; 6e
	const SHARP_BEAK   ; 6f
	const POISON_BARB  ; 70
	const SOFT_SAND    ; 71
	const HARD_STONE   ; 72
	const SILVERPOWDER ; 73
	const SPELL_TAG    ; 74
	const METAL_COAT   ; 75
	const CHARCOAL     ; 76
	const MYSTIC_WATER ; 77
	const MIRACLE_SEED ; 78
	const MAGNET       ; 79
	const TWISTEDSPOON ; 7a
	const NEVERMELTICE ; 7b
	const DRAGON_FANG  ; 7c
	const BLACKGLASSES ; 7d
	const PINK_BOW     ; 7e

	const BRIGHTPOWDER ; 7f
	const SCOPE_LENS   ; 80
	const QUICK_CLAW   ; 81
	const KINGS_ROCK   ; 82
	const FOCUS_BAND   ; 83
	const LEFTOVERS    ; 84
	const LUCKY_EGG    ; 85
	const AMULET_COIN  ; 86
	const CLEANSE_TAG  ; 87
	const SMOKE_BALL   ; 88
	const BERSERK_GENE ; 89

	const LIGHT_BALL   ; 8a
	const STICK        ; 8b
	const THICK_CLUB   ; 8c
	const LUCKY_PUNCH  ; 8d
	const METAL_POWDER ; 8e
	const QUICK_POWDER ; 8f
	const ARMOR_SUIT   ; 90

	const AIR_BALLOON  ; 91
	const ASSAULT_VEST ; 92
	const BIG_ROOT     ; 93
	const BINDING_BAND ; 94
	const DESTINY_KNOT ; 95
	const EVIOLITE     ; 96
	const EXPERT_BELT  ; 97
	const FOCUS_SASH   ; 98
	const GRIP_CLAW    ; 99
	const LIFE_ORB     ; 9a
	const LIGHT_CLAY   ; 9b
	const METRONOME_I  ; 9c
	const MUSCLE_BAND  ; 9d
	const PROTECT_PADS ; 9e
	const ROCKY_HELMET ; 9f
	const SAFE_GOGGLES ; a0
	const SHED_SHELL   ; a1
	const SHELL_BELL   ; a2
	const SOOTHE_BELL  ; a3
	const WEAK_POLICY  ; a4
	const WIDE_LENS    ; a5
	const WISE_GLASSES ; a6
	const ZOOM_LENS    ; a7

	const EJECT_PACK   ; a8
	const ROOM_SERVICE ; a9
	const BLUNDRPOLICY ; aa
	const THROAT_SPRAY ; ab
	const HEAVY_BOOTS  ; ac
	const UTILUMBRELLA ; ad

	const MENTAL_HERB  ; ae
	const POWER_HERB   ; af
	const WHITE_HERB   ; b0

	const DAMP_ROCK    ; b1
	const HEAT_ROCK    ; b2
	const SMOOTH_ROCK  ; b3
	const ICY_ROCK     ; b4

	const CHOICE_BAND  ; b5
	const CHOICE_SCARF ; b6
	const CHOICE_SPECS ; b7

	const FLAME_ORB    ; b8
	const TOXIC_ORB    ; b9
	const BLACK_SLUDGE ; ba

	const MACHO_BRACE  ; bb
	const POWER_WEIGHT ; bc
	const POWER_BRACER ; bd
	const POWER_BELT   ; be
	const POWER_LENS   ; bf
	const POWER_BAND   ; c0
	const POWER_ANKLET ; c1

	const DRAGON_SCALE ; c2
	const UP_GRADE     ; c3
	const DUBIOUS_DISC ; c4
	const PROTECTOR    ; c5
	const ELECTIRIZER  ; c6
	const MAGMARIZER   ; c7
	const RAZOR_FANG   ; c8
	const RAZOR_CLAW   ; c9
	const ODD_SOUVENIR ; ca

	const NUGGET       ; cb
	const BIG_NUGGET   ; cc
	const TINYMUSHROOM ; cd
	const BIG_MUSHROOM ; ce
	const BALMMUSHROOM ; cf
	const PEARL        ; d0
	const BIG_PEARL    ; d1
	const PEARL_STRING ; d2
	const STARDUST     ; d3
	const STAR_PIECE   ; d4
	const BRICK_PIECE  ; d5
	const RARE_BONE    ; d6
	const SILVER_LEAF  ; d7
	const GOLD_LEAF    ; d8
	const SLOWPOKETAIL ; d9
	const BOTTLE_CAP   ; da

	const HELIX_FOSSIL ; db
	const DOME_FOSSIL  ; dc
	const OLD_AMBER    ; dd

	const MULCH        ; de
	const SWEET_HONEY  ; df
	const MINT         ; e0

	const FLOWER_MAIL  ; e1
	const SURF_MAIL    ; e2
	const LITEBLUEMAIL ; e3
	const PORTRAITMAIL ; e4
	const LOVELY_MAIL  ; e5
	const EON_MAIL     ; e6
	const MORPH_MAIL   ; e7
	const BLUESKY_MAIL ; e8
	const MUSIC_MAIL   ; e9
	const MIRAGE_MAIL  ; ea
NUM_ITEMS EQU const_value +- 1

ITEM_FROM_MEM EQU $ff

; See data/items/name_order.asm
	const_def
	const NAM_NO_ITEM      ; 00
	const NAM_ABILITY_CAP  ; 01
	const NAM_AIR_BALLOON  ; 02
	const NAM_AMULET_COIN  ; 03
	const NAM_ANTIDOTE     ; 04
	const NAM_APICOT_BERRY ; 05
	const NAM_ARMOR_SUIT   ; 06
	const NAM_ASPEAR_BERRY ; 07
	const NAM_ASSAULT_VEST ; 08
	const NAM_AWAKENING    ; 09
	const NAM_BALMMUSHROOM ; 0a
	const NAM_BERRY_JUICE  ; 0b
	const NAM_BERSERK_GENE ; 0c
	const NAM_BIG_MUSHROOM ; 0d
	const NAM_BIG_NUGGET   ; 0e
	const NAM_BIG_PEARL    ; 0f
	const NAM_BIG_ROOT     ; 10
	const NAM_BINDING_BAND ; 11
	const NAM_BLACK_BELT   ; 12
	const NAM_BLACK_SLUDGE ; 13
	const NAM_BLACKGLASSES ; 14
	const NAM_BLUESKY_MAIL ; 15
	const NAM_BLUNDRPOLICY ; 16
	const NAM_BOTTLE_CAP   ; 17
	const NAM_BRICK_PIECE  ; 18
	const NAM_BRIGHTPOWDER ; 19
	const NAM_BURN_HEAL    ; 1a
	const NAM_CALCIUM      ; 1b
	const NAM_CARBOS       ; 1c
	const NAM_CHARCOAL     ; 1d
	const NAM_CHERI_BERRY  ; 1e
	const NAM_CHERISH_BALL ; 1f
	const NAM_CHESTO_BERRY ; 20
	const NAM_CHOICE_BAND  ; 21
	const NAM_CHOICE_SCARF ; 22
	const NAM_CHOICE_SPECS ; 23
	const NAM_CLEANSE_TAG  ; 24
	const NAM_DAMP_ROCK    ; 25
	const NAM_DESTINY_KNOT ; 26
	const NAM_DIRE_HIT     ; 27
	const NAM_DIVE_BALL    ; 28
	const NAM_DOME_FOSSIL  ; 29
	const NAM_DRAGON_FANG  ; 2a
	const NAM_DRAGON_SCALE ; 2b
	const NAM_DREAM_BALL   ; 2c
	const NAM_DUBIOUS_DISC ; 2d
	const NAM_DUSK_BALL    ; 2e
	const NAM_DUSK_STONE   ; 2f
	const NAM_EJECT_PACK   ; 30
	const NAM_ELECTIRIZER  ; 31
	const NAM_ELIXIR       ; 32
	const NAM_ENERGY_ROOT  ; 33
	const NAM_ENERGYPOWDER ; 34
	const NAM_EON_MAIL     ; 35
	const NAM_ESCAPE_ROPE  ; 36
	const NAM_ETHER        ; 37
	const NAM_EVERSTONE    ; 38
	const NAM_EVIOLITE     ; 39
	const NAM_EXP_SHARE    ; 3a
	const NAM_EXPERT_BELT  ; 3b
	const NAM_FAST_BALL    ; 3c
	const NAM_FIGY_BERRY   ; 3d
	const NAM_FIRE_STONE   ; 3e
	const NAM_FLAME_ORB    ; 3f
	const NAM_FLOWER_MAIL  ; 40
	const NAM_FOCUS_BAND   ; 41
	const NAM_FOCUS_SASH   ; 42
	const NAM_FRESH_WATER  ; 43
	const NAM_FRIEND_BALL  ; 44
	const NAM_FULL_HEAL    ; 45
	const NAM_FULL_RESTORE ; 46
	const NAM_GANLON_BERRY ; 47
	const NAM_GOLD_LEAF    ; 48
	const NAM_GREAT_BALL   ; 49
	const NAM_GRIP_CLAW    ; 4a
	const NAM_GUARD_SPEC   ; 4b
	const NAM_HARD_STONE   ; 4c
	const NAM_HEAL_BALL    ; 4d
	const NAM_HEAL_POWDER  ; 4e
	const NAM_HEAT_ROCK    ; 4f
	const NAM_HEAVY_BALL   ; 50
	const NAM_HEAVY_BOOTS  ; 51
	const NAM_HELIX_FOSSIL ; 52
	const NAM_HP_UP        ; 53
	const NAM_HYPER_POTION ; 54
	const NAM_ICE_HEAL     ; 55
	const NAM_ICE_STONE    ; 56
	const NAM_ICY_ROCK     ; 57
	const NAM_IRON         ; 58
	const NAM_JABOCA_BERRY ; 59
	const NAM_KEE_BERRY    ; 5a
	const NAM_KINGS_ROCK   ; 5b
	const NAM_LEAF_STONE   ; 5c
	const NAM_LEFTOVERS    ; 5d
	const NAM_LEMONADE     ; 5e
	const NAM_LEPPA_BERRY  ; 5f
	const NAM_LEVEL_BALL   ; 60
	const NAM_LIECHI_BERRY ; 61
	const NAM_LIFE_ORB     ; 62
	const NAM_LIGHT_BALL   ; 63
	const NAM_LIGHT_CLAY   ; 64
	const NAM_LITEBLUEMAIL ; 65
	const NAM_LOVE_BALL    ; 66
	const NAM_LOVELY_MAIL  ; 67
	const NAM_LUCKY_EGG    ; 68
	const NAM_LUCKY_PUNCH  ; 69
	const NAM_LUM_BERRY    ; 6a
	const NAM_LURE_BALL    ; 6b
	const NAM_LUXURY_BALL  ; 6c
	const NAM_MACHO_BRACE  ; 6d
	const NAM_MAGMARIZER   ; 6e
	const NAM_MAGNET       ; 6f
	const NAM_MARANGABERRY ; 70
	const NAM_MASTER_BALL  ; 71
	const NAM_MAX_ELIXIR   ; 72
	const NAM_MAX_ETHER    ; 73
	const NAM_MAX_POTION   ; 74
	const NAM_MAX_REPEL    ; 75
	const NAM_MAX_REVIVE   ; 76
	const NAM_MENTAL_HERB  ; 77
	const NAM_METAL_COAT   ; 78
	const NAM_METAL_POWDER ; 79
	const NAM_METRONOME_I  ; 7a
	const NAM_MINT         ; 7b
	const NAM_MIRACLE_SEED ; 7c
	const NAM_MIRAGE_MAIL  ; 7d
	const NAM_MOOMOO_MILK  ; 7e
	const NAM_MOON_BALL    ; 7f
	const NAM_MOON_STONE   ; 80
	const NAM_MORPH_MAIL   ; 81
	const NAM_MULCH        ; 82
	const NAM_MUSCLE_BAND  ; 83
	const NAM_MUSIC_MAIL   ; 84
	const NAM_MYSTIC_WATER ; 85
	const NAM_NEST_BALL    ; 86
	const NAM_NET_BALL     ; 87
	const NAM_NEVERMELTICE ; 88
	const NAM_NUGGET       ; 89
	const NAM_ODD_SOUVENIR ; 8a
	const NAM_OLD_AMBER    ; 8b
	const NAM_ORAN_BERRY   ; 8c
	const NAM_PARALYZEHEAL ; 8d
	const NAM_PARK_BALL    ; 8e
	const NAM_PEARL        ; 8f
	const NAM_PEARL_STRING ; 90
	const NAM_PECHA_BERRY  ; 91
	const NAM_PERSIM_BERRY ; 92
	const NAM_PETAYA_BERRY ; 93
	const NAM_PEWTERCRUNCH ; 94
	const NAM_PINK_BOW     ; 95
	const NAM_POISON_BARB  ; 96
	const NAM_POKE_BALL    ; 97
	const NAM_POKE_DOLL    ; 98
	const NAM_PORTRAITMAIL ; 99
	const NAM_POTION       ; 9a
	const NAM_POWER_ANKLET ; 9b
	const NAM_POWER_BAND   ; 9c
	const NAM_POWER_BELT   ; 9d
	const NAM_POWER_BRACER ; 9e
	const NAM_POWER_HERB   ; 9f
	const NAM_POWER_LENS   ; a0
	const NAM_POWER_WEIGHT ; a1
	const NAM_PP_MAX       ; a2
	const NAM_PP_UP        ; a3
	const NAM_PREMIER_BALL ; a4
	const NAM_PROTECT_PADS ; a5
	const NAM_PROTECTOR    ; a6
	const NAM_PROTEIN      ; a7
	const NAM_QUICK_BALL   ; a8
	const NAM_QUICK_CLAW   ; a9
	const NAM_QUICK_POWDER ; aa
	const NAM_RAGECANDYBAR ; ab
	const NAM_RARE_BONE    ; ac
	const NAM_RARE_CANDY   ; ad
	const NAM_RAWST_BERRY  ; ae
	const NAM_RAZOR_CLAW   ; af
	const NAM_RAZOR_FANG   ; b0
	const NAM_REPEAT_BALL  ; b1
	const NAM_REPEL        ; b2
	const NAM_REVIVAL_HERB ; b3
	const NAM_REVIVE       ; b4
	const NAM_ROCKY_HELMET ; b5
	const NAM_ROOM_SERVICE ; b6
	const NAM_ROWAP_BERRY  ; b7
	const NAM_SACRED_ASH   ; b8
	const NAM_SAFARI_BALL  ; b9
	const NAM_SAFE_GOGGLES ; ba
	const NAM_SALAC_BERRY  ; bb
	const NAM_SCOPE_LENS   ; bc
	const NAM_SHARP_BEAK   ; bd
	const NAM_SHED_SHELL   ; be
	const NAM_SHELL_BELL   ; bf
	const NAM_SHINY_STONE  ; c0
	const NAM_SILK_SCARF   ; c1
	const NAM_SILVER_LEAF  ; c2
	const NAM_SILVERPOWDER ; c3
	const NAM_SITRUS_BERRY ; c4
	const NAM_SLOWPOKETAIL ; c5
	const NAM_SMOKE_BALL   ; c6
	const NAM_SMOOTH_ROCK  ; c7
	const NAM_SODA_POP     ; c8
	const NAM_SOFT_SAND    ; c9
	const NAM_SOOTHE_BELL  ; ca
	const NAM_SPELL_TAG    ; cb
	const NAM_STAR_PIECE   ; cc
	const NAM_STARDUST     ; cd
	const NAM_STICK        ; ce
	const NAM_SUN_STONE    ; cf
	const NAM_SUPER_POTION ; d0
	const NAM_SUPER_REPEL  ; d1
	const NAM_SURF_MAIL    ; d2
	const NAM_SWEET_HONEY  ; d3
	const NAM_THICK_CLUB   ; d4
	const NAM_THROAT_SPRAY ; d5
	const NAM_THUNDERSTONE ; d6
	const NAM_TIMER_BALL   ; d7
	const NAM_TINYMUSHROOM ; d8
	const NAM_TOXIC_ORB    ; d9
	const NAM_TWISTEDSPOON ; da
	const NAM_ULTRA_BALL   ; db
	const NAM_UP_GRADE     ; dc
	const NAM_UTILUMBRELLA ; dd
	const NAM_WATER_STONE  ; de
	const NAM_WEAK_POLICY  ; df
	const NAM_WHITE_HERB   ; e0
	const NAM_WIDE_LENS    ; e1
	const NAM_WISE_GLASSES ; e2
	const NAM_X_ACCURACY   ; e3
	const NAM_X_ATTACK     ; e4
	const NAM_X_DEFEND     ; e5
	const NAM_X_SPCL_ATK   ; e6
	const NAM_X_SPCL_DEF   ; e7
	const NAM_X_SPEED      ; e8
	const NAM_ZINC         ; e9
	const NAM_ZOOM_LENS    ; ea

; APRICORN_BOX contents
	const_def 1
	const RED_APRICORN ; 1
	const BLU_APRICORN ; 2
	const YLW_APRICORN ; 3
	const GRN_APRICORN ; 4
	const WHT_APRICORN ; 5
	const BLK_APRICORN ; 6
	const PNK_APRICORN ; 7
NUM_APRICORNS EQU const_value +- 1

; Key Item constants
	const_def
	const BICYCLE      ; 00
	const OLD_ROD      ; 01
	const GOOD_ROD     ; 02
	const SUPER_ROD    ; 03
	const COIN_CASE    ; 04
	const ITEMFINDER   ; 05
	const MYSTERY_EGG  ; 06
	const SQUIRTBOTTLE ; 07
	const SECRETPOTION ; 08
	const RED_SCALE    ; 09
	const CARD_KEY     ; 0a
	const BASEMENT_KEY ; 0b
	const S_S_TICKET   ; 0c
	const PASS         ; 0d
	const MACHINE_PART ; 0e
	const LOST_ITEM    ; 0f
	const RAINBOW_WING ; 10
	const SILVER_WING  ; 11
	const CLEAR_BELL   ; 12
	const GS_BALL      ; 13
	const BLUE_CARD    ; 14
	const ORANGETICKET ; 15
	const MYSTICTICKET ; 16
	const OLD_SEA_MAP  ; 17
	const SHINY_CHARM  ; 18
	const OVAL_CHARM   ; 19
	const CATCH_CHARM  ; 1a
	const SILPHSCOPE2  ; 1b
	const APRICORN_BOX ; 1c
NUM_KEY_ITEMS EQU const_value +- 1
