	const_def
	const NO_ITEM      ; 00

	const POKE_BALL    ; 01
	const GREAT_BALL   ; 02
	const ULTRA_BALL   ; 03
	const MASTER_BALL  ; 04

	const SAFARI_BALL  ; 05

	const LEVEL_BALL   ; 06
	const LURE_BALL    ; 07
	const MOON_BALL    ; 08
	const FRIEND_BALL  ; 09
	const FAST_BALL    ; 0a
	const HEAVY_BALL   ; 0b
	const LOVE_BALL    ; 0c

	const PARK_BALL    ; 0d

	const REPEAT_BALL  ; 0e
	const TIMER_BALL   ; 0f
	const NEST_BALL    ; 10
	const NET_BALL     ; 11
	const DIVE_BALL    ; 12
	const LUXURY_BALL  ; 13
	const HEAL_BALL    ; 14
	const QUICK_BALL   ; 15
	const DUSK_BALL    ; 16
	const PREMIER_BALL ; 17
	const CHERISH_BALL ; 18

	const POTION       ; 19
	const SUPER_POTION ; 1a
	const HYPER_POTION ; 1b
	const MAX_POTION   ; 1c

	const ANTIDOTE     ; 1d
	const BURN_HEAL    ; 1e
	const PARALYZEHEAL ; 1f
	const AWAKENING    ; 20
	const ICE_HEAL     ; 21
	const FULL_HEAL    ; 22
	const FULL_RESTORE ; 23

	const REVIVE       ; 24
	const MAX_REVIVE   ; 25

	const ETHER        ; 26
	const MAX_ETHER    ; 27
	const ELIXIR       ; 28
	const MAX_ELIXIR   ; 29

	const HP_UP        ; 2a
	const PROTEIN      ; 2b
	const IRON         ; 2c
	const CARBOS       ; 2d
	const CALCIUM      ; 2e
	const ZINC         ; 2f
	const RARE_CANDY   ; 30
	const PP_UP        ; 31
	const PP_MAX       ; 32

	const FRESH_WATER  ; 33
	const SODA_POP     ; 34
	const LEMONADE     ; 35
	const MOOMOO_MILK  ; 36
	const RAGECANDYBAR ; 37
	const PEWTERCRUNCH ; 38

	const SACRED_ASH   ; 39
	const ENERGYPOWDER ; 3a
	const ENERGY_ROOT  ; 3b
	const HEAL_POWDER  ; 3c
	const REVIVAL_HERB ; 3d

	const X_ATTACK     ; 3e
	const X_DEFEND     ; 3f
	const X_SPEED      ; 40
	const X_SPCL_ATK   ; 41
	const X_SPCL_DEF   ; 42
	const X_ACCURACY   ; 43
	const DIRE_HIT     ; 44
	const GUARD_SPEC   ; 45

	const REPEL        ; 46
	const SUPER_REPEL  ; 47
	const MAX_REPEL    ; 48
	const ESCAPE_ROPE  ; 49
	const POKE_DOLL    ; 4a

	const ABILITY_CAP  ; 4b

	const LEAF_STONE   ; 4c
	const FIRE_STONE   ; 4d
	const WATER_STONE  ; 4e
	const THUNDERSTONE ; 4f
	const MOON_STONE   ; 50
	const SUN_STONE    ; 51
	const DUSK_STONE   ; 52
	const SHINY_STONE  ; 53
	const ICE_STONE    ; 54
	const EVERSTONE    ; 55

	const EXP_SHARE    ; 56

	const TERU_SAMA_01 ; 57
	const TERU_SAMA_02 ; 58
	const TERU_SAMA_03 ; 59
	const TERU_SAMA_04 ; 5a
	const TERU_SAMA_05 ; 5b
	const TERU_SAMA_06 ; 5c
	const TERU_SAMA_07 ; 5d
	const TERU_SAMA_08 ; 5e
	const TERU_SAMA_09 ; 5f
	const TERU_SAMA_10 ; 60
	const TERU_SAMA_11 ; 61
	const TERU_SAMA_12 ; 62
	const TERU_SAMA_13 ; 63
	const TERU_SAMA_14 ; 64
	const TERU_SAMA_15 ; 65
	const TERU_SAMA_16 ; 66
	const TERU_SAMA_17 ; 67
	const TERU_SAMA_18 ; 68
	const TERU_SAMA_19 ; 69
	const TERU_SAMA_20 ; 6a
	const TERU_SAMA_21 ; 6b
	const TERU_SAMA_22 ; 6c
	const TERU_SAMA_23 ; 6d
	const TERU_SAMA_24 ; 6e
	const TERU_SAMA_25 ; 6f
	const TERU_SAMA_26 ; 70
	const TERU_SAMA_27 ; 71
	const TERU_SAMA_28 ; 72
	const TERU_SAMA_29 ; 73

	const CHERI_BERRY  ; 74
	const CHESTO_BERRY ; 75
	const PECHA_BERRY  ; 76
	const RAWST_BERRY  ; 77
	const ASPEAR_BERRY ; 78
	const LEPPA_BERRY  ; 79
	const ORAN_BERRY   ; 7a
	const PERSIM_BERRY ; 7b
	const LUM_BERRY    ; 7c
	const SITRUS_BERRY ; 7d
	const FIGY_BERRY   ; 7e
	const LIECHI_BERRY ; 7f
	const GANLON_BERRY ; 80
	const SALAC_BERRY  ; 81
	const PETAYA_BERRY ; 82
	const APICOT_BERRY ; 83
	const JABOCA_BERRY ; 84
	const ROWAP_BERRY  ; 85
	const KEE_BERRY    ; 86
	const MARANGABERRY ; 87

	const SILK_SCARF   ; 88
	const BLACK_BELT   ; 89
	const SHARP_BEAK   ; 8a
	const POISON_BARB  ; 8b
	const SOFT_SAND    ; 8c
	const HARD_STONE   ; 8d
	const SILVERPOWDER ; 8e
	const SPELL_TAG    ; 8f
	const METAL_COAT   ; 90
	const CHARCOAL     ; 91
	const MYSTIC_WATER ; 92
	const MIRACLE_SEED ; 93
	const MAGNET       ; 94
	const TWISTEDSPOON ; 95
	const NEVERMELTICE ; 96
	const DRAGON_FANG  ; 97
	const BLACKGLASSES ; 98
	const PINK_BOW     ; 99

	const BRIGHTPOWDER ; 9a
	const SCOPE_LENS   ; 9b
	const QUICK_CLAW   ; 9c
	const KINGS_ROCK   ; 9d
	const FOCUS_BAND   ; 9e
	const LEFTOVERS    ; 9f
	const LUCKY_EGG    ; a0
	const AMULET_COIN  ; a1
	const CLEANSE_TAG  ; a2
	const SMOKE_BALL   ; a3
	const BERSERK_GENE ; a4

	const LIGHT_BALL   ; a5
	const STICK        ; a6
	const THICK_CLUB   ; a7
	const LUCKY_PUNCH  ; a8
	const METAL_POWDER ; a9
	const QUICK_POWDER ; aa
	const ARMOR_SUIT   ; ab

	const AIR_BALLOON  ; ac
	const ASSAULT_VEST ; ad
	const BIG_ROOT     ; ae
	const BINDING_BAND ; af
	const DESTINY_KNOT ; b0
	const EVIOLITE     ; b1
	const EXPERT_BELT  ; b2
	const FOCUS_SASH   ; b3
	const GRIP_CLAW    ; b4
	const LIFE_ORB     ; b5
	const LIGHT_CLAY   ; b6
	const METRONOME_I  ; b7
	const MUSCLE_BAND  ; b8
	const PROTECT_PADS ; b9
	const ROCKY_HELMET ; ba
	const SAFE_GOGGLES ; bb
	const SHED_SHELL   ; bc
	const SHELL_BELL   ; bd
	const SOOTHE_BELL  ; be
	const WEAK_POLICY  ; bf
	const WIDE_LENS    ; c0
	const WISE_GLASSES ; c1
	const ZOOM_LENS    ; c2

	const MENTAL_HERB  ; c3
	const POWER_HERB   ; c4
	const WHITE_HERB   ; c5

	const DAMP_ROCK    ; c6
	const HEAT_ROCK    ; c7
	const SMOOTH_ROCK  ; c8
	const ICY_ROCK     ; c9

	const CHOICE_BAND  ; ca
	const CHOICE_SCARF ; cb
	const CHOICE_SPECS ; cc

	const FLAME_ORB    ; cd
	const TOXIC_ORB    ; ce
	const BLACK_SLUDGE ; cf

	const MACHO_BRACE  ; d0
	const POWER_WEIGHT ; d1
	const POWER_BRACER ; d2
	const POWER_BELT   ; d3
	const POWER_LENS   ; d4
	const POWER_BAND   ; d5
	const POWER_ANKLET ; d6

	const DRAGON_SCALE ; d7
	const UP_GRADE     ; d8
	const DUBIOUS_DISC ; d9
	const PROTECTOR    ; da
	const ELECTIRIZER  ; db
	const MAGMARIZER   ; dc
	const RAZOR_FANG   ; dd
	const RAZOR_CLAW   ; de
	const ODD_SOUVENIR ; df

	const NUGGET       ; e0
	const BIG_NUGGET   ; e1
	const TINYMUSHROOM ; e2
	const BIG_MUSHROOM ; e3
	const BALMMUSHROOM ; e4
	const PEARL        ; e5
	const BIG_PEARL    ; e6
	const PEARL_STRING ; e7
	const STARDUST     ; e8
	const STAR_PIECE   ; e9
	const BRICK_PIECE  ; ea
	const RARE_BONE    ; eb
	const SILVER_LEAF  ; ec
	const GOLD_LEAF    ; ed
	const SLOWPOKETAIL ; ee
	const BOTTLE_CAP   ; ef

	const HELIX_FOSSIL ; f0
	const DOME_FOSSIL  ; f1
	const OLD_AMBER    ; f2

	const MULCH        ; f3
	const SWEET_HONEY  ; f4

	const FLOWER_MAIL  ; f5
	const SURF_MAIL    ; f6
	const LITEBLUEMAIL ; f7
	const PORTRAITMAIL ; f8
	const LOVELY_MAIL  ; f9
	const EON_MAIL     ; fa
	const MORPH_MAIL   ; fb
	const BLUESKY_MAIL ; fc
	const MUSIC_MAIL   ; fd
	const MIRAGE_MAIL  ; fe
NUM_ITEMS EQU const_value +- 1

	const ITEM_FROM_MEM ; ff

; See data/items/name_order.asm
	const_def
	const NAM_NO_ITEM      ; 00
	const NAM_ABILITY_CAP  ; 01
	const NAM_AIR_BALLOON  ; 02
	const NAM_AMULET_COIN  ; 03
	const NAM_ANTIDOTE     ; 04
	const NAM_APICOT_BERRY ; 05
	const NAM_ARMOR_SUIT   ; 06
	const NAM_ASPEAR_BERRY ; 07
	const NAM_ASSAULT_VEST ; 08
	const NAM_AWAKENING    ; 09
	const NAM_BALMMUSHROOM ; 0a
	const NAM_BERSERK_GENE ; 0b
	const NAM_BIG_MUSHROOM ; 0c
	const NAM_BIG_NUGGET   ; 0d
	const NAM_BIG_PEARL    ; 0e
	const NAM_BIG_ROOT     ; 0f
	const NAM_BINDING_BAND ; 10
	const NAM_BLACK_BELT   ; 11
	const NAM_BLACK_SLUDGE ; 12
	const NAM_BLACKGLASSES ; 13
	const NAM_BLUESKY_MAIL ; 14
	const NAM_BOTTLE_CAP   ; 15
	const NAM_BRICK_PIECE  ; 16
	const NAM_BRIGHTPOWDER ; 17
	const NAM_BURN_HEAL    ; 18
	const NAM_CALCIUM      ; 19
	const NAM_CARBOS       ; 1a
	const NAM_CHARCOAL     ; 1b
	const NAM_CHERI_BERRY  ; 1c
	const NAM_CHERISH_BALL ; 1d
	const NAM_CHESTO_BERRY ; 1e
	const NAM_CHOICE_BAND  ; 1f
	const NAM_CHOICE_SCARF ; 20
	const NAM_CHOICE_SPECS ; 21
	const NAM_CLEANSE_TAG  ; 22
	const NAM_DAMP_ROCK    ; 23
	const NAM_DESTINY_KNOT ; 24
	const NAM_DIRE_HIT     ; 25
	const NAM_DIVE_BALL    ; 26
	const NAM_DOME_FOSSIL  ; 27
	const NAM_DRAGON_FANG  ; 28
	const NAM_DRAGON_SCALE ; 29
	const NAM_DUBIOUS_DISC ; 2a
	const NAM_DUSK_BALL    ; 2b
	const NAM_DUSK_STONE   ; 2c
	const NAM_ELECTIRIZER  ; 2d
	const NAM_ELIXIR       ; 2e
	const NAM_ENERGY_ROOT  ; 2f
	const NAM_ENERGYPOWDER ; 30
	const NAM_EON_MAIL     ; 31
	const NAM_ESCAPE_ROPE  ; 32
	const NAM_ETHER        ; 33
	const NAM_EVERSTONE    ; 34
	const NAM_EVIOLITE     ; 35
	const NAM_EXP_SHARE    ; 36
	const NAM_EXPERT_BELT  ; 37
	const NAM_FAST_BALL    ; 38
	const NAM_FIGY_BERRY   ; 39
	const NAM_FIRE_STONE   ; 3a
	const NAM_FLAME_ORB    ; 3b
	const NAM_FLOWER_MAIL  ; 3c
	const NAM_FOCUS_BAND   ; 3d
	const NAM_FOCUS_SASH   ; 3e
	const NAM_FRESH_WATER  ; 3f
	const NAM_FRIEND_BALL  ; 40
	const NAM_FULL_HEAL    ; 41
	const NAM_FULL_RESTORE ; 42
	const NAM_GANLON_BERRY ; 43
	const NAM_GOLD_LEAF    ; 44
	const NAM_GREAT_BALL   ; 45
	const NAM_GRIP_CLAW    ; 46
	const NAM_GUARD_SPEC   ; 47
	const NAM_HARD_STONE   ; 48
	const NAM_HEAL_BALL    ; 49
	const NAM_HEAL_POWDER  ; 4a
	const NAM_HEAT_ROCK    ; 4b
	const NAM_HEAVY_BALL   ; 4c
	const NAM_HELIX_FOSSIL ; 4d
	const NAM_HP_UP        ; 4e
	const NAM_HYPER_POTION ; 4f
	const NAM_ICE_HEAL     ; 50
	const NAM_ICE_STONE    ; 51
	const NAM_ICY_ROCK     ; 52
	const NAM_IRON         ; 53
	const NAM_JABOCA_BERRY ; 54
	const NAM_KEE_BERRY    ; 55
	const NAM_KINGS_ROCK   ; 56
	const NAM_LEAF_STONE   ; 57
	const NAM_LEFTOVERS    ; 58
	const NAM_LEMONADE     ; 59
	const NAM_LEPPA_BERRY  ; 5a
	const NAM_LEVEL_BALL   ; 5b
	const NAM_LIECHI_BERRY ; 5c
	const NAM_LIFE_ORB     ; 5d
	const NAM_LIGHT_BALL   ; 5e
	const NAM_LIGHT_CLAY   ; 5f
	const NAM_LITEBLUEMAIL ; 60
	const NAM_LOVE_BALL    ; 61
	const NAM_LOVELY_MAIL  ; 62
	const NAM_LUCKY_EGG    ; 63
	const NAM_LUCKY_PUNCH  ; 64
	const NAM_LUM_BERRY    ; 65
	const NAM_LURE_BALL    ; 66
	const NAM_LUXURY_BALL  ; 67
	const NAM_MACHO_BRACE  ; 68
	const NAM_MAGMARIZER   ; 69
	const NAM_MAGNET       ; 6a
	const NAM_MARANGABERRY ; 6b
	const NAM_MASTER_BALL  ; 6c
	const NAM_MAX_ELIXIR   ; 6d
	const NAM_MAX_ETHER    ; 6e
	const NAM_MAX_POTION   ; 6f
	const NAM_MAX_REPEL    ; 70
	const NAM_MAX_REVIVE   ; 71
	const NAM_MENTAL_HERB  ; 72
	const NAM_METAL_COAT   ; 73
	const NAM_METAL_POWDER ; 74
	const NAM_METRONOME_I  ; 75
	const NAM_MIRACLE_SEED ; 76
	const NAM_MIRAGE_MAIL  ; 77
	const NAM_MOOMOO_MILK  ; 78
	const NAM_MOON_BALL    ; 79
	const NAM_MOON_STONE   ; 7a
	const NAM_MORPH_MAIL   ; 7b
	const NAM_MULCH        ; 7c
	const NAM_MUSCLE_BAND  ; 7d
	const NAM_MUSIC_MAIL   ; 7e
	const NAM_MYSTIC_WATER ; 7f
	const NAM_NEST_BALL    ; 80
	const NAM_NET_BALL     ; 81
	const NAM_NEVERMELTICE ; 82
	const NAM_NUGGET       ; 83
	const NAM_ODD_SOUVENIR ; 84
	const NAM_OLD_AMBER    ; 85
	const NAM_ORAN_BERRY   ; 86
	const NAM_PARALYZEHEAL ; 87
	const NAM_PARK_BALL    ; 88
	const NAM_PEARL        ; 89
	const NAM_PEARL_STRING ; 8a
	const NAM_PECHA_BERRY  ; 8b
	const NAM_PERSIM_BERRY ; 8c
	const NAM_PETAYA_BERRY ; 8d
	const NAM_PEWTERCRUNCH ; 8e
	const NAM_PINK_BOW     ; 8f
	const NAM_POISON_BARB  ; 90
	const NAM_POKE_BALL    ; 91
	const NAM_POKE_DOLL    ; 92
	const NAM_PORTRAITMAIL ; 93
	const NAM_POTION       ; 94
	const NAM_POWER_ANKLET ; 95
	const NAM_POWER_BAND   ; 96
	const NAM_POWER_BELT   ; 97
	const NAM_POWER_BRACER ; 98
	const NAM_POWER_HERB   ; 99
	const NAM_POWER_LENS   ; 9a
	const NAM_POWER_WEIGHT ; 9b
	const NAM_PP_MAX       ; 9c
	const NAM_PP_UP        ; 9d
	const NAM_PREMIER_BALL ; 9e
	const NAM_PROTECT_PADS ; 9f
	const NAM_PROTECTOR    ; a0
	const NAM_PROTEIN      ; a1
	const NAM_QUICK_BALL   ; a2
	const NAM_QUICK_CLAW   ; a3
	const NAM_QUICK_POWDER ; a4
	const NAM_RAGECANDYBAR ; a5
	const NAM_RARE_BONE    ; a6
	const NAM_RARE_CANDY   ; a7
	const NAM_RAWST_BERRY  ; a8
	const NAM_RAZOR_CLAW   ; a9
	const NAM_RAZOR_FANG   ; aa
	const NAM_REPEAT_BALL  ; ab
	const NAM_REPEL        ; ac
	const NAM_REVIVAL_HERB ; ad
	const NAM_REVIVE       ; ae
	const NAM_ROCKY_HELMET ; af
	const NAM_ROWAP_BERRY  ; b0
	const NAM_SACRED_ASH   ; b1
	const NAM_SAFARI_BALL  ; b2
	const NAM_SAFE_GOGGLES ; b3
	const NAM_SALAC_BERRY  ; b4
	const NAM_SCOPE_LENS   ; b5
	const NAM_SHARP_BEAK   ; b6
	const NAM_SHED_SHELL   ; b7
	const NAM_SHELL_BELL   ; b8
	const NAM_SHINY_STONE  ; b9
	const NAM_SILK_SCARF   ; ba
	const NAM_SILVER_LEAF  ; bb
	const NAM_SILVERPOWDER ; bc
	const NAM_SITRUS_BERRY ; bd
	const NAM_SLOWPOKETAIL ; be
	const NAM_SMOKE_BALL   ; bf
	const NAM_SMOOTH_ROCK  ; c0
	const NAM_SODA_POP     ; c1
	const NAM_SOFT_SAND    ; c2
	const NAM_SOOTHE_BELL  ; c3
	const NAM_SPELL_TAG    ; c4
	const NAM_STAR_PIECE   ; c5
	const NAM_STARDUST     ; c6
	const NAM_STICK        ; c7
	const NAM_SUN_STONE    ; c8
	const NAM_SUPER_POTION ; c9
	const NAM_SUPER_REPEL  ; ca
	const NAM_SURF_MAIL    ; cb
	const NAM_SWEET_HONEY  ; cc
	const NAM_THICK_CLUB   ; cd
	const NAM_THUNDERSTONE ; ce
	const NAM_TIMER_BALL   ; cf
	const NAM_TINYMUSHROOM ; d0
	const NAM_TOXIC_ORB    ; d1
	const NAM_TWISTEDSPOON ; d2
	const NAM_ULTRA_BALL   ; d3
	const NAM_UP_GRADE     ; d4
	const NAM_WATER_STONE  ; d5
	const NAM_WEAK_POLICY  ; d6
	const NAM_WIDE_LENS    ; d7
	const NAM_WISE_GLASSES ; d8
	const NAM_WHITE_HERB   ; d9
	const NAM_X_ACCURACY   ; da
	const NAM_X_ATTACK     ; db
	const NAM_X_DEFEND     ; dc
	const NAM_X_SPCL_ATK   ; dd
	const NAM_X_SPCL_DEF   ; de
	const NAM_X_SPEED      ; df
	const NAM_ZINC         ; e0
	const NAM_ZOOM_LENS    ; e1
	const NAM_TERU_SAMA_01 ; e2
	const NAM_TERU_SAMA_02 ; e3
	const NAM_TERU_SAMA_03 ; e4
	const NAM_TERU_SAMA_04 ; e5
	const NAM_TERU_SAMA_05 ; e6
	const NAM_TERU_SAMA_06 ; e7
	const NAM_TERU_SAMA_07 ; e8
	const NAM_TERU_SAMA_08 ; e9
	const NAM_TERU_SAMA_09 ; ea
	const NAM_TERU_SAMA_10 ; eb
	const NAM_TERU_SAMA_11 ; ec
	const NAM_TERU_SAMA_12 ; ed
	const NAM_TERU_SAMA_13 ; ee
	const NAM_TERU_SAMA_14 ; ef
	const NAM_TERU_SAMA_15 ; f0
	const NAM_TERU_SAMA_16 ; f1
	const NAM_TERU_SAMA_17 ; f2
	const NAM_TERU_SAMA_18 ; f3
	const NAM_TERU_SAMA_19 ; f4
	const NAM_TERU_SAMA_20 ; f5
	const NAM_TERU_SAMA_21 ; f6
	const NAM_TERU_SAMA_22 ; f7
	const NAM_TERU_SAMA_23 ; f8
	const NAM_TERU_SAMA_24 ; f9
	const NAM_TERU_SAMA_25 ; fa
	const NAM_TERU_SAMA_26 ; fb
	const NAM_TERU_SAMA_27 ; fc
	const NAM_TERU_SAMA_28 ; fd
	const NAM_TERU_SAMA_29 ; fe

; APRICORN_BOX contents
	const_def 1
	const RED_APRICORN ; 1
	const BLU_APRICORN ; 2
	const YLW_APRICORN ; 3
	const GRN_APRICORN ; 4
	const WHT_APRICORN ; 5
	const BLK_APRICORN ; 6
	const PNK_APRICORN ; 7
NUM_APRICORNS EQU const_value +- 1

; Key Item constants
	const_def
	const BICYCLE      ; 00
	const OLD_ROD      ; 01
	const GOOD_ROD     ; 02
	const SUPER_ROD    ; 03
	const COIN_CASE    ; 04
	const ITEMFINDER   ; 05
	const MYSTERY_EGG  ; 06
	const SQUIRTBOTTLE ; 07
	const SECRETPOTION ; 08
	const RED_SCALE    ; 09
	const CARD_KEY     ; 0a
	const BASEMENT_KEY ; 0b
	const S_S_TICKET   ; 0c
	const PASS         ; 0d
	const MACHINE_PART ; 0e
	const LOST_ITEM    ; 0f
	const RAINBOW_WING ; 10
	const SILVER_WING  ; 11
	const CLEAR_BELL   ; 12
	const GS_BALL      ; 13
	const BLUE_CARD    ; 14
	const ORANGETICKET ; 15
	const MYSTICTICKET ; 16
	const OLD_SEA_MAP  ; 17
	const SHINY_CHARM  ; 18
	const OVAL_CHARM   ; 19
	const SILPHSCOPE2  ; 1a
	const APRICORN_BOX ; 1b
NUM_KEY_ITEMS EQU const_value +- 1
