
	const_def

	const SPECIAL_MAP       ; 00
	const NEW_BARK_TOWN     ; 01
	const ROUTE_29          ; 02
	const CHERRYGROVE_CITY  ; 03
	const CHERRYGROVE_BAY   ; 04
	const ROUTE_30          ; 05
	const ROUTE_31          ; 06
	const VIOLET_CITY       ; 07
	const SPROUT_TOWER      ; 08
	const ROUTE_32          ; 09
	const RUINS_OF_ALPH     ; 0a
	const UNION_CAVE        ; 0b
	const ROUTE_33          ; 0c
	const AZALEA_TOWN       ; 0d
	const SLOWPOKE_WELL     ; 0e
	const ILEX_FOREST       ; 0f
	const ROUTE_34          ; 10
	const GOLDENROD_CITY    ; 11
	const RADIO_TOWER       ; 12
	const GOLDENROD_HARBOR  ; 13
	const ROUTE_35          ; 14
	const NATIONAL_PARK     ; 15
	const ROUTE_36          ; 16
	const ROUTE_37          ; 17
	const ECRUTEAK_CITY     ; 18
	const BELLCHIME_TRAIL   ; 19
	const TIN_TOWER         ; 1a
	const BURNED_TOWER      ; 1b
	const ROUTE_38          ; 1c
	const ROUTE_39          ; 1d
	const OLIVINE_CITY      ; 1e
	const LIGHTHOUSE        ; 1f
	const ROUTE_40          ; 20
	const BATTLE_TOWER      ; 21
	const WHIRL_ISLANDS     ; 22
	const ROUTE_41          ; 23
	const CIANWOOD_CITY     ; 24
	const CLIFF_EDGE_GATE   ; 25
	const ROUTE_47          ; 26
	const CLIFF_CAVE        ; 27
	const ROUTE_48          ; 28
	const YELLOW_FOREST     ; 29
	const QUIET_CAVE        ; 2a
	const ROUTE_42          ; 2b
	const MT_MORTAR         ; 2c
	const MAHOGANY_TOWN     ; 2d
	const ROUTE_43          ; 2e
	const LAKE_OF_RAGE      ; 2f
	const ROUTE_44          ; 30
	const ICE_PATH          ; 31
	const BLACKTHORN_CITY   ; 32
	const DRAGONS_DEN       ; 33
	const ROUTE_45          ; 34
	const DARK_CAVE         ; 35
	const ROUTE_46          ; 36
	const SILVER_CAVE       ; 37

KANTO_LANDMARK EQU const_value

	const PALLET_TOWN       ; 38
	const ROUTE_1           ; 39
	const VIRIDIAN_CITY     ; 3a
	const ROUTE_2           ; 3b
	const VIRIDIAN_FOREST   ; 3c
	const PEWTER_CITY       ; 3d
	const ROUTE_3           ; 3e
	const MT_MOON           ; 3f
	const ROUTE_4           ; 40
	const CERULEAN_CITY     ; 41
	const CERULEAN_CAVE     ; 42
	const ROUTE_24          ; 43
	const ROUTE_25          ; 44
	const ROUTE_5           ; 45
	const UNDERGROUND       ; 46
	const ROUTE_6           ; 47
	const VERMILION_CITY    ; 48
	const DIGLETTS_CAVE     ; 49
	const ROUTE_7           ; 4a
	const ROUTE_8           ; 4b
	const ROUTE_9           ; 4c
	const ROCK_TUNNEL       ; 4d
	const ROUTE_10          ; 4e
	const POWER_PLANT       ; 4f
	const LAVENDER_TOWN     ; 50
	const LAV_RADIO_TOWER   ; 51
	const CELADON_CITY      ; 52
	const SAFFRON_CITY      ; 53
	const ROUTE_11          ; 54
	const ROUTE_12          ; 55
	const ROUTE_13          ; 56
	const ROUTE_14          ; 57
	const ROUTE_15          ; 58
	const ROUTE_16          ; 59
	const ROUTE_17          ; 5a
	const ROUTE_18          ; 5b
	const FUCHSIA_CITY      ; 5c
	const SAFARI_ZONE       ; 5d
	const ROUTE_19          ; 5e
	const ROUTE_20          ; 5f
	const SEAFOAM_ISLANDS   ; 60
	const CINNABAR_ISLAND   ; 61
	const CINNABAR_VOLCANO  ; 62
	const POKEMON_MANSION   ; 63
	const ROUTE_21          ; 64
	const ROUTE_22          ; 65
	const VICTORY_ROAD      ; 66
	const ROUTE_23          ; 67
	const INDIGO_PLATEAU    ; 68
	const ROUTE_26          ; 69
	const ROUTE_27          ; 6a
	const TOHJO_FALLS       ; 6b
	const ROUTE_28          ; 6c
	const FAST_SHIP         ; 6d
	const NAVEL_ROCK        ; 6e
