
	const_def

	const SPECIAL_MAP        ; 00
	const NEW_BARK_TOWN      ; 01
	const ROUTE_29           ; 02
	const CHERRYGROVE_CITY   ; 03
	const CHERRYGROVE_BAY    ; 04
	const ROUTE_30           ; 05
	const ROUTE_31           ; 06
	const VIOLET_CITY        ; 07
	const SPROUT_TOWER       ; 08
	const ROUTE_32           ; 09
	const ROUTE_32_COAST     ; 0a
	const RUINS_OF_ALPH      ; 0b
	const UNION_CAVE         ; 0c
	const ROUTE_33           ; 0d
	const AZALEA_TOWN        ; 0e
	const SLOWPOKE_WELL      ; 0f
	const ILEX_FOREST        ; 10
	const ROUTE_34           ; 11
	const ROUTE_34_COAST     ; 12
	const STORMY_BEACH       ; 13
	const MURKY_SWAMP        ; 14
	const GOLDENROD_CITY     ; 15
	const RADIO_TOWER        ; 16
	const GOLDENROD_HARBOR   ; 17
	const ROUTE_35           ; 18
	const ROUTE_35_COAST     ; 19
	const NATIONAL_PARK      ; 1a
	const ROUTE_36           ; 1b
	const ROUTE_37           ; 1c
	const ECRUTEAK_CITY      ; 1d
	const BELLCHIME_TRAIL    ; 1e
	const TIN_TOWER          ; 1f
	const BURNED_TOWER       ; 20
	const ROUTE_38           ; 21
	const ROUTE_39           ; 22
	const OLIVINE_CITY       ; 23
	const LIGHTHOUSE         ; 24
	const ROUTE_40           ; 25
	const BATTLE_TOWER       ; 26
	const WHIRL_ISLANDS      ; 27
	const ROUTE_41           ; 28
	const CIANWOOD_CITY      ; 29
	const CLIFF_EDGE_GATE    ; 2a
	const ROUTE_47           ; 2b
	const CLIFF_CAVE         ; 2c
	const ROUTE_48           ; 2d
	const YELLOW_FOREST      ; 2e
	const QUIET_CAVE         ; 2f
	const ROUTE_42           ; 30
	const MT_MORTAR          ; 31
	const MAHOGANY_TOWN      ; 32
	const ROUTE_43           ; 33
	const LAKE_OF_RAGE       ; 34
	const ROUTE_44           ; 35
	const ICE_PATH           ; 36
	const BLACKTHORN_CITY    ; 37
	const DRAGONS_DEN        ; 38
	const ROUTE_45           ; 39
	const DARK_CAVE          ; 3a
	const ROUTE_46           ; 3b
	const SILVER_CAVE        ; 3c
	const SINJOH_RUINS       ; 3d
	const MYSTRI_STAGE       ; 3e

KANTO_LANDMARK EQU const_value

	const PALLET_TOWN        ; 3f
	const ROUTE_1            ; 40
	const VIRIDIAN_CITY      ; 41
	const ROUTE_2            ; 42
	const VIRIDIAN_FOREST    ; 43
	const PEWTER_CITY        ; 44
	const ROUTE_3            ; 45
	const MT_MOON            ; 46
	const ROUTE_4            ; 47
	const CERULEAN_CITY      ; 48
	const CERULEAN_CAVE      ; 49
	const ROUTE_24           ; 4a
	const ROUTE_25           ; 4b
	const CERULEAN_CAPE      ; 4c
	const ROUTE_5            ; 4d
	const UNDERGROUND        ; 4e
	const ROUTE_6            ; 4f
	const VERMILION_CITY     ; 50
	const DIGLETTS_CAVE      ; 51
	const ROUTE_7            ; 52
	const ROUTE_8            ; 53
	const ROUTE_9            ; 54
	const ROUTE_10           ; 55
	const ROCK_TUNNEL        ; 56
	const POWER_PLANT        ; 57
	const DIM_CAVE           ; 58
	const LAVENDER_TOWN      ; 59
	const LAV_RADIO_TOWER    ; 5a
	const SOUL_HOUSE         ; 5b
	const CELADON_CITY       ; 5c
	const CELADON_UNIVERSITY ; 5d
	const SAFFRON_CITY       ; 5e
	const ROUTE_11           ; 5f
	const ROUTE_12           ; 60
	const ROUTE_13           ; 61
	const ROUTE_14           ; 62
	const ROUTE_15           ; 63
	const LUCKY_ISLAND       ; 64
	const ROUTE_16           ; 65
	const ROUTE_17           ; 66
	const ROUTE_18           ; 67
	const FUCHSIA_CITY       ; 68
	const SAFARI_ZONE        ; 69
	const URAGA_CHANNEL      ; 6a
	const SCARY_CAVE         ; 6b
	const ROUTE_19           ; 6c
	const ROUTE_20           ; 6d
	const SEAFOAM_ISLANDS    ; 6e
	const CINNABAR_ISLAND    ; 6f
	const POKEMON_MANSION    ; 70
	const CINNABAR_VOLCANO   ; 71
	const ROUTE_21           ; 72
	const ROUTE_22           ; 73
	const ROUTE_27           ; 74
	const TOHJO_FALLS        ; 75
	const ROUTE_26           ; 76
	const POKEMON_LEAGUE     ; 77
	const ROUTE_23           ; 78
	const VICTORY_ROAD       ; 79
	const INDIGO_PLATEAU     ; 7a
	const ROUTE_28           ; 7b

SHAMOUTI_LANDMARK EQU const_value

	const SHAMOUTI_ISLAND    ; 7c
	const BEAUTIFUL_BEACH    ; 7d
	const SHAMOUTI_TUNNEL    ; 7e
	const WARM_BEACH         ; 7f
	const ROCKY_BEACH        ; 80
	const NOISY_FOREST       ; 81
	const SHRINE_RUINS       ; 82
	const FAST_SHIP          ; 83
	const NAVEL_ROCK         ; 84
	const FARAWAY_ISLAND     ; 85
	const CINNABAR_LAB       ; 86

NUM_LANDMARKS EQU const_value
