; see engine/map_setup.asm:MapSetupScripts
	const_def $f1
	const MAPSETUP_WARP
	const MAPSETUP_CONTINUE
	const MAPSETUP_RELOADMAP
	const MAPSETUP_TELEPORT
	const MAPSETUP_DOOR
	const MAPSETUP_FALL
	const MAPSETUP_CONNECTION
	const MAPSETUP_LINKRETURN
	const MAPSETUP_TRAIN
	const MAPSETUP_SUBMENU
	const MAPSETUP_BADWARP
	const MAPSETUP_FLY

	const_def 1
	const MAPCALLBACK_TILES
	const MAPCALLBACK_OBJECTS
	const MAPCALLBACK_STONETABLE
	const MAPCALLBACK_SPRITES
	const MAPCALLBACK_NEWMAP
