; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_SILPH
	const MARTTYPE_ADVENTURER
	const MARTTYPE_INFORMAL
	const MARTTYPE_BAZAAR
	const MARTTYPE_TM
	const MARTTYPE_BLUECARD
	const MARTTYPE_BP

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_CHERRYGROVE
	const MART_CHERRYGROVE_DEX
	const MART_VIOLET
	const MART_AZALEA
	const MART_GOLDENROD_2F_1
	const MART_GOLDENROD_2F_2
	const MART_GOLDENROD_2F_2_EEVEE
	const MART_GOLDENROD_3F
	const MART_GOLDENROD_4F
	const MART_GOLDENROD_5F_TM
	const MART_GOLDENROD_HARBOR
	const MART_UNDERGROUND
	const MART_ECRUTEAK
	const MART_OLIVINE
	const MART_CIANWOOD
	const MART_YELLOW_FOREST
	const MART_MAHOGANY_1
	const MART_MAHOGANY_2
	const MART_BLACKTHORN
	const MART_INDIGO_PLATEAU
	const MART_VIRIDIAN
	const MART_PEWTER
	const MART_MT_MOON
	const MART_CERULEAN
	const MART_LAVENDER
	const MART_VERMILION
	const MART_CELADON_2F_1
	const MART_CELADON_2F_2
	const MART_CELADON_3F_TM
	const MART_CELADON_4F
	const MART_CELADON_5F_1
	const MART_CELADON_5F_2
	const MART_SAFFRON
	const MART_SILPH_CO
	const MART_FUCHSIA
	const MART_SHAMOUTI_1
	const MART_SHAMOUTI_2
	const MART_BT_1
	const MART_BT_2
	const MART_BT_3
NUM_MARTS EQU const_value
