; Boolean checks
FALSE EQU 0
TRUE  EQU 1

; flag manipulation
RESET_FLAG EQU 0
SET_FLAG   EQU 1
CHECK_FLAG EQU 2

SAVE_CHECK_VALUE_1 EQU 99
SAVE_CHECK_VALUE_2 EQU 127

HMENURETURN_SCRIPT EQU %10000000
HMENURETURN_ASM    EQU %11111111

MORN_HOUR EQU  5 ; 5 AM - 9 AM (4 hours)
DAY_HOUR  EQU  9 ; 9 AM - 5 PM (8 hours)
EVE_HOUR  EQU 17 ; 5 PM - 9 PM (4 hours)
NITE_HOUR EQU 21 ; 9 PM - 5 AM (8 hours)

if DEF(NO_RTC)
NO_RTC_SPEEDUP EQU 6
endc

	const_def
	const ERR_RST_0
	const ERR_DIV_ZERO
	const ERR_EGG_SPECIES
	const ERR_EXECUTING_RAM
	const ERR_STACK_OVERFLOW
	const ERR_STACK_UNDERFLOW
	const ERR_BT_STATE
FIRST_VBLANK_ERR EQU ERR_EXECUTING_RAM
