; New mobile
	const_def 1
	const MOBILE_RECEIVING
	const MOBILE_SENDING
	const MOBILE_STANDBY

DEF MOBILE_USEFUL_F EQU 6
DEF MOBILE_NEXTBYTE_F EQU 7

DEF MOBILE_COMMAND_BEGIN_SESSION            EQU $10
DEF MOBILE_COMMAND_END_SESSION              EQU $11
DEF MOBILE_COMMAND_DIAL_TELEPHONE           EQU $12
DEF MOBILE_COMMAND_HANG_UP_TELEPHONE        EQU $13
DEF MOBILE_COMMAND_WAIT_FOR_TELEPHONE_CALL  EQU $14
DEF MOBILE_COMMAND_TRANSFER_DATA            EQU $15
DEF MOBILE_COMMAND_TELEPHONE_STATUS         EQU $17
DEF MOBILE_COMMAND_READ_CONFIGURATION_DATA  EQU $19
DEF MOBILE_COMMAND_WRITE_CONFIGURATION_DATA EQU $1a
DEF MOBILE_COMMAND_TRANSFER_DATA_END        EQU $1f
DEF MOBILE_COMMAND_ISP_LOGIN                EQU $21
DEF MOBILE_COMMAND_ISP_LOGOUT               EQU $22
DEF MOBILE_COMMAND_OPEN_TCP_CONNECTION      EQU $23
DEF MOBILE_COMMAND_CLOSE_TCP_CONNECTION     EQU $24
DEF MOBILE_COMMAND_DNS_QUERY                EQU $28

DEF MOBILE_DEVICE_CGB                       EQU $80
DEF MOBILE_DEVICE_AGB                       EQU $81
DEF MOBILE_DEVICE_PDC                       EQU $88
DEF MOBILE_DEVICE_CDMA                      EQU $89
DEF MOBILE_DEVICE_PHS                       EQU $8a
DEF MOBILE_DEVICE_DDI                       EQU $8b

DEF MOBILE_ERROR_COMMAND                    EQU $6e
DEF MOBILE_ERROR_CHECKSUM                   EQU $71

; Bytes sent by the non-communicating device.
; RECV is sent by the GameBoy, SEND by the Adapter
DEF MOBILE_RECV_BYTE                        EQU $4b
DEF MOBILE_SEND_BYTE                        EQU $d2
DEF MOBILE_MAX_PACKET_SIZE                  EQU $fe
DEF MOBILE_CONFIGURATION_SIZE               EQU $c0

DEF MACFG_HEADER        EQU $00
DEF MACFG_REGISTERED    EQU $02
DEF MACFG_PRIMARY_DNS   EQU $04
DEF MACFG_SECONDARY_DNS EQU $08
DEF MACFG_LOGIN         EQU $0c
DEF MACFG_EMAIL         EQU $2c
DEF MACFG_SMTP          EQU $4a
DEF MACFG_POP           EQU $5e
DEF MACFG_PHONE1        EQU $76
DEF MACFG_PHONE2        EQU $8e
DEF MACFG_PHONE3        EQU $a6
DEF MACFG_CHECKSUM      EQU $be

DEF MOBILE_CONFIG_PHONE_BYTES EQU 8
DEF MOBILE_CONFIG_LOGIN_BYTES EQU 10
DEF MOBILE_CONFIG_IS_REGISTERED EQU $81

; wMobileLightsFlags
	const_def
	const MOBILE_LIGHTS_CYCLE_DOWN_F ; 0
