; Generated by utils/music_huffman.py; do not edit manually.
; Source corpus: MUSIC_HUFFMAN byte log from the assembled music streams.
; 127 direct leaves plus one raw-byte escape leaf.
; Longest encoded byte: 13 bits.

musichuffleaf 01011
musichuffmap $00, 0, 11100 ; 6110
musichuffmap $01, 1, 00001 ; 3486
musichuffmap $02, 2, 1000101 ; 1159
musichuffmap $03, 3, 1010101 ; 1257
musichuffmap $04, 4, 00000101 ; 428
musichuffmap $05, 5, 110101101 ; 370
musichuffmap $06, 6, 10010101 ; 600
musichuffmap $07, 7, 100101001 ; 297
musichuffmap $08, 8, 10000001 ; 557
musichuffmap $09, 9, 1001100000 ; 150
musichuffmap $0b, 10, 1000000000 ; 137
musichuffmap $0c, 11, 001001 ; 1805
musichuffmap $0f, 12, 0010000 ; 884
musichuffmap $10, 13, 110100 ; 2908
musichuffmap $11, 14, 00011 ; 3540
musichuffmap $12, 15, 10011001 ; 608
musichuffmap $13, 16, 000000 ; 1710
musichuffmap $14, 17, 011101011 ; 272
musichuffmap $15, 18, 01110100 ; 519
musichuffmap $17, 19, 01010101 ; 518
musichuffmap $19, 20, 1100110010 ; 176
musichuffmap $1f, 21, 1100110011 ; 178
musichuffmap $20, 22, 011110 ; 2158
musichuffmap $21, 23, 011111 ; 2195
musichuffmap $22, 24, 111100110 ; 417
musichuffmap $23, 25, 0100000 ; 900
musichuffmap $24, 26, 1011011110 ; 168
musichuffmap $25, 27, 110000101 ; 352
musichuffmap $27, 28, 101010011 ; 311
musichuffmap $30, 29, 101100 ; 2564
musichuffmap $31, 30, 00010 ; 3519
musichuffmap $32, 31, 000001100 ; 214
musichuffmap $33, 32, 1000001 ; 1109
musichuffmap $35, 33, 101101001 ; 315
musichuffmap $37, 34, 101101101 ; 326
musichuffmap $39, 35, 0100101111 ; 121
musichuffmap $3f, 36, 1001100001 ; 152
musichuffmap $40, 37, 101011 ; 2557
musichuffmap $41, 38, 111011 ; 3221
musichuffmap $42, 39, 1010100100 ; 152
musichuffmap $43, 40, 0110011 ; 1036
musichuffmap $45, 41, 100010001 ; 283
musichuffmap $47, 42, 101101011 ; 325
musichuffmap $4f, 43, 1001010001 ; 146
musichuffmap $50, 44, 011000 ; 2039
musichuffmap $51, 45, 110110 ; 3004
musichuffmap $52, 46, 1011011111 ; 168
musichuffmap $53, 47, 0110010 ; 1021
musichuffmap $55, 48, 100000001 ; 276
musichuffmap $57, 49, 110011000 ; 354
musichuffmap $5f, 50, 1000100000 ; 139
musichuffmap $60, 51, 1101010 ; 1492
musichuffmap $61, 52, 100111 ; 2446
musichuffmap $62, 53, 1101011000 ; 183
musichuffmap $63, 54, 0111011 ; 1078
musichuffmap $65, 55, 010010101 ; 239
musichuffmap $67, 56, 101101110 ; 330
musichuffmap $6f, 57, 1000100001 ; 143
musichuffmap $70, 58, 1100111 ; 1446
musichuffmap $71, 59, 011100 ; 2105
musichuffmap $72, 60, 1010100101 ; 156
musichuffmap $73, 61, 11101001 ; 769
musichuffmap $75, 62, 1110101011 ; 198
musichuffmap $77, 63, 111100111 ; 419
musichuffmap $80, 64, 110111 ; 3035
musichuffmap $81, 65, 00101 ; 3629
musichuffmap $82, 66, 110000011 ; 342
musichuffmap $83, 67, 1001101 ; 1223
musichuffmap $84, 68, 0000011101 ; 108
musichuffmap $85, 69, 101101100 ; 325
musichuffmap $87, 70, 01001000 ; 456
musichuffmap $8f, 71, 1000000001 ; 137
musichuffmap $90, 72, 1111010 ; 1675
musichuffmap $91, 73, 011010 ; 2066
musichuffmap $92, 74, 010101000 ; 246
musichuffmap $93, 75, 11010111 ; 754
musichuffmap $95, 76, 010010100 ; 225
musichuffmap $97, 77, 111010100 ; 389
musichuffmap $a0, 78, 011011 ; 2073
musichuffmap $a1, 79, 110010 ; 2822
musichuffmap $a2, 80, 110011011 ; 365
musichuffmap $a3, 81, 0101011 ; 1018
musichuffmap $a4, 82, 0100101110 ; 120
musichuffmap $a5, 83, 100110001 ; 304
musichuffmap $a7, 84, 10101000 ; 609
musichuffmap $af, 85, 0101010010 ; 121
musichuffmap $b0, 86, 010001 ; 1843
musichuffmap $b1, 87, 100001 ; 2269
musichuffmap $b2, 88, 00000100 ; 424
musichuffmap $b3, 89, 1001011 ; 1197
musichuffmap $b4, 90, 1110101111 ; 209
musichuffmap $b5, 91, 110011010 ; 361
musichuffmap $b7, 92, 11110010 ; 814
musichuffmap $bf, 93, 0000011100 ; 107
musichuffmap $c0, 94, 010100 ; 1907
musichuffmap $c1, 95, 100011 ; 2325
musichuffmap $c2, 96, 01001001 ; 460
musichuffmap $c3, 97, 0100001 ; 909
musichuffmap $c4, 98, 000001111 ; 221
musichuffmap $c5, 99, 101101010 ; 322
musichuffmap $c7, 100, 0010001 ; 893
musichuffmap $c8, 101, 1001010000 ; 145
musichuffmap $d2, 102, 111010110 ; 401
musichuffmap $d3, 103, 010011 ; 1881
musichuffmap $d4, 104, 10111 ; 5332
musichuffmap $d5, 105, 0011 ; 7291
musichuffmap $d6, 106, 10100 ; 4946
musichuffmap $d7, 107, 1111011 ; 1693
musichuffmap $d8, 108, 011101010 ; 256
musichuffmap $d9, 109, 010010110 ; 240
musichuffmap $da, 110, 110000010 ; 341
musichuffmap $db, 111, 101101000 ; 314
musichuffmap $dc, 112, 110001 ; 2797
musichuffmap $de, 113, 1110101110 ; 203
musichuffmap $df, 114, 11111 ; 6681
musichuffmap $e4, 115, 10001001 ; 572
musichuffmap $e5, 116, 0101010011 ; 128
musichuffmap $e6, 117, 1100001001 ; 173
musichuffmap $e7, 118, 000001101 ; 214
musichuffmap $ed, 119, 1110101010 ; 195
musichuffmap $ee, 120, 1101011001 ; 185
musichuffmap $ef, 121, 1100001000 ; 170
musichuffmap $f8, 122, 1111000 ; 1609
musichuffmap $fc, 123, 11000000 ; 680
musichuffmap $fd, 124, 11000011 ; 700
musichuffmap $fe, 125, 100100 ; 2352
musichuffmap $ff, 126, 11101000 ; 767
musichuffesc $0a, 0101100001010 ; 69
musichuffesc $0d, 0101100001101 ; 62
musichuffesc $0e, 0101100001110 ; 50
musichuffesc $16, 0101100010110 ; 101
musichuffesc $18, 0101100011000 ; 20
musichuffesc $1a, 0101100011010 ; 14
musichuffesc $1b, 0101100011011 ; 87
musichuffesc $1c, 0101100011100 ; 19
musichuffesc $1d, 0101100011101 ; 9
musichuffesc $1e, 0101100011110 ; 5
musichuffesc $26, 0101100100110 ; 47
musichuffesc $28, 0101100101000 ; 13
musichuffesc $29, 0101100101001 ; 47
musichuffesc $2a, 0101100101010 ; 13
musichuffesc $2b, 0101100101011 ; 64
musichuffesc $2c, 0101100101100 ; 1
musichuffesc $2d, 0101100101101 ; 5
musichuffesc $2e, 0101100101110 ; 7
musichuffesc $2f, 0101100101111 ; 85
musichuffesc $34, 0101100110100 ; 69
musichuffesc $36, 0101100110110 ; 46
musichuffesc $38, 0101100111000 ; 18
musichuffesc $3a, 0101100111010 ; 13
musichuffesc $3b, 0101100111011 ; 103
musichuffesc $3c, 0101100111100 ; 4
musichuffesc $3d, 0101100111101 ; 16
musichuffesc $3e, 0101100111110 ; 8
musichuffesc $44, 0101101000100 ; 45
musichuffesc $46, 0101101000110 ; 19
musichuffesc $48, 0101101001000 ; 21
musichuffesc $49, 0101101001001 ; 39
musichuffesc $4a, 0101101001010 ; 12
musichuffesc $4b, 0101101001011 ; 91
musichuffesc $4c, 0101101001100 ; 10
musichuffesc $4d, 0101101001101 ; 8
musichuffesc $4e, 0101101001110 ; 10
musichuffesc $54, 0101101010100 ; 34
musichuffesc $56, 0101101010110 ; 23
musichuffesc $58, 0101101011000 ; 17
musichuffesc $59, 0101101011001 ; 77
musichuffesc $5a, 0101101011010 ; 30
musichuffesc $5b, 0101101011011 ; 71
musichuffesc $5c, 0101101011100 ; 3
musichuffesc $5d, 0101101011101 ; 26
musichuffesc $5e, 0101101011110 ; 10
musichuffesc $64, 0101101100100 ; 50
musichuffesc $66, 0101101100110 ; 20
musichuffesc $68, 0101101101000 ; 13
musichuffesc $69, 0101101101001 ; 35
musichuffesc $6a, 0101101101010 ; 10
musichuffesc $6b, 0101101101011 ; 67
musichuffesc $6c, 0101101101100 ; 8
musichuffesc $6d, 0101101101101 ; 14
musichuffesc $6e, 0101101101110 ; 7
musichuffesc $74, 0101101110100 ; 55
musichuffesc $76, 0101101110110 ; 15
musichuffesc $78, 0101101111000 ; 20
musichuffesc $79, 0101101111001 ; 17
musichuffesc $7a, 0101101111010 ; 2
musichuffesc $7b, 0101101111011 ; 81
musichuffesc $7c, 0101101111100 ; 4
musichuffesc $7d, 0101101111101 ; 12
musichuffesc $7e, 0101101111110 ; 5
musichuffesc $7f, 0101101111111 ; 59
musichuffesc $86, 0101110000110 ; 57
musichuffesc $88, 0101110001000 ; 32
musichuffesc $89, 0101110001001 ; 39
musichuffesc $8a, 0101110001010 ; 8
musichuffesc $8b, 0101110001011 ; 85
musichuffesc $8c, 0101110001100 ; 4
musichuffesc $8d, 0101110001101 ; 11
musichuffesc $8e, 0101110001110 ; 8
musichuffesc $94, 0101110010100 ; 86
musichuffesc $96, 0101110010110 ; 39
musichuffesc $98, 0101110011000 ; 55
musichuffesc $99, 0101110011001 ; 26
musichuffesc $9a, 0101110011010 ; 10
musichuffesc $9b, 0101110011011 ; 67
musichuffesc $9c, 0101110011100 ; 3
musichuffesc $9d, 0101110011101 ; 8
musichuffesc $9e, 0101110011110 ; 2
musichuffesc $9f, 0101110011111 ; 74
musichuffesc $a6, 0101110100110 ; 48
musichuffesc $a8, 0101110101000 ; 43
musichuffesc $a9, 0101110101001 ; 35
musichuffesc $aa, 0101110101010 ; 7
musichuffesc $ab, 0101110101011 ; 81
musichuffesc $ac, 0101110101100 ; 1
musichuffesc $ad, 0101110101101 ; 17
musichuffesc $ae, 0101110101110 ; 8
musichuffesc $b6, 0101110110110 ; 74
musichuffesc $b8, 0101110111000 ; 38
musichuffesc $b9, 0101110111001 ; 47
musichuffesc $ba, 0101110111010 ; 7
musichuffesc $bb, 0101110111011 ; 74
musichuffesc $bc, 0101110111100 ; 6
musichuffesc $bd, 0101110111101 ; 12
musichuffesc $be, 0101110111110 ; 3
musichuffesc $c6, 0101111000110 ; 48
musichuffesc $c9, 0101111001001 ; 25
musichuffesc $ca, 0101111001010 ; 6
musichuffesc $cb, 0101111001011 ; 95
musichuffesc $cc, 0101111001100 ; 2
musichuffesc $cd, 0101111001101 ; 7
musichuffesc $ce, 0101111001110 ; 6
musichuffesc $cf, 0101111001111 ; 105
musichuffesc $d0, 0101111010000 ; 30
musichuffesc $d1, 0101111010001 ; 63
musichuffesc $dd, 0101111011101 ; 43
musichuffesc $e0, 0101111100000 ; 102
musichuffesc $e1, 0101111100001 ; 43
musichuffesc $e2, 0101111100010 ; 1
musichuffesc $e3, 0101111100011 ; 19
musichuffesc $e8, 0101111101000 ; 3
musichuffesc $e9, 0101111101001 ; 0
musichuffesc $ea, 0101111101010 ; 0
musichuffesc $eb, 0101111101011 ; 0
musichuffesc $ec, 0101111101100 ; 1
musichuffesc $f0, 0101111110000 ; 6
musichuffesc $f1, 0101111110001 ; 18
musichuffesc $f2, 0101111110010 ; 32
musichuffesc $f3, 0101111110011 ; 7
musichuffesc $f4, 0101111110100 ; 0
musichuffesc $f5, 0101111110101 ; 0
musichuffesc $f6, 0101111110110 ; 0
musichuffesc $f7, 0101111110111 ; 29
musichuffesc $f9, 0101111111001 ; 22
musichuffesc $fa, 0101111111010 ; 0
musichuffesc $fb, 0101111111011 ; 100
