	const_def

	const MUSIC_NONE                           ; 00
	const MUSIC_TITLE                          ; 01
	const MUSIC_ROUTE_1                        ; 02
	const MUSIC_ROUTE_3                        ; 03
	const MUSIC_ROUTE_12                       ; 04
	const MUSIC_MAGNET_TRAIN                   ; 05
	const MUSIC_KANTO_GYM_LEADER_BATTLE        ; 06
	const MUSIC_KANTO_TRAINER_BATTLE           ; 07
	const MUSIC_KANTO_WILD_BATTLE              ; 08
	const MUSIC_POKEMON_CENTER                 ; 09
	const MUSIC_HIKER_ENCOUNTER                ; 0a
	const MUSIC_LASS_ENCOUNTER                 ; 0b
	const MUSIC_OFFICER_ENCOUNTER              ; 0c
	const MUSIC_HEAL                           ; 0d
	const MUSIC_LAVENDER_TOWN                  ; 0e
	const MUSIC_VIRIDIAN_FOREST                ; 0f
	const MUSIC_MT_MOON                        ; 10
	const MUSIC_SHOW_ME_AROUND                 ; 11
	const MUSIC_GAME_CORNER                    ; 12
	const MUSIC_BICYCLE                        ; 13
	const MUSIC_HALL_OF_FAME                   ; 14
	const MUSIC_VIRIDIAN_CITY                  ; 15
	const MUSIC_CELADON_CITY                   ; 16
	const MUSIC_TRAINER_VICTORY                ; 17
	const MUSIC_WILD_VICTORY                   ; 18
	const MUSIC_GYM_VICTORY                    ; 19
	const MUSIC_MT_MOON_SQUARE                 ; 1a
	const MUSIC_GYM                            ; 1b
	const MUSIC_PALLET_TOWN                    ; 1c
	const MUSIC_POKEMON_TALK                   ; 1d
	const MUSIC_PROF_OAK                       ; 1e
	const MUSIC_RIVAL_ENCOUNTER                ; 1f
	const MUSIC_RIVAL_AFTER                    ; 20
	const MUSIC_SURF                           ; 21
	const MUSIC_EVOLUTION                      ; 22
	const MUSIC_NATIONAL_PARK                  ; 23
	const MUSIC_CREDITS                        ; 24
	const MUSIC_AZALEA_TOWN                    ; 25
	const MUSIC_CHERRYGROVE_CITY               ; 26
	const MUSIC_KIMONO_ENCOUNTER               ; 27
	const MUSIC_UNION_CAVE                     ; 28
	const MUSIC_JOHTO_WILD_BATTLE              ; 29
	const MUSIC_JOHTO_TRAINER_BATTLE           ; 2a
	const MUSIC_ROUTE_30                       ; 2b
	const MUSIC_ECRUTEAK_CITY                  ; 2c
	const MUSIC_VIOLET_CITY                    ; 2d
	const MUSIC_JOHTO_GYM_LEADER_BATTLE        ; 2e
	const MUSIC_CHAMPION_BATTLE                ; 2f
	const MUSIC_RIVAL_BATTLE                   ; 30
	const MUSIC_ROCKET_BATTLE                  ; 31
	const MUSIC_PROF_ELM                       ; 32
	const MUSIC_DARK_CAVE                      ; 33
	const MUSIC_ROUTE_29                       ; 34
	const MUSIC_ROUTE_36                       ; 35
	const MUSIC_SS_AQUA                        ; 36
	const MUSIC_YOUNGSTER_ENCOUNTER            ; 37
	const MUSIC_BEAUTY_ENCOUNTER               ; 38
	const MUSIC_ROCKET_ENCOUNTER               ; 39
	const MUSIC_POKEMANIAC_ENCOUNTER           ; 3a
	const MUSIC_SAGE_ENCOUNTER                 ; 3b
	const MUSIC_NEW_BARK_TOWN                  ; 3c
	const MUSIC_GOLDENROD_CITY                 ; 3d
	const MUSIC_VERMILION_CITY                 ; 3e
	const MUSIC_POKEMON_CHANNEL                ; 3f
	const MUSIC_POKE_FLUTE_CHANNEL             ; 40
	const MUSIC_TIN_TOWER                      ; 41
	const MUSIC_SPROUT_TOWER                   ; 42
	const MUSIC_BURNED_TOWER                   ; 43
	const MUSIC_LIGHTHOUSE                     ; 44
	const MUSIC_LAKE_OF_RAGE                   ; 45
	const MUSIC_INDIGO_PLATEAU                 ; 46
	const MUSIC_ROUTE_37                       ; 47
	const MUSIC_ROCKET_HIDEOUT                 ; 48
	const MUSIC_DRAGONS_DEN                    ; 49
	const MUSIC_JOHTO_WILD_BATTLE_NIGHT        ; 4a
	const MUSIC_RUINS_OF_ALPH_RADIO            ; 4b
	const MUSIC_CAPTURE                        ; 4c
	const MUSIC_ROUTE_26                       ; 4d
	const MUSIC_MOM                            ; 4e
	const MUSIC_VICTORY_ROAD                   ; 4f
	const MUSIC_POKEMON_LULLABY                ; 50
	const MUSIC_POKEMON_MARCH                  ; 51
	const MUSIC_MAIN_MENU                      ; 52
	const MUSIC_RUINS_OF_ALPH_INTERIOR         ; 53
	const MUSIC_ROCKET_OVERTURE                ; 54
	const MUSIC_DANCING_HALL                   ; 55
	const MUSIC_BUG_CATCHING_CONTEST_RANKING   ; 56
	const MUSIC_BUG_CATCHING_CONTEST           ; 57
	const MUSIC_LAKE_OF_RAGE_ROCKET_RADIO      ; 58
	const MUSIC_POST_CREDITS                   ; 59
	const MUSIC_CLAIR                          ; 5a
	const MUSIC_BUENAS_PASSWORD                ; 5b
	const MUSIC_MYSTICALMAN_ENCOUNTER          ; 5c
	const MUSIC_CRYSTAL_OPENING                ; 5d
	const MUSIC_BATTLE_TOWER_THEME             ; 5e
	const MUSIC_SUICUNE_BATTLE                 ; 5f
	const MUSIC_BATTLE_TOWER_LOBBY             ; 60
	const MUSIC_POKECOM_CENTER                 ; 61
	const MUSIC_SURFING_PIKACHU                ; 62
	const MUSIC_JESSIE_JAMES_ENCOUNTER         ; 63
	const MUSIC_MART_HGSS                      ; 64
	const MUSIC_CIANWOOD_CITY_HGSS             ; 65
	const MUSIC_CERULEAN_CITY_HGSS             ; 66
	const MUSIC_CINNABAR_ISLAND_HGSS           ; 67
	const MUSIC_NUGGET_BRIDGE_HGSS             ; 68
	const MUSIC_ROUTE_47_HGSS                  ; 69
	const MUSIC_SAFARI_ZONE_GATE_HGSS          ; 6a
	const MUSIC_LYRA_ENCOUNTER_HGSS            ; 6b
	const MUSIC_LYRA_DEPARTURE_HGSS            ; 6c
	const MUSIC_HO_OH_BATTLE_HGSS              ; 6d
	const MUSIC_LUGIA_BATTLE_HGSS              ; 6e
	const MUSIC_SUMMONING_DANCE_HGSS           ; 6f
	const MUSIC_ROUTE_203_DPPT                 ; 70
	const MUSIC_ROUTE_205_DPPT                 ; 71
	const MUSIC_ROUTE_209_DPPT                 ; 72
	const MUSIC_ROUTE_210_DPPT                 ; 73
	const MUSIC_CANALAVE_CITY_DPPT             ; 74
	const MUSIC_SUNYSHORE_CITY_DPPT            ; 75
	const MUSIC_OREBURGH_GATE_DPPT             ; 76
	const MUSIC_STARK_MOUNTAIN_DPPT            ; 77
	const MUSIC_MOUNT_CORONET_DPPT             ; 78
	const MUSIC_ETERNA_FOREST_DPPT             ; 79
	const MUSIC_GAME_CORNER_DPPT               ; 7a
	const MUSIC_TRAINER_BATTLE_DPPT            ; 7b
	const MUSIC_CHAMPION_BATTLE_DPPT           ; 7c
	const MUSIC_ROUTE_4_BW                     ; 7d
	const MUSIC_ROUTE_12_BW                    ; 7e
	const MUSIC_CELESTIAL_TOWER_BW             ; 7f
	const MUSIC_BLACK_CITY_BW                  ; 80
	const MUSIC_TRAINER_BATTLE_BW              ; 81
	const MUSIC_ELITE_FOUR_BATTLE_BW           ; 82
	const MUSIC_WCS_BATTLE_BW                  ; 83
	const MUSIC_FINAL_POKEMON_BW               ; 84
	const MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2 ; 85
	const MUSIC_REVERSAL_MOUNTAIN_W2           ; 86
	const MUSIC_WHITE_TREEHOLLOW_W2            ; 87
	const MUSIC_CHAMPION_BATTLE_B2W2           ; 88
	const MUSIC_TITLE_XY                       ; 89
	const MUSIC_BICYCLE_XY                     ; 8a
	const MUSIC_LAVERRE_CITY_XY                ; 8b
	const MUSIC_FROST_CAVERN_XY                ; 8c
	const MUSIC_POWER_PLANT_XY                 ; 8d
	const MUSIC_RIVAL_BATTLE_XY                ; 8e
	const MUSIC_GYM_LEADER_BATTLE_XY           ; 8f
	const MUSIC_LAVENDER_TOWN_RBY              ; 90
	const MUSIC_POKEMON_TOWER_RBY              ; 91
	const MUSIC_CINNABAR_MANSION_RBY           ; 92
	const MUSIC_DIGLETTS_CAVE_RBY              ; 93
	const MUSIC_CERULEAN_CAVE_RBY              ; 94
	const MUSIC_INDIGO_PLATEAU_RBY             ; 95
	const MUSIC_ROUTE_101_RSE                  ; 96
	const MUSIC_DEWFORD_TOWN_RSE               ; 97
	const MUSIC_METEOR_FALLS_RSE               ; 98
	const MUSIC_MOUNT_CHIMNEY_RSE              ; 99
	const MUSIC_MOUNT_PYRE_RSE                 ; 9a
	const MUSIC_ABANDONED_SHIP_RSE             ; 9b
	const MUSIC_GYM_LEADER_BATTLE_RSE          ; 9c
	const MUSIC_GYM_LEADER_BATTLE_DPPT         ; 9d
	const MUSIC_GYM_LEADER_BATTLE_BW           ; 9e
	const MUSIC_CHAMPION_BATTLE_RSE            ; 9f
	const MUSIC_FRONTIER_BRAIN_BATTLE_RSE      ; a0
	const MUSIC_KANTO_LEGEND_BATTLE_XY         ; a1
	const MUSIC_WALLY_ENCOUNTER_ORAS           ; a2
	const MUSIC_WALLY_BATTLE_ORAS              ; a3
	const MUSIC_ZINNIA_ENCOUNTER_ORAS          ; a4
	const MUSIC_ZINNIA_BATTLE_ORAS             ; a5
	const MUSIC_WILD_BATTLE_SM                 ; a6
	const MUSIC_TRAINER_BATTLE_SM              ; a7
	const MUSIC_ELITE_FOUR_BATTLE_SM           ; a8
	const MUSIC_MOTHER_BEAST_BATTLE_SM         ; a9
	const MUSIC_SPIKY_EARED_PICHU_HGSS         ; aa
	const MUSIC_LUGIAS_SONG_2000               ; ab
	; special
	const MUSIC_RADIO_TOWER                    ; ac
	const MUSIC_MAHOGANY_MART                  ; ad
