; song ids
; Music indexes (see audio/music_pointers.asm)
	const_def
	const MUSIC_NONE                           ; 00
	const MUSIC_CRYSTAL_OPENING                ; 01
	const MUSIC_TITLE                          ; 02
	const MUSIC_MAIN_MENU                      ; 03
	const MUSIC_NEW_BARK_TOWN                  ; 04
	const MUSIC_MOM                            ; 05
	const MUSIC_PROF_ELM                       ; 06
	const MUSIC_LYRA_ENCOUNTER_HGSS            ; 07
	const MUSIC_RIVAL_BATTLE_XY                ; 08
	const MUSIC_LYRA_DEPARTURE_HGSS            ; 09
	const MUSIC_ROUTE_29                       ; 0a
	const MUSIC_JOHTO_WILD_BATTLE              ; 0b
	const MUSIC_JOHTO_WILD_BATTLE_NIGHT        ; 0c
	const MUSIC_WILD_VICTORY                   ; 0d
	const MUSIC_CHERRYGROVE_CITY               ; 0e
	const MUSIC_SHOW_ME_AROUND                 ; 0f
	const MUSIC_POKEMON_CENTER                 ; 10
	const MUSIC_HEAL                           ; 11
	const MUSIC_CAPTURE                        ; 12
	const MUSIC_YOUNGSTER_ENCOUNTER            ; 13
	const MUSIC_JOHTO_TRAINER_BATTLE           ; 14
	const MUSIC_TRAINER_VICTORY                ; 15
	const MUSIC_ROUTE_30                       ; 16
	const MUSIC_VIOLET_CITY                    ; 17
	const MUSIC_SPROUT_TOWER                   ; 18
	const MUSIC_SAGE_ENCOUNTER                 ; 19
	const MUSIC_MART_HGSS                      ; 1a
	const MUSIC_HIDDEN_GROTTO_B2W2             ; 1b
	const MUSIC_UNION_CAVE                     ; 1c
	const MUSIC_RUINS_OF_ALPH_INTERIOR         ; 1d
	const MUSIC_RUINS_OF_ALPH_RADIO            ; 1e
	const MUSIC_AZALEA_TOWN                    ; 1f
	const MUSIC_ROCKET_ENCOUNTER               ; 20
	const MUSIC_ROCKET_BATTLE                  ; 21
	const MUSIC_ROUTE_36                       ; 22
	const MUSIC_RIVAL_ENCOUNTER                ; 23
	const MUSIC_RIVAL_BATTLE                   ; 24
	const MUSIC_RIVAL_AFTER                    ; 25
	const MUSIC_EVOLUTION                      ; 26
	const MUSIC_GOLDENROD_CITY                 ; 27
	const MUSIC_POKECOM_CENTER                 ; 28
	const MUSIC_GYM                            ; 29
	const MUSIC_JOHTO_GYM_LEADER_BATTLE        ; 2a
	const MUSIC_FINAL_POKEMON_BW               ; 2b
	const MUSIC_GYM_VICTORY                    ; 2c
	const MUSIC_POKEMON_CHANNEL                ; 2d
	const MUSIC_BUENAS_PASSWORD                ; 2e
	const MUSIC_GAME_CORNER                    ; 2f
	const MUSIC_BICYCLE                        ; 30
	const MUSIC_LASS_ENCOUNTER                 ; 31
	const MUSIC_NATIONAL_PARK                  ; 32
	const MUSIC_BUG_CATCHING_CONTEST           ; 33
	const MUSIC_BUG_CATCHING_CONTEST_RANKING   ; 34
	const MUSIC_ECRUTEAK_CITY                  ; 35
	const MUSIC_DANCING_HALL                   ; 36
	const MUSIC_KIMONO_ENCOUNTER               ; 37
	const MUSIC_BURNED_TOWER                   ; 38
	const MUSIC_MYSTICALMAN_ENCOUNTER          ; 39
	const MUSIC_POKEMON_TALK                   ; 3a
	const MUSIC_ROUTE_37                       ; 3b
	const MUSIC_POKEMON_MARCH                  ; 3c
	const MUSIC_LIGHTHOUSE                     ; 3d
	const MUSIC_SURF                           ; 3e
	const MUSIC_CIANWOOD_CITY_HGSS             ; 3f
	const MUSIC_ROUTE_47_HGSS                  ; 40
	const MUSIC_JESSIE_JAMES_ENCOUNTER         ; 41
	const MUSIC_SAFARI_ZONE_GATE_HGSS          ; 42
	const MUSIC_SURFING_PIKACHU                ; 43
	const MUSIC_LAKE_OF_RAGE                   ; 44
	const MUSIC_STARK_MOUNTAIN_DPPT            ; 45
	const MUSIC_LAKE_OF_RAGE_ROCKET_RADIO      ; 46
	const MUSIC_ROCKET_HIDEOUT                 ; 47
	const MUSIC_POKEMANIAC_ENCOUNTER           ; 48
	const MUSIC_ROCKET_OVERTURE                ; 49
	const MUSIC_DARK_CAVE                      ; 4a
	const MUSIC_DRAGONS_DEN                    ; 4b
	const MUSIC_CLAIR                          ; 4c
	const MUSIC_ROUTE_4_BW                     ; 4d
	const MUSIC_TIN_TOWER                      ; 4e
	const MUSIC_SUICUNE_BATTLE                 ; 4f
	const MUSIC_ROUTE_26                       ; 50
	const MUSIC_INDIGO_PLATEAU_RBY             ; 51
	const MUSIC_VICTORY_ROAD                   ; 52
	const MUSIC_INDIGO_PLATEAU                 ; 53
	const MUSIC_ELITE_FOUR_BATTLE_SM           ; 54
	const MUSIC_CHAMPION_BATTLE                ; 55
	const MUSIC_HALL_OF_FAME                   ; 56
	const MUSIC_SS_AQUA                        ; 57
	const MUSIC_SURF_KANTO                     ; 58
	const MUSIC_VERMILION_CITY                 ; 59
	const MUSIC_KANTO_GYM_LEADER_BATTLE        ; 5a
	const MUSIC_LAVENDER_TOWN_RBY              ; 5b
	const MUSIC_POKEMON_TOWER_RBY              ; 5c
	const MUSIC_LAVENDER_TOWN                  ; 5d
	const MUSIC_KANTO_WILD_BATTLE              ; 5e
	const MUSIC_KANTO_WILD_BATTLE_NIGHT        ; 5f
	const MUSIC_CERULEAN_CITY_HGSS             ; 60
	const MUSIC_BICYCLE_RB                     ; 61
	const MUSIC_NUGGET_BRIDGE_HGSS             ; 62
	const MUSIC_MAGNET_TRAIN                   ; 63
	const MUSIC_BLACK_CITY_BW                  ; 64
	const MUSIC_POKEMON_LULLABY                ; 65
	const MUSIC_CELADON_CITY                   ; 66
	const MUSIC_GAME_CORNER_DPPT               ; 67
	const MUSIC_CANALAVE_CITY_DPPT             ; 68
	const MUSIC_BICYCLE_XY                     ; 69
	const MUSIC_ROUTE_12                       ; 6a
	const MUSIC_POKE_FLUTE_CHANNEL             ; 6b
	const MUSIC_ROUTE_209_DPPT                 ; 6c
	const MUSIC_ROUTE_210_DPPT                 ; 6d
	const MUSIC_ROUTE_225_DPPT                 ; 6e
	const MUSIC_WILD_BATTLE_GO                 ; 6f
	const MUSIC_DIGLETTS_CAVE_RBY              ; 70
	const MUSIC_VIRIDIAN_FOREST                ; 71
	const MUSIC_HIKER_ENCOUNTER                ; 72
	const MUSIC_VIRIDIAN_CITY                  ; 73
	const MUSIC_ROUTE_3                        ; 74
	const MUSIC_OFFICER_ENCOUNTER              ; 75
	const MUSIC_MT_MOON                        ; 76
	const MUSIC_MT_MOON_SQUARE                 ; 77
	const MUSIC_ROUTE_1                        ; 78
	const MUSIC_PALLET_TOWN                    ; 79
	const MUSIC_PROF_OAK                       ; 7a
	const MUSIC_BEAUTY_ENCOUNTER               ; 7b
	const MUSIC_KANTO_TRAINER_BATTLE           ; 7c
	const MUSIC_CINNABAR_ISLAND_HGSS           ; 7d
	const MUSIC_CINNABAR_MANSION_RBY           ; 7e
	const MUSIC_TRAINER_BATTLE_DPPT            ; 7f
	const MUSIC_SCARY_HOUSE_XY                 ; 80
	const MUSIC_ETERNA_FOREST_DPPT             ; 81
	const MUSIC_MOUNT_CHIMNEY_RSE              ; 82
	const MUSIC_MOUNT_PYRE_RSE                 ; 83
	const MUSIC_BATTLE_TOWER_THEME             ; 84
	const MUSIC_BATTLE_TOWER_LOBBY             ; 85
	const MUSIC_BATTLE_FACTORY_RSE             ; 86
	const MUSIC_TRAINER_BATTLE_BW              ; 87
	const MUSIC_FRONTIER_BRAIN_BATTLE_RSE      ; 88
	const MUSIC_ZINNIA_ENCOUNTER_ORAS          ; 89
	const MUSIC_ROUTE_205_DPPT                 ; 8a
	const MUSIC_SURF_HOENN                     ; 8b
	const MUSIC_BICYCLE_RSE                    ; 8c
	const MUSIC_WILD_BATTLE_SM                 ; 8d
	const MUSIC_SUNYSHORE_CITY_DPPT            ; 8e
	const MUSIC_TRAINER_BATTLE_SM              ; 8f
	const MUSIC_ROUTE_203_DPPT                 ; 90
	const MUSIC_WHITE_TREEHOLLOW_W2            ; 91
	const MUSIC_LAVERRE_CITY_XY                ; 92
	const MUSIC_ROUTE_101_RSE                  ; 93
	const MUSIC_EVER_GRANDE_CITY_RSE           ; 94
	const MUSIC_OREBURGH_GATE_DPPT             ; 95
	const MUSIC_ROUTE_12_BW                    ; 96
	const MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2 ; 97
	const MUSIC_ZINNIA_BATTLE_ORAS             ; 98
	const MUSIC_WALLY_ENCOUNTER_ORAS           ; 99
	const MUSIC_WALLY_BATTLE_ORAS              ; 9a
	const MUSIC_SPIKY_EARED_PICHU_HGSS         ; 9b
	const MUSIC_MOTHER_BEAST_BATTLE_SM         ; 9c
	const MUSIC_FROST_CAVERN_XY                ; 9d
	const MUSIC_POWER_PLANT_XY                 ; 9e
	const MUSIC_REVERSAL_MOUNTAIN_W2           ; 9f
	const MUSIC_METEOR_FALLS_RSE               ; a0
	const MUSIC_LUGIAS_SONG_2000               ; a1
	const MUSIC_LUGIA_BATTLE_HGSS              ; a2
	const MUSIC_SUMMONING_DANCE_HGSS           ; a3
	const MUSIC_HO_OH_BATTLE_HGSS              ; a4
	const MUSIC_CERULEAN_CAVE_RBY              ; a5
	const MUSIC_MEWTWO_BATTLE_STADIUM          ; a6
	const MUSIC_ABANDONED_SHIP_RSE             ; a7
	const MUSIC_KANTO_LEGEND_BATTLE_XY         ; a8
	const MUSIC_GYM_LEADER_BATTLE_RSE          ; a9
	const MUSIC_GYM_LEADER_BATTLE_DPPT         ; aa
	const MUSIC_GYM_LEADER_BATTLE_BW           ; ab
	const MUSIC_GYM_LEADER_BATTLE_XY           ; ac
	const MUSIC_GYM_LEADER_BATTLE_GO           ; ad
	const MUSIC_ELITE_FOUR_BATTLE_BW           ; ae
	const MUSIC_CELESTIAL_TOWER_BW             ; af
	const MUSIC_CHAMPION_BATTLE_RSE            ; b0
	const MUSIC_MOUNT_CORONET_DPPT             ; b1
	const MUSIC_CHAMPION_BATTLE_DPPT           ; b2
	const MUSIC_WCS_BATTLE_BW                  ; b3
	const MUSIC_CHAMPION_BATTLE_B2W2           ; b4
	const MUSIC_CREDITS                        ; b5
	const MUSIC_POST_CREDITS                   ; b6
	const MUSIC_TITLE_XY                       ; b7
	const MUSIC_DEWFORD_TOWN_RSE               ; b8 ; unused
	const MUSIC_MARINE_TUBE_B2W2               ; b9 ; unused
	const MUSIC_LEGENDARY_BATTLE_XY            ; ba ; unused
	const MUSIC_WILD_BATTLE_PRISM              ; bb ; unused
	const MUSIC_TRAINER_BATTLE_PRISM           ; bc ; unused
	const MUSIC_GYM_LEADER_BATTLE_PRISM        ; bd ; unused
	const MUSIC_PALETTE_BATTLE_PRISM           ; be ; unused
	const MUSIC_UNDERTALE_MEGALOVANIA          ; bf ; unused
NUM_MUSIC_SONGS EQU const_value

; GetMapMusic picks music for these values (see data/maps/special_map_music.asm)
	const_def $ff, -1
	const MUSIC_RADIO_TOWER   ; ff
	const MUSIC_MAHOGANY_MART ; fe
	const MUSIC_LAVENDER      ; fd
FIRST_ALT_MUSIC EQU const_value + 1
