; nature constants
; NatureNames indexes (see data/natures.asm)
; NatureIndicators indexes (see data/natures.asm)
	const_def
	const HARDY
	const LONELY
	const BRAVE
	const ADAMANT
	const NAUGHTY
	const BOLD
	const DOCILE
	const RELAXED
	const IMPISH
	const LAX
	const TIMID
	const HASTY
	const SERIOUS
	const JOLLY
	const NAIVE
	const MODEST
	const MILD
	const QUIET
	const BASHFUL
	const RASH
	const CALM
	const GENTLE
	const SASSY
	const CAREFUL
	const QUIRKY
NUM_NATURES EQU const_value
NO_NATURE   EQU const_value

NAT_ATK_UP_DEF_DOWN   EQU LONELY
NAT_ATK_UP_SPD_DOWN   EQU BRAVE
NAT_ATK_UP_SATK_DOWN  EQU ADAMANT
NAT_ATK_UP_SDEF_DOWN  EQU NAUGHTY
NAT_DEF_UP_ATK_DOWN   EQU BOLD
NAT_DEF_UP_SPD_DOWN   EQU RELAXED
NAT_DEF_UP_SATK_DOWN  EQU IMPISH
NAT_DEF_UP_SDEF_DOWN  EQU LAX
NAT_SPD_UP_ATK_DOWN   EQU TIMID
NAT_SPD_UP_DEF_DOWN   EQU HASTY
NAT_SPD_UP_SATK_DOWN  EQU JOLLY
NAT_SPD_UP_SDEF_DOWN  EQU NAIVE
NAT_SATK_UP_ATK_DOWN  EQU MODEST
NAT_SATK_UP_DEF_DOWN  EQU MILD
NAT_SATK_UP_SPD_DOWN  EQU QUIET
NAT_SATK_UP_SDEF_DOWN EQU RASH
NAT_SDEF_UP_ATK_DOWN  EQU CALM
NAT_SDEF_UP_DEF_DOWN  EQU GENTLE
NAT_SDEF_UP_SPD_DOWN  EQU SASSY
NAT_SDEF_UP_SATK_DOWN EQU CAREFUL
NAT_NEUTRAL           EQU QUIRKY
