
; sprites
	const_def
	const SPRITE_NONE ; $00
	const SPRITE_CHRIS ; $01
	const SPRITE_CHRIS_BIKE ; $02
	const SPRITE_CHRIS_SURF ; $03
	const SPRITE_KRIS ; $04
	const SPRITE_KRIS_BIKE ; $05
	const SPRITE_KRIS_SURF ; $06
	const SPRITE_MOM ; $07
	const SPRITE_DAD ; $08
	const SPRITE_LYRA ; $09
	const SPRITE_SILVER ; $0a
	const SPRITE_FALKNER ; $0b
	const SPRITE_BUGSY ; $0c
	const SPRITE_WHITNEY ; $0d
	const SPRITE_MORTY ; $0e
	const SPRITE_CHUCK ; $0f
	const SPRITE_JASMINE ; $10
	const SPRITE_PRYCE ; $11
	const SPRITE_CLAIR ; $12
	const SPRITE_WILL ; $13
	const SPRITE_KOGA ; $14
	const SPRITE_BRUNO ; $15
	const SPRITE_KAREN ; $16
	const SPRITE_LANCE ; $17
	const SPRITE_BROCK ; $18
	const SPRITE_MISTY ; $19
	const SPRITE_SURGE ; $1a
	const SPRITE_ERIKA ; $1b
	const SPRITE_JANINE ; $1c
	const SPRITE_SABRINA ; $1d
	const SPRITE_BLAINE ; $1e
	const SPRITE_BLUE ; $1f
	const SPRITE_RED ; $20
	const SPRITE_LEAF ; $21
	const SPRITE_YELLOW ; $22
	const SPRITE_OAK ; $23
	const SPRITE_ELM ; $24
	const SPRITE_IVY ; $25
	const SPRITE_BILL ; $26
	const SPRITE_KURT ; $27
	const SPRITE_REDS_MOM ; $28
	const SPRITE_DAISY ; $29
	const SPRITE_LORELEI ; $2a
	const SPRITE_AGATHA ; $2b
	const SPRITE_PALMER ; $2c
	const SPRITE_WALKER ; $2d
	const SPRITE_IMAKUNI ; $2e
	const SPRITE_LAWRENCE ; $2f
	const SPRITE_JAMES ; $30
	const SPRITE_JESSIE ; $31
	const SPRITE_PROTON ; $32
	const SPRITE_PETREL ; $33
	const SPRITE_ARCHER ; $34
	const SPRITE_ARIANA ; $35
	const SPRITE_GIOVANNI ; $36
	const SPRITE_CHERYL ; $37
	const SPRITE_RILEY ; $38
	const SPRITE_BUCK ; $39
	const SPRITE_MARLEY ; $3a
	const SPRITE_MIRA ; $3b
	const SPRITE_ANABEL ; $3c
	const SPRITE_FLANNERY ; $3d
	const SPRITE_MAYLENE ; $3e
	const SPRITE_SKYLA ; $3f
	const SPRITE_VALERIE ; $40
	const SPRITE_CAITLIN ; $41
	const SPRITE_DARACH ; $42
	const SPRITE_STEVEN ; $43
	const SPRITE_CYNTHIA ; $44
	const SPRITE_CANDELA ; $45
	const SPRITE_BLANCHE ; $46
	const SPRITE_SPARK ; $47
	const SPRITE_BUENA ; $48
	const SPRITE_CAPTAIN ; $49
	const SPRITE_BAKER ; $4a
	const SPRITE_BEAUTY ; $4b
	const SPRITE_BIKER ; $4c
	const SPRITE_BLACK_BELT ; $4d
	const SPRITE_BOARDER ; $4e
	const SPRITE_BREEDER ; $4f
	const SPRITE_BUG_CATCHER ; $50
	const SPRITE_BUG_MANIAC ; $51
	const SPRITE_CHILD ; $52
	const SPRITE_COOLTRAINER_F ; $53
	const SPRITE_COOLTRAINER_M ; $54
	const SPRITE_COSPLAYER ; $55
	const SPRITE_COWGIRL ; $56
	const SPRITE_DRAGON_TAMER ; $57
	const SPRITE_ELDER ; $58
	const SPRITE_ENGINEER ; $59
	const SPRITE_FISHER ; $5a
	const SPRITE_GENTLEMAN ; $5b
	const SPRITE_GRAMPS ; $5c
	const SPRITE_GRANNY ; $5d
	const SPRITE_HEX_MANIAC ; $5e
	const SPRITE_KIMONO_GIRL ; $5f
	const SPRITE_LADY ; $60
	const SPRITE_LASS ; $61
	const SPRITE_OFFICER ; $62
	const SPRITE_OFFICER_F ; $63
	const SPRITE_PHARMACIST ; $64
	const SPRITE_PI ; $65
	const SPRITE_POKEFAN_F ; $66
	const SPRITE_POKEFAN_M ; $67
	const SPRITE_RICH_BOY ; $68
	const SPRITE_ROCKER ; $69
	const SPRITE_ROCKET ; $6a
	const SPRITE_ROCKET_GIRL ; $6b
	const SPRITE_ROUGHNECK ; $6c
	const SPRITE_SAGE ; $6d
	const SPRITE_SAILOR ; $6e
	const SPRITE_SCIENTIST ; $6f
	const SPRITE_SIGHTSEER_M ; $70
	const SPRITE_SKIER ; $71
	const SPRITE_SUPER_NERD ; $72
	const SPRITE_SWIMMER_GIRL ; $73
	const SPRITE_SWIMMER_GUY ; $74
	const SPRITE_TEACHER ; $75
	const SPRITE_TWIN ; $76
	const SPRITE_VETERAN_M ; $77
	const SPRITE_VETERAN_F ; $78
	const SPRITE_YOUNGSTER ; $79
	const SPRITE_NURSE ; $7a
	const SPRITE_CLERK ; $7b
	const SPRITE_RECEPTIONIST ; $7c
	const SPRITE_LINK_RECEPTIONIST ; $7d
	const SPRITE_GYM_GUY ; $7e
	const SPRITE_FISHING_GURU ; $7f
	const SPRITE_GAMEBOY_KID ; $80
	const SPRITE_SILPH_EMPLOYEE ; $81
	const SPRITE_SWIMMING_OFFICER ; $82
	const SPRITE_SWIMMING_OFFICER_F ; $83
	const SPRITE_CLEFAIRY_WALK ; $84
	const SPRITE_FARFETCH_D ; $85
	const SPRITE_LAPRAS ; $86
	const SPRITE_EEVEE ; $87
	const SPRITE_DRAGONITE ; $88
	const SPRITE_MEW ; $89
	const SPRITE_CELEBI ; $8a
	const SPRITE_SURFING_PIKACHU ; $8b
	const SPRITE_ARMORED_MEWTWO ; $8c
	const SPRITE_BIG_SNORLAX ; $8d
	const SPRITE_BIG_LAPRAS ; $8e
	const SPRITE_BIG_ONIX ; $8f
	const SPRITE_WEIRD_TREE ; $90
	const SPRITE_GYARADOS_TOP_LEFT ; $91
	const SPRITE_GYARADOS_TOP_RIGHT ; $92
	const SPRITE_GYARADOS_BOTTOM_LEFT ; $93
	const SPRITE_GYARADOS_BOTTOM_RIGHT ; $94
	const SPRITE_BALL_CUT_FRUIT ; $95
	const SPRITE_ROCK_BOULDER_FOSSIL ; $96
	const SPRITE_PAPER_UNOWN_W ; $97
	const SPRITE_POKEDEX_UNOWN_A ; $98
	const SPRITE_BOOK_UNOWN_R ; $99
	const SPRITE_SIGN_UNOWN_P ; $9a
	const SPRITE_ELECTRIC_FENCE_LEFT ; $9b
	const SPRITE_ELECTRIC_FENCE_RIGHT ; $9c
	const SPRITE_SNES ; $9d
	const SPRITE_N64 ; $9e
	const SPRITE_GAMECUBE ; $9f
	const SPRITE_WII ; $a0
	const SPRITE_SILVER_TROPHY ; $a1
	const SPRITE_GOLD_TROPHY ; $a2

const_value set $ab
SPRITE_POKEMON EQU const_value
	const SPRITE_BULBASAUR ; $ab
	const SPRITE_CHARMANDER ; $ac
	const SPRITE_SQUIRTLE ; $ad
	const SPRITE_WEEDLE ; $ae
	const SPRITE_PIDGEY ; $af
	const SPRITE_PIDGEOTTO ; $b0
	const SPRITE_PIDGEOT ; $b1
	const SPRITE_RATTATA ; $b2
	const SPRITE_PIKACHU ; $b3
	const SPRITE_NIDORAN_F ; $b4
	const SPRITE_NIDORAN_M ; $b5
	const SPRITE_NIDORINO ; $b6
	const SPRITE_CLEFAIRY ; $b7
	const SPRITE_JIGGLYPUFF ; $b8
	const SPRITE_ZUBAT ; $b9
	const SPRITE_ODDISH ; $ba
	const SPRITE_VILEPLUME ; $bb
	const SPRITE_DIGLETT ; $bc
	const SPRITE_MEOWTH ; $bd
	const SPRITE_PERSIAN ; $be
	const SPRITE_PSYDUCK ; $bf
	const SPRITE_POLIWAG ; $c0
	const SPRITE_POLIWRATH ; $c1
	const SPRITE_ABRA ; $c2
	const SPRITE_MACHOP ; $c3
	const SPRITE_MACHOKE ; $c4
	const SPRITE_TENTACOOL ; $c5
	const SPRITE_GEODUDE ; $c6
	const SPRITE_SLOWPOKE ; $c7
	const SPRITE_SLOWBRO ; $c8
	const SPRITE_DODRIO ; $c9
	const SPRITE_GRIMER ; $ca
	const SPRITE_SHELLDER ; $cb
	const SPRITE_GENGAR ; $cc
	const SPRITE_VOLTORB ; $cd
	const SPRITE_ELECTRODE ; $ce
	const SPRITE_RHYDON ; $cf
	const SPRITE_CHANSEY ; $d0
	const SPRITE_KANGASKHAN ; $d1
	const SPRITE_STARYU ; $d2
	const SPRITE_MAGIKARP ; $d3
	const SPRITE_ARTICUNO ; $d4
	const SPRITE_ZAPDOS ; $d5
	const SPRITE_MOLTRES ; $d6
	const SPRITE_DRATINI ; $d7
	const SPRITE_MEWTWO ; $d8
	const SPRITE_BAYLEEF ; $d9
	const SPRITE_FURRET ; $da
	const SPRITE_HOOTHOOT ; $db
	const SPRITE_AMPHAROS ; $dc
	const SPRITE_MARILL ; $dd
	const SPRITE_MURKROW ; $de
	const SPRITE_UNOWN ; $df
	const SPRITE_HERACROSS ; $e0
	const SPRITE_URSARING ; $e1
	const SPRITE_SKARMORY ; $e2
	const SPRITE_SMEARGLE ; $e3
	const SPRITE_MILTANK ; $e4
	const SPRITE_BLISSEY ; $e5
	const SPRITE_RAIKOU ; $e6
	const SPRITE_ENTEI ; $e7
	const SPRITE_SUICUNE ; $e8
	const SPRITE_LUGIA ; $e9
	const SPRITE_HO_OH ; $ea
	const SPRITE_EGG ; $eb

	const SPRITE_DAYCARE_MON_1 ; $ec
	const SPRITE_DAYCARE_MON_2 ; $ed

SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; $ee
	const SPRITE_DOLL_1 ; $ef
	const SPRITE_DOLL_2 ; $f0
	const SPRITE_BIG_DOLL ; $f1
	const SPRITE_FUCHSIA_GYM_1 ; $f2
	const SPRITE_FUCHSIA_GYM_2 ; $f3
	const SPRITE_FUCHSIA_GYM_3 ; $f4
	const SPRITE_FUCHSIA_GYM_4 ; $f5
	const SPRITE_COPYCAT ; $f6
	const SPRITE_JANINE_IMPERSONATOR ; $f7
	const SPRITE_REMATCH_GYM_LEADER_1 ; $f8
	const SPRITE_REMATCH_GYM_LEADER_2 ; $f9
	const SPRITE_REMATCH_GYM_LEADER_3 ; $fa
	const SPRITE_NEW_BARK_LYRA ; $fb
	const SPRITE_AZALEA_ROCKET ; $fc
	const SPRITE_CHERRYGROVE_RIVAL ; $fd
	const SPRITE_OLIVINE_RIVAL ; $fe
	const SPRITE_CERULEAN_CAPE_MISTY ; $ff


; sprite types
const_value SET 1
	const WALKING_SPRITE
	const STANDING_SPRITE
	const STILL_SPRITE

; sprite header fields
	const_def
	const SPRITEHEADER_ADDR_LO
	const SPRITEHEADER_ADDR_HI
	const SPRITEHEADER_SIZE
	const SPRITEHEADER_BANK
	const SPRITEHEADER_TYPE
	const SPRITEHEADER_PALETTE
NUM_SPRITEHEADER_FIELDS EQU const_value

; sprite palettes
	const_def
	const PAL_OW_RED
	const PAL_OW_BLUE
	const PAL_OW_GREEN
	const PAL_OW_BROWN
	const PAL_OW_PURPLE
	const PAL_OW_SILVER
	const PAL_OW_TREE
	const PAL_OW_ROCK

; sprite movement data table indices
	const_def
	const SPRITEMOVEDATA_00                   ; 00
	const SPRITEMOVEDATA_DOLL                 ; 01
	const SPRITEMOVEDATA_WANDER               ; 02
	const SPRITEMOVEDATA_SPINRANDOM_SLOW      ; 03
	const SPRITEMOVEDATA_WALK_UP_DOWN         ; 04
	const SPRITEMOVEDATA_WALK_LEFT_RIGHT      ; 05
	const SPRITEMOVEDATA_STANDING_DOWN        ; 06
	const SPRITEMOVEDATA_STANDING_UP          ; 07
	const SPRITEMOVEDATA_STANDING_LEFT        ; 08
	const SPRITEMOVEDATA_STANDING_RIGHT       ; 09
	const SPRITEMOVEDATA_SPINRANDOM_FAST      ; 0a
	const SPRITEMOVEDATA_PLAYER               ; 0b
	const SPRITEMOVEDATA_0C                   ; 0c
	const SPRITEMOVEDATA_0D                   ; 0d
	const SPRITEMOVEDATA_0E                   ; 0e
	const SPRITEMOVEDATA_0F                   ; 0f
	const SPRITEMOVEDATA_10                   ; 10
	const SPRITEMOVEDATA_11                   ; 11
	const SPRITEMOVEDATA_CUTTABLE_TREE        ; 12
	const SPRITEMOVEDATA_FOLLOWING            ; 13
	const SPRITEMOVEDATA_SCRIPTED             ; 14
	const SPRITEMOVEDATA_SNORLAX              ; 15
	const SPRITEMOVEDATA_POKEMON              ; 16
	const SPRITEMOVEDATA_SUDOWOODO            ; 17
	const SPRITEMOVEDATA_SMASHABLE_ROCK       ; 18
	const SPRITEMOVEDATA_STRENGTH_BOULDER     ; 19
	const SPRITEMOVEDATA_FOLLOWNOTEXACT       ; 1a
	const SPRITEMOVEDATA_SHADOW               ; 1b
	const SPRITEMOVEDATA_EMOTE                ; 1c
	const SPRITEMOVEDATA_SCREENSHAKE          ; 1d
	const SPRITEMOVEDATA_SPINCOUNTERCLOCKWISE ; 1e
	const SPRITEMOVEDATA_SPINCLOCKWISE        ; 1f
	const SPRITEMOVEDATA_20                   ; 20
	const SPRITEMOVEDATA_BIGDOLL              ; 21
	const SPRITEMOVEDATA_BOULDERDUST          ; 22
	const SPRITEMOVEDATA_GRASS                ; 23
	const SPRITEMOVEDATA_LAPRAS               ; 24
	const SPRITEMOVEDATA_25                   ; 25
NUM_SPRITEMOVEDATA EQU const_value +- 1
SPRITEMOVEDATA_FIELDS EQU 6

; sprite movement functions
	const_def
	const SPRITEMOVEFN_00
	const SPRITEMOVEFN_RANDOM_WALK_Y
	const SPRITEMOVEFN_RANDOM_WALK_X
	const SPRITEMOVEFN_RANDOM_WALK_XY
	const SPRITEMOVEFN_SLOW_RANDOM_SPIN
	const SPRITEMOVEFN_FAST_RANDOM_SPIN
	const SPRITEMOVEFN_STANDING
	const SPRITEMOVEFN_OBEY_DPAD
	const SPRITEMOVEFN_08
	const SPRITEMOVEFN_09
	const SPRITEMOVEFN_0A
	const SPRITEMOVEFN_0B
	const SPRITEMOVEFN_0C
	const SPRITEMOVEFN_0D
	const SPRITEMOVEFN_0E
	const SPRITEMOVEFN_FOLLOW
	const SPRITEMOVEFN_SCRIPTED
	const SPRITEMOVEFN_STRENGTH
	const SPRITEMOVEFN_FOLLOWNOTEXACT
	const SPRITEMOVEFN_SHADOW
	const SPRITEMOVEFN_EMOTE
	const SPRITEMOVEFN_BIG_SNORLAX
	const SPRITEMOVEFN_BOUNCE
	const SPRITEMOVEFN_SCREENSHAKE
	const SPRITEMOVEFN_SPIN_CLOCKWISE
	const SPRITEMOVEFN_SPIN_COUNTERCLOCKWISE
	const SPRITEMOVEFN_BOULDERDUST
	const SPRITEMOVEFN_GRASS

MAX_OUTDOOR_SPRITES EQU 23

	const_def
	const STEP_TYPE_00
	const STEP_TYPE_SLEEP
	const STEP_TYPE_NPC_WALK
	const STEP_TYPE_03
	const STEP_TYPE_04
	const STEP_TYPE_05
	const STEP_TYPE_PLAYER_WALK
	const STEP_TYPE_07
	const STEP_TYPE_NPC_JUMP
	const STEP_TYPE_PLAYER_JUMP
	const STEP_TYPE_HALF_STEP
	const STEP_TYPE_BUMP
	const STEP_TYPE_TELEPORT_FROM
	const STEP_TYPE_TELEPORT_TO
	const STEP_TYPE_SKYFALL
	const STEP_TYPE_0F
	const STEP_TYPE_GOT_BITE
	const STEP_TYPE_ROCK_SMASH
	const STEP_TYPE_RETURN_DIG
	const STEP_TYPE_TRACKING_OBJECT
	const STEP_TYPE_14
	const STEP_TYPE_15
	const STEP_TYPE_16
	const STEP_TYPE_17
	const STEP_TYPE_18
	const STEP_TYPE_SKYFALL_TOP

	const_def
	const PERSON_ACTION_00
	const PERSON_ACTION_STAND
	const PERSON_ACTION_STEP
	const PERSON_ACTION_BUMP
	const PERSON_ACTION_SPIN
	const PERSON_ACTION_SPIN_FLICKER
	const PERSON_ACTION_FISHING
	const PERSON_ACTION_07
	const PERSON_ACTION_EMOTE
	const PERSON_ACTION_09
	const PERSON_ACTION_0A
	const PERSON_ACTION_0B
	const PERSON_ACTION_0C
	const PERSON_ACTION_0D
	const PERSON_ACTION_0E
	const PERSON_ACTION_0F
	const PERSON_ACTION_10

	const_def
	const FACING_00
	const FACING_01
	const FACING_02
	const FACING_03
	const FACING_04
	const FACING_05
	const FACING_06
	const FACING_07
	const FACING_08
	const FACING_09
	const FACING_0A
	const FACING_0B
	const FACING_0C
	const FACING_0D
	const FACING_0E
	const FACING_0F
	const FACING_10
	const FACING_11
	const FACING_12
	const FACING_13
	const FACING_EMOTE
	const FACING_15
	const FACING_16
	const FACING_17
	const FACING_18
	const FACING_19
	const FACING_1A
	const FACING_1B
	const FACING_1C
	const FACING_1D
	const FACING_1E
	const FACING_1F

	const_def
	const SPRITEANIMSTRUCT_INDEX          ; 0
	const SPRITEANIMSTRUCT_FRAMESET_ID    ; 1
	const SPRITEANIMSTRUCT_ANIM_SEQ_ID    ; 2
	const SPRITEANIMSTRUCT_TILE_ID        ; 3
	const SPRITEANIMSTRUCT_XCOORD         ; 4
	const SPRITEANIMSTRUCT_YCOORD         ; 5
	const SPRITEANIMSTRUCT_XOFFSET        ; 6
	const SPRITEANIMSTRUCT_YOFFSET        ; 7
	const SPRITEANIMSTRUCT_DURATION       ; 8
	const SPRITEANIMSTRUCT_DURATIONOFFSET ; 9
	const SPRITEANIMSTRUCT_FRAME          ; a
	const SPRITEANIMSTRUCT_0B             ; b
	const SPRITEANIMSTRUCT_0C             ; c
	const SPRITEANIMSTRUCT_0D             ; d
	const SPRITEANIMSTRUCT_0E             ; e
	const SPRITEANIMSTRUCT_0F             ; f

	const_def
	const SPRITE_ANIM_FRAMESET_00
	const SPRITE_ANIM_FRAMESET_01
	const SPRITE_ANIM_FRAMESET_02
	const SPRITE_ANIM_FRAMESET_03
	const SPRITE_ANIM_FRAMESET_04
	const SPRITE_ANIM_FRAMESET_05
	const SPRITE_ANIM_FRAMESET_06
	const SPRITE_ANIM_FRAMESET_07
	const SPRITE_ANIM_FRAMESET_08
	const SPRITE_ANIM_FRAMESET_09
	const SPRITE_ANIM_FRAMESET_GAMEFREAK_LOGO
	const SPRITE_ANIM_FRAMESET_0B
	const SPRITE_ANIM_FRAMESET_0C
	const SPRITE_ANIM_FRAMESET_SLOTS_GOLEM
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY
	const SPRITE_ANIM_FRAMESET_0F
	const SPRITE_ANIM_FRAMESET_SLOTS_EGG
	const SPRITE_ANIM_FRAMESET_WALK_CYCLE
	const SPRITE_ANIM_FRAMESET_12
	const SPRITE_ANIM_FRAMESET_13
	const SPRITE_ANIM_FRAMESET_14
	const SPRITE_ANIM_FRAMESET_15
	const SPRITE_ANIM_FRAMESET_16
	const SPRITE_ANIM_FRAMESET_17
	const SPRITE_ANIM_FRAMESET_18
	const SPRITE_ANIM_FRAMESET_19
	const SPRITE_ANIM_FRAMESET_1A
	const SPRITE_ANIM_FRAMESET_1B
	const SPRITE_ANIM_FRAMESET_1C
	const SPRITE_ANIM_FRAMESET_LEAF
	const SPRITE_ANIM_FRAMESET_1E
	const SPRITE_ANIM_FRAMESET_1F
	const SPRITE_ANIM_FRAMESET_20
	const SPRITE_ANIM_FRAMESET_21
	const SPRITE_ANIM_FRAMESET_22
	const SPRITE_ANIM_FRAMESET_23
	const SPRITE_ANIM_FRAMESET_24
	const SPRITE_ANIM_FRAMESET_HEADBUTT
	const SPRITE_ANIM_FRAMESET_26
	const SPRITE_ANIM_FRAMESET_27
	const SPRITE_ANIM_FRAMESET_28
	const SPRITE_ANIM_FRAMESET_29
	const SPRITE_ANIM_FRAMESET_2A
	const SPRITE_ANIM_FRAMESET_2B
	const SPRITE_ANIM_FRAMESET_2C
	const SPRITE_ANIM_FRAMESET_2D
	const SPRITE_ANIM_FRAMESET_2E
	const SPRITE_ANIM_FRAMESET_2F
	const SPRITE_ANIM_FRAMESET_30
	const SPRITE_ANIM_FRAMESET_31
	const SPRITE_ANIM_FRAMESET_32
	const SPRITE_ANIM_FRAMESET_33
	const SPRITE_ANIM_FRAMESET_34
	const SPRITE_ANIM_FRAMESET_35
	const SPRITE_ANIM_FRAMESET_36
	const SPRITE_ANIM_FRAMESET_37
	const SPRITE_ANIM_FRAMESET_38
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_1
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_2
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_3
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_4
	const SPRITE_ANIM_FRAMESET_3D
	const SPRITE_ANIM_FRAMESET_3E
	const SPRITE_ANIM_FRAMESET_3F
	const SPRITE_ANIM_FRAMESET_CELEBI_LEFT
	const SPRITE_ANIM_FRAMESET_CELEBI_RIGHT

	const_def
	const SPRITE_ANIM_SEQ_NULL
	const SPRITE_ANIM_SEQ_PARTY_MON
	const SPRITE_ANIM_SEQ_PARTY_MON_SWITCH
	const SPRITE_ANIM_SEQ_PARTY_MON_SELECTED
	const SPRITE_ANIM_SEQ_04
	const SPRITE_ANIM_SEQ_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_SEQ_GAMEFREAK_LOGO
	const SPRITE_ANIM_SEQ_07
	const SPRITE_ANIM_SEQ_08
	const SPRITE_ANIM_SEQ_SLOTS_GOLEM
	const SPRITE_ANIM_SEQ_SLOTS_CHANSEY
	const SPRITE_ANIM_SEQ_SLOTS_EGG
	const SPRITE_ANIM_SEQ_COMPOSE_MAIL_CURSOR
	const SPRITE_ANIM_SEQ_0D
	const SPRITE_ANIM_SEQ_0E
	const SPRITE_ANIM_SEQ_0F
	const SPRITE_ANIM_SEQ_10
	const SPRITE_ANIM_SEQ_11
	const SPRITE_ANIM_SEQ_12
	const SPRITE_ANIM_SEQ_EGG_SHELL
	const SPRITE_ANIM_SEQ_RADIO_TUNING_KNOB
	const SPRITE_ANIM_SEQ_CUT_GRASS_LEAVES
	const SPRITE_ANIM_SEQ_FLY_FROM
	const SPRITE_ANIM_SEQ_FLY_LEAF
	const SPRITE_ANIM_SEQ_FLY_TO
	const SPRITE_ANIM_SEQ_19
	const SPRITE_ANIM_SEQ_1A
	const SPRITE_ANIM_SEQ_1B
	const SPRITE_ANIM_SEQ_1C
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE
	const SPRITE_ANIM_SEQ_PICHU_WOOPER
	const SPRITE_ANIM_SEQ_CELEBI
	const SPRITE_ANIM_SEQ_UNOWN
	const SPRITE_ANIM_SEQ_UNOWN_F
	const SPRITE_ANIM_SEQ_SUICUNE_AWAY

	const_def
	const SPRITE_ANIM_INDEX_00
	const SPRITE_ANIM_INDEX_01
	const SPRITE_ANIM_INDEX_02
	const SPRITE_ANIM_INDEX_GAMEFREAK_LOGO
	const SPRITE_ANIM_INDEX_04
	const SPRITE_ANIM_INDEX_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_INDEX_SLOTS_GOLEM
	const SPRITE_ANIM_INDEX_SLOTS_CHANSEY
	const SPRITE_ANIM_INDEX_SLOTS_EGG
	const SPRITE_ANIM_INDEX_09
	const SPRITE_ANIM_INDEX_RED_WALK
	const SPRITE_ANIM_INDEX_0B
	const SPRITE_ANIM_INDEX_COMPOSE_MAIL_CURSOR
	const SPRITE_ANIM_INDEX_0D
	const SPRITE_ANIM_INDEX_0E
	const SPRITE_ANIM_INDEX_0F
	const SPRITE_ANIM_INDEX_10
	const SPRITE_ANIM_INDEX_11
	const SPRITE_ANIM_INDEX_12
	const SPRITE_ANIM_INDEX_13
	const SPRITE_ANIM_INDEX_14
	const SPRITE_ANIM_INDEX_15
	const SPRITE_ANIM_INDEX_LEAF
	const SPRITE_ANIM_INDEX_CUT_TREE
	const SPRITE_ANIM_INDEX_FLY_LEAF
	const SPRITE_ANIM_INDEX_19
	const SPRITE_ANIM_INDEX_1A
	const SPRITE_ANIM_INDEX_HEADBUTT
	const SPRITE_ANIM_INDEX_EGG_HATCH
	const SPRITE_ANIM_INDEX_1D
	const SPRITE_ANIM_INDEX_BLUE_WALK
	const SPRITE_ANIM_INDEX_1F
	const SPRITE_ANIM_INDEX_20
	const SPRITE_ANIM_INDEX_21
	const SPRITE_ANIM_INDEX_22
	const SPRITE_ANIM_INDEX_23
	const SPRITE_ANIM_INDEX_24
	const SPRITE_ANIM_INDEX_25
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE
	const SPRITE_ANIM_INDEX_INTRO_PICHU
	const SPRITE_ANIM_INDEX_INTRO_WOOPER
	const SPRITE_ANIM_INDEX_INTRO_UNOWN
	const SPRITE_ANIM_INDEX_INTRO_UNOWN_F
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE_AWAY
	const SPRITE_ANIM_INDEX_CELEBI
