; sprites
	const_def
	const SPRITE_NONE ; $00
	const SPRITE_CHRIS ; $01
	const SPRITE_CHRIS_BIKE ; $02
	const SPRITE_CHRIS_SURF ; $03
	const SPRITE_KRIS ; $04
	const SPRITE_KRIS_BIKE ; $05
	const SPRITE_KRIS_SURF ; $06
	const SPRITE_MOM ; $07
	const SPRITE_DAD ; $08
	const SPRITE_LYRA ; $09
	const SPRITE_SILVER ; $0a
	const SPRITE_FALKNER ; $0b
	const SPRITE_BUGSY ; $0c
	const SPRITE_WHITNEY ; $0d
	const SPRITE_MORTY ; $0e
	const SPRITE_CHUCK ; $0f
	const SPRITE_JASMINE ; $10
	const SPRITE_PRYCE ; $11
	const SPRITE_CLAIR ; $12
	const SPRITE_WILL ; $13
	const SPRITE_KOGA ; $14
	const SPRITE_BRUNO ; $15
	const SPRITE_KAREN ; $16
	const SPRITE_LANCE ; $17
	const SPRITE_BROCK ; $18
	const SPRITE_MISTY ; $19
	const SPRITE_SURGE ; $1a
	const SPRITE_ERIKA ; $1b
	const SPRITE_JANINE ; $1c
	const SPRITE_SABRINA ; $1d
	const SPRITE_BLAINE ; $1e
	const SPRITE_BLUE ; $1f
	const SPRITE_RED ; $20
	const SPRITE_LEAF ; $21
	const SPRITE_YELLOW ; $22
	const SPRITE_OAK ; $23
	const SPRITE_ELM ; $24
	const SPRITE_IVY ; $25
	const SPRITE_WESTWOOD ; $26
	const SPRITE_WILLOW ; $27
	const SPRITE_ANDY ; $28
	const SPRITE_BILL ; $29
	const SPRITE_EUSINE ; $2a
	const SPRITE_KURT ; $2b
	const SPRITE_REDS_MOM ; $2c
	const SPRITE_DAISY ; $2d
	const SPRITE_LORELEI ; $2e
	const SPRITE_AGATHA ; $2f
	const SPRITE_PALMER ; $30
	const SPRITE_WALKER ; $31
	const SPRITE_IMAKUNI ; $32
	const SPRITE_LAWRENCE ; $33
	const SPRITE_JAMES ; $34
	const SPRITE_JESSIE ; $35
	const SPRITE_PROTON ; $36
	const SPRITE_PETREL ; $37
	const SPRITE_ARCHER ; $38
	const SPRITE_ARIANA ; $39
	const SPRITE_GIOVANNI ; $3a
	const SPRITE_CHERYL ; $3b
	const SPRITE_RILEY ; $3c
	const SPRITE_BUCK ; $3d
	const SPRITE_MARLEY ; $3e
	const SPRITE_MIRA ; $3f
	const SPRITE_ANABEL ; $40
	const SPRITE_FLANNERY ; $41
	const SPRITE_MAYLENE ; $42
	const SPRITE_SKYLA ; $43
	const SPRITE_VALERIE ; $44
	const SPRITE_KUKUI ; $45
	const SPRITE_CAITLIN ; $46
	const SPRITE_DARACH ; $47
	const SPRITE_STEVEN ; $48
	const SPRITE_CYNTHIA ; $49
	const SPRITE_CANDELA ; $4a
	const SPRITE_BLANCHE ; $4b
	const SPRITE_SPARK ; $4c
	const SPRITE_BUENA ; $4d
	const SPRITE_CAPTAIN ; $4e
	const SPRITE_MATSUMOTO ; $4f
	const SPRITE_ARTIST ; $50
	const SPRITE_BAKER ; $51
	const SPRITE_BEAUTY ; $52
	const SPRITE_BIKER ; $53
	const SPRITE_BLACK_BELT ; $54
	const SPRITE_BOARDER ; $55
	const SPRITE_BREEDER ; $56
	const SPRITE_BUG_CATCHER ; $57
	const SPRITE_BUG_MANIAC ; $58
	const SPRITE_CHILD ; $59
	const SPRITE_COOLTRAINER_F ; $5a
	const SPRITE_COOLTRAINER_M ; $5b
	const SPRITE_COSPLAYER ; $5c
	const SPRITE_COWGIRL ; $5d
	const SPRITE_DRAGON_TAMER ; $5e
	const SPRITE_ELDER ; $5f
	const SPRITE_ENGINEER ; $60
	const SPRITE_FISHER ; $61
	const SPRITE_GENTLEMAN ; $62
	const SPRITE_GRAMPS ; $63
	const SPRITE_GRANNY ; $64
	const SPRITE_HEX_MANIAC ; $65
	const SPRITE_KIMONO_GIRL ; $66
	const SPRITE_LADY ; $67
	const SPRITE_LASS ; $68
	const SPRITE_NURSE ; $69
	const SPRITE_OFFICER ; $6a
	const SPRITE_OFFICER_F ; $6b
	const SPRITE_PHARMACIST ; $6c
	const SPRITE_PI ; $6d
	const SPRITE_POKEFAN_F ; $6e
	const SPRITE_POKEFAN_M ; $6f
	const SPRITE_RICH_BOY ; $70
	const SPRITE_ROCKER ; $71
	const SPRITE_ROCKET ; $72
	const SPRITE_ROCKET_GIRL ; $73
	const SPRITE_ROUGHNECK ; $74
	const SPRITE_SAGE ; $75
	const SPRITE_SAILOR ; $76
	const SPRITE_SCIENTIST ; $77
	const SPRITE_SIGHTSEER_M ; $78
	const SPRITE_SKIER ; $79
	const SPRITE_SUPER_NERD ; $7a
	const SPRITE_SWIMMER_GIRL ; $7b
	const SPRITE_SWIMMER_GUY ; $7c
	const SPRITE_TEACHER ; $7d
	const SPRITE_TWIN ; $7e
	const SPRITE_VETERAN_M ; $7f
	const SPRITE_VETERAN_F ; $80
	const SPRITE_YOUNGSTER ; $81
	const SPRITE_BOWING_NURSE ; $82
	const SPRITE_CLERK ; $83
	const SPRITE_RECEPTIONIST ; $84
	const SPRITE_LINK_RECEPTIONIST ; $85
	const SPRITE_GYM_GUY ; $86
	const SPRITE_FISHING_GURU ; $87
	const SPRITE_GAMEBOY_KID ; $88
	const SPRITE_SILPH_EMPLOYEE ; $89
	const SPRITE_SWIMMING_OFFICER ; $8a
	const SPRITE_SWIMMING_OFFICER_F ; $8b
	const SPRITE_CLEFAIRY_WALK ; $8c
	const SPRITE_FARFETCH_D ; $8d
	const SPRITE_LAPRAS ; $8e
	const SPRITE_EEVEE ; $8f
	const SPRITE_DRAGONITE ; $90
	const SPRITE_MEW ; $91
	const SPRITE_CELEBI ; $92
	const SPRITE_SURFING_PIKACHU ; $93
	const SPRITE_ARMORED_MEWTWO ; $94
	const SPRITE_BIG_SNORLAX ; $95
	const SPRITE_BIG_LAPRAS ; $96
	const SPRITE_BIG_ONIX ; $97
	const SPRITE_BIG_GYARADOS ; $98
	const SPRITE_SLOWPOKETAIL ; $99
	const SPRITE_WEIRD_TREE ; $9a
	const SPRITE_BALL_CUT_FRUIT ; $9b
	const SPRITE_BOULDER_ROCK_FOSSIL ; $9c
	const SPRITE_PAPER ; $9d
	const SPRITE_POKEDEX ; $9e
	const SPRITE_BOOK ; $9f
	const SPRITE_ELECTRIC_FENCE_LEFT ; $a0
	const SPRITE_ELECTRIC_FENCE_RIGHT ; $a1
	const SPRITE_SNES ; $a2
	const SPRITE_N64 ; $a3
	const SPRITE_GAMECUBE ; $a4
	const SPRITE_WII ; $a5
	const SPRITE_SILVER_TROPHY ; $a6
	const SPRITE_GOLD_TROPHY ; $a7

	const SPRITE_UNUSED ; $a8

	; Only use this on outdoor maps--it will default to the player's
	; sprite if it is not in the map group's overworld sprite set
	const SPRITE_PLAYER ; $a9

SPRITE_POKEMON EQU const_value
	const SPRITE_BULBASAUR ; $aa
	const SPRITE_CHARMANDER ; $ab
	const SPRITE_SQUIRTLE ; $ac
	const SPRITE_WEEDLE ; $ad
	const SPRITE_PIDGEY ; $ae
	const SPRITE_PIDGEOTTO ; $af
	const SPRITE_RATTATA ; $b0
	const SPRITE_PIKACHU ; $b1
	const SPRITE_NIDORAN_F ; $b2
	const SPRITE_NIDORAN_M ; $b3
	const SPRITE_NIDORINO ; $b4
	const SPRITE_CLEFAIRY ; $b5
	const SPRITE_JIGGLYPUFF ; $b6
	const SPRITE_ODDISH ; $b7
	const SPRITE_VILEPLUME ; $b8
	const SPRITE_DIGLETT ; $b9
	const SPRITE_MEOWTH ; $ba
	const SPRITE_PERSIAN ; $bb
	const SPRITE_PSYDUCK ; $bc
	const SPRITE_POLIWAG ; $bd
	const SPRITE_POLIWRATH ; $be
	const SPRITE_ABRA ; $bf
	const SPRITE_MACHOP ; $c0
	const SPRITE_MACHOKE ; $c1
	const SPRITE_TENTACOOL ; $c2
	const SPRITE_GEODUDE ; $c3
	const SPRITE_SLOWPOKE ; $c4
	const SPRITE_SLOWBRO ; $c5
	const SPRITE_DODRIO ; $c6
	const SPRITE_GRIMER ; $c7
	const SPRITE_SHELLDER ; $c8
	const SPRITE_GENGAR ; $c9
	const SPRITE_VOLTORB ; $ca
	const SPRITE_ELECTRODE ; $cb
	const SPRITE_RHYDON ; $cc
	const SPRITE_CHANSEY ; $cd
	const SPRITE_STARYU ; $ce
	const SPRITE_MAGIKARP ; $cf
	const SPRITE_ARTICUNO ; $d0
	const SPRITE_ZAPDOS ; $d1
	const SPRITE_MOLTRES ; $d2
	const SPRITE_DRATINI ; $d3
	const SPRITE_MEWTWO ; $d4
	const SPRITE_FURRET ; $d5
	const SPRITE_HOOTHOOT ; $d6
	const SPRITE_AMPHAROS ; $d7
	const SPRITE_MARILL ; $d8
	const SPRITE_MURKROW ; $d9
	const SPRITE_SLOWKING ; $da
	const SPRITE_UNOWN ; $db
	const SPRITE_HERACROSS ; $dc
	const SPRITE_WEAVILE ; $dd
	const SPRITE_URSARING ; $de
	const SPRITE_SKARMORY ; $df
	const SPRITE_SMEARGLE ; $e0
	const SPRITE_MILTANK ; $e1
	const SPRITE_BLISSEY ; $e2
	const SPRITE_RAIKOU ; $e3
	const SPRITE_ENTEI ; $e4
	const SPRITE_SUICUNE ; $e5
	const SPRITE_LUGIA ; $e6
	const SPRITE_HO_OH ; $e7
	const SPRITE_EGG ; $e8

	const SPRITE_DAYCARE_MON_1 ; $e9
	const SPRITE_DAYCARE_MON_2 ; $ea
	const SPRITE_GROTTO_MON    ; $eb

SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; $ec
	const SPRITE_DOLL_1 ; $ed
	const SPRITE_DOLL_2 ; $ee
	const SPRITE_BIG_DOLL ; $ef
	const SPRITE_FUCHSIA_GYM_1 ; $f0
	const SPRITE_FUCHSIA_GYM_2 ; $f1
	const SPRITE_FUCHSIA_GYM_3 ; $f2
	const SPRITE_FUCHSIA_GYM_4 ; $f3
	const SPRITE_COPYCAT ; $f4
	const SPRITE_JANINE_IMPERSONATOR ; $f5
	const SPRITE_REMATCH_GYM_LEADER_1 ; $f6
	const SPRITE_REMATCH_GYM_LEADER_2 ; $f7
	const SPRITE_GUIDE_GENT ; $f8
	const SPRITE_NEW_BARK_LYRA ; $f9
	const SPRITE_GOLDENROD_LYRA ; $fa
	const SPRITE_ROUTE_30_RATTATA ; $fb
	const SPRITE_CHERRYGROVE_RIVAL ; $fc
	const SPRITE_OLIVINE_RIVAL ; $fd
	const SPRITE_LAKE_OF_RAGE_LANCE ; $fe
	const SPRITE_CERULEAN_CAPE_MISTY ; $ff


; sprite types
const_value SET 1
	const WALKING_SPRITE
	const STANDING_SPRITE
	const STILL_SPRITE
	const MON_SPRITE
	const BIG_GYARADOS_SPRITE

; sprite header fields
	const_def
	const SPRITEHEADER_ADDR_LO
	const SPRITEHEADER_ADDR_HI
	const SPRITEHEADER_SIZE
	const SPRITEHEADER_BANK
	const SPRITEHEADER_TYPE
	const SPRITEHEADER_PALETTE
NUM_SPRITEHEADER_FIELDS EQU const_value

; sprite palettes
	const_def
	const PAL_OW_RED    ; 0
	const PAL_OW_BLUE   ; 1
	const PAL_OW_GREEN  ; 2
	const PAL_OW_BROWN  ; 3
	const PAL_OW_PURPLE ; 4
	const PAL_OW_SILVER ; 5
	const PAL_OW_TREE   ; 6
	const PAL_OW_ROCK   ; 7

; for party menu icons
const_value SET PAL_OW_SILVER
	const PAL_OW_GRAY   ; 5
	const PAL_OW_PINK   ; 6
	const PAL_OW_TEAL   ; 7

; sprite movement data table indices
; see data/map_objects.asm
	const_def
	const SPRITEMOVEDATA_00                   ; 00
	const SPRITEMOVEDATA_DOLL                 ; 01
	const SPRITEMOVEDATA_WANDER               ; 02
	const SPRITEMOVEDATA_SPINRANDOM_SLOW      ; 03
	const SPRITEMOVEDATA_WALK_UP_DOWN         ; 04
	const SPRITEMOVEDATA_WALK_LEFT_RIGHT      ; 05
	const SPRITEMOVEDATA_STANDING_DOWN        ; 06
	const SPRITEMOVEDATA_STANDING_UP          ; 07
	const SPRITEMOVEDATA_STANDING_LEFT        ; 08
	const SPRITEMOVEDATA_STANDING_RIGHT       ; 09
	const SPRITEMOVEDATA_SPINRANDOM_FAST      ; 0a
	const SPRITEMOVEDATA_PLAYER               ; 0b
	const SPRITEMOVEDATA_CUTTABLE_TREE        ; 0c
	const SPRITEMOVEDATA_FOLLOWING            ; 0d
	const SPRITEMOVEDATA_SCRIPTED             ; 0e
	const SPRITEMOVEDATA_SNORLAX              ; 0f
	const SPRITEMOVEDATA_POKEMON              ; 10
	const SPRITEMOVEDATA_SUDOWOODO            ; 11
	const SPRITEMOVEDATA_SMASHABLE_ROCK       ; 12
	const SPRITEMOVEDATA_STRENGTH_BOULDER     ; 13
	const SPRITEMOVEDATA_FOLLOWNOTEXACT       ; 14
	const SPRITEMOVEDATA_SHADOW               ; 15
	const SPRITEMOVEDATA_EMOTE                ; 16
	const SPRITEMOVEDATA_SCREENSHAKE          ; 17
	const SPRITEMOVEDATA_SPINCOUNTERCLOCKWISE ; 18
	const SPRITEMOVEDATA_SPINCLOCKWISE        ; 19
	const SPRITEMOVEDATA_BIGDOLL              ; 1a
	const SPRITEMOVEDATA_BOULDERDUST          ; 1b
	const SPRITEMOVEDATA_GRASS                ; 1c
	const SPRITEMOVEDATA_PUDDLE               ; 1d
	const SPRITEMOVEDATA_SWIM_AROUND          ; 1e
	const SPRITEMOVEDATA_SWIM_UP_DOWN         ; 1f
	const SPRITEMOVEDATA_SWIM_LEFT_RIGHT      ; 20
	const SPRITEMOVEDATA_BIG_GYARADOS         ; 21
	const SPRITEMOVEDATA_STANDING_DOWN_FLIP   ; 22
	const SPRITEMOVEDATA_STANDING_UP_FLIP     ; 23
NUM_SPRITEMOVEDATA EQU const_value
SPRITEMOVEDATA_FIELDS EQU 6

; sprite movement functions
; see engine/map_objects.asm:MapObjectMovementPattern.Pointers
	const_def
	const SPRITEMOVEFN_00                    ; 00
	const SPRITEMOVEFN_RANDOM_WALK_Y         ; 01
	const SPRITEMOVEFN_RANDOM_WALK_X         ; 02
	const SPRITEMOVEFN_RANDOM_WALK_XY        ; 03
	const SPRITEMOVEFN_SLOW_RANDOM_SPIN      ; 04
	const SPRITEMOVEFN_FAST_RANDOM_SPIN      ; 05
	const SPRITEMOVEFN_STANDING              ; 06
	const SPRITEMOVEFN_OBEY_DPAD             ; 07
	const SPRITEMOVEFN_FOLLOW                ; 08
	const SPRITEMOVEFN_SCRIPTED              ; 09
	const SPRITEMOVEFN_STRENGTH              ; 0a
	const SPRITEMOVEFN_FOLLOWNOTEXACT        ; 0b
	const SPRITEMOVEFN_SHADOW                ; 0c
	const SPRITEMOVEFN_EMOTE                 ; 0d
	const SPRITEMOVEFN_BIG_SNORLAX           ; 0e
	const SPRITEMOVEFN_BOUNCE                ; 0f
	const SPRITEMOVEFN_SCREENSHAKE           ; 10
	const SPRITEMOVEFN_SPIN_CLOCKWISE        ; 11
	const SPRITEMOVEFN_SPIN_COUNTERCLOCKWISE ; 12
	const SPRITEMOVEFN_BOULDERDUST           ; 13
	const SPRITEMOVEFN_GRASS                 ; 14
	const SPRITEMOVEFN_PUDDLE                ; 15
	const SPRITEMOVEFN_BIG_GYARADOS          ; 16
	const SPRITEMOVEFN_STANDING_FLIP         ; 17

; sprite step types
; see engine/map_objects.asm:StepTypesJumptable
	const_def
	const STEP_TYPE_00              ; 00
	const STEP_TYPE_SLEEP           ; 01
	const STEP_TYPE_NPC_WALK        ; 02
	const STEP_TYPE_03              ; 03
	const STEP_TYPE_04              ; 04
	const STEP_TYPE_05              ; 05
	const STEP_TYPE_PLAYER_WALK     ; 06
	const STEP_TYPE_07              ; 07
	const STEP_TYPE_NPC_JUMP        ; 08
	const STEP_TYPE_PLAYER_JUMP     ; 09
	const STEP_TYPE_HALF_STEP       ; 0a
	const STEP_TYPE_BUMP            ; 0b
	const STEP_TYPE_TELEPORT_FROM   ; 0c
	const STEP_TYPE_TELEPORT_TO     ; 0d
	const STEP_TYPE_SKYFALL         ; 0e
	const STEP_TYPE_0F              ; 0f
	const STEP_TYPE_GOT_BITE        ; 10
	const STEP_TYPE_ROCK_SMASH      ; 11
	const STEP_TYPE_RETURN_DIG      ; 12
	const STEP_TYPE_TRACKING_OBJECT ; 13
	const STEP_TYPE_14              ; 14
	const STEP_TYPE_SKYFALL_TOP     ; 15

; see engine/map_object_action.asm:Pointers445f
	const_def
	const PERSON_ACTION_00            ; 00
	const PERSON_ACTION_STAND         ; 01
	const PERSON_ACTION_STEP          ; 02
	const PERSON_ACTION_BUMP          ; 03
	const PERSON_ACTION_SPIN          ; 04
	const PERSON_ACTION_SPIN_FLICKER  ; 05
	const PERSON_ACTION_FISHING       ; 06
	const PERSON_ACTION_SHADOW        ; 07
	const PERSON_ACTION_EMOTE         ; 08
	const PERSON_ACTION_BIG_SNORLAX   ; 09
	const PERSON_ACTION_BOUNCE        ; 0a
	const PERSON_ACTION_WEIRD_TREE    ; 0b
	const PERSON_ACTION_BIG_DOLL      ; 0c
	const PERSON_ACTION_BOULDER_DUST  ; 0d
	const PERSON_ACTION_GRASS_SHAKE   ; 0e
	const PERSON_ACTION_PUDDLE_SPLASH ; 0f
	const PERSON_ACTION_SKYFALL       ; 10
	const PERSON_ACTION_BIG_GYARADOS  ; 11
	const PERSON_ACTION_STAND_FLIP    ; 12

; see engine/facings.asm:Facings
	const_def
	const FACING_STEP_DOWN_0    ; 00
	const FACING_STEP_DOWN_1    ; 01
	const FACING_STEP_DOWN_2    ; 02
	const FACING_STEP_DOWN_3    ; 03
	const FACING_STEP_UP_0      ; 04
	const FACING_STEP_UP_1      ; 05
	const FACING_STEP_UP_2      ; 06
	const FACING_STEP_UP_3      ; 07
	const FACING_STEP_LEFT_0    ; 08
	const FACING_STEP_LEFT_1    ; 09
	const FACING_STEP_LEFT_2    ; 0a
	const FACING_STEP_LEFT_3    ; 0b
	const FACING_STEP_RIGHT_0   ; 0c
	const FACING_STEP_RIGHT_1   ; 0d
	const FACING_STEP_RIGHT_2   ; 0e
	const FACING_STEP_RIGHT_3   ; 0f
	const FACING_FISH_DOWN      ; 10
	const FACING_FISH_UP        ; 11
	const FACING_FISH_LEFT      ; 12
	const FACING_FISH_RIGHT     ; 13
	const FACING_EMOTE          ; 14
	const FACING_SHADOW         ; 15
	const FACING_BIG_DOLL_ASYM  ; 16
	const FACING_BIG_DOLL_SYM   ; 17
	const FACING_WEIRD_TREE_0   ; 18
	const FACING_WEIRD_TREE_1   ; 19
	const FACING_WEIRD_TREE_2   ; 1a
	const FACING_WEIRD_TREE_3   ; 1b
	const FACING_BOULDER_DUST_1 ; 1c
	const FACING_BOULDER_DUST_2 ; 1d
	const FACING_GRASS_1        ; 1e
	const FACING_GRASS_2        ; 1f
	const FACING_SPLASH_1       ; 20
	const FACING_SPLASH_2       ; 21
	const FACING_BIG_GYARADOS_1 ; 22
	const FACING_BIG_GYARADOS_2 ; 23
	const FACING_STEP_DOWN_FLIP ; 24
	const FACING_STEP_UP_FLIP   ; 25

	const_def
	const SPRITEANIMSTRUCT_INDEX           ; 0
	const SPRITEANIMSTRUCT_FRAMESET_ID     ; 1
	const SPRITEANIMSTRUCT_ANIM_SEQ_ID     ; 2
	const SPRITEANIMSTRUCT_TILE_ID         ; 3
	const SPRITEANIMSTRUCT_XCOORD          ; 4
	const SPRITEANIMSTRUCT_YCOORD          ; 5
	const SPRITEANIMSTRUCT_XOFFSET         ; 6
	const SPRITEANIMSTRUCT_YOFFSET         ; 7
	const SPRITEANIMSTRUCT_DURATION        ; 8
	const SPRITEANIMSTRUCT_DURATIONOFFSET  ; 9
	const SPRITEANIMSTRUCT_FRAME           ; a
	const SPRITEANIMSTRUCT_JUMPTABLE_INDEX ; b
	const SPRITEANIMSTRUCT_0C              ; c
	const SPRITEANIMSTRUCT_0D              ; d
	const SPRITEANIMSTRUCT_0E              ; e
	const SPRITEANIMSTRUCT_0F              ; f

; see data/sprite_engine.asm:SpriteAnimFrameData
	const_def
	const SPRITE_ANIM_FRAMESET_NULL
	const SPRITE_ANIM_FRAMESET_PARTY_MON
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_MAIL
	const SPRITE_ANIM_FRAMESET_PARTY_MON_WITH_ITEM
	const SPRITE_ANIM_FRAMESET_04
	const SPRITE_ANIM_FRAMESET_05
	const SPRITE_ANIM_FRAMESET_06
	const SPRITE_ANIM_FRAMESET_07
	const SPRITE_ANIM_FRAMESET_TEXT_ENTRY_CURSOR
	const SPRITE_ANIM_FRAMESET_09
	const SPRITE_ANIM_FRAMESET_GAMEFREAK_LOGO
	const SPRITE_ANIM_FRAMESET_0B
	const SPRITE_ANIM_FRAMESET_0C
	const SPRITE_ANIM_FRAMESET_SLOTS_GOLEM
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY
	const SPRITE_ANIM_FRAMESET_SLOTS_CHANSEY_2
	const SPRITE_ANIM_FRAMESET_SLOTS_EGG
	const SPRITE_ANIM_FRAMESET_RED_WALK
	const SPRITE_ANIM_FRAMESET_STILL_CURSOR
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL
	const SPRITE_ANIM_FRAMESET_TRADE_POKE_BALL_0
	const SPRITE_ANIM_FRAMESET_TRADE_POOF
	const SPRITE_ANIM_FRAMESET_TRADE_TUBE_BULGE
	const SPRITE_ANIM_FRAMESET_TRADEMON_ICON
	const SPRITE_ANIM_FRAMESET_TRADEMON_BUBBLE
	const SPRITE_ANIM_FRAMESET_EVOLUTION_BALL_OF_LIGHT
	const SPRITE_ANIM_FRAMESET_RADIO_TUNING_KNOB
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_RED
	const SPRITE_ANIM_FRAMESET_1C
	const SPRITE_ANIM_FRAMESET_LEAF
	const SPRITE_ANIM_FRAMESET_CUT_TREE
	const SPRITE_ANIM_FRAMESET_EGG_CRACK
	const SPRITE_ANIM_FRAMESET_EGG_HATCH
	const SPRITE_ANIM_FRAMESET_21
	const SPRITE_ANIM_FRAMESET_22
	const SPRITE_ANIM_FRAMESET_23
	const SPRITE_ANIM_FRAMESET_24
	const SPRITE_ANIM_FRAMESET_HEADBUTT
	const SPRITE_ANIM_FRAMESET_26
	const SPRITE_ANIM_FRAMESET_27
	const SPRITE_ANIM_FRAMESET_28
	const SPRITE_ANIM_FRAMESET_29
	const SPRITE_ANIM_FRAMESET_2A
	const SPRITE_ANIM_FRAMESET_2B
	const SPRITE_ANIM_FRAMESET_2C
	const SPRITE_ANIM_FRAMESET_BLUE_WALK
	const SPRITE_ANIM_FRAMESET_MAGNET_TRAIN_BLUE
	const SPRITE_ANIM_FRAMESET_2F
	const SPRITE_ANIM_FRAMESET_30
	const SPRITE_ANIM_FRAMESET_31
	const SPRITE_ANIM_FRAMESET_32
	const SPRITE_ANIM_FRAMESET_33
	const SPRITE_ANIM_FRAMESET_34
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_2
	const SPRITE_ANIM_FRAMESET_INTRO_PICHU
	const SPRITE_ANIM_FRAMESET_INTRO_WOOPER
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_1
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_2
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_3
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_4
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F_2
	const SPRITE_ANIM_FRAMESET_INTRO_SUICUNE_AWAY
	const SPRITE_ANIM_FRAMESET_INTRO_UNOWN_F
	const SPRITE_ANIM_FRAMESET_CELEBI_LEFT
	const SPRITE_ANIM_FRAMESET_CELEBI_RIGHT

; see engine/sprite_anims.asm:DoAnimFrame.Jumptable
	const_def
	const SPRITE_ANIM_SEQ_NULL
	const SPRITE_ANIM_SEQ_PARTY_MON
	const SPRITE_ANIM_SEQ_PARTY_MON_SWITCH
	const SPRITE_ANIM_SEQ_PARTY_MON_SELECTED
	const SPRITE_ANIM_SEQ_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_SEQ_COMPOSE_MAIL_CURSOR
	const SPRITE_ANIM_SEQ_GAMEFREAK_LOGO
	const SPRITE_ANIM_SEQ_SLOTS_GOLEM
	const SPRITE_ANIM_SEQ_SLOTS_CHANSEY
	const SPRITE_ANIM_SEQ_SLOTS_EGG
;	const SPRITE_ANIM_SEQ_DUMMY_GAME_CURSOR
	const SPRITE_ANIM_SEQ_POKEGEAR_MODE_ARROW
	const SPRITE_ANIM_SEQ_TRADE_POKE_BALL
	const SPRITE_ANIM_SEQ_TRADE_TUBE_BULGE
	const SPRITE_ANIM_SEQ_TRADEMON_IN_TUBE
	const SPRITE_ANIM_SEQ_REVEAL_NEW_MON
	const SPRITE_ANIM_SEQ_RADIO_TUNING_KNOB
	const SPRITE_ANIM_SEQ_CUT_GRASS_LEAVES
	const SPRITE_ANIM_SEQ_FLY_FROM
	const SPRITE_ANIM_SEQ_FLY_LEAF
	const SPRITE_ANIM_SEQ_FLY_TO
	const SPRITE_ANIM_SEQ_INTRO_SUICUNE
	const SPRITE_ANIM_SEQ_PICHU_WOOPER
	const SPRITE_ANIM_SEQ_UNOWN
	const SPRITE_ANIM_SEQ_UNOWN_F
	const SPRITE_ANIM_SEQ_SUICUNE_AWAY
	const SPRITE_ANIM_SEQ_CELEBI

; see engine/sprites.asm:SpriteAnimSeqData
	const_def
	const SPRITE_ANIM_INDEX_PARTY_MON
	const SPRITE_ANIM_INDEX_NAMING_SCREEN_CURSOR
	const SPRITE_ANIM_INDEX_GAMEFREAK_LOGO
	const SPRITE_ANIM_INDEX_SLOTS_GOLEM
	const SPRITE_ANIM_INDEX_SLOTS_CHANSEY
	const SPRITE_ANIM_INDEX_SLOTS_EGG
	const SPRITE_ANIM_INDEX_COMPOSE_MAIL_CURSOR
	const SPRITE_ANIM_INDEX_RED_WALK
;	const SPRITE_ANIM_INDEX_DUMMY_GAME
	const SPRITE_ANIM_INDEX_POKEGEAR_MODE_ARROW
	const SPRITE_ANIM_INDEX_TRADE_POKE_BALL
	const SPRITE_ANIM_INDEX_TRADE_POOF
	const SPRITE_ANIM_INDEX_TRADE_TUBE_BULGE
	const SPRITE_ANIM_INDEX_TRADEMON_ICON
	const SPRITE_ANIM_INDEX_TRADEMON_BUBBLE
	const SPRITE_ANIM_INDEX_EVOLUTION_BALL_OF_LIGHT
	const SPRITE_ANIM_INDEX_RADIO_TUNING_KNOB
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_RED
	const SPRITE_ANIM_INDEX_LEAF
	const SPRITE_ANIM_INDEX_CUT_TREE
	const SPRITE_ANIM_INDEX_FLY_LEAF
	const SPRITE_ANIM_INDEX_EGG_CRACK
	const SPRITE_ANIM_INDEX_HEADBUTT
	const SPRITE_ANIM_INDEX_EGG_HATCH
	const SPRITE_ANIM_INDEX_BLUE_WALK
	const SPRITE_ANIM_INDEX_MAGNET_TRAIN_BLUE
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE
	const SPRITE_ANIM_INDEX_INTRO_PICHU
	const SPRITE_ANIM_INDEX_INTRO_WOOPER
	const SPRITE_ANIM_INDEX_INTRO_UNOWN
	const SPRITE_ANIM_INDEX_INTRO_UNOWN_F
	const SPRITE_ANIM_INDEX_INTRO_SUICUNE_AWAY
	const SPRITE_ANIM_INDEX_CELEBI

; see data/sprite_engine.asm:SpriteAnimOAMData
	const_def
	const SPRITE_ANIM_FRAME_IDX_00
	const SPRITE_ANIM_FRAME_IDX_01
	const SPRITE_ANIM_FRAME_IDX_02
	const SPRITE_ANIM_FRAME_IDX_03
	const SPRITE_ANIM_FRAME_IDX_04
	const SPRITE_ANIM_FRAME_IDX_05
	const SPRITE_ANIM_FRAME_IDX_06
	const SPRITE_ANIM_FRAME_IDX_07
	const SPRITE_ANIM_FRAME_IDX_08
	const SPRITE_ANIM_FRAME_IDX_09
	const SPRITE_ANIM_FRAME_IDX_0A
	const SPRITE_ANIM_FRAME_IDX_0B
	const SPRITE_ANIM_FRAME_IDX_0C
	const SPRITE_ANIM_FRAME_IDX_0D
	const SPRITE_ANIM_FRAME_IDX_0E
	const SPRITE_ANIM_FRAME_IDX_0F
	const SPRITE_ANIM_FRAME_IDX_10
	const SPRITE_ANIM_FRAME_IDX_11
	const SPRITE_ANIM_FRAME_IDX_12
	const SPRITE_ANIM_FRAME_IDX_13
	const SPRITE_ANIM_FRAME_IDX_14
	const SPRITE_ANIM_FRAME_IDX_15
	const SPRITE_ANIM_FRAME_IDX_16
	const SPRITE_ANIM_FRAME_IDX_17
	const SPRITE_ANIM_FRAME_IDX_18
	const SPRITE_ANIM_FRAME_IDX_19
	const SPRITE_ANIM_FRAME_IDX_1A
	const SPRITE_ANIM_FRAME_IDX_1B
	const SPRITE_ANIM_FRAME_IDX_1C
	const SPRITE_ANIM_FRAME_IDX_1D
	const SPRITE_ANIM_FRAME_IDX_1E
	const SPRITE_ANIM_FRAME_IDX_1F
	const SPRITE_ANIM_FRAME_IDX_20
	const SPRITE_ANIM_FRAME_IDX_21
	const SPRITE_ANIM_FRAME_IDX_22
	const SPRITE_ANIM_FRAME_IDX_23
	const SPRITE_ANIM_FRAME_IDX_24
	const SPRITE_ANIM_FRAME_IDX_25
	const SPRITE_ANIM_FRAME_IDX_26
	const SPRITE_ANIM_FRAME_IDX_27
	const SPRITE_ANIM_FRAME_IDX_28
	const SPRITE_ANIM_FRAME_IDX_29
	const SPRITE_ANIM_FRAME_IDX_2A
	const SPRITE_ANIM_FRAME_IDX_2B
	const SPRITE_ANIM_FRAME_IDX_2C
	const SPRITE_ANIM_FRAME_IDX_2D
	const SPRITE_ANIM_FRAME_IDX_2E
	const SPRITE_ANIM_FRAME_IDX_2F
	const SPRITE_ANIM_FRAME_IDX_30
	const SPRITE_ANIM_FRAME_IDX_31
	const SPRITE_ANIM_FRAME_IDX_32
	const SPRITE_ANIM_FRAME_IDX_33
	const SPRITE_ANIM_FRAME_IDX_34
	const SPRITE_ANIM_FRAME_IDX_35
	const SPRITE_ANIM_FRAME_IDX_36
	const SPRITE_ANIM_FRAME_IDX_37
	const SPRITE_ANIM_FRAME_IDX_38
	const SPRITE_ANIM_FRAME_IDX_39
	const SPRITE_ANIM_FRAME_IDX_3A
	const SPRITE_ANIM_FRAME_IDX_3B
	const SPRITE_ANIM_FRAME_IDX_3C
	const SPRITE_ANIM_FRAME_IDX_3D
	const SPRITE_ANIM_FRAME_IDX_3E
	const SPRITE_ANIM_FRAME_IDX_3F
	const SPRITE_ANIM_FRAME_IDX_40
	const SPRITE_ANIM_FRAME_IDX_41
	const SPRITE_ANIM_FRAME_IDX_42
	const SPRITE_ANIM_FRAME_IDX_43
	const SPRITE_ANIM_FRAME_IDX_44
	const SPRITE_ANIM_FRAME_IDX_45
	const SPRITE_ANIM_FRAME_IDX_46
	const SPRITE_ANIM_FRAME_IDX_47
	const SPRITE_ANIM_FRAME_IDX_48
	const SPRITE_ANIM_FRAME_IDX_49
	const SPRITE_ANIM_FRAME_IDX_4A
	const SPRITE_ANIM_FRAME_IDX_4B
	const SPRITE_ANIM_FRAME_IDX_4C
	const SPRITE_ANIM_FRAME_IDX_4D
	const SPRITE_ANIM_FRAME_IDX_4E
	const SPRITE_ANIM_FRAME_IDX_4F
	const SPRITE_ANIM_FRAME_IDX_50
	const SPRITE_ANIM_FRAME_IDX_51
	const SPRITE_ANIM_FRAME_IDX_52
	const SPRITE_ANIM_FRAME_IDX_53
	const SPRITE_ANIM_FRAME_IDX_54
	const SPRITE_ANIM_FRAME_IDX_55
	const SPRITE_ANIM_FRAME_IDX_56
	const SPRITE_ANIM_FRAME_IDX_57
	const SPRITE_ANIM_FRAME_IDX_58
	const SPRITE_ANIM_FRAME_IDX_59
	const SPRITE_ANIM_FRAME_IDX_5A
	const SPRITE_ANIM_FRAME_IDX_5B
	const SPRITE_ANIM_FRAME_IDX_5C
	const SPRITE_ANIM_FRAME_IDX_5D
	const SPRITE_ANIM_FRAME_IDX_5E
	const SPRITE_ANIM_FRAME_IDX_5F
	const SPRITE_ANIM_FRAME_IDX_60
	const SPRITE_ANIM_FRAME_IDX_61
	const SPRITE_ANIM_FRAME_IDX_62
	const SPRITE_ANIM_FRAME_IDX_63
	const SPRITE_ANIM_FRAME_IDX_64
	const SPRITE_ANIM_FRAME_IDX_65
	const SPRITE_ANIM_FRAME_IDX_66
	const SPRITE_ANIM_FRAME_IDX_67
	const SPRITE_ANIM_FRAME_IDX_68
	const SPRITE_ANIM_FRAME_IDX_69
	const SPRITE_ANIM_FRAME_IDX_6A
	const SPRITE_ANIM_FRAME_IDX_6B
	const SPRITE_ANIM_FRAME_IDX_6C
	const SPRITE_ANIM_FRAME_IDX_6D
	const SPRITE_ANIM_FRAME_IDX_6E
	const SPRITE_ANIM_FRAME_IDX_6F
	const SPRITE_ANIM_FRAME_IDX_70
	const SPRITE_ANIM_FRAME_IDX_71
	const SPRITE_ANIM_FRAME_IDX_72
	const SPRITE_ANIM_FRAME_IDX_73
	const SPRITE_ANIM_FRAME_IDX_74
	const SPRITE_ANIM_FRAME_IDX_75
	const SPRITE_ANIM_FRAME_IDX_76
	const SPRITE_ANIM_FRAME_IDX_77
	const SPRITE_ANIM_FRAME_IDX_78
	const SPRITE_ANIM_FRAME_IDX_79
	const SPRITE_ANIM_FRAME_IDX_7A
	const SPRITE_ANIM_FRAME_IDX_7B
	const SPRITE_ANIM_FRAME_IDX_7C
	const SPRITE_ANIM_FRAME_IDX_7D
	const SPRITE_ANIM_FRAME_IDX_7E
	const SPRITE_ANIM_FRAME_IDX_7F
	const SPRITE_ANIM_FRAME_IDX_80
	const SPRITE_ANIM_FRAME_IDX_81
	const SPRITE_ANIM_FRAME_IDX_82
	const SPRITE_ANIM_FRAME_IDX_83
	const SPRITE_ANIM_FRAME_IDX_84
	const SPRITE_ANIM_FRAME_IDX_85
	const SPRITE_ANIM_FRAME_IDX_86
	const SPRITE_ANIM_FRAME_IDX_87
	const SPRITE_ANIM_FRAME_IDX_88
	const SPRITE_ANIM_FRAME_IDX_89
	const SPRITE_ANIM_FRAME_IDX_8A
	const SPRITE_ANIM_FRAME_IDX_8B
	const SPRITE_ANIM_FRAME_IDX_8C
	const SPRITE_ANIM_FRAME_IDX_8D
