	const_def
	const pokecenternurse
	const difficultbookshelf
	const picturebookshelf
	const magazinebookshelf
	const teamrocketoath
	const incenseburner
	const merchandiseshelf
	const townmap
	const window
	const tv
	const radio1
	const radio2
	const trashcan
	const strengthboulder
	const smashrock
	const pokecentersign
	const martsign
	const elevatorbutton
	const daytotext
	const bugcontestresultswarp
	const bugcontestresults
	const asknumber1m
	const asknumber2m
	const registerednumberm
	const numberacceptedm
	const numberdeclinedm
	const phonefullm
	const rematchm
	const giftm
	const packfullm
	const rematchgiftm
	const asknumber1f
	const asknumber2f
	const registerednumberf
	const numberacceptedf
	const numberdeclinedf
	const phonefullf
	const rematchf
	const giftf
	const packfullf
	const rematchgiftf
	const gymstatue0
	const gymstatue1
	const gymstatue2
	const gymstatue3
	const receiveitem
	const pcscript
	const gamecornercoinvendor
	const happinesschecknpc
	const cuttree
	const refrigerator
	const sink
	const stove
	const vendingmachine
	const treegrotto
	const cavegrotto
