	const_def
	const SUMMARY_PINK_PAGE
	const SUMMARY_BLUE_PAGE
	const SUMMARY_GREEN_PAGE
	const SUMMARY_ORANGE_PAGE
DEF NUM_SUMMARY_PAGES EQU const_value

; Routines for hblank (see home/lcd.asm)
DEF SUMMARY_LCD_HIDE_WINDOW EQU 0
DEF SUMMARY_LCD_SHOW_WINDOW EQU 1
DEF SUMMARY_LCD_SCROLL_BACKGROUND EQU 2
