	const_def
	const NO_TMHM       ; $00

	add_tm DYNAMICPUNCH ; $01
	add_tm DRAGON_CLAW  ; $02
	add_tm CURSE        ; $03
	add_tm CALM_MIND    ; $04
	add_tm ROAR         ; $05
	add_tm TOXIC        ; $06
	add_tm HAIL         ; $07
	add_tm BULK_UP      ; $08
	add_tm SWORDS_DANCE ; $09
	add_tm HIDDEN_POWER ; $0a
	add_tm SUNNY_DAY    ; $0b
	add_tm HONE_CLAWS   ; $0c
	add_tm ICE_BEAM     ; $0d
	add_tm BLIZZARD     ; $0e
	add_tm HYPER_BEAM   ; $0f
	add_tm LIGHT_SCREEN ; $10
	add_tm PROTECT      ; $11
	add_tm RAIN_DANCE   ; $12
	add_tm GIGA_DRAIN   ; $13
	add_tm SAFEGUARD    ; $14
	add_tm DRAGONBREATH ; $15
	add_tm SOLAR_BEAM   ; $16
	add_tm IRON_TAIL    ; $17
	add_tm THUNDERBOLT  ; $18
	add_tm THUNDER      ; $19
	add_tm EARTHQUAKE   ; $1a
	add_tm RETURN       ; $1b
	add_tm DIG          ; $1c
	add_tm PSYCHIC      ; $1d
	add_tm SHADOW_BALL  ; $1e
	add_tm MUD_SLAP     ; $1f
	add_tm DOUBLE_TEAM  ; $20
	add_tm REFLECT      ; $21
	add_tm FLASH_CANNON ; $22
	add_tm FLAMETHROWER ; $23
	add_tm SLUDGE_BOMB  ; $24
	add_tm SANDSTORM    ; $25
	add_tm FIRE_BLAST   ; $26
	add_tm SWIFT        ; $27
	add_tm AERIAL_ACE   ; $28
	add_tm STONE_EDGE   ; $29
	add_tm AVALANCHE    ; $2a
	add_tm WILD_CHARGE  ; $2b
	add_tm REST         ; $2c
	add_tm ATTRACT      ; $2d
	add_tm THIEF        ; $2e
	add_tm STEEL_WING   ; $2f
	add_tm ROCK_SLIDE   ; $30
	add_tm FURY_CUTTER  ; $31
	add_tm SUBSTITUTE   ; $32
	add_tm BODY_SLAM    ; $33
	add_tm FOCUS_BLAST  ; $34
	add_tm ENERGY_BALL  ; $35
	add_tm FALSE_SWIPE  ; $36
	add_tm SCALD        ; $37
	add_tm X_SCISSOR    ; $38
	add_tm DARK_PULSE   ; $39
	add_tm ENDURE       ; $3a
	add_tm DRAGON_PULSE ; $3b
	add_tm DAZZLINGLEAM ; $3c
	add_tm WILL_O_WISP  ; $3d
	add_tm POISON_JAB   ; $3e
	add_tm THUNDER_WAVE ; $3f
	add_tm EXPLOSION    ; $40
	add_tm SHADOW_CLAW  ; $41
NUM_TMS = const_value - TM01

	add_hm CUT          ; $42
	add_hm FLY          ; $43
	add_hm SURF         ; $44
	add_hm STRENGTH     ; $45
	add_hm FLASH        ; $46
	add_hm WHIRLPOOL    ; $47
	add_hm WATERFALL    ; $48
	add_hm ROCK_SMASH   ; $49
NUM_HMS = const_value - HM01

	add_mt AQUA_TAIL    ; $4a
	add_mt COUNTER      ; $4b
	add_mt DEFENSE_CURL ; $4c
	add_mt DOUBLE_EDGE  ; $4d
	add_mt DREAM_EATER  ; $4e
	add_mt EARTH_POWER  ; $4f
	add_mt FIRE_PUNCH   ; $50
	add_mt HEADBUTT     ; $51
	add_mt HYPER_VOICE  ; $52
	add_mt ICE_PUNCH    ; $53
	add_mt ICY_WIND     ; $54
	add_mt IRON_HEAD    ; $55
	add_mt ROLLOUT      ; $56
	add_mt SEED_BOMB    ; $57
	add_mt SEISMIC_TOSS ; $58
	add_mt SLEEP_TALK   ; $59
	add_mt SWAGGER      ; $5a
	add_mt THUNDERPUNCH ; $5b
	add_mt WATER_PULSE  ; $5c
	add_mt ZAP_CANNON   ; $5d
	add_mt ZEN_HEADBUTT ; $5e
