; Each trainer class has its own group. See trainers.asm.

TrainerGroups: ; 0x39999
	dw KayGroup
	dw CalGroup
	dw FalknerGroup
	dw BugsyGroup
	dw WhitneyGroup
	dw MortyGroup
	dw ChuckGroup
	dw JasmineGroup
	dw PryceGroup
	dw ClairGroup
	dw WillGroup
	dw KogaGroup
	dw BrunoGroup
	dw KarenGroup
	dw ChampionGroup
	dw BrockGroup
	dw MistyGroup
	dw LtSurgeGroup
	dw ErikaGroup
	dw JanineGroup
	dw SabrinaGroup
	dw BlaineGroup
	dw BlueGroup
	dw RedGroup
	dw LeafGroup
	dw Rival0Group
	dw Rival1Group
	dw Rival2Group
	dw Lyra1Group
	dw Lyra2Group
	dw YoungsterGroup
	dw BugCatcherGroup
	dw CamperGroup
	dw PicnickerGroup
	dw TwinsGroup
	dw FisherGroup
	dw BirdKeeperGroup
	dw HikerGroup
	dw GruntMGroup
	dw GruntFGroup
	dw PokefanMGroup
	dw PokefanFGroup
	dw OfficerMGroup
	dw OfficerFGroup
	dw PokemaniacGroup
	dw CosplayerGroup
	dw SuperNerdGroup
	dw LassGroup
	dw BeautyGroup
	dw BugManiacGroup
	dw RuinManiacGroup
	dw FirebreatherGroup
	dw JugglerGroup
	dw SchoolboyGroup
	dw SchoolgirlGroup
	dw PsychicGroup
	dw HexManiacGroup
	dw SageGroup
	dw MediumGroup
	dw KimonoGirlGroup
	dw ElderGroup
	dw SrAndJrGroup
	dw CoupleGroup
	dw GentlemanGroup
	dw RichBoyGroup
	dw LadyGroup
	dw BreederGroup
	dw BakerGroup
	dw CowgirlGroup
	dw SailorGroup
	dw SwimmerMGroup
	dw SwimmerFGroup
	dw BurglarGroup
	dw PIGroup
	dw ScientistGroup
	dw BoarderGroup
	dw SkierGroup
	dw BlackbeltGroup
	dw BattleGirlGroup
	dw DragonTamerGroup
	dw TeacherGroup
	dw GuitaristMGroup
	dw GuitaristFGroup
	dw BikerGroup
	dw RoughneckGroup
	dw SightseerMGroup
	dw SightseerFGroup
	dw CooltrainerMGroup
	dw CooltrainerFGroup
	dw AceDuoGroup
	dw VeteranMGroup
	dw VeteranFGroup
	dw ProtonGroup
	dw PetrelGroup
	dw ArcherGroup
	dw ArianaGroup
	dw GiovanniGroup
	dw ProfOakGroup
	dw ProfElmGroup
	dw ProfIvyGroup
	dw MysticalmanGroup
	dw KarateKingGroup
	dw TowerTycoonGroup
	dw JessieJamesGroup
	dw LoreleiGroup
	dw AgathaGroup
	dw StevenGroup
	dw CynthiaGroup
	dw CherylGroup
	dw RileyGroup
	dw BuckGroup
	dw MarleyGroup
	dw MiraGroup
	dw AnabelGroup
	dw DarachGroup
	dw CaitlinGroup
	dw ValerieGroup
	dw BillGroup
	dw YellowGroup
	dw WalkerGroup
	dw LawrenceGroup
	dw ReiGroup
