; Each trainer class has its own group. See trainers.asm.

TrainerGroups: ; 0x39999
	dw KayGroup
	dw CalGroup
	dw FalknerGroup
	dw BugsyGroup
	dw WhitneyGroup
	dw MortyGroup
	dw ChuckGroup
	dw JasmineGroup
	dw PryceGroup
	dw ClairGroup
	dw WillGroup
	dw KogaGroup
	dw BrunoGroup
	dw KarenGroup
	dw ChampionGroup
	dw BrockGroup
	dw MistyGroup
	dw LtSurgeGroup
	dw ErikaGroup
	dw JanineGroup
	dw SabrinaGroup
	dw BlaineGroup
	dw BlueGroup
	dw RedGroup
	dw LeafGroup
	dw Rival1Group
	dw Rival2Group
	dw YoungsterGroup
	dw BugCatcherGroup
	dw CamperGroup
	dw PicnickerGroup
	dw TwinsGroup
	dw FisherGroup
	dw BirdKeeperGroup
	dw HikerGroup
	dw GruntMGroup
	dw GruntFGroup
	dw JessieJamesGroup
	dw PokefanMGroup
	dw PokefanFGroup
	dw OfficerMGroup
	dw OfficerFGroup
	dw PokemaniacGroup
	dw SuperNerdGroup
	dw LassGroup
	dw BeautyGroup
	dw FirebreatherGroup
	dw JugglerGroup
	dw SchoolboyGroup
	dw SchoolgirlGroup
	dw PsychicGroup
	dw HexManiacGroup
	dw SageGroup
	dw MediumGroup
	dw KimonoGirlGroup
	dw ElderGroup
	dw SrAndJrGroup
	dw CoupleGroup
	dw GentlemanGroup
	dw RichBoyGroup
	dw CowgirlGroup
	dw SailorGroup
	dw SwimmerMGroup
	dw SwimmerFGroup
	dw BurglarGroup
	dw PIGroup
	dw ScientistGroup
	dw BoarderGroup
	dw SkierGroup
	dw BlackbeltGroup
	dw BattleGirlGroup
	dw DragonTamerGroup
	dw TeacherGroup
	dw GuitaristMGroup
	dw GuitaristFGroup
	dw BikerGroup
	dw RoughneckGroup
	dw CooltrainerMGroup
	dw CooltrainerFGroup
	dw AceDuoGroup
	dw ExecutiveMGroup
	dw ExecutiveFGroup
	dw PokemonProfGroup
	dw GameFreakGroup
	dw MysticalmanGroup
	dw LyraGroup
	dw LoreleiGroup
	dw AgathaGroup
	dw YellowGroup
	dw BillGroup
	dw LawrenceGroup
	dw GiovanniGroup
	dw StevenGroup
	dw CynthiaGroup
	dw TowerTycoonGroup
	dw ValerieGroup
	dw ReiGroup
	dw OmastarFossilGroup
	dw KabutopsFossilGroup
	dw AerodactylFossilGroup
