; Generated by Siren
; Source: 430.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_430:
	channel_count 3
	channel 5, Cry_Custom_430_Ch5
	channel 6, Cry_Custom_430_Ch6
	channel 8, Cry_Custom_430_Ch8

Cry_Custom_430_Ch5:
	duty_cycle 3
	square_note 1, 15, 8, 1070
	duty_cycle 2
	square_note 1, 15, 8, 1138
	square_note 1, 15, 8, 368
	duty_cycle 1
	square_note 1, 15, 8, 1055
	square_note 1, 15, 8, 811
	duty_cycle 2
	square_note 1, 15, 8, 1636
	duty_cycle 1
	square_note 1, 15, 8, 1870
	square_note 1, 15, 8, 1871
	square_note 1, 15, 8, 1873
	duty_cycle 2
	square_note 1, 15, 8, 1878
	duty_cycle 1
	square_note 1, 15, 8, 1874
	square_note 1, 15, 8, 1084
	duty_cycle 3
	square_note 1, 15, 8, 1040
	duty_cycle 2
	square_note 1, 15, 8, 450
	square_note 1, 15, 8, 1524
	duty_cycle 1
	square_note 1, 15, 8, 1877
	duty_cycle 2
	square_note 1, 15, 8, 1876
	square_note 1, 15, 8, 1875
	square_note 1, 15, 8, 1876
	square_note 1, 15, 8, 1876
	square_note 1, 15, 8, 1876
	square_note 1, 15, 8, 1197
	square_note 1, 15, 8, 737
	square_note 1, 15, 8, 763
	square_note 1, 15, 8, 1125
	square_note 1, 15, 8, 1084
	duty_cycle 1
	square_note 1, 15, 8, 524
	duty_cycle 2
	square_note 1, 15, 8, 450
	square_note 1, 15, 8, 1070
	duty_cycle 3
	square_note 1, 15, 8, 878
	duty_cycle 1
	square_note 1, 14, 8, 0
	duty_cycle 2
	square_note 1, 10, 8, 592
	square_note 1, 8, 8, 450
	square_note 1, 6, 8, 737
	square_note 1, 6, 8, 737
	square_note 1, 5, 8, 0
	duty_cycle 1
	square_note 1, 2, 8, 0
	duty_cycle 2
	square_note 1, 1, 8, 0
	duty_cycle 3
	square_note 0, 1, 8, 763
	sound_ret

Cry_Custom_430_Ch6:
	duty_cycle 2
	square_note 1, 13, 8, 811
	square_note 1, 13, 8, 592
	duty_cycle 3
	square_note 1, 13, 8, 1430
	square_note 1, 11, 8, 1493
	duty_cycle 0
	square_note 1, 11, 8, 1747
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 11, 8, 1804
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 13, 8, 1733
	duty_cycle 0
	square_note 1, 11, 8, 1804
	square_note 1, 9, 8, 1803
	duty_cycle 2
	square_note 1, 9, 8, 1872
	duty_cycle 3
	square_note 1, 11, 8, 1878
	square_note 1, 13, 8, 1877
	duty_cycle 2
	square_note 1, 11, 8, 1876
	duty_cycle 0
	square_note 1, 9, 8, 1804
	square_note 1, 9, 8, 1804
	square_note 1, 9, 8, 1806
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 15, 8, 1875
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 15, 8, 1876
	duty_cycle 0
	square_note 1, 11, 8, 1856
	square_note 1, 0, 8, 0
	square_note 1, 13, 8, 1849
	duty_cycle 1
	square_note 1, 9, 8, 1852
	square_note 1, 15, 8, 1852
	duty_cycle 0
	square_note 1, 11, 8, 1852
	square_note 1, 0, 8, 0
	duty_cycle 1
	square_note 1, 13, 8, 1855
	duty_cycle 3
	square_note 1, 11, 8, 1853
	duty_cycle 2
	square_note 1, 6, 8, 1876
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 2, 8, 1840
	duty_cycle 1
	square_note 1, 2, 8, 1865
	duty_cycle 3
	square_note 1, 2, 8, 1849
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 2, 8, 737
	duty_cycle 3
	square_note 0, 2, 8, 1055
	sound_ret

Cry_Custom_430_Ch8:
	noise_note 1, 0, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 0, 3, 8, 75
	sound_ret
