; Generated by Siren
; Source: 458.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_458:
	channel_count 3
	channel 5, Cry_Custom_458_Ch5
	channel 6, Cry_Custom_458_Ch6
	channel 8, Cry_Custom_458_Ch8

Cry_Custom_458_Ch5:
	duty_cycle 2
	square_note 1, 13, 8, 1548
	square_note 1, 13, 8, 1596
	square_note 1, 13, 8, 1583
	duty_cycle 3
	square_note 1, 13, 8, 1674
	square_note 1, 13, 8, 1540
	square_note 1, 13, 8, 1555
	square_note 1, 12, 8, 1528
	duty_cycle 2
	square_note 1, 13, 8, 1676
	square_note 1, 12, 8, 1620
	square_note 1, 7, 8, 1951
	square_note 1, 10, 8, 1555
	square_note 1, 6, 8, 1932
	square_note 1, 3, 8, 1933
	square_note 1, 2, 8, 1930
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_458_Ch6:
	duty_cycle 2
	square_note 1, 5, 8, 1596
	duty_cycle 3
	square_note 1, 6, 8, 1515
	duty_cycle 2
	square_note 1, 7, 8, 1690
	square_note 1, 5, 8, 1705
	square_note 1, 5, 8, 1478
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 4, 8, 1583
	square_note 1, 5, 8, 1620
	square_note 1, 5, 8, 1676
	duty_cycle 2
	square_note 1, 3, 8, 1933
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 2, 8, 1865
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 1, 8, 1854
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_458_Ch8:
	noise_note 1, 0, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 2, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 0, 0, 8, 44
	sound_ret
