; Generated by Siren
; Source: 458.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Custom_458:
	channel_count 4
	channel 5, Cry_Custom_458_Ch5
	channel 6, Cry_Custom_458_Ch6
	channel 7, Cry_Custom_458_Ch7
	channel 8, Cry_Custom_458_Ch8

Cry_Custom_458_Ch5:
	duty_cycle 1
	square_note 0, 13, 8, 1519
	square_note 0, 13, 8, 1566
	duty_cycle 2
	square_note 0, 13, 8, 1599
	duty_cycle 1
	square_note 0, 12, 8, 1483
	duty_cycle 2
	square_note 0, 11, 8, 1577
	square_note 0, 13, 8, 1656
	square_note 0, 13, 8, 1680
	square_note 0, 13, 8, 1580
	duty_cycle 3
	square_note 0, 9, 8, 1536
	square_note 0, 13, 8, 1540
	square_note 0, 11, 8, 1577
	duty_cycle 2
	square_note 0, 13, 8, 1548
	square_note 0, 12, 8, 1966
	square_note 0, 8, 8, 1656
	square_note 0, 13, 8, 1583
	square_note 0, 13, 8, 1658
	square_note 0, 12, 8, 1943
	duty_cycle 1
	square_note 0, 10, 8, 1933
	duty_cycle 2
	square_note 0, 10, 8, 1955
	square_note 0, 9, 8, 1955
	duty_cycle 1
	square_note 0, 11, 8, 1555
	duty_cycle 2
	square_note 0, 10, 8, 1944
	square_note 0, 7, 8, 1931
	square_note 0, 3, 8, 1936
	square_note 0, 2, 8, 1933
	square_note 0, 1, 8, 1929
	square_note 0, 1, 8, 1932
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_458_Ch6:
	duty_cycle 2
	square_note 0, 8, 8, 1577
	square_note 0, 7, 8, 1611
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 8, 8, 1544
	duty_cycle 2
	square_note 0, 6, 8, 1524
	square_note 8, 0, 8, 0
	square_note 0, 8, 8, 1948
	square_note 0, 6, 8, 1942
	square_note 0, 6, 8, 2010
	square_note 0, 4, 8, 2010
	square_note 0, 7, 8, 1960
	square_note 0, 4, 8, 1959
	square_note 0, 7, 8, 1952
	square_note 6, 0, 8, 0
	sound_ret

Cry_Custom_458_Ch7:
	square_note 0, 1, 3, 1906
	square_note 0, 1, 1, 2006
	square_note 0, 1, 3, 1916
	square_note 0, 1, 1, 2021
	square_note 0, 1, 8, 1873
	square_note 0, 1, 1, 2022
	square_note 1, 1, 1, 2023
	square_note 0, 1, 1, 2030
	square_note 0, 1, 9, 1824
	square_note 0, 1, 9, 1842
	square_note 0, 1, 8, 1761
	square_note 0, 1, 1, 2010
	square_note 0, 1, 1, 2012
	square_note 0, 1, 4, 1864
	square_note 0, 1, 9, 1871
	square_note 0, 1, 2, 1994
	square_note 0, 1, 1, 1994
	square_note 1, 1, 1, 2000
	square_note 0, 1, 1, 1997
	square_note 0, 1, 4, 1798
	square_note 0, 1, 1, 2006
	square_note 0, 3, 1, 1990
	square_note 0, 3, 6, 1937
	square_note 0, 3, 1, 1990
	square_note 0, 0, 1, 1992
	square_note 0, 0, 0, 1995
	sound_ret

Cry_Custom_458_Ch8:
	noise_note 0, 9, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 1, 13, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 1, 8, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 11, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 1, 8, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 0, 8, 8, 100
	noise_note 0, 6, 8, 100
	noise_note 0, 3, 8, 100
	noise_note 0, 2, 8, 100
	noise_note 1, 1, 8, 100
	noise_note 0, 0, 8, 100
	sound_ret
