; Generated by Siren
; Source: 464.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_464:
	channel_count 3
	channel 5, Cry_Custom_464_Ch5
	channel 6, Cry_Custom_464_Ch6
	channel 8, Cry_Custom_464_Ch8

Cry_Custom_464_Ch5:
	duty_cycle 2
	square_note 1, 13, 8, 1901
	duty_cycle 3
	square_note 1, 13, 8, 1761
	duty_cycle 2
	square_note 1, 13, 8, 1774
	square_note 1, 13, 8, 1915
	duty_cycle 3
	square_note 1, 13, 8, 1483
	duty_cycle 1
	square_note 1, 13, 8, 1777
	duty_cycle 3
	square_note 1, 13, 8, 1779
	square_note 1, 13, 8, 1773
	duty_cycle 1
	square_note 1, 13, 8, 1779
	duty_cycle 2
	square_note 1, 13, 8, 1372
	square_note 1, 13, 8, 1669
	square_note 1, 13, 8, 1186
	duty_cycle 1
	square_note 1, 13, 8, 1774
	duty_cycle 3
	square_note 1, 13, 8, 1775
	square_note 1, 13, 8, 1773
	duty_cycle 2
	square_note 1, 13, 8, 1762
	square_note 1, 13, 8, 1766
	square_note 1, 13, 8, 1764
	duty_cycle 3
	square_note 1, 13, 8, 1229
	duty_cycle 2
	square_note 1, 13, 8, 1208
	duty_cycle 0
	square_note 1, 13, 8, 1186
	duty_cycle 2
	square_note 1, 13, 8, 1208
	duty_cycle 3
	square_note 1, 13, 8, 1812
	duty_cycle 2
	square_note 1, 13, 8, 1651
	square_note 1, 13, 8, 1671
	square_note 1, 13, 8, 1641
	square_note 1, 13, 8, 1909
	duty_cycle 3
	square_note 1, 13, 8, 1753
	duty_cycle 2
	square_note 1, 13, 8, 1519
	duty_cycle 1
	square_note 1, 13, 8, 1712
	square_note 1, 12, 8, 1186
	duty_cycle 2
	square_note 1, 6, 8, 1186
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_464_Ch6:
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 6, 8, 1901
	duty_cycle 2
	square_note 1, 6, 8, 1880
	square_note 1, 8, 8, 1782
	duty_cycle 0
	square_note 1, 6, 8, 1665
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 6, 8, 1674
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 9, 8, 1782
	square_note 1, 8, 8, 1775
	square_note 1, 9, 8, 1771
	duty_cycle 2
	square_note 1, 9, 8, 1688
	duty_cycle 0
	square_note 1, 9, 8, 1686
	square_note 1, 5, 8, 1646
	duty_cycle 2
	square_note 1, 8, 8, 1646
	duty_cycle 1
	square_note 1, 7, 8, 1665
	duty_cycle 2
	square_note 1, 6, 8, 1638
	square_note 1, 8, 8, 1724
	square_note 1, 9, 8, 1688
	duty_cycle 3
	square_note 1, 8, 8, 1764
	square_note 1, 8, 8, 1761
	square_note 1, 8, 8, 1767
	duty_cycle 2
	square_note 1, 9, 8, 1910
	square_note 1, 9, 8, 1909
	square_note 1, 8, 8, 1873
	square_note 1, 6, 8, 1872
	duty_cycle 1
	square_note 1, 6, 8, 1833
	duty_cycle 2
	square_note 1, 9, 8, 1758
	duty_cycle 0
	square_note 1, 9, 8, 1625
	square_note 1, 9, 8, 1478
	duty_cycle 3
	square_note 1, 3, 8, 1532
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_464_Ch8:
	noise_note 1, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
