; Generated by Siren
; Source: 467.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_467:
	channel_count 3
	channel 5, Cry_Custom_467_Ch5
	channel 6, Cry_Custom_467_Ch6
	channel 8, Cry_Custom_467_Ch8

Cry_Custom_467_Ch5:
	duty_cycle 0
	square_note 1, 15, 8, 1643
	duty_cycle 1
	square_note 1, 15, 8, 1857
	duty_cycle 3
	square_note 1, 15, 8, 1839
	duty_cycle 2
	square_note 1, 15, 8, 1641
	square_note 1, 15, 8, 1625
	square_note 1, 14, 8, 1638
	duty_cycle 0
	square_note 1, 15, 8, 1637
	duty_cycle 3
	square_note 1, 15, 8, 1636
	duty_cycle 0
	square_note 1, 14, 8, 1138
	square_note 1, 15, 8, 1239
	square_note 1, 11, 8, 1617
	duty_cycle 1
	square_note 1, 14, 8, 1832
	duty_cycle 2
	square_note 1, 14, 8, 1811
	square_note 1, 14, 8, 1811
	duty_cycle 3
	square_note 1, 15, 8, 1824
	duty_cycle 2
	square_note 1, 11, 8, 1775
	duty_cycle 1
	square_note 1, 10, 8, 1750
	duty_cycle 2
	square_note 1, 10, 8, 1643
	square_note 1, 14, 8, 1643
	square_note 1, 10, 8, 1070
	duty_cycle 0
	square_note 1, 14, 8, 918
	duty_cycle 1
	square_note 1, 15, 8, 1473
	duty_cycle 2
	square_note 1, 15, 8, 1690
	duty_cycle 0
	square_note 1, 14, 8, 956
	duty_cycle 2
	square_note 1, 15, 8, 834
	square_note 1, 10, 8, 1055
	duty_cycle 1
	square_note 1, 11, 8, 1286
	duty_cycle 2
	square_note 1, 7, 8, 1405
	duty_cycle 1
	square_note 1, 6, 8, 277
	duty_cycle 2
	square_note 1, 6, 8, 277
	square_note 1, 6, 8, 277
	square_note 1, 7, 8, 1138
	duty_cycle 1
	square_note 1, 8, 8, 737
	duty_cycle 3
	square_note 1, 11, 8, 878
	duty_cycle 1
	square_note 1, 14, 8, 1070
	duty_cycle 2
	square_note 1, 15, 8, 654
	square_note 1, 10, 8, 1008
	duty_cycle 3
	square_note 1, 3, 8, 1286
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_467_Ch6:
	duty_cycle 0
	square_note 1, 15, 8, 1746
	square_note 1, 13, 8, 1746
	square_note 1, 13, 8, 1743
	duty_cycle 2
	square_note 1, 9, 8, 1783
	duty_cycle 3
	square_note 1, 9, 8, 1674
	square_note 1, 0, 8, 0
	square_note 1, 15, 8, 1622
	duty_cycle 0
	square_note 1, 9, 8, 1694
	square_note 1, 13, 8, 1684
	square_note 1, 13, 8, 1694
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 9, 8, 1768
	square_note 1, 9, 8, 1769
	duty_cycle 2
	square_note 1, 15, 8, 1771
	square_note 1, 11, 8, 1853
	square_note 1, 9, 8, 1852
	square_note 1, 9, 8, 1779
	square_note 1, 13, 8, 1776
	square_note 1, 9, 8, 1778
	square_note 1, 9, 8, 1762
	square_note 1, 13, 8, 1740
	square_note 1, 11, 8, 1759
	square_note 1, 13, 8, 1698
	square_note 1, 9, 8, 1528
	square_note 1, 6, 8, 1526
	duty_cycle 0
	square_note 1, 9, 8, 1524
	duty_cycle 2
	square_note 1, 4, 8, 1524
	duty_cycle 0
	square_note 1, 4, 8, 1524
	square_note 1, 0, 8, 0
	duty_cycle 3
	square_note 1, 2, 8, 1393
	duty_cycle 2
	square_note 1, 4, 8, 1424
	duty_cycle 3
	square_note 1, 4, 8, 1286
	duty_cycle 2
	square_note 1, 9, 8, 1125
	duty_cycle 0
	square_note 1, 9, 8, 524
	duty_cycle 2
	square_note 1, 13, 8, 1174
	duty_cycle 3
	square_note 1, 6, 8, 1379
	duty_cycle 0
	square_note 1, 2, 8, 811
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_467_Ch8:
	noise_note 1, 15, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 13, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 12, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 7, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
