; Generated by Siren
; Source: 472.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_472:
	channel_count 3
	channel 5, Cry_Custom_472_Ch5
	channel 6, Cry_Custom_472_Ch6
	channel 8, Cry_Custom_472_Ch8

Cry_Custom_472_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 2, 8, 1932
	square_note 0, 3, 8, 1941
	duty_cycle 2
	square_note 0, 4, 8, 1870
	square_note 0, 4, 8, 1862
	duty_cycle 1
	square_note 0, 5, 8, 1917
	duty_cycle 3
	square_note 0, 8, 8, 1905
	duty_cycle 2
	square_note 0, 8, 8, 1796
	square_note 0, 11, 8, 1766
	duty_cycle 0
	square_note 0, 9, 8, 1731
	duty_cycle 2
	square_note 0, 11, 8, 1684
	duty_cycle 1
	square_note 0, 10, 8, 1662
	duty_cycle 2
	square_note 0, 10, 8, 410
	duty_cycle 3
	square_note 0, 9, 8, 1611
	duty_cycle 0
	square_note 0, 8, 8, 1559
	duty_cycle 2
	square_note 0, 10, 8, 1686
	duty_cycle 0
	square_note 0, 7, 8, 898
	square_note 0, 8, 8, 524
	duty_cycle 2
	square_note 0, 13, 8, 410
	square_note 0, 11, 8, 1286
	duty_cycle 3
	square_note 0, 13, 8, 592
	duty_cycle 1
	square_note 0, 13, 8, 788
	duty_cycle 2
	square_note 0, 11, 8, 410
	square_note 0, 13, 8, 410
	square_note 0, 13, 8, 1441
	duty_cycle 1
	square_note 0, 12, 8, 1008
	duty_cycle 3
	square_note 0, 13, 8, 974
	duty_cycle 2
	square_note 0, 13, 8, 1197
	square_note 0, 13, 8, 410
	square_note 0, 13, 8, 683
	square_note 0, 13, 8, 450
	duty_cycle 3
	square_note 0, 11, 8, 763
	duty_cycle 0
	square_note 0, 12, 8, 1040
	duty_cycle 2
	square_note 0, 11, 8, 410
	square_note 0, 13, 8, 763
	square_note 0, 13, 8, 654
	square_note 0, 13, 8, 856
	square_note 0, 13, 8, 1008
	duty_cycle 3
	square_note 0, 13, 8, 1162
	duty_cycle 2
	square_note 0, 13, 8, 1268
	duty_cycle 0
	square_note 0, 10, 8, 1303
	square_note 0, 10, 8, 1768
	duty_cycle 3
	square_note 0, 13, 8, 683
	duty_cycle 2
	square_note 0, 12, 8, 1740
	duty_cycle 0
	square_note 0, 11, 8, 1747
	duty_cycle 2
	square_note 0, 9, 8, 1774
	square_note 0, 9, 8, 1922
	duty_cycle 0
	square_note 0, 8, 8, 1801
	square_note 0, 7, 8, 1797
	duty_cycle 1
	square_note 0, 5, 8, 1736
	duty_cycle 3
	square_note 0, 3, 8, 1753
	duty_cycle 2
	square_note 0, 3, 8, 1913
	square_note 0, 3, 8, 1943
	duty_cycle 3
	square_note 0, 5, 8, 1379
	square_note 0, 3, 8, 1939
	square_note 0, 3, 8, 1351
	duty_cycle 0
	square_note 0, 1, 8, 1447
	duty_cycle 2
	square_note 0, 3, 8, 1365
	duty_cycle 1
	square_note 0, 1, 8, 1524
	duty_cycle 0
	square_note 0, 2, 8, 1916
	duty_cycle 2
	square_note 0, 3, 8, 1098
	square_note 0, 3, 8, 1412
	duty_cycle 3
	square_note 0, 2, 8, 1055
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 2, 8, 1940
	square_note 0, 3, 8, 1937
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_472_Ch6:
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 1, 8, 1876
	duty_cycle 2
	square_note 0, 2, 8, 1885
	square_note 0, 2, 8, 1885
	duty_cycle 3
	square_note 0, 2, 8, 1923
	square_note 0, 2, 8, 1849
	square_note 0, 5, 8, 1844
	duty_cycle 0
	square_note 0, 3, 8, 1880
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 4, 8, 1699
	square_note 0, 0, 8, 0
	square_note 0, 5, 8, 1622
	duty_cycle 0
	square_note 0, 6, 8, 1608
	duty_cycle 2
	square_note 0, 4, 8, 1566
	square_note 0, 4, 8, 1703
	duty_cycle 3
	square_note 0, 6, 8, 1536
	duty_cycle 2
	square_note 0, 3, 8, 1766
	duty_cycle 0
	square_note 0, 3, 8, 1753
	duty_cycle 3
	square_note 0, 6, 8, 1749
	duty_cycle 2
	square_note 0, 5, 8, 1750
	square_note 0, 4, 8, 1764
	square_note 0, 5, 8, 1769
	square_note 0, 5, 8, 1447
	square_note 0, 6, 8, 1430
	square_note 0, 5, 8, 1680
	square_note 0, 4, 8, 1715
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 6, 8, 1671
	duty_cycle 2
	square_note 0, 5, 8, 1745
	square_note 0, 5, 8, 1784
	duty_cycle 3
	square_note 0, 4, 8, 1757
	duty_cycle 2
	square_note 0, 5, 8, 1795
	square_note 0, 5, 8, 1799
	duty_cycle 0
	square_note 0, 4, 8, 1804
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 6, 8, 1755
	duty_cycle 3
	square_note 0, 6, 8, 1742
	square_note 0, 8, 8, 1742
	square_note 0, 5, 8, 1751
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 6, 8, 1770
	square_note 0, 0, 8, 0
	square_note 0, 5, 8, 1848
	square_note 0, 3, 8, 1918
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 3
	square_note 0, 3, 8, 1912
	duty_cycle 1
	square_note 0, 2, 8, 1852
	duty_cycle 3
	square_note 0, 2, 8, 1854
	duty_cycle 2
	square_note 0, 2, 8, 1937
	duty_cycle 0
	square_note 0, 2, 8, 1900
	duty_cycle 1
	square_note 0, 2, 8, 1884
	duty_cycle 0
	square_note 0, 2, 8, 1899
	square_note 0, 2, 8, 1899
	square_note 0, 1, 8, 1894
	square_note 0, 1, 8, 1891
	duty_cycle 2
	square_note 0, 1, 8, 1724
	duty_cycle 0
	square_note 0, 1, 8, 1872
	square_note 0, 1, 8, 1617
	duty_cycle 3
	square_note 0, 2, 8, 1312
	duty_cycle 2
	square_note 0, 1, 8, 1599
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 1, 8, 1923
	duty_cycle 3
	square_note 0, 2, 8, 1911
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_472_Ch8:
	noise_note 0, 0, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
