; Generated by Siren
; Source: 863.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_863:
	channel_count 3
	channel 5, Cry_Custom_863_Ch5
	channel 6, Cry_Custom_863_Ch6
	channel 8, Cry_Custom_863_Ch8

Cry_Custom_863_Ch5:
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 11, 8, 1676
	duty_cycle 0
	square_note 1, 7, 8, 1820
	square_note 1, 4, 8, 1824
	square_note 1, 4, 8, 1821
	square_note 1, 4, 8, 1818
	square_note 1, 0, 8, 0
	square_note 1, 4, 8, 1678
	square_note 1, 15, 8, 1802
	square_note 1, 15, 8, 1799
	square_note 1, 11, 8, 1775
	square_note 1, 11, 8, 1802
	square_note 1, 7, 8, 1803
	square_note 1, 7, 8, 1803
	square_note 1, 11, 8, 1803
	square_note 1, 11, 8, 1801
	square_note 1, 7, 8, 1720
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_863_Ch6:
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 8, 8, 1740
	square_note 1, 8, 8, 1750
	square_note 1, 8, 8, 1667
	duty_cycle 2
	square_note 1, 8, 8, 1694
	duty_cycle 3
	square_note 1, 8, 8, 1743
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 8, 8, 1843
	square_note 1, 8, 8, 1829
	square_note 1, 15, 8, 1830
	duty_cycle 3
	square_note 1, 8, 8, 1843
	duty_cycle 0
	square_note 1, 8, 8, 1855
	square_note 1, 8, 8, 1843
	square_note 1, 8, 8, 1802
	square_note 1, 8, 8, 1720
	square_note 1, 8, 8, 1845
	square_note 1, 8, 8, 1830
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	sound_ret

Cry_Custom_863_Ch8:
	noise_note 1, 0, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 15, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	sound_ret
