; Generated by Siren
; Source: 899.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_899:
	channel_count 3
	channel 5, Cry_Custom_899_Ch5
	channel 6, Cry_Custom_899_Ch6
	channel 8, Cry_Custom_899_Ch8

Cry_Custom_899_Ch5:
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 4, 8, 1868
	square_note 1, 8, 8, 1871
	square_note 1, 7, 8, 1874
	square_note 1, 8, 8, 1229
	duty_cycle 0
	square_note 1, 7, 8, 1418
	duty_cycle 2
	square_note 1, 8, 8, 1821
	square_note 1, 7, 8, 1544
	square_note 1, 7, 8, 1563
	square_note 1, 8, 8, 1555
	duty_cycle 0
	square_note 1, 8, 8, 1622
	duty_cycle 1
	square_note 1, 7, 8, 1631
	duty_cycle 0
	square_note 1, 8, 8, 1631
	duty_cycle 3
	square_note 1, 7, 8, 1566
	duty_cycle 2
	square_note 1, 7, 8, 1577
	square_note 1, 7, 8, 1727
	duty_cycle 0
	square_note 1, 7, 8, 1620
	square_note 1, 7, 8, 974
	square_note 1, 7, 8, 1633
	duty_cycle 2
	square_note 1, 6, 8, 1628
	duty_cycle 0
	square_note 1, 4, 8, 1441
	square_note 1, 3, 8, 1611
	square_note 1, 4, 8, 1633
	duty_cycle 3
	square_note 1, 3, 8, 1638
	duty_cycle 0
	square_note 1, 2, 8, 1622
	square_note 1, 2, 8, 1617
	square_note 1, 1, 8, 1633
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_899_Ch6:
	square_note 1, 0, 8, 0
	duty_cycle 2
	square_note 1, 2, 8, 1829
	duty_cycle 3
	square_note 1, 4, 8, 1733
	duty_cycle 2
	square_note 1, 3, 8, 1749
	square_note 1, 0, 8, 0
	square_note 1, 4, 8, 1796
	duty_cycle 0
	square_note 1, 3, 8, 1751
	duty_cycle 2
	square_note 1, 4, 8, 1821
	square_note 1, 4, 8, 1827
	square_note 1, 4, 8, 1828
	duty_cycle 0
	square_note 1, 2, 8, 1789
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 3, 8, 1829
	duty_cycle 3
	square_note 1, 3, 8, 1835
	duty_cycle 2
	square_note 1, 4, 8, 1867
	square_note 1, 3, 8, 1867
	square_note 1, 3, 8, 1830
	duty_cycle 3
	square_note 1, 2, 8, 1807
	square_note 1, 2, 8, 1737
	duty_cycle 0
	square_note 1, 2, 8, 1643
	square_note 1, 1, 8, 1544
	square_note 1, 1, 8, 1488
	duty_cycle 3
	square_note 1, 1, 8, 1739
	duty_cycle 0
	square_note 1, 1, 8, 1712
	duty_cycle 3
	square_note 1, 1, 8, 1754
	square_note 1, 1, 8, 1804
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_899_Ch8:
	noise_note 1, 0, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
