; Generated by Siren
; Source: 901-0.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_901_0:
	channel_count 3
	channel 5, Cry_Custom_901_0_Ch5
	channel 6, Cry_Custom_901_0_Ch6
	channel 8, Cry_Custom_901_0_Ch8

Cry_Custom_901_0_Ch5:
	duty_cycle 0
	square_note 1, 8, 8, 1540
	square_note 1, 10, 8, 1719
	square_note 1, 13, 8, 683
	duty_cycle 3
	square_note 1, 15, 8, 1651
	duty_cycle 2
	square_note 1, 13, 8, 1848
	duty_cycle 0
	square_note 1, 13, 8, 1150
	square_note 1, 15, 8, 1511
	duty_cycle 2
	square_note 1, 15, 8, 1821
	square_note 1, 15, 8, 1819
	duty_cycle 0
	square_note 1, 13, 8, 1524
	square_note 1, 13, 8, 1528
	square_note 1, 13, 8, 1524
	duty_cycle 3
	square_note 1, 10, 8, 1524
	duty_cycle 0
	square_note 1, 13, 8, 1519
	duty_cycle 3
	square_note 1, 13, 8, 1605
	square_note 1, 10, 8, 1722
	duty_cycle 0
	square_note 1, 5, 8, 737
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_901_0_Ch6:
	duty_cycle 3
	square_note 1, 5, 8, 1680
	duty_cycle 2
	square_note 1, 10, 8, 1788
	square_note 1, 15, 8, 1790
	duty_cycle 3
	square_note 1, 15, 8, 1694
	duty_cycle 2
	square_note 1, 10, 8, 1692
	square_note 1, 10, 8, 1740
	duty_cycle 3
	square_note 1, 15, 8, 1818
	duty_cycle 2
	square_note 1, 15, 8, 1844
	square_note 1, 15, 8, 1870
	square_note 1, 15, 8, 1843
	square_note 1, 15, 8, 1846
	square_note 1, 15, 8, 1826
	square_note 1, 5, 8, 1739
	square_note 1, 10, 8, 1731
	square_note 1, 10, 8, 1671
	square_note 1, 10, 8, 1478
	duty_cycle 3
	square_note 1, 5, 8, 1714
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_901_0_Ch8:
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 8, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 0, 0, 8, 44
	sound_ret
