; Generated by Siren
; Source: 903.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_903:
	channel_count 3
	channel 5, Cry_Custom_903_Ch5
	channel 6, Cry_Custom_903_Ch6
	channel 8, Cry_Custom_903_Ch8

Cry_Custom_903_Ch5:
	duty_cycle 2
	square_note 0, 2, 8, 0
	square_note 0, 6, 8, 0
	square_note 0, 8, 8, 120
	duty_cycle 1
	square_note 0, 8, 8, 918
	duty_cycle 2
	square_note 0, 8, 8, 1138
	square_note 0, 7, 8, 991
	square_note 0, 7, 8, 1295
	square_note 0, 5, 8, 1458
	duty_cycle 3
	square_note 0, 4, 8, 0
	duty_cycle 2
	square_note 0, 4, 8, 0
	square_note 0, 3, 8, 0
	square_note 0, 4, 8, 0
	square_note 0, 5, 8, 1519
	square_note 0, 7, 8, 1608
	duty_cycle 3
	square_note 0, 7, 8, 1803
	duty_cycle 2
	square_note 0, 7, 8, 1365
	square_note 0, 8, 8, 1877
	square_note 0, 7, 8, 1463
	square_note 0, 5, 8, 1536
	square_note 0, 7, 8, 1876
	square_note 0, 6, 8, 1528
	square_note 0, 6, 8, 1478
	duty_cycle 1
	square_note 0, 5, 8, 1885
	duty_cycle 2
	square_note 0, 4, 8, 1552
	square_note 0, 3, 8, 1767
	duty_cycle 0
	square_note 0, 2, 8, 1532
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_903_Ch6:
	duty_cycle 2
	square_note 0, 1, 8, 1870
	square_note 0, 2, 8, 1463
	square_note 0, 5, 8, 1473
	square_note 0, 4, 8, 1399
	square_note 0, 3, 8, 1286
	square_note 0, 2, 8, 1186
	duty_cycle 3
	square_note 0, 3, 8, 956
	square_note 0, 2, 8, 1040
	duty_cycle 0
	square_note 0, 2, 8, 1452
	duty_cycle 3
	square_note 0, 2, 8, 1614
	duty_cycle 2
	square_note 0, 1, 8, 1828
	square_note 0, 2, 8, 1548
	square_note 0, 2, 8, 1452
	duty_cycle 3
	square_note 0, 4, 8, 1754
	duty_cycle 2
	square_note 0, 3, 8, 1839
	duty_cycle 3
	square_note 0, 3, 8, 1849
	square_note 0, 4, 8, 1856
	duty_cycle 2
	square_note 0, 4, 8, 1871
	duty_cycle 1
	square_note 0, 2, 8, 1884
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 3, 8, 1873
	duty_cycle 3
	square_note 0, 3, 8, 1887
	duty_cycle 0
	square_note 0, 2, 8, 1808
	duty_cycle 2
	square_note 0, 2, 8, 1878
	duty_cycle 0
	square_note 0, 2, 8, 1880
	duty_cycle 2
	square_note 0, 1, 8, 1883
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_903_Ch8:
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
