; Generated by Siren
; Source: 904.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Custom_904:
	channel_count 3
	channel 5, Cry_Custom_904_Ch5
	channel 6, Cry_Custom_904_Ch6
	channel 8, Cry_Custom_904_Ch8

Cry_Custom_904_Ch5:
	duty_cycle 1
	square_note 1, 5, 8, 1767
	duty_cycle 0
	square_note 1, 11, 8, 918
	duty_cycle 1
	square_note 1, 6, 8, 1813
	duty_cycle 3
	square_note 1, 8, 8, 1112
	duty_cycle 0
	square_note 1, 3, 8, 834
	duty_cycle 3
	square_note 1, 2, 8, 974
	duty_cycle 0
	square_note 1, 1, 8, 1424
	duty_cycle 3
	square_note 1, 1, 8, 878
	square_note 1, 9, 8, 1277
	duty_cycle 0
	square_note 1, 4, 8, 1208
	duty_cycle 2
	square_note 1, 1, 8, 1643
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_904_Ch6:
	duty_cycle 0
	square_note 1, 2, 8, 1617
	square_note 1, 5, 8, 1757
	duty_cycle 2
	square_note 1, 3, 8, 1747
	square_note 1, 4, 8, 1755
	square_note 1, 1, 8, 1830
	square_note 1, 1, 8, 1892
	square_note 1, 1, 8, 1295
	square_note 1, 0, 8, 0
	duty_cycle 0
	square_note 1, 3, 8, 1731
	square_note 1, 2, 8, 1722
	duty_cycle 2
	square_note 1, 1, 8, 1781
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Custom_904_Ch8:
	noise_note 1, 3, 8, 44
	noise_note 1, 6, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 5, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 1, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 0, 0, 8, 44
	sound_ret
