; Generated by Siren
; Source: 1010.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Annihilape:
	channel_count 4
	channel 5, Cry_Annihilape_Ch5
	channel 6, Cry_Annihilape_Ch6
	channel 7, Cry_Annihilape_Ch7
	channel 8, Cry_Annihilape_Ch8

Cry_Annihilape_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 13, 8, 1047
	square_note 2, 15, 8, 1055
	square_note 2, 15, 8, 1047
	square_note 5, 14, 8, 1047
	square_note 2, 14, 8, 1038
	square_note 2, 13, 8, 1038
	square_note 2, 13, 8, 1079
	square_note 2, 13, 8, 1071
	square_note 2, 13, 8, 1087
	square_note 2, 12, 8, 1389
	square_note 2, 11, 8, 641
	square_note 2, 11, 8, 1071
	square_note 2, 11, 8, 1055
	square_note 2, 11, 8, 1029
	square_note 2, 12, 8, 1071
	square_note 2, 12, 8, 1122
	square_note 2, 12, 8, 618
	square_note 2, 12, 8, 662
	square_note 2, 11, 8, 1020
	square_note 2, 11, 8, 1079
	square_note 2, 9, 8, 1055
	square_note 2, 10, 8, 1394
	square_note 2, 11, 8, 1603
	square_note 2, 9, 8, 1425
	square_note 2, 10, 8, 1618
	square_note 2, 9, 8, 740
	square_note 2, 8, 8, 1588
	square_note 1, 8, 8, 1543
	square_note 0, 7, 8, 1543
	square_note 2, 6, 8, 1560
	square_note 2, 5, 8, 641
	square_note 1, 4, 8, 740
	square_note 0, 3, 8, 740
	square_note 1, 3, 8, 722
	square_note 1, 2, 8, 722
	square_note 1, 1, 8, 722
	square_note 0, 1, 8, 758
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Annihilape_Ch6:
	duty_cycle_pattern 0, 1, 0, 1
	square_note 2, 14, 8, 1690
	square_note 5, 15, 8, 1478
	square_note 2, 15, 8, 1466
	square_note 5, 15, 8, 1470
	square_note 2, 14, 8, 1453
	square_note 2, 15, 8, 1493
	square_note 2, 14, 8, 1486
	square_note 2, 14, 8, 1493
	square_note 2, 12, 8, 1610
	square_note 2, 12, 8, 1628
	square_note 2, 12, 8, 1622
	square_note 2, 11, 8, 1632
	square_note 2, 11, 8, 1731
	square_note 2, 12, 8, 1751
	square_note 2, 12, 8, 1730
	square_note 2, 12, 8, 1747
	square_note 2, 12, 8, 1733
	square_note 2, 12, 8, 1737
	square_note 2, 12, 8, 1738
	square_note 2, 9, 8, 1695
	square_note 2, 11, 8, 1771
	square_note 2, 11, 8, 1867
	square_note 2, 9, 8, 1858
	square_note 2, 9, 8, 1874
	square_note 2, 9, 8, 1875
	square_note 2, 8, 8, 1742
	square_note 0, 9, 8, 1689
	square_note 1, 8, 8, 1689
	square_note 2, 6, 8, 1679
	square_note 2, 5, 8, 1617
	square_note 1, 4, 8, 1682
	square_note 0, 3, 8, 1682
	square_note 1, 3, 8, 1691
	square_note 0, 2, 8, 1691
	square_note 1, 2, 8, 1333
	square_note 0, 1, 8, 1333
	square_note 0, 1, 8, 1104
	square_note 1, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Annihilape_Ch7:
	square_note 2, 1, 5, 1548
	square_note 2, 1, 2, 1552
	square_note 2, 1, 2, 1548
	square_note 2, 1, 4, 1548
	square_note 2, 1, 2, 1548
	square_note 2, 1, 6, 1543
	square_note 2, 1, 5, 1543
	square_note 2, 1, 4, 1564
	square_note 2, 1, 4, 1560
	square_note 2, 1, 2, 1568
	square_note 2, 1, 2, 1719
	square_note 2, 1, 7, 1345
	square_note 2, 1, 7, 1560
	square_note 2, 1, 2, 1552
	square_note 2, 1, 2, 1539
	square_note 2, 1, 7, 1560
	square_note 2, 1, 1, 1585
	square_note 2, 1, 6, 1333
	square_note 2, 1, 4, 1355
	square_note 2, 1, 7, 1535
	square_note 2, 1, 7, 1564
	square_note 2, 1, 5, 1552
	square_note 2, 1, 7, 1721
	square_note 2, 1, 1, 1826
	square_note 2, 2, 6, 1736
	square_note 2, 1, 5, 1834
	square_note 2, 1, 8, 1394
	square_note 2, 1, 9, 1819
	square_note 1, 1, 5, 1796
	square_note 0, 2, 5, 1796
	square_note 2, 2, 3, 1805
	square_note 2, 3, 8, 1345
	square_note 2, 2, 5, 1394
	square_note 2, 3, 3, 1385
	square_note 2, 0, 4, 1385
	square_note 2, 0, 4, 1403
	square_note 0, 0, 7, 1321
	sound_ret

Cry_Annihilape_Ch8:
	noise_note 5, 14, 8, 84
	noise_note 5, 14, 4, 84
	noise_note 5, 11, 8, 84
	noise_note 5, 10, 8, 84
	noise_note 5, 10, 5, 84
	noise_note 5, 10, 8, 84
	noise_note 5, 9, 8, 100
	noise_note 5, 13, 8, 84
	noise_note 5, 14, 5, 84
	noise_note 5, 14, 8, 108
	noise_note 5, 15, 2, 76
	noise_note 5, 14, 8, 76
	noise_note 5, 11, 8, 76
	noise_note 2, 13, 8, 76
	noise_note 1, 12, 8, 76
	noise_note 0, 11, 8, 76
	noise_note 0, 9, 4, 92
	noise_note 2, 8, 4, 92
	noise_note 1, 7, 4, 92
	noise_note 0, 6, 8, 100
	noise_note 2, 5, 8, 100
	noise_note 1, 4, 8, 100
	noise_note 1, 3, 2, 100
	noise_note 2, 2, 2, 100
	noise_note 0, 1, 2, 100
	noise_note 0, 1, 8, 100
	noise_note 2, 0, 8, 100
	sound_ret
