; Generated by Siren
; Source: azurill.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Azurill:
	channel_count 3
	channel 5, Cry_Azurill_Ch5
	channel 7, Cry_Azurill_Ch7
	channel 8, Cry_Azurill_Ch8

Cry_Azurill_Ch5:
	duty_cycle 2
	square_note 0, 9, 8, 1987
	square_note 1, 12, 8, 1987
	square_note 0, 15, 8, 1986
	square_note 1, 15, 8, 1985
	square_note 1, 15, 8, 1984
	square_note 0, 12, 8, 1983
	square_note 0, 15, 8, 1982
	square_note 0, 6, 8, 1982
	square_note 0, 3, 8, 1980
	square_note 0, 3, 8, 1979
	square_note 0, 6, 8, 1980
	square_note 0, 9, 8, 1978
	square_note 0, 12, 8, 1995
	square_note 0, 9, 8, 1996
	square_note 0, 6, 8, 1996
	square_note 0, 9, 8, 1996
	square_note 0, 12, 8, 1995
	square_note 0, 12, 8, 1994
	square_note 0, 15, 8, 1993
	square_note 0, 9, 8, 1993
	square_note 0, 12, 8, 1991
	square_note 0, 6, 8, 1990
	square_note 0, 3, 8, 1990
	square_note 1, 6, 8, 1989
	square_note 0, 3, 8, 1988
	sound_ret

Cry_Azurill_Ch7:
	square_note 5, 1, 1, 2017
	square_note 1, 1, 1, 2016
	square_note 1, 1, 1, 2015
	square_note 0, 2, 1, 2015
	square_note 0, 3, 1, 2014
	square_note 1, 2, 1, 2014
	square_note 0, 1, 1, 2013
	square_note 0, 1, 1, 2021
	square_note 3, 1, 1, 2022
	square_note 1, 1, 1, 2021
	square_note 1, 1, 1, 2020
	square_note 2, 2, 1, 2019
	square_note 0, 2, 1, 2018
	square_note 0, 3, 1, 2018
	sound_ret

Cry_Azurill_Ch8:
	noise_note 8, 8, 8, 92
	noise_note 0, 15, 8, 92
	noise_note 0, 8, 8, 92
	noise_note 1, 0, 8, 0
	noise_note 11, 8, 8, 92
	noise_note 0, 0, 8, 0
	noise_note 1, 8, 8, 92
	noise_note 0, 0, 8, 0
	sound_ret
