; Generated by Siren
; Source: 1009.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Clodsire:
	channel_count 4
	channel 5, Cry_Clodsire_Ch5
	channel 6, Cry_Clodsire_Ch6
	channel 7, Cry_Clodsire_Ch7
	channel 8, Cry_Clodsire_Ch8

Cry_Clodsire_Ch5:
	square_note 1, 0, 8, 0
	duty_cycle_pattern 2, 2, 1, 1
	square_note 0, 1, 8, 1687
	square_note 1, 2, 8, 1562
	square_note 0, 3, 8, 1562
	square_note 0, 4, 8, 1482
	square_note 0, 5, 8, 1482
	square_note 0, 6, 8, 1482
	square_note 0, 8, 8, 789
	square_note 0, 9, 8, 789
	square_note 0, 10, 8, 789
	square_note 0, 10, 8, 1411
	square_note 0, 11, 8, 1411
	square_note 0, 12, 8, 1411
	square_note 2, 13, 8, 1442
	square_note 2, 14, 8, 1424
	square_note 2, 14, 8, 1455
	square_note 2, 13, 8, 1497
	square_note 2, 14, 8, 1494
	square_note 2, 13, 8, 1442
	square_note 2, 12, 8, 1405
	square_note 2, 13, 8, 1457
	square_note 2, 13, 8, 1455
	square_note 2, 12, 8, 1460
	square_note 2, 11, 8, 1460
	square_note 1, 9, 8, 965
	square_note 0, 8, 8, 965
	square_note 0, 6, 8, 1466
	square_note 1, 5, 8, 1466
	square_note 1, 3, 8, 1424
	square_note 0, 2, 8, 1424
	square_note 2, 1, 8, 1460
	square_note 2, 0, 8, 0
	sound_ret

Cry_Clodsire_Ch6:
	square_note 2, 0, 8, 0
	duty_cycle_pattern 0, 3, 0, 3
	square_note 2, 1, 8, 1610
	square_note 1, 2, 8, 1719
	square_note 0, 3, 8, 1719
	square_note 2, 4, 8, 1610
	square_note 1, 5, 8, 1497
	square_note 0, 6, 8, 1497
	square_note 2, 6, 8, 1476
	square_note 2, 6, 8, 1502
	square_note 2, 6, 8, 1516
	square_note 2, 6, 8, 1418
	square_note 2, 6, 8, 1411
	square_note 2, 6, 8, 1346
	square_note 2, 6, 8, 1581
	square_note 2, 6, 8, 1418
	square_note 2, 6, 8, 1370
	square_note 5, 5, 8, 1529
	square_note 0, 4, 8, 1113
	square_note 1, 3, 8, 1113
	square_note 2, 2, 8, 1052
	square_note 2, 1, 8, 1411
	square_note 1, 1, 8, 1529
	square_note 0, 0, 8, 0
	square_note 2, 0, 8, 0
	sound_ret

Cry_Clodsire_Ch7:
	square_note 2, 0, 1, 1868
	square_note 2, 0, 0, 1805
	square_note 1, 0, 4, 1765
	square_note 0, 3, 4, 1765
	square_note 2, 3, 7, 1419
	square_note 2, 3, 3, 1730
	square_note 2, 3, 1, 1746
	square_note 2, 3, 1, 1736
	square_note 2, 3, 1, 1751
	square_note 2, 3, 0, 1773
	square_note 2, 3, 1, 1771
	square_note 2, 3, 9, 1746
	square_note 2, 3, 7, 1727
	square_note 2, 3, 3, 1753
	square_note 2, 3, 3, 1751
	square_note 2, 3, 3, 1754
	square_note 2, 3, 1, 1754
	square_note 2, 3, 6, 1506
	square_note 2, 3, 3, 1757
	square_note 0, 3, 9, 1736
	square_note 1, 0, 9, 1736
	square_note 2, 0, 1, 1754
	square_note 2, 0, 6, 1767
	sound_ret

Cry_Clodsire_Ch8:
	noise_note 2, 0, 8, 108
	noise_note 2, 1, 8, 108
	noise_note 3, 2, 8, 108
	noise_note 1, 3, 8, 108
	noise_note 1, 4, 3, 108
	noise_note 9, 5, 3, 108
	noise_note 5, 4, 8, 108
	noise_note 5, 4, 5, 108
	noise_note 5, 4, 8, 108
	noise_note 5, 4, 3, 108
	noise_note 1, 3, 2, 124
	noise_note 3, 2, 2, 124
	noise_note 0, 2, 1, 108
	noise_note 4, 1, 1, 108
	noise_note 2, 0, 1, 108
	sound_ret
