; Generated by Siren
; Source: 917.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Dudunsparce:
	channel_count 3
	channel 5, Cry_Dudunsparce_Ch5
	channel 6, Cry_Dudunsparce_Ch6
	channel 8, Cry_Dudunsparce_Ch8

Cry_Dudunsparce_Ch5:
	duty_cycle 1
	square_note 0, 4, 8, 1848
	duty_cycle 2
	square_note 0, 13, 8, 1848
	square_note 0, 13, 8, 1596
	square_note 0, 13, 8, 1589
	square_note 0, 13, 8, 1587
	square_note 0, 13, 8, 1859
	square_note 0, 13, 8, 1601
	duty_cycle 0
	square_note 0, 13, 8, 1615
	duty_cycle 2
	square_note 0, 13, 8, 1615
	duty_cycle 0
	square_note 0, 13, 8, 1615
	duty_cycle 2
	square_note 0, 13, 8, 1397
	square_note 0, 13, 8, 1428
	square_note 0, 13, 8, 1582
	square_note 0, 13, 8, 1442
	square_note 0, 13, 8, 1433
	square_note 0, 13, 8, 1566
	duty_cycle 1
	square_note 0, 13, 8, 1461
	duty_cycle 2
	square_note 0, 13, 8, 1568
	square_note 0, 13, 8, 1386
	square_note 0, 13, 8, 1562
	square_note 0, 13, 8, 1461
	square_note 0, 13, 8, 1568
	square_note 0, 13, 8, 1515
	square_note 0, 13, 8, 1551
	square_note 0, 13, 8, 1532
	duty_cycle 3
	square_note 0, 13, 8, 1551
	duty_cycle 2
	square_note 0, 13, 8, 1574
	duty_cycle 1
	square_note 0, 13, 8, 1548
	duty_cycle 2
	square_note 0, 13, 8, 1554
	square_note 0, 13, 8, 1538
	square_note 0, 13, 8, 1542
	square_note 0, 13, 8, 1522
	square_note 0, 13, 8, 1551
	square_note 0, 13, 8, 1587
	duty_cycle 3
	square_note 0, 13, 8, 1548
	duty_cycle 2
	square_note 0, 13, 8, 1554
	square_note 0, 13, 8, 1542
	square_note 0, 13, 8, 1548
	square_note 0, 13, 8, 1519
	square_note 0, 13, 8, 1557
	square_note 0, 13, 8, 1596
	square_note 0, 13, 8, 1551
	square_note 0, 13, 8, 1560
	square_note 0, 13, 8, 1542
	square_note 0, 13, 8, 1554
	square_note 0, 13, 8, 1519
	square_note 0, 13, 8, 1560
	square_note 0, 13, 8, 1423
	square_note 0, 13, 8, 1548
	square_note 0, 13, 8, 1560
	square_note 0, 13, 8, 1542
	square_note 0, 13, 8, 1576
	square_note 0, 13, 8, 1522
	square_note 0, 13, 8, 1582
	square_note 0, 13, 8, 1433
	square_note 0, 13, 8, 1548
	square_note 0, 13, 8, 1554
	square_note 0, 13, 8, 1538
	square_note 0, 13, 8, 1562
	square_note 0, 13, 8, 1548
	square_note 0, 13, 8, 1584
	square_note 0, 13, 8, 1437
	duty_cycle 3
	square_note 0, 13, 8, 1542
	duty_cycle 2
	square_note 0, 13, 8, 1548
	duty_cycle 1
	square_note 0, 13, 8, 1538
	duty_cycle 2
	square_note 0, 13, 8, 1560
	square_note 0, 13, 8, 1557
	square_note 0, 13, 8, 1584
	square_note 0, 13, 8, 1437
	square_note 0, 13, 8, 1548
	square_note 1, 13, 8, 1538
	square_note 0, 13, 8, 1554
	square_note 0, 13, 8, 1560
	square_note 0, 13, 8, 1584
	square_note 0, 13, 8, 1442
	square_note 0, 13, 8, 1548
	square_note 0, 12, 8, 1532
	square_note 0, 12, 8, 1535
	square_note 0, 11, 8, 1554
	square_note 0, 11, 8, 1560
	square_note 0, 10, 8, 1571
	square_note 0, 10, 8, 1566
	square_note 0, 9, 8, 1554
	square_note 0, 9, 8, 1542
	square_note 0, 8, 8, 1538
	square_note 0, 8, 8, 1529
	duty_cycle 3
	square_note 0, 7, 8, 1525
	duty_cycle 2
	square_note 0, 7, 8, 1542
	square_note 0, 6, 8, 1485
	square_note 0, 5, 8, 1522
	square_note 0, 5, 8, 1456
	square_note 0, 4, 8, 1522
	square_note 0, 4, 8, 1465
	square_note 0, 3, 8, 1493
	square_note 0, 3, 8, 1489
	square_note 0, 2, 8, 1473
	square_note 0, 2, 8, 1481
	duty_cycle 1
	square_note 0, 1, 8, 1461
	duty_cycle 2
	square_note 0, 1, 8, 1469
	square_note 0, 0, 8, 0
	sound_ret

Cry_Dudunsparce_Ch6:
	duty_cycle 0
	square_note 0, 3, 8, 1797
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 6, 8, 1632
	duty_cycle 0
	square_note 0, 9, 8, 1556
	duty_cycle 2
	square_note 0, 8, 8, 1623
	square_note 0, 0, 8, 0
	square_note 0, 9, 8, 1860
	duty_cycle 3
	square_note 0, 8, 8, 1868
	duty_cycle 2
	square_note 0, 6, 8, 1868
	duty_cycle 0
	square_note 0, 8, 8, 1868
	duty_cycle 2
	square_note 0, 8, 8, 1869
	square_note 0, 8, 8, 1494
	square_note 0, 8, 8, 1546
	square_note 0, 8, 8, 1570
	square_note 0, 10, 8, 1578
	square_note 0, 10, 8, 1466
	duty_cycle 3
	square_note 0, 9, 8, 1570
	square_note 0, 8, 8, 1530
	square_note 0, 9, 8, 1567
	duty_cycle 2
	square_note 0, 8, 8, 1603
	square_note 0, 6, 8, 1576
	duty_cycle 3
	square_note 0, 8, 8, 1608
	duty_cycle 2
	square_note 0, 8, 8, 1564
	duty_cycle 3
	square_note 0, 8, 8, 1434
	duty_cycle 2
	square_note 0, 8, 8, 1487
	square_note 0, 8, 8, 1418
	square_note 0, 8, 8, 1453
	duty_cycle 3
	square_note 0, 6, 8, 1453
	duty_cycle 2
	square_note 0, 8, 8, 1448
	square_note 0, 8, 8, 1494
	square_note 0, 8, 8, 1586
	square_note 0, 8, 8, 1570
	square_note 0, 8, 8, 1593
	square_note 0, 9, 8, 1429
	duty_cycle 3
	square_note 0, 8, 8, 1443
	duty_cycle 2
	square_note 0, 8, 8, 1423
	square_note 0, 6, 8, 1498
	square_note 0, 8, 8, 1591
	square_note 0, 8, 8, 1567
	square_note 0, 8, 8, 1598
	square_note 0, 9, 8, 1429
	square_note 0, 8, 8, 1443
	square_note 0, 8, 8, 1423
	square_note 0, 6, 8, 1586
	square_note 0, 8, 8, 1598
	square_note 0, 8, 8, 1567
	square_note 0, 8, 8, 1600
	square_note 0, 10, 8, 1600
	square_note 0, 8, 8, 1591
	square_note 0, 8, 8, 1600
	square_note 0, 6, 8, 1586
	square_note 0, 8, 8, 1540
	square_note 0, 8, 8, 1570
	square_note 0, 8, 8, 1546
	square_note 0, 9, 8, 1603
	square_note 0, 6, 8, 1591
	square_note 0, 8, 8, 1596
	square_note 0, 8, 8, 1583
	square_note 0, 8, 8, 1603
	square_note 0, 8, 8, 1506
	square_note 0, 8, 8, 1549
	square_note 0, 8, 8, 1593
	square_note 0, 8, 8, 1586
	square_note 0, 8, 8, 1591
	square_note 0, 8, 8, 1586
	square_note 0, 8, 8, 1600
	square_note 0, 8, 8, 1517
	square_note 0, 8, 8, 1549
	square_note 0, 8, 8, 1502
	square_note 0, 6, 8, 1506
	square_note 0, 8, 8, 1586
	square_note 0, 6, 8, 1583
	square_note 0, 8, 8, 1598
	square_note 0, 8, 8, 1517
	square_note 0, 8, 8, 1549
	square_note 0, 8, 8, 1598
	duty_cycle 3
	square_note 0, 8, 8, 1506
	duty_cycle 2
	square_note 0, 8, 8, 1578
	square_note 0, 7, 8, 1580
	square_note 0, 5, 8, 1596
	square_note 0, 5, 8, 1520
	square_note 0, 5, 8, 1610
	square_note 0, 5, 8, 1527
	square_note 0, 6, 8, 1596
	square_note 0, 5, 8, 1586
	square_note 0, 5, 8, 1583
	square_note 0, 5, 8, 1483
	duty_cycle 3
	square_note 0, 4, 8, 1457
	duty_cycle 2
	square_note 0, 3, 8, 1498
	duty_cycle 3
	square_note 0, 3, 8, 1540
	duty_cycle 2
	square_note 0, 3, 8, 1570
	square_note 0, 3, 8, 1517
	square_note 0, 3, 8, 1570
	square_note 0, 2, 8, 1524
	square_note 0, 2, 8, 1438
	square_note 0, 1, 8, 1434
	square_note 0, 1, 8, 1530
	square_note 0, 1, 8, 1537
	square_note 0, 1, 8, 1520
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Dudunsparce_Ch8:
	noise_note 0, 1, 8, 75
	noise_note 5, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 5, 4, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 4, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 6, 4, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 3, 2, 8, 75
	noise_note 2, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 3, 4, 8, 75
	noise_note 2, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 5, 0, 8, 75
	sound_ret
