; Generated by Siren
; Source: 466.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Electivire:
	channel_count 4
	channel 5, Cry_Electivire_Ch5
	channel 6, Cry_Electivire_Ch6
	channel 7, Cry_Electivire_Ch7
	channel 8, Cry_Electivire_Ch8

Cry_Electivire_Ch5:
	duty_cycle_pattern 2, 2, 2, 2
	square_note 2, 14, 8, 1320
	square_note 2, 14, 8, 1551
	square_note 2, 12, 8, 1820
	square_note 2, 14, 8, 1816
	square_note 2, 13, 8, 1812
	square_note 2, 13, 8, 1760
	square_note 2, 13, 8, 1763
	square_note 2, 13, 8, 1800
	square_note 2, 12, 8, 1793
	square_note 2, 12, 8, 1790
	square_note 2, 13, 8, 1787
	square_note 2, 12, 8, 1783
	square_note 2, 9, 8, 1779
	square_note 2, 7, 8, 1775
	square_note 2, 9, 8, 1773
	square_note 2, 9, 8, 1768
	square_note 2, 6, 8, 1768
	square_note 2, 9, 8, 1764
	square_note 2, 8, 8, 1762
	square_note 2, 7, 8, 1756
	square_note 2, 7, 8, 1755
	square_note 2, 8, 8, 1750
	square_note 2, 7, 8, 1748
	square_note 2, 5, 8, 1744
	square_note 5, 4, 8, 1743
	square_note 2, 3, 8, 1743
	square_note 1, 3, 8, 1738
	square_note 0, 2, 8, 1738
	square_note 2, 2, 8, 1734
	square_note 2, 1, 8, 1734
	square_note 0, 1, 8, 1732
	square_note 4, 0, 8, 0
	square_note 7, 0, 8, 0
	sound_ret

Cry_Electivire_Ch6:
	duty_cycle_pattern 1, 2, 1, 2
	square_note 2, 14, 8, 1440
	square_note 2, 14, 8, 1597
	square_note 2, 12, 8, 1706
	square_note 2, 14, 8, 1689
	square_note 2, 12, 8, 1727
	square_note 2, 14, 8, 1783
	square_note 2, 14, 8, 1774
	square_note 2, 14, 8, 1840
	square_note 2, 12, 8, 1828
	square_note 2, 11, 8, 1731
	square_note 2, 12, 8, 1872
	square_note 2, 11, 8, 1871
	square_note 2, 9, 8, 1697
	square_note 2, 6, 8, 1870
	square_note 2, 9, 8, 1863
	square_note 2, 9, 8, 1684
	square_note 2, 5, 8, 1682
	square_note 2, 9, 8, 1679
	square_note 2, 7, 8, 1678
	square_note 2, 6, 8, 1667
	square_note 2, 7, 8, 1865
	square_note 2, 7, 8, 1662
	square_note 2, 6, 8, 1864
	square_note 2, 5, 8, 1652
	square_note 8, 4, 8, 1650
	square_note 0, 4, 8, 1643
	square_note 1, 3, 8, 1643
	square_note 0, 2, 8, 1638
	square_note 4, 1, 8, 1638
	square_note 0, 1, 8, 1635
	square_note 4, 0, 8, 0
	square_note 7, 0, 8, 0
	sound_ret

Cry_Electivire_Ch7:
	square_note 2, 1, 2, 1684
	square_note 2, 1, 8, 1800
	square_note 2, 1, 1, 1934
	square_note 2, 1, 1, 1932
	square_note 2, 1, 2, 1930
	square_note 2, 1, 6, 1904
	square_note 2, 1, 3, 1906
	square_note 2, 1, 1, 1924
	square_note 2, 1, 6, 1921
	square_note 2, 1, 1, 1920
	square_note 2, 1, 3, 1918
	square_note 2, 1, 3, 1916
	square_note 2, 1, 1, 1914
	square_note 2, 2, 1, 1911
	square_note 2, 1, 1, 1911
	square_note 2, 2, 4, 1908
	square_note 2, 2, 1, 1908
	square_note 2, 2, 4, 1906
	square_note 2, 2, 3, 1906
	square_note 2, 2, 1, 1902
	square_note 2, 2, 1, 1901
	square_note 2, 2, 5, 1900
	square_note 2, 2, 9, 1898
	square_note 2, 2, 9, 1896
	square_note 8, 2, 3, 1895
	square_note 2, 2, 1, 1893
	square_note 0, 2, 1, 1891
	square_note 4, 3, 1, 1891
	square_note 5, 3, 1, 1890
	square_note 7, 0, 0, 0
	sound_ret

Cry_Electivire_Ch8:
	noise_note 5, 14, 8, 68
	noise_note 5, 14, 3, 84
	noise_note 5, 11, 8, 52
	noise_note 5, 13, 3, 52
	noise_note 5, 12, 8, 52
	noise_note 5, 13, 1, 52
	noise_note 5, 11, 2, 52
	noise_note 5, 11, 1, 52
	noise_note 5, 9, 8, 52
	noise_note 5, 9, 1, 52
	noise_note 5, 9, 2, 52
	noise_note 5, 8, 2, 100
	noise_note 11, 2, 8, 92
	noise_note 0, 2, 5, 92
	noise_note 4, 1, 5, 92
	noise_note 0, 1, 8, 92
	noise_note 4, 0, 8, 92
	noise_note 5, 0, 8, 76
	noise_note 1, 0, 8, 44
	sound_ret
