; Generated by Siren
; Source: 471.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Glaceon:
	channel_count 4
	channel 5, Cry_Glaceon_Ch5
	channel 6, Cry_Glaceon_Ch6
	channel 7, Cry_Glaceon_Ch7
	channel 8, Cry_Glaceon_Ch8

Cry_Glaceon_Ch5:
	duty_cycle 2
	square_note 0, 6, 8, 1970
	square_note 0, 15, 8, 1973
	square_note 0, 15, 8, 1909
	square_note 0, 15, 8, 1916
	square_note 0, 12, 8, 1911
	square_note 0, 6, 8, 1911
	duty_cycle 1
	square_note 0, 6, 8, 1911
	square_note 0, 3, 8, 1912
	duty_cycle 2
	square_note 0, 6, 8, 1919
	square_note 0, 3, 8, 1913
	square_note 0, 3, 8, 2006
	square_note 0, 9, 8, 2006
	square_note 0, 6, 8, 1917
	square_note 0, 6, 8, 1916
	square_note 0, 6, 8, 1917
	square_note 0, 9, 8, 1915
	square_note 0, 9, 8, 1907
	square_note 0, 6, 8, 1903
	square_note 0, 12, 8, 1898
	square_note 0, 9, 8, 1893
	square_note 0, 9, 8, 1895
	square_note 0, 9, 8, 1892
	square_note 0, 6, 8, 1892
	square_note 0, 3, 8, 1893
	square_note 0, 6, 8, 1895
	square_note 0, 9, 8, 1896
	square_note 0, 9, 8, 1899
	square_note 0, 6, 8, 1898
	square_note 0, 9, 8, 1899
	square_note 0, 6, 8, 1902
	square_note 0, 6, 8, 1914
	square_note 0, 6, 8, 1913
	square_note 0, 12, 8, 1914
	square_note 1, 15, 8, 1916
	square_note 0, 9, 8, 1917
	square_note 0, 9, 8, 1918
	square_note 0, 15, 8, 1919
	square_note 2, 15, 8, 1920
	square_note 2, 15, 8, 1921
	square_note 0, 15, 8, 1922
	square_note 0, 15, 8, 1923
	square_note 0, 15, 8, 1925
	square_note 0, 15, 8, 1937
	square_note 0, 15, 8, 1939
	square_note 0, 15, 8, 1924
	square_note 0, 12, 8, 1979
	square_note 0, 9, 8, 1920
	duty_cycle 1
	square_note 0, 6, 8, 1916
	duty_cycle 2
	square_note 0, 6, 8, 1986
	square_note 0, 6, 8, 1987
	square_note 0, 9, 8, 1988
	square_note 0, 12, 8, 1917
	square_note 0, 6, 8, 1919
	square_note 0, 9, 8, 1920
	square_note 0, 6, 8, 1991
	square_note 0, 12, 8, 1991
	square_note 0, 15, 8, 1989
	square_note 0, 6, 8, 1989
	square_note 0, 15, 8, 1987
	square_note 0, 12, 8, 1984
	square_note 0, 9, 8, 1984
	square_note 0, 9, 8, 1983
	duty_cycle 3
	square_note 0, 6, 8, 1922
	duty_cycle 2
	square_note 0, 6, 8, 2003
	duty_cycle 3
	square_note 0, 9, 8, 1961
	duty_cycle 2
	square_note 0, 6, 8, 1955
	square_note 0, 6, 8, 1952
	square_note 0, 6, 8, 1948
	square_note 0, 6, 8, 2001
	square_note 0, 9, 8, 2001
	square_note 0, 6, 8, 1932
	square_note 0, 6, 8, 1928
	square_note 0, 6, 8, 1924
	square_note 0, 9, 8, 1921
	square_note 0, 9, 8, 1919
	square_note 0, 6, 8, 1906
	square_note 0, 6, 8, 1902
	square_note 0, 6, 8, 1893
	square_note 0, 6, 8, 1892
	square_note 0, 6, 8, 1894
	square_note 0, 3, 8, 1893
	square_note 0, 3, 8, 1894
	square_note 0, 3, 8, 1892
	square_note 0, 3, 8, 1919
	square_note 0, 3, 8, 1921
	square_note 0, 3, 8, 1914
	square_note 9, 0, 8, 0
	sound_ret

Cry_Glaceon_Ch6:
	square_note 2, 0, 8, 0
	duty_cycle 2
	square_note 0, 8, 8, 1973
	square_note 0, 7, 8, 1973
	square_note 0, 0, 8, 0
	square_note 1, 3, 8, 1974
	square_note 8, 0, 8, 0
	square_note 1, 8, 8, 1985
	square_note 7, 0, 8, 0
	square_note 0, 7, 8, 1969
	square_note 0, 8, 8, 1969
	square_note 17, 0, 8, 0
	square_note 0, 12, 8, 1926
	square_note 0, 15, 8, 1926
	square_note 0, 0, 8, 0
	square_note 0, 15, 8, 1938
	square_note 0, 10, 8, 1935
	square_note 0, 7, 8, 1936
	square_note 2, 0, 8, 0
	square_note 0, 13, 8, 1989
	square_note 0, 5, 8, 1990
	square_note 0, 8, 8, 1991
	square_note 3, 0, 8, 0
	square_note 0, 8, 8, 1992
	square_note 0, 8, 8, 1991
	square_note 0, 12, 8, 1991
	square_note 0, 0, 8, 0
	square_note 0, 7, 8, 1988
	square_note 0, 7, 8, 1986
	square_note 0, 7, 8, 1985
	square_note 0, 5, 8, 1984
	square_note 10, 0, 8, 0
	square_note 0, 5, 8, 2001
	square_note 0, 3, 8, 2001
	square_note 4, 0, 8, 0
	square_note 1, 2, 8, 1892
	square_note 0, 2, 8, 1890
	square_note 0, 2, 8, 1893
	square_note 7, 0, 8, 0
	sound_ret

Cry_Glaceon_Ch7:
	square_note 0, 2, 1, 2009
	square_note 0, 1, 1, 2011
	square_note 0, 1, 1, 1979
	square_note 0, 1, 1, 1982
	square_note 1, 2, 1, 1979
	square_note 0, 2, 1, 1980
	square_note 0, 3, 2, 1980
	square_note 0, 2, 1, 1983
	square_note 0, 3, 1, 1981
	square_note 0, 3, 1, 2027
	square_note 0, 2, 1, 2027
	square_note 0, 2, 0, 1983
	square_note 0, 2, 1, 1982
	square_note 0, 2, 1, 1983
	square_note 0, 2, 1, 1982
	square_note 0, 2, 1, 1978
	square_note 0, 2, 1, 1976
	square_note 0, 1, 1, 1973
	square_note 1, 2, 1, 1971
	square_note 1, 2, 1, 1970
	square_note 0, 3, 1, 1971
	square_note 0, 2, 1, 1971
	square_note 0, 2, 1, 1972
	square_note 1, 2, 1, 1973
	square_note 0, 2, 1, 1974
	square_note 0, 2, 1, 1975
	square_note 1, 2, 1, 1981
	square_note 0, 1, 1, 1981
	square_note 1, 1, 1, 1982
	square_note 1, 2, 1, 1983
	square_note 0, 1, 1, 1983
	square_note 4, 1, 1, 1984
	square_note 1, 1, 1, 1985
	square_note 1, 1, 1, 1986
	square_note 0, 1, 1, 1993
	square_note 0, 1, 1, 1994
	square_note 0, 1, 1, 1986
	square_note 0, 1, 1, 2014
	square_note 0, 2, 1, 1984
	square_note 0, 2, 2, 1982
	square_note 0, 2, 1, 2017
	square_note 1, 2, 1, 2018
	square_note 0, 1, 1, 1983
	square_note 1, 2, 1, 1984
	square_note 0, 2, 1, 2020
	square_note 0, 1, 1, 2020
	square_note 0, 1, 1, 2018
	square_note 0, 2, 1, 2018
	square_note 0, 1, 1, 2017
	square_note 0, 1, 1, 2016
	square_note 1, 2, 1, 2016
	square_note 0, 2, 2, 1985
	square_note 0, 2, 1, 2026
	square_note 0, 2, 2, 2005
	square_note 0, 2, 1, 2002
	square_note 0, 2, 1, 2000
	square_note 0, 2, 1, 1998
	square_note 1, 2, 1, 2025
	square_note 0, 2, 1, 1990
	square_note 0, 2, 1, 1988
	square_note 0, 2, 1, 1986
	square_note 0, 2, 1, 1985
	square_note 0, 2, 1, 1983
	square_note 0, 2, 3, 1977
	square_note 0, 2, 1, 1975
	square_note 0, 2, 1, 1971
	square_note 0, 2, 1, 1970
	square_note 0, 2, 1, 1971
	square_note 1, 3, 1, 1971
	square_note 0, 3, 1, 1970
	square_note 0, 3, 1, 1983
	square_note 0, 3, 1, 1985
	square_note 0, 3, 0, 1981
	square_note 0, 3, 1, 1987
	square_note 0, 3, 3, 1982
	square_note 0, 3, 1, 1971
	square_note 4, 3, 1, 1970
	square_note 1, 0, 0, 0
	sound_ret

Cry_Glaceon_Ch8:
	noise_note 67, 0, 8, 0
	noise_note 0, 15, 8, 92
	noise_note 31, 0, 8, 0
	sound_ret
