; Generated by Siren
; Source: 440.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Happiny:
	channel_count 3
	channel 5, Cry_Happiny_Ch5
	channel 7, Cry_Happiny_Ch7
	channel 8, Cry_Happiny_Ch8

Cry_Happiny_Ch5:
	duty_cycle 1
	square_note 0, 15, 8, 1928
	duty_cycle 3
	square_note 0, 15, 8, 1923
	duty_cycle 2
	square_note 0, 15, 8, 1972
	duty_cycle 3
	square_note 0, 15, 8, 1895
	duty_cycle 2
	square_note 0, 9, 8, 1977
	square_note 0, 15, 8, 1975
	square_note 0, 15, 8, 1974
	duty_cycle 3
	square_note 0, 15, 8, 1900
	duty_cycle 1
	square_note 0, 12, 8, 1898
	duty_cycle 2
	square_note 0, 3, 8, 1950
	square_note 0, 6, 8, 1974
	square_note 0, 6, 8, 1975
	duty_cycle 3
	square_note 0, 9, 8, 1904
	square_note 2, 0, 8, 0
	duty_cycle 2
	square_note 0, 15, 8, 1983
	duty_cycle 3
	square_note 0, 15, 8, 1919
	duty_cycle 1
	square_note 0, 15, 8, 1923
	duty_cycle 2
	square_note 0, 12, 8, 1947
	square_note 0, 3, 8, 1968
	square_note 0, 12, 8, 1968
	duty_cycle 3
	square_note 0, 12, 8, 1937
	duty_cycle 2
	square_note 0, 12, 8, 1962
	duty_cycle 1
	square_note 0, 12, 8, 1882
	duty_cycle 2
	square_note 0, 6, 8, 1960
	square_note 0, 3, 8, 1966
	square_note 0, 3, 8, 1987
	square_note 0, 3, 8, 1992
	square_note 0, 3, 8, 1993
	square_note 0, 0, 8, 0
	sound_ret

Cry_Happiny_Ch7:
	square_note 0, 1, 6, 1988
	square_note 0, 1, 2, 1986
	square_note 0, 1, 1, 2010
	square_note 0, 1, 6, 1972
	square_note 0, 1, 1, 2012
	square_note 1, 1, 1, 2011
	square_note 0, 1, 6, 1974
	square_note 0, 1, 6, 1973
	square_note 0, 2, 1, 1999
	square_note 1, 2, 1, 2011
	square_note 0, 0, 0, 0
	square_note 0, 3, 6, 1975
	square_note 0, 3, 1, 2013
	square_note 0, 3, 1, 2014
	square_note 0, 1, 1, 2016
	square_note 0, 1, 6, 1984
	square_note 0, 1, 6, 1986
	square_note 0, 1, 2, 1998
	square_note 0, 3, 1, 2008
	square_note 0, 1, 1, 2008
	square_note 0, 1, 2, 1993
	square_note 0, 1, 1, 2005
	square_note 0, 1, 2, 1965
	square_note 0, 2, 1, 2004
	square_note 0, 3, 1, 2007
	square_note 0, 2, 1, 2018
	square_note 0, 3, 1, 2020
	square_note 1, 3, 1, 2021
	sound_ret

Cry_Happiny_Ch8:
	noise_note 7, 0, 8, 0
	noise_note 0, 8, 8, 92
	noise_note 2, 0, 8, 0
	noise_note 0, 8, 8, 92
	noise_note 3, 0, 8, 0
	noise_note 0, 8, 8, 92
	noise_note 0, 15, 8, 92
	noise_note 0, 8, 8, 92
	noise_note 0, 0, 8, 0
	noise_note 1, 15, 8, 92
	noise_note 0, 8, 8, 92
	noise_note 6, 0, 8, 0
	sound_ret
