; Generated by Siren
; Source: 430.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Honchkrow:
	channel_count 4
	channel 5, Cry_Honchkrow_Ch5
	channel 6, Cry_Honchkrow_Ch6
	channel 7, Cry_Honchkrow_Ch7
	channel 8, Cry_Honchkrow_Ch8

Cry_Honchkrow_Ch5:
	duty_cycle_pattern 2, 2, 1, 1
	square_note 2, 13, 8, 176
	square_note 2, 12, 8, 0
	square_note 2, 11, 8, 92
	square_note 2, 12, 8, 1850
	square_note 2, 11, 8, 1854
	square_note 2, 12, 8, 638
	square_note 2, 12, 8, 1192
	square_note 2, 14, 8, 1844
	square_note 2, 12, 8, 1032
	square_note 2, 12, 8, 0
	square_note 2, 13, 8, 0
	square_note 2, 12, 8, 1804
	square_note 2, 12, 8, 92
	square_note 2, 11, 8, 1708
	square_note 2, 13, 8, 0
	square_note 2, 11, 8, 0
	square_note 2, 11, 8, 176
	square_note 2, 11, 8, 1848
	square_note 2, 10, 8, 92
	square_note 2, 11, 8, 1770
	square_note 2, 9, 8, 1770
	square_note 2, 7, 8, 1750
	square_note 2, 5, 8, 0
	square_note 2, 5, 8, 0
	square_note 2, 3, 8, 0
	square_note 1, 2, 8, 0
	sound_ret

Cry_Honchkrow_Ch6:
	duty_cycle_pattern 0, 3, 0, 3
	square_note 2, 10, 8, 0
	square_note 2, 10, 8, 1840
	square_note 2, 9, 8, 1842
	square_note 2, 9, 8, 1844
	square_note 2, 9, 8, 1798
	square_note 2, 9, 8, 1852
	square_note 2, 9, 8, 1816
	square_note 2, 11, 8, 1818
	square_note 2, 9, 8, 1796
	square_note 2, 10, 8, 1808
	square_note 2, 10, 8, 1804
	square_note 2, 10, 8, 1704
	square_note 2, 9, 8, 1806
	square_note 2, 9, 8, 1816
	square_note 2, 10, 8, 1854
	square_note 2, 9, 8, 1856
	square_note 2, 9, 8, 1846
	square_note 2, 9, 8, 1866
	square_note 2, 8, 8, 1850
	square_note 2, 9, 8, 1838
	square_note 2, 7, 8, 1776
	square_note 2, 5, 8, 1758
	square_note 2, 4, 8, 1838
	square_note 2, 3, 8, 1844
	square_note 2, 2, 8, 1796
	square_note 1, 2, 8, 0
	sound_ret

Cry_Honchkrow_Ch7:
	square_note 2, 2, 8, 1112
	square_note 2, 2, 3, 684
	square_note 2, 2, 7, 1070
	square_note 2, 2, 1, 1950
	square_note 2, 2, 1, 1952
	square_note 2, 2, 5, 1344
	square_note 2, 2, 7, 1620
	square_note 2, 2, 1, 1946
	square_note 2, 2, 1, 1540
	square_note 2, 2, 7, 0
	square_note 2, 2, 4, 0
	square_note 2, 2, 1, 1926
	square_note 2, 2, 1, 1070
	square_note 2, 2, 1, 1878
	square_note 2, 2, 4, 0
	square_note 2, 2, 7, 712
	square_note 2, 2, 1, 1112
	square_note 2, 2, 1, 1948
	square_note 2, 2, 3, 1070
	square_note 2, 2, 0, 1910
	square_note 2, 2, 1, 1910
	square_note 2, 3, 1, 1900
	square_note 2, 3, 8, 764
	square_note 2, 3, 8, 592
	square_note 2, 3, 4, 278
	square_note 1, 3, 4, 0
	sound_ret

Cry_Honchkrow_Ch8:
	noise_note 5, 9, 4, 116
	noise_note 5, 10, 8, 68
	noise_note 5, 11, 2, 68
	noise_note 5, 12, 8, 68
	noise_note 5, 10, 5, 68
	noise_note 5, 11, 8, 92
	noise_note 5, 11, 2, 92
	noise_note 5, 11, 3, 76
	noise_note 5, 10, 8, 76
	noise_note 5, 10, 3, 76
	noise_note 5, 8, 2, 76
	noise_note 5, 5, 3, 76
	noise_note 4, 3, 3, 76
	sound_ret
