; Generated by Siren
; Source: 900.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Kleavor:
	channel_count 3
	channel 5, Cry_Kleavor_Ch5
	channel 6, Cry_Kleavor_Ch6
	channel 8, Cry_Kleavor_Ch8

Cry_Kleavor_Ch5:
	duty_cycle 2
	square_note 0, 11, 8, 1389
	square_note 0, 13, 8, 1743
	square_note 0, 13, 8, 1193
	square_note 0, 13, 8, 1059
	square_note 1, 13, 8, 1115
	square_note 0, 13, 8, 1804
	square_note 0, 13, 8, 1794
	square_note 0, 13, 8, 1938
	square_note 0, 13, 8, 1687
	duty_cycle 1
	square_note 0, 13, 8, 1414
	duty_cycle 2
	square_note 0, 13, 8, 1809
	square_note 0, 13, 8, 1786
	duty_cycle 1
	square_note 0, 13, 8, 1600
	duty_cycle 2
	square_note 0, 13, 8, 1794
	square_note 0, 13, 8, 1801
	square_note 0, 13, 8, 1797
	square_note 0, 13, 8, 1916
	square_note 0, 13, 8, 1918
	square_note 0, 13, 8, 1851
	square_note 0, 13, 8, 1905
	square_note 0, 13, 8, 1913
	square_note 0, 13, 8, 1910
	square_note 0, 13, 8, 1917
	duty_cycle 1
	square_note 0, 13, 8, 1775
	duty_cycle 2
	square_note 0, 13, 8, 1907
	square_note 0, 13, 8, 1914
	square_note 0, 13, 8, 1932
	square_note 0, 13, 8, 1913
	square_note 0, 13, 8, 1917
	square_note 0, 12, 8, 1936
	square_note 0, 12, 8, 1733
	square_note 0, 12, 8, 1913
	square_note 0, 10, 8, 1915
	square_note 0, 9, 8, 1935
	square_note 0, 7, 8, 1939
	square_note 0, 4, 8, 1939
	square_note 0, 2, 8, 1939
	duty_cycle 1
	square_note 0, 1, 8, 1706
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Kleavor_Ch6:
	duty_cycle 2
	square_note 0, 9, 8, 1808
	duty_cycle 1
	square_note 0, 11, 8, 1799
	duty_cycle 2
	square_note 0, 11, 8, 1795
	square_note 0, 7, 8, 1785
	square_note 0, 9, 8, 1817
	square_note 0, 9, 8, 1811
	square_note 0, 8, 8, 1840
	square_note 0, 8, 8, 1849
	square_note 0, 7, 8, 1859
	square_note 0, 7, 8, 1845
	square_note 0, 11, 8, 1861
	duty_cycle 1
	square_note 0, 7, 8, 1867
	square_note 0, 9, 8, 1869
	duty_cycle 2
	square_note 0, 12, 8, 1830
	square_note 0, 7, 8, 1832
	square_note 0, 8, 8, 1844
	square_note 0, 7, 8, 1849
	square_note 0, 11, 8, 1839
	square_note 0, 12, 8, 1845
	square_note 0, 8, 8, 1827
	square_note 0, 11, 8, 1841
	duty_cycle 1
	square_note 0, 11, 8, 1830
	duty_cycle 2
	square_note 0, 8, 8, 1937
	square_note 0, 12, 8, 1941
	square_note 0, 8, 8, 1910
	square_note 0, 9, 8, 1892
	square_note 0, 9, 8, 1901
	square_note 0, 11, 8, 1913
	square_note 0, 9, 8, 1941
	square_note 0, 8, 8, 1898
	square_note 0, 8, 8, 1920
	square_note 0, 9, 8, 1941
	square_note 0, 7, 8, 1933
	square_note 0, 6, 8, 1940
	square_note 0, 7, 8, 1917
	square_note 0, 5, 8, 1925
	square_note 0, 4, 8, 1926
	square_note 0, 2, 8, 1929
	square_note 0, 1, 8, 1922
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Kleavor_Ch8:
	noise_note 0, 10, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 1, 10, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 1, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 10, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 11, 8, 75
	noise_note 2, 10, 8, 75
	noise_note 2, 9, 8, 75
	noise_note 0, 10, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 10, 8, 75
	noise_note 5, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 5, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 1, 0, 8, 75
	sound_ret
