; Generated by Siren
; Source: 463.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Lickilicky:
	channel_count 4
	channel 5, Cry_Lickilicky_Ch5
	channel 6, Cry_Lickilicky_Ch6
	channel 7, Cry_Lickilicky_Ch7
	channel 8, Cry_Lickilicky_Ch8

Cry_Lickilicky_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 6, 8, 1839
	square_note 2, 10, 8, 1794
	square_note 2, 3, 8, 1774
	square_note 2, 7, 8, 1828
	square_note 2, 7, 8, 1771
	square_note 2, 12, 8, 0
	square_note 2, 13, 8, 120
	square_note 2, 12, 8, 559
	square_note 2, 13, 8, 1815
	square_note 2, 12, 8, 1882
	square_note 2, 11, 8, 1870
	square_note 2, 11, 8, 1852
	square_note 2, 11, 8, 1868
	square_note 2, 12, 8, 1874
	square_note 2, 10, 8, 1881
	square_note 2, 11, 8, 1866
	square_note 2, 10, 8, 1832
	square_note 2, 12, 8, 1586
	square_note 2, 10, 8, 1665
	square_note 2, 11, 8, 1570
	square_note 1, 12, 8, 1703
	square_note 0, 11, 8, 1703
	square_note 0, 13, 8, 956
	square_note 0, 12, 8, 956
	square_note 0, 11, 8, 956
	square_note 0, 8, 8, 0
	square_note 1, 7, 8, 0
	square_note 0, 5, 8, 0
	square_note 1, 4, 8, 0
	square_note 4, 2, 8, 0
	square_note 2, 1, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Lickilicky_Ch6:
	duty_cycle_pattern 0, 2, 0, 2
	square_note 2, 7, 8, 1914
	square_note 2, 11, 8, 1808
	square_note 2, 3, 8, 1815
	square_note 2, 7, 8, 1737
	square_note 2, 8, 8, 1701
	square_note 2, 12, 8, 623
	square_note 2, 15, 8, 711
	square_note 2, 12, 8, 1847
	square_note 2, 14, 8, 1730
	square_note 2, 12, 8, 1821
	square_note 2, 12, 8, 1835
	square_note 2, 12, 8, 1954
	square_note 2, 12, 8, 1856
	square_note 2, 12, 8, 1864
	square_note 2, 11, 8, 1870
	square_note 2, 12, 8, 1886
	square_note 2, 11, 8, 1878
	square_note 2, 12, 8, 1631
	square_note 2, 11, 8, 1636
	square_note 2, 12, 8, 1617
	square_note 1, 14, 8, 1583
	square_note 0, 13, 8, 1583
	square_note 0, 14, 8, 1174
	square_note 0, 13, 8, 1174
	square_note 0, 12, 8, 1174
	square_note 1, 8, 8, 0
	square_note 0, 7, 8, 0
	square_note 0, 5, 8, 1208
	square_note 1, 4, 8, 1208
	square_note 2, 2, 8, 0
	square_note 1, 2, 8, 1229
	square_note 2, 1, 8, 1229
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Lickilicky_Ch7:
	square_note 2, 2, 0, 1944
	square_note 2, 1, 3, 1921
	square_note 2, 2, 7, 1911
	square_note 2, 2, 1, 1938
	square_note 2, 2, 7, 1910
	square_note 2, 1, 6, 1024
	square_note 2, 1, 3, 1084
	square_note 2, 1, 8, 1304
	square_note 2, 1, 0, 1932
	square_note 2, 1, 0, 1965
	square_note 2, 1, 0, 1959
	square_note 2, 1, 1, 1950
	square_note 2, 1, 3, 1958
	square_note 2, 1, 1, 1961
	square_note 2, 1, 0, 1965
	square_note 2, 1, 4, 1957
	square_note 2, 1, 4, 1940
	square_note 2, 1, 4, 1817
	square_note 2, 1, 2, 1857
	square_note 2, 1, 7, 1809
	square_note 2, 1, 6, 1876
	square_note 2, 1, 4, 1502
	square_note 0, 1, 6, 1024
	square_note 1, 2, 6, 1024
	square_note 6, 3, 6, 1024
	square_note 1, 0, 6, 1024
	square_note 2, 0, 2, 1024
	square_note 0, 0, 4, 1605
	sound_ret

Cry_Lickilicky_Ch8:
	noise_note 5, 9, 3, 92
	noise_note 5, 10, 2, 76
	noise_note 5, 15, 2, 100
	noise_note 5, 13, 2, 116
	noise_note 5, 14, 2, 92
	noise_note 5, 14, 8, 76
	noise_note 5, 10, 8, 76
	noise_note 5, 11, 8, 76
	noise_note 11, 13, 8, 92
	noise_note 1, 13, 8, 84
	noise_note 1, 12, 8, 84
	noise_note 0, 11, 8, 84
	noise_note 0, 10, 8, 84
	noise_note 0, 7, 2, 100
	noise_note 1, 6, 2, 100
	noise_note 2, 5, 2, 100
	noise_note 0, 3, 8, 116
	noise_note 3, 2, 8, 116
	noise_note 0, 1, 8, 116
	noise_note 1, 1, 1, 116
	noise_note 1, 0, 1, 116
	sound_ret
