; Generated by Siren
; Source: 467.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Magmortar:
	channel_count 4
	channel 5, Cry_Magmortar_Ch5
	channel 6, Cry_Magmortar_Ch6
	channel 7, Cry_Magmortar_Ch7
	channel 8, Cry_Magmortar_Ch8

Cry_Magmortar_Ch5:
	duty_cycle_pattern 2, 2, 2, 2
	square_note 2, 14, 8, 1938
	square_note 2, 14, 8, 1821
	square_note 2, 14, 8, 1586
	square_note 2, 13, 8, 1614
	square_note 2, 14, 8, 1835
	square_note 2, 13, 8, 1848
	square_note 2, 14, 8, 1584
	square_note 2, 13, 8, 1812
	square_note 2, 13, 8, 1793
	square_note 2, 13, 8, 1748
	square_note 2, 11, 8, 1837
	square_note 2, 10, 8, 1609
	square_note 2, 12, 8, 315
	square_note 2, 12, 8, 864
	square_note 2, 14, 8, 1698
	square_note 2, 13, 8, 955
	square_note 2, 14, 8, 883
	square_note 2, 11, 8, 655
	square_note 2, 7, 8, 1061
	square_note 2, 7, 8, 178
	square_note 1, 6, 8, 178
	square_note 0, 5, 8, 178
	square_note 0, 6, 8, 1182
	square_note 1, 5, 8, 1182
	square_note 1, 6, 8, 883
	square_note 0, 5, 8, 883
	square_note 1, 5, 8, 469
	square_note 0, 4, 8, 469
	square_note 1, 2, 8, 626
	square_note 0, 1, 8, 626
	square_note 1, 0, 8, 0
	sound_ret

Cry_Magmortar_Ch6:
	duty_cycle_pattern 1, 2, 1, 2
	square_note 2, 13, 8, 1903
	square_note 2, 13, 8, 1647
	square_note 2, 13, 8, 1625
	square_note 2, 12, 8, 1760
	square_note 2, 13, 8, 1855
	square_note 2, 12, 8, 1914
	square_note 2, 13, 8, 1919
	square_note 2, 12, 8, 1884
	square_note 2, 12, 8, 1928
	square_note 2, 12, 8, 1873
	square_note 2, 11, 8, 1751
	square_note 2, 9, 8, 1647
	square_note 2, 12, 8, 1593
	square_note 2, 12, 8, 1722
	square_note 2, 13, 8, 1589
	square_note 2, 13, 8, 1148
	square_note 2, 13, 8, 1100
	square_note 2, 9, 8, 1003
	square_note 2, 7, 8, 1489
	square_note 2, 6, 8, 1338
	square_note 1, 6, 8, 1484
	square_note 0, 5, 8, 1484
	square_note 1, 5, 8, 1378
	square_note 0, 4, 8, 1378
	square_note 1, 6, 8, 1100
	square_note 0, 5, 8, 1100
	square_note 0, 5, 8, 843
	square_note 1, 4, 8, 843
	square_note 0, 2, 8, 938
	square_note 1, 1, 8, 938
	square_note 1, 0, 8, 0
	sound_ret

Cry_Magmortar_Ch7:
	square_note 2, 1, 1, 1994
	square_note 2, 1, 1, 1935
	square_note 2, 1, 7, 1817
	square_note 2, 1, 4, 1831
	square_note 2, 1, 2, 1942
	square_note 2, 1, 2, 1948
	square_note 2, 1, 7, 1816
	square_note 2, 1, 7, 1930
	square_note 2, 1, 3, 1921
	square_note 2, 1, 0, 1898
	square_note 2, 1, 2, 1943
	square_note 2, 1, 4, 1829
	square_note 2, 1, 7, 1182
	square_note 2, 1, 4, 1456
	square_note 2, 1, 3, 1873
	square_note 2, 1, 4, 1502
	square_note 2, 1, 6, 1466
	square_note 2, 1, 6, 1352
	square_note 2, 2, 3, 1555
	square_note 2, 2, 6, 1113
	square_note 2, 2, 3, 1113
	square_note 2, 3, 9, 1615
	square_note 2, 2, 2, 1466
	square_note 0, 2, 7, 1259
	square_note 1, 3, 7, 1259
	square_note 1, 3, 7, 1338
	square_note 0, 0, 7, 1338
	square_note 1, 0, 2, 1352
	sound_ret

Cry_Magmortar_Ch8:
	noise_note 5, 15, 8, 76
	noise_note 5, 14, 8, 68
	noise_note 5, 15, 4, 68
	noise_note 5, 15, 3, 68
	noise_note 5, 14, 8, 76
	noise_note 5, 11, 2, 76
	noise_note 11, 12, 8, 108
	noise_note 5, 11, 2, 124
	noise_note 5, 8, 2, 124
	noise_note 1, 8, 8, 124
	noise_note 1, 7, 8, 124
	noise_note 1, 6, 8, 124
	noise_note 0, 7, 8, 124
	noise_note 0, 6, 8, 124
	noise_note 1, 5, 8, 124
	noise_note 0, 4, 8, 124
	noise_note 0, 3, 8, 124
	noise_note 1, 2, 1, 124
	noise_note 1, 1, 1, 124
	noise_note 0, 0, 1, 124
	sound_ret
