; Generated by Siren
; Source: 473.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Mamoswine:
	channel_count 4
	channel 5, Cry_Mamoswine_Ch5
	channel 6, Cry_Mamoswine_Ch6
	channel 7, Cry_Mamoswine_Ch7
	channel 8, Cry_Mamoswine_Ch8

Cry_Mamoswine_Ch5:
	duty_cycle_pattern 2, 2, 2, 2
	square_note 2, 9, 8, 204
	square_note 2, 10, 8, 706
	square_note 2, 8, 8, 1915
	square_note 2, 10, 8, 1805
	square_note 2, 14, 8, 1824
	square_note 2, 14, 8, 1834
	square_note 2, 15, 8, 1847
	square_note 2, 11, 8, 1850
	square_note 2, 11, 8, 1166
	square_note 2, 11, 8, 1154
	square_note 2, 13, 8, 1656
	square_note 2, 12, 8, 1651
	square_note 2, 10, 8, 1651
	square_note 2, 10, 8, 1721
	square_note 2, 10, 8, 1742
	square_note 2, 10, 8, 1653
	square_note 2, 11, 8, 1656
	square_note 2, 11, 8, 1652
	square_note 2, 12, 8, 1615
	square_note 2, 11, 8, 1646
	square_note 2, 9, 8, 1629
	square_note 2, 10, 8, 1649
	square_note 2, 10, 8, 419
	square_note 2, 11, 8, 1854
	square_note 2, 10, 8, 1853
	square_note 2, 11, 8, 1621
	square_note 2, 11, 8, 1565
	square_note 2, 10, 8, 1698
	square_note 2, 4, 8, 1506
	square_note 2, 2, 8, 1306
	square_note 2, 1, 8, 1606
	square_note 2, 1, 8, 1626
	square_note 1, 0, 8, 0
	sound_ret

Cry_Mamoswine_Ch6:
	duty_cycle_pattern 1, 2, 1, 2
	square_note 2, 9, 8, 1619
	square_note 2, 11, 8, 1636
	square_note 2, 9, 8, 1805
	square_note 2, 11, 8, 1695
	square_note 2, 15, 8, 1736
	square_note 2, 15, 8, 1748
	square_note 2, 15, 8, 1766
	square_note 2, 11, 8, 1771
	square_note 2, 11, 8, 1848
	square_note 2, 12, 8, 1644
	square_note 2, 14, 8, 1765
	square_note 2, 12, 8, 1908
	square_note 2, 11, 8, 1856
	square_note 2, 11, 8, 1825
	square_note 2, 11, 8, 1856
	square_note 2, 11, 8, 1908
	square_note 2, 12, 8, 1909
	square_note 2, 11, 8, 1830
	square_note 2, 12, 8, 1647
	square_note 2, 12, 8, 1596
	square_note 2, 9, 8, 1571
	square_note 2, 11, 8, 1644
	square_note 2, 11, 8, 1591
	square_note 2, 11, 8, 1776
	square_note 2, 11, 8, 1803
	square_note 2, 12, 8, 1848
	square_note 2, 11, 8, 1795
	square_note 2, 11, 8, 1737
	square_note 2, 4, 8, 1553
	square_note 2, 3, 8, 1337
	square_note 2, 1, 8, 1429
	square_note 2, 1, 8, 1458
	square_note 1, 0, 8, 0
	sound_ret

Cry_Mamoswine_Ch7:
	square_note 2, 1, 7, 1125
	square_note 2, 1, 5, 1376
	square_note 2, 2, 1, 1981
	square_note 2, 1, 6, 1927
	square_note 2, 1, 1, 1936
	square_note 2, 1, 1, 1940
	square_note 2, 1, 1, 1947
	square_note 2, 1, 3, 1950
	square_note 2, 1, 6, 1608
	square_note 2, 1, 3, 1602
	square_note 2, 1, 2, 1852
	square_note 2, 1, 4, 1849
	square_note 2, 1, 3, 1849
	square_note 2, 1, 2, 1885
	square_note 2, 1, 6, 1895
	square_note 2, 1, 2, 1850
	square_note 2, 1, 2, 1852
	square_note 2, 1, 3, 1850
	square_note 2, 1, 6, 1832
	square_note 2, 1, 3, 1847
	square_note 2, 1, 4, 1839
	square_note 2, 1, 3, 1849
	square_note 2, 1, 7, 1235
	square_note 2, 1, 1, 1952
	square_note 2, 1, 1, 1952
	square_note 2, 1, 2, 1835
	square_note 2, 1, 6, 1806
	square_note 2, 1, 2, 1874
	square_note 2, 2, 2, 1778
	square_note 2, 2, 2, 1678
	square_note 2, 2, 1, 1827
	square_note 2, 2, 4, 1837
	square_note 1, 0, 0, 0
	sound_ret

Cry_Mamoswine_Ch8:
	noise_note 5, 13, 6, 84
	noise_note 5, 11, 8, 84
	noise_note 5, 14, 8, 92
	noise_note 5, 14, 1, 92
	noise_note 5, 13, 3, 84
	noise_note 5, 15, 2, 84
	noise_note 5, 13, 3, 68
	noise_note 5, 13, 8, 92
	noise_note 5, 13, 5, 92
	noise_note 5, 15, 2, 108
	noise_note 5, 13, 3, 92
	noise_note 5, 11, 8, 92
	noise_note 5, 11, 8, 92
	noise_note 5, 9, 2, 92
	noise_note 5, 6, 1, 108
	noise_note 5, 1, 8, 108
	noise_note 1, 0, 8, 108
	sound_ret
