; Generated by Siren
; Source: 458.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Mantyke:
	channel_count 3
	channel 5, Cry_Mantyke_Ch5
	channel 6, Cry_Mantyke_Ch6
	channel 8, Cry_Mantyke_Ch8

Cry_Mantyke_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 2, 8, 1550
	duty_cycle 2
	square_note 0, 4, 8, 1589
	duty_cycle 1
	square_note 0, 6, 8, 1449
	duty_cycle 2
	square_note 0, 7, 8, 1563
	square_note 0, 11, 8, 1656
	square_note 0, 13, 8, 1684
	square_note 0, 13, 8, 1567
	duty_cycle 3
	square_note 0, 9, 8, 1514
	duty_cycle 1
	square_note 0, 13, 8, 1518
	square_note 0, 11, 8, 1563
	duty_cycle 2
	square_note 0, 13, 8, 1528
	duty_cycle 3
	square_note 0, 12, 8, 1493
	duty_cycle 2
	square_note 0, 8, 8, 1656
	square_note 0, 13, 8, 1570
	square_note 0, 13, 8, 1658
	square_note 0, 12, 8, 1959
	duty_cycle 3
	square_note 0, 10, 8, 1954
	duty_cycle 0
	square_note 0, 10, 8, 1877
	square_note 0, 9, 8, 1887
	duty_cycle 3
	square_note 0, 11, 8, 1537
	duty_cycle 2
	square_note 0, 10, 8, 1963
	square_note 0, 8, 8, 1952
	square_note 0, 5, 8, 1956
	square_note 0, 4, 8, 1954
	square_note 0, 4, 8, 1950
	square_note 0, 3, 8, 1953
	square_note 0, 2, 8, 1962
	square_note 0, 0, 8, 0
	sound_ret

Cry_Mantyke_Ch6:
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 1, 8, 1611
	square_note 0, 1, 8, 1428
	duty_cycle 0
	square_note 0, 2, 8, 1532
	duty_cycle 2
	square_note 0, 2, 8, 1508
	duty_cycle 3
	square_note 0, 3, 8, 1614
	duty_cycle 2
	square_note 0, 2, 8, 1726
	square_note 0, 4, 8, 1687
	duty_cycle 0
	square_note 0, 2, 8, 1581
	duty_cycle 2
	square_note 0, 3, 8, 1586
	square_note 0, 3, 8, 1642
	square_note 0, 3, 8, 1465
	square_note 0, 3, 8, 1421
	duty_cycle 3
	square_note 0, 2, 8, 1614
	duty_cycle 2
	square_note 0, 3, 8, 1703
	square_note 0, 4, 8, 1703
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 0
	square_note 0, 3, 8, 1799
	square_note 0, 2, 8, 1776
	duty_cycle 2
	square_note 0, 2, 8, 1836
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 0, 1, 8, 1888
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 1, 8, 1874
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Mantyke_Ch8:
	noise_note 2, 0, 8, 75
	noise_note 3, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 3, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 5, 1, 8, 75
	noise_note 5, 0, 8, 75
	sound_ret
