; Generated by Siren
; Source: 439.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Mime_Jr:
	channel_count 4
	channel 5, Cry_Mime_Jr_Ch5
	channel 6, Cry_Mime_Jr_Ch6
	channel 7, Cry_Mime_Jr_Ch7
	channel 8, Cry_Mime_Jr_Ch8

Cry_Mime_Jr_Ch5:
	duty_cycle 0
	square_note 0, 15, 8, 1923
	duty_cycle 1
	square_note 1, 15, 8, 1923
	duty_cycle 0
	square_note 1, 15, 8, 1827
	duty_cycle 1
	square_note 0, 14, 8, 1808
	duty_cycle 0
	square_note 0, 2, 8, 1865
	duty_cycle 2
	square_note 0, 15, 8, 1876
	duty_cycle 1
	square_note 0, 15, 8, 1889
	duty_cycle 3
	square_note 0, 15, 8, 1903
	duty_cycle 1
	square_note 0, 15, 8, 1897
	square_note 0, 15, 8, 1892
	square_note 0, 14, 8, 1942
	duty_cycle 0
	square_note 0, 15, 8, 1971
	square_note 0, 15, 8, 1969
	duty_cycle 2
	square_note 0, 15, 8, 2008
	square_note 0, 15, 8, 1946
	square_note 0, 15, 8, 1944
	square_note 0, 15, 8, 1947
	square_note 0, 15, 8, 1959
	square_note 0, 7, 8, 1960
	duty_cycle 0
	square_note 0, 1, 8, 1969
	duty_cycle 2
	square_note 0, 8, 8, 1946
	square_note 0, 15, 8, 1944
	square_note 0, 15, 8, 1947
	square_note 0, 13, 8, 1959
	square_note 0, 5, 8, 1960
	duty_cycle 0
	square_note 0, 1, 8, 1969
	duty_cycle 2
	square_note 0, 6, 8, 1946
	square_note 0, 11, 8, 1944
	square_note 0, 11, 8, 1947
	square_note 0, 8, 8, 1959
	square_note 0, 2, 8, 1960
	square_note 0, 1, 8, 1959
	square_note 0, 2, 8, 1946
	square_note 0, 5, 8, 1945
	square_note 0, 5, 8, 1947
	square_note 0, 2, 8, 1963
	square_note 0, 1, 8, 1960
	square_note 0, 0, 8, 0
	sound_ret

Cry_Mime_Jr_Ch6:
	square_note 2, 0, 8, 0
	duty_cycle 2
	square_note 0, 12, 8, 1993
	square_note 0, 13, 8, 1993
	square_note 3, 0, 8, 0
	square_note 0, 15, 8, 1972
	square_note 0, 13, 8, 1977
	square_note 5, 0, 8, 0
	square_note 0, 12, 8, 1980
	square_note 0, 10, 8, 1979
	square_note 0, 13, 8, 1951
	square_note 0, 3, 8, 1953
	duty_cycle 3
	square_note 0, 2, 8, 1959
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 12, 8, 1980
	square_note 0, 8, 8, 1979
	square_note 0, 12, 8, 1952
	square_note 0, 3, 8, 1954
	square_note 1, 0, 8, 0
	square_note 0, 10, 8, 1980
	square_note 0, 8, 8, 1979
	square_note 3, 0, 8, 0
	square_note 0, 3, 8, 1980
	square_note 0, 3, 8, 1979
	square_note 2, 0, 8, 0
	sound_ret

Cry_Mime_Jr_Ch7:
	square_note 0, 1, 1, 2032
	square_note 0, 1, 1, 2016
	square_note 0, 1, 1, 1987
	square_note 0, 1, 0, 1988
	square_note 0, 1, 7, 1943
	square_note 0, 1, 3, 1984
	square_note 0, 3, 3, 1952
	square_note 0, 1, 2, 1958
	square_note 0, 1, 1, 2020
	square_note 0, 1, 0, 1968
	square_note 0, 1, 0, 1977
	square_note 0, 1, 0, 2005
	square_note 0, 1, 0, 1994
	square_note 0, 1, 2, 2010
	square_note 0, 1, 1, 2009
	square_note 0, 1, 1, 2028
	square_note 0, 1, 0, 1998
	square_note 0, 1, 1, 2013
	square_note 0, 1, 1, 1996
	square_note 0, 1, 1, 2006
	square_note 0, 2, 1, 2006
	square_note 0, 3, 1, 2005
	square_note 0, 2, 1, 1996
	square_note 0, 1, 1, 2013
	square_note 0, 1, 1, 1996
	square_note 0, 1, 1, 2006
	square_note 0, 2, 1, 2006
	square_note 0, 3, 1, 2006
	square_note 0, 2, 0, 1998
	square_note 0, 1, 1, 2013
	square_note 0, 1, 1, 1996
	square_note 0, 2, 1, 2006
	square_note 0, 3, 1, 2006
	square_note 0, 3, 0, 2005
	square_note 0, 3, 0, 1998
	square_note 0, 2, 1, 1995
	square_note 0, 2, 1, 1996
	square_note 1, 3, 1, 2005
	square_note 0, 0, 0, 0
	sound_ret

Cry_Mime_Jr_Ch8:
	noise_note 0, 0, 8, 0
	noise_note 0, 14, 8, 100
	noise_note 0, 15, 8, 100
	noise_note 0, 13, 8, 100
	noise_note 0, 11, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 2, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 0, 8, 8, 100
	noise_note 0, 14, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 10, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 9, 8, 100
	noise_note 0, 12, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 4, 8, 100
	noise_note 0, 7, 8, 100
	noise_note 0, 6, 8, 100
	noise_note 0, 5, 8, 100
	noise_note 0, 1, 8, 100
	noise_note 0, 3, 8, 100
	noise_note 0, 4, 8, 100
	noise_note 0, 6, 8, 100
	noise_note 0, 5, 8, 100
	noise_note 0, 4, 8, 100
	noise_note 0, 1, 8, 100
	noise_note 0, 2, 8, 100
	noise_note 0, 3, 8, 100
	noise_note 0, 4, 8, 100
	noise_note 0, 3, 8, 100
	noise_note 0, 2, 8, 100
	noise_note 0, 0, 8, 0
	noise_note 0, 1, 8, 100
	noise_note 2, 2, 8, 100
	noise_note 1, 0, 8, 0
	sound_ret
