; Generated by Siren
; Source: 429.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Mismagius:
	channel_count 3
	channel 5, Cry_Mismagius_Ch5
	channel 6, Cry_Mismagius_Ch6
	channel 8, Cry_Mismagius_Ch8

Cry_Mismagius_Ch5:
	duty_cycle 2
	square_note 0, 1, 8, 1913
	square_note 0, 4, 8, 1915
	duty_cycle 0
	square_note 0, 7, 8, 1512
	square_note 0, 10, 8, 1531
	duty_cycle 2
	square_note 0, 12, 8, 1517
	square_note 0, 13, 8, 1521
	square_note 0, 13, 8, 1534
	square_note 0, 13, 8, 1507
	square_note 0, 13, 8, 1512
	duty_cycle 1
	square_note 0, 13, 8, 1547
	duty_cycle 2
	square_note 0, 13, 8, 1539
	square_note 0, 13, 8, 1547
	square_note 0, 11, 8, 1560
	square_note 0, 12, 8, 1507
	duty_cycle 1
	square_note 0, 12, 8, 1887
	square_note 0, 9, 8, 1925
	duty_cycle 0
	square_note 0, 9, 8, 1799
	duty_cycle 1
	square_note 0, 8, 8, 1805
	duty_cycle 0
	square_note 0, 9, 8, 1816
	square_note 0, 8, 8, 1822
	duty_cycle 2
	square_note 0, 8, 8, 1827
	duty_cycle 1
	square_note 0, 10, 8, 1827
	square_note 0, 9, 8, 1818
	duty_cycle 0
	square_note 0, 9, 8, 1560
	duty_cycle 2
	square_note 0, 12, 8, 1543
	duty_cycle 1
	square_note 0, 13, 8, 1889
	duty_cycle 2
	square_note 0, 13, 8, 1492
	square_note 0, 13, 8, 1507
	square_note 0, 13, 8, 1498
	square_note 0, 11, 8, 1825
	square_note 0, 9, 8, 1517
	duty_cycle 1
	square_note 0, 9, 8, 1853
	square_note 0, 9, 8, 1822
	duty_cycle 2
	square_note 0, 9, 8, 1829
	duty_cycle 1
	square_note 0, 10, 8, 1877
	square_note 0, 10, 8, 1882
	square_note 0, 9, 8, 1883
	duty_cycle 0
	square_note 0, 12, 8, 1534
	square_note 0, 12, 8, 1418
	duty_cycle 2
	square_note 0, 12, 8, 1466
	square_note 0, 13, 8, 1543
	duty_cycle 0
	square_note 0, 12, 8, 1563
	duty_cycle 1
	square_note 0, 10, 8, 1897
	duty_cycle 2
	square_note 0, 8, 8, 1472
	square_note 0, 13, 8, 1418
	square_note 1, 13, 8, 1411
	square_note 0, 12, 8, 1411
	duty_cycle 1
	square_note 0, 11, 8, 1455
	duty_cycle 0
	square_note 0, 10, 8, 1521
	duty_cycle 2
	square_note 0, 5, 8, 1886
	square_note 0, 4, 8, 1766
	duty_cycle 1
	square_note 0, 4, 8, 1492
	duty_cycle 2
	square_note 0, 8, 8, 1449
	duty_cycle 1
	square_note 0, 10, 8, 1449
	duty_cycle 2
	square_note 0, 10, 8, 1424
	square_note 0, 10, 8, 1418
	square_note 0, 12, 8, 1424
	square_note 0, 13, 8, 1472
	square_note 0, 7, 8, 1555
	square_note 0, 5, 8, 1534
	square_note 0, 5, 8, 1563
	square_note 0, 7, 8, 1488
	duty_cycle 1
	square_note 0, 6, 8, 1405
	duty_cycle 2
	square_note 0, 5, 8, 1534
	square_note 0, 6, 8, 1492
	square_note 0, 3, 8, 1517
	square_note 0, 2, 8, 1747
	duty_cycle 0
	square_note 0, 2, 8, 1786
	duty_cycle 2
	square_note 0, 2, 8, 1904
	square_note 0, 1, 8, 1534
	square_note 0, 1, 8, 1539
	square_note 0, 1, 8, 1563
	square_note 0, 1, 8, 1512
	square_note 0, 1, 8, 1543
	square_note 0, 1, 8, 1498
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Mismagius_Ch6:
	duty_cycle 1
	square_note 0, 1, 8, 1892
	duty_cycle 2
	square_note 0, 1, 8, 1870
	duty_cycle 1
	square_note 0, 3, 8, 1874
	duty_cycle 2
	square_note 0, 4, 8, 1872
	square_note 0, 4, 8, 1575
	square_note 0, 4, 8, 1578
	square_note 0, 4, 8, 1466
	square_note 0, 4, 8, 1567
	square_note 0, 4, 8, 1571
	square_note 0, 4, 8, 1482
	square_note 0, 4, 8, 1472
	square_note 0, 4, 8, 1482
	duty_cycle 0
	square_note 0, 4, 8, 1817
	square_note 0, 4, 8, 1813
	square_note 0, 4, 8, 1808
	duty_cycle 1
	square_note 0, 3, 8, 1882
	duty_cycle 2
	square_note 0, 2, 8, 1881
	duty_cycle 1
	square_note 0, 1, 8, 1885
	duty_cycle 2
	square_note 0, 4, 8, 1853
	duty_cycle 1
	square_note 0, 4, 8, 1860
	square_note 1, 4, 8, 1862
	duty_cycle 0
	square_note 0, 3, 8, 1854
	duty_cycle 1
	square_note 0, 4, 8, 1849
	duty_cycle 2
	square_note 0, 5, 8, 1849
	duty_cycle 1
	square_note 0, 4, 8, 1852
	duty_cycle 2
	square_note 0, 4, 8, 1823
	duty_cycle 0
	square_note 0, 4, 8, 1827
	duty_cycle 2
	square_note 0, 4, 8, 1831
	square_note 0, 4, 8, 1862
	square_note 0, 4, 8, 1857
	duty_cycle 0
	square_note 0, 3, 8, 1816
	duty_cycle 1
	square_note 0, 4, 8, 1860
	duty_cycle 2
	square_note 0, 4, 8, 1864
	square_note 0, 4, 8, 1846
	square_note 0, 3, 8, 1851
	duty_cycle 0
	square_note 0, 2, 8, 1852
	duty_cycle 1
	square_note 0, 4, 8, 1879
	square_note 0, 5, 8, 1874
	duty_cycle 2
	square_note 0, 4, 8, 1877
	duty_cycle 1
	square_note 0, 4, 8, 1882
	square_note 0, 4, 8, 1891
	duty_cycle 2
	square_note 0, 4, 8, 1868
	square_note 0, 3, 8, 1539
	square_note 0, 4, 8, 1312
	square_note 1, 4, 8, 1492
	square_note 0, 4, 8, 1303
	square_note 0, 4, 8, 1362
	duty_cycle 0
	square_note 0, 4, 8, 1449
	duty_cycle 2
	square_note 0, 1, 8, 1770
	duty_cycle 0
	square_note 0, 1, 8, 1649
	square_note 0, 1, 8, 1411
	duty_cycle 2
	square_note 0, 3, 8, 1354
	square_note 0, 4, 8, 1354
	square_note 0, 3, 8, 1321
	square_note 0, 3, 8, 1312
	square_note 0, 4, 8, 1312
	square_note 0, 4, 8, 1543
	square_note 0, 4, 8, 1449
	square_note 0, 1, 8, 1466
	square_note 0, 1, 8, 1503
	square_note 0, 3, 8, 1551
	square_note 0, 1, 8, 1488
	square_note 0, 1, 8, 1362
	square_note 0, 1, 8, 1411
	square_note 0, 1, 8, 1578
	square_note 0, 1, 8, 1543
	square_note 0, 1, 8, 1716
	duty_cycle 0
	square_note 1, 1, 8, 1918
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Mismagius_Ch8:
	noise_note 0, 0, 8, 75
	noise_note 6, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 3, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 3, 2, 8, 75
	noise_note 12, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 11, 1, 8, 75
	noise_note 1, 0, 8, 75
	noise_note 9, 1, 8, 75
	noise_note 0, 0, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 10, 0, 8, 75
	sound_ret
