; Generated by Siren
; Source: 446.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Munchlax:
	channel_count 4
	channel 5, Cry_Munchlax_Ch5
	channel 6, Cry_Munchlax_Ch6
	channel 7, Cry_Munchlax_Ch7
	channel 8, Cry_Munchlax_Ch8

Cry_Munchlax_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 13, 8, 323
	square_note 2, 14, 8, 176
	square_note 2, 14, 8, 654
	square_note 2, 11, 8, 683
	square_note 2, 12, 8, 737
	square_note 2, 12, 8, 368
	square_note 2, 14, 8, 683
	square_note 2, 13, 8, 176
	square_note 0, 12, 8, 559
	square_note 0, 10, 8, 559
	square_note 0, 9, 8, 559
	square_note 0, 4, 8, 559
	square_note 0, 3, 8, 559
	square_note 0, 2, 8, 559
	square_note 0, 1, 8, 62
	square_note 0, 0, 8, 0
	sound_ret

Cry_Munchlax_Ch6:
	duty_cycle_pattern 0, 2, 0, 2
	square_note 2, 12, 8, 1617
	square_note 2, 13, 8, 0
	square_note 2, 13, 8, 1566
	square_note 2, 9, 8, 1583
	square_note 2, 11, 8, 1583
	square_note 2, 12, 8, 1739
	square_note 2, 13, 8, 1722
	square_note 2, 13, 8, 0
	square_note 0, 11, 8, 1737
	square_note 0, 9, 8, 1737
	square_note 0, 8, 8, 1737
	square_note 1, 3, 8, 1658
	square_note 0, 2, 8, 1658
	square_note 0, 1, 8, 711
	square_note 0, 0, 8, 0
	sound_ret

Cry_Munchlax_Ch7:
	square_note 2, 1, 4, 1186
	square_note 2, 1, 4, 1112
	square_note 2, 1, 5, 1351
	square_note 2, 1, 5, 1366
	square_note 2, 1, 8, 1393
	square_note 2, 1, 7, 1208
	square_note 2, 1, 7, 1366
	square_note 2, 1, 1, 1112
	square_note 1, 1, 9, 1304
	square_note 0, 2, 9, 1304
	square_note 2, 3, 9, 1304
	square_note 1, 0, 8, 1055
	sound_ret

Cry_Munchlax_Ch8:
	noise_note 5, 12, 8, 108
	noise_note 5, 11, 1, 100
	noise_note 5, 11, 8, 100
	noise_note 5, 12, 8, 100
	noise_note 0, 10, 1, 100
	noise_note 0, 9, 1, 100
	noise_note 0, 7, 1, 100
	noise_note 0, 6, 1, 100
	noise_note 0, 4, 1, 100
	noise_note 0, 3, 1, 100
	noise_note 0, 1, 1, 100
	noise_note 0, 0, 1, 100
	sound_ret
