; Generated by Siren
; Source: 904.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Overqwil:
	channel_count 3
	channel 5, Cry_Overqwil_Ch5
	channel 6, Cry_Overqwil_Ch6
	channel 8, Cry_Overqwil_Ch8

Cry_Overqwil_Ch5:
	duty_cycle 1
	square_note 0, 13, 8, 1595
	duty_cycle 0
	square_note 0, 13, 8, 1228
	duty_cycle 1
	square_note 0, 13, 8, 1889
	square_note 0, 13, 8, 1394
	duty_cycle 0
	square_note 0, 13, 8, 1693
	duty_cycle 1
	square_note 0, 13, 8, 1556
	duty_cycle 0
	square_note 0, 13, 8, 1175
	square_note 0, 13, 8, 1602
	duty_cycle 1
	square_note 0, 13, 8, 1614
	square_note 0, 13, 8, 1175
	square_note 0, 13, 8, 1860
	square_note 0, 13, 8, 1164
	square_note 0, 13, 8, 1370
	square_note 0, 13, 8, 1479
	duty_cycle 0
	square_note 0, 13, 8, 1164
	duty_cycle 1
	square_note 0, 13, 8, 1175
	square_note 0, 13, 8, 1357
	duty_cycle 0
	square_note 0, 13, 8, 1721
	duty_cycle 1
	square_note 0, 13, 8, 1701
	duty_cycle 0
	square_note 0, 13, 8, 1256
	duty_cycle 1
	square_note 0, 13, 8, 1646
	duty_cycle 0
	square_note 0, 13, 8, 1680
	duty_cycle 1
	square_note 0, 11, 8, 1657
	square_note 0, 11, 8, 1844
	square_note 0, 11, 8, 1854
	square_note 0, 9, 8, 1791
	square_note 0, 6, 8, 1904
	square_note 0, 5, 8, 1899
	square_note 0, 4, 8, 1915
	square_note 0, 2, 8, 1917
	square_note 0, 1, 8, 1915
	square_note 0, 0, 8, 0
	sound_ret

Cry_Overqwil_Ch6:
	duty_cycle 0
	square_note 0, 6, 8, 1763
	duty_cycle 1
	square_note 0, 7, 8, 1799
	duty_cycle 0
	square_note 0, 8, 8, 1851
	duty_cycle 1
	square_note 0, 5, 8, 1827
	square_note 0, 8, 8, 1810
	duty_cycle 0
	square_note 0, 10, 8, 1841
	duty_cycle 1
	square_note 0, 8, 8, 1705
	duty_cycle 0
	square_note 0, 7, 8, 1725
	duty_cycle 1
	square_note 0, 6, 8, 1773
	duty_cycle 0
	square_note 0, 5, 8, 1769
	duty_cycle 1
	square_note 0, 5, 8, 1836
	square_note 0, 10, 8, 1832
	duty_cycle 0
	square_note 0, 5, 8, 1831
	duty_cycle 1
	square_note 0, 7, 8, 1586
	square_note 0, 6, 8, 1542
	square_note 0, 6, 8, 1549
	square_note 0, 6, 8, 1500
	square_note 0, 5, 8, 1580
	square_note 0, 7, 8, 1586
	square_note 0, 6, 8, 1673
	square_note 0, 8, 8, 1784
	square_note 0, 5, 8, 1790
	square_note 0, 7, 8, 1808
	square_note 0, 7, 8, 1891
	square_note 0, 6, 8, 1888
	square_note 0, 4, 8, 1906
	square_note 0, 4, 8, 1905
	square_note 0, 3, 8, 1895
	square_note 0, 3, 8, 1890
	square_note 0, 1, 8, 1887
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Overqwil_Ch8:
	noise_note 9, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 1, 8, 8, 75
	noise_note 0, 4, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 2, 9, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 7, 8, 75
	noise_note 0, 8, 8, 75
	noise_note 0, 9, 8, 75
	noise_note 0, 6, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 1, 0, 8, 75
	sound_ret
