; Generated by Siren
; Source: 474.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Porygon_Z:
	channel_count 4
	channel 5, Cry_Porygon_Z_Ch5
	channel 6, Cry_Porygon_Z_Ch6
	channel 7, Cry_Porygon_Z_Ch7
	channel 8, Cry_Porygon_Z_Ch8

Cry_Porygon_Z_Ch5:
	duty_cycle 2
	square_note 0, 4, 8, 1990
	square_note 0, 4, 8, 1991
	square_note 2, 4, 8, 1992
	square_note 0, 5, 8, 1991
	square_note 0, 7, 8, 1792
	square_note 0, 5, 8, 1991
	square_note 0, 5, 8, 1989
	square_note 0, 4, 8, 1992
	square_note 0, 5, 8, 1992
	square_note 0, 7, 8, 1992
	square_note 1, 5, 8, 1992
	square_note 0, 15, 8, 1990
	square_note 0, 5, 8, 1990
	square_note 0, 5, 8, 1992
	square_note 0, 4, 8, 1961
	square_note 0, 4, 8, 1937
	square_note 0, 3, 8, 1938
	square_note 0, 3, 8, 1945
	square_note 0, 5, 8, 1946
	duty_cycle 0
	square_note 0, 5, 8, 1628
	duty_cycle 1
	square_note 0, 5, 8, 1628
	duty_cycle 2
	square_note 0, 5, 8, 1963
	duty_cycle 3
	square_note 0, 5, 8, 1943
	duty_cycle 1
	square_note 1, 5, 8, 1943
	duty_cycle 2
	square_note 0, 4, 8, 2010
	square_note 1, 3, 8, 2010
	square_note 0, 3, 8, 1599
	duty_cycle 1
	square_note 0, 4, 8, 1840
	duty_cycle 2
	square_note 0, 4, 8, 1839
	square_note 0, 5, 8, 1839
	duty_cycle 3
	square_note 0, 5, 8, 1611
	duty_cycle 2
	square_note 0, 3, 8, 1876
	square_note 0, 7, 8, 1870
	square_note 0, 5, 8, 1877
	square_note 1, 3, 8, 1800
	square_note 0, 1, 8, 1871
	square_note 0, 1, 8, 2010
	square_note 0, 1, 8, 1876
	square_note 0, 1, 8, 1875
	square_note 0, 1, 8, 1870
	square_note 1, 1, 8, 2010
	duty_cycle 0
	square_note 0, 1, 8, 1972
	duty_cycle 2
	square_note 0, 3, 8, 2010
	square_note 1, 1, 8, 2010
	square_note 2, 0, 8, 0
	duty_cycle 1
	square_note 0, 1, 8, 1703
	duty_cycle 0
	square_note 0, 1, 8, 1872
	duty_cycle 2
	square_note 0, 1, 8, 2013
	square_note 3, 0, 8, 0
	square_note 0, 1, 8, 1717
	square_note 0, 1, 8, 1731
	square_note 4, 0, 8, 0
	square_note 0, 1, 8, 1733
	square_note 0, 3, 8, 2011
	square_note 0, 1, 8, 1714
	square_note 0, 1, 8, 1730
	duty_cycle 0
	square_note 0, 1, 8, 1727
	duty_cycle 2
	square_note 0, 1, 8, 2013
	square_note 0, 1, 8, 1717
	square_note 0, 1, 8, 1734
	square_note 0, 1, 8, 1722
	square_note 1, 1, 8, 2013
	square_note 4, 0, 8, 0
	sound_ret

Cry_Porygon_Z_Ch6:
	square_note 26, 0, 8, 0
	duty_cycle 2
	square_note 1, 15, 8, 1992
	square_note 0, 9, 8, 1992
	square_note 0, 6, 8, 1992
	square_note 11, 0, 8, 0
	square_note 2, 4, 8, 2010
	square_note 24, 0, 8, 0
	square_note 2, 2, 8, 2013
	square_note 0, 0, 8, 0
	square_note 1, 4, 8, 2013
	square_note 0, 2, 8, 2013
	square_note 6, 0, 8, 0
	sound_ret

Cry_Porygon_Z_Ch7:
	square_note 0, 1, 2, 2019
	square_note 4, 1, 1, 2020
	square_note 0, 1, 3, 1920
	square_note 0, 1, 1, 2020
	square_note 0, 1, 1, 2019
	square_note 4, 1, 1, 2020
	square_note 0, 0, 0, 0
	square_note 0, 1, 2, 2019
	square_note 0, 1, 1, 2020
	square_note 0, 1, 1, 2005
	square_note 1, 1, 1, 1993
	square_note 0, 2, 3, 1996
	square_note 0, 1, 1, 1997
	square_note 0, 1, 7, 1838
	square_note 0, 1, 6, 1838
	square_note 0, 1, 1, 2006
	square_note 1, 1, 0, 1996
	square_note 0, 1, 1, 1996
	square_note 1, 1, 1, 2029
	square_note 0, 2, 1, 2029
	square_note 0, 1, 8, 1824
	square_note 0, 1, 0, 1944
	square_note 1, 1, 3, 1944
	square_note 0, 0, 0, 0
	square_note 0, 1, 1, 1962
	square_note 0, 1, 1, 1959
	square_note 0, 1, 1, 1963
	square_note 1, 2, 1, 1924
	square_note 0, 2, 3, 1960
	square_note 0, 2, 1, 2029
	square_note 1, 2, 4, 1962
	square_note 0, 2, 1, 1959
	square_note 1, 3, 1, 2029
	square_note 0, 3, 6, 2010
	square_note 0, 2, 1, 2029
	square_note 3, 3, 1, 2029
	square_note 0, 3, 3, 1874
	square_note 0, 2, 4, 1876
	square_note 0, 3, 4, 1960
	square_note 0, 3, 1, 2031
	square_note 0, 3, 4, 1887
	square_note 0, 3, 4, 1892
	square_note 0, 3, 3, 1874
	square_note 0, 3, 2, 1859
	square_note 0, 2, 4, 1883
	square_note 0, 2, 4, 1890
	square_note 1, 3, 1, 2031
	square_note 0, 3, 3, 1863
	square_note 0, 3, 1, 1872
	square_note 0, 3, 8, 1896
	square_note 0, 2, 8, 1891
	square_note 0, 2, 1, 2030
	square_note 0, 3, 4, 1881
	square_note 0, 2, 4, 1889
	square_note 0, 3, 4, 1888
	square_note 0, 3, 1, 2031
	square_note 0, 3, 4, 1883
	square_note 0, 2, 1, 1891
	square_note 0, 3, 4, 1885
	square_note 2, 3, 1, 2031
	square_note 0, 3, 1, 1875
	square_note 0, 3, 9, 1889
	square_note 0, 3, 9, 1865
	square_note 0, 0, 0, 0
	sound_ret

Cry_Porygon_Z_Ch8:
	noise_note 0, 15, 8, 92
	noise_note 2, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 1, 15, 8, 92
	noise_note 1, 10, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 1, 10, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 0, 15, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 2, 5, 8, 92
	noise_note 3, 10, 8, 92
	noise_note 0, 15, 8, 92
	noise_note 1, 10, 8, 92
	noise_note 1, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 0, 5, 8, 92
	noise_note 0, 15, 8, 92
	noise_note 5, 5, 8, 92
	noise_note 0, 0, 8, 0
	noise_note 1, 5, 8, 92
	noise_note 1, 0, 8, 0
	noise_note 3, 5, 8, 92
	noise_note 0, 0, 8, 0
	noise_note 2, 5, 8, 92
	noise_note 0, 0, 8, 0
	noise_note 3, 5, 8, 92
	noise_note 2, 0, 8, 0
	noise_note 3, 5, 8, 92
	noise_note 2, 0, 8, 0
	noise_note 0, 5, 8, 92
	noise_note 0, 10, 8, 92
	noise_note 9, 5, 8, 92
	noise_note 3, 0, 8, 0
	sound_ret
