; Generated by Siren
; Source: 464.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Rhyperior:
	channel_count 4
	channel 5, Cry_Rhyperior_Ch5
	channel 6, Cry_Rhyperior_Ch6
	channel 7, Cry_Rhyperior_Ch7
	channel 8, Cry_Rhyperior_Ch8

Cry_Rhyperior_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 15, 8, 1764
	square_note 2, 15, 8, 1781
	square_note 2, 14, 8, 1483
	square_note 2, 14, 8, 1775
	square_note 2, 14, 8, 1532
	square_note 2, 14, 8, 0
	square_note 2, 13, 8, 1674
	square_note 2, 14, 8, 1268
	square_note 2, 15, 8, 1775
	square_note 2, 14, 8, 1774
	square_note 2, 13, 8, 1773
	square_note 2, 14, 8, 1758
	square_note 2, 14, 8, 120
	square_note 2, 14, 8, 1762
	square_note 2, 14, 8, 1768
	square_note 2, 14, 8, 1641
	square_note 2, 15, 8, 1648
	square_note 2, 14, 8, 1909
	square_note 2, 14, 8, 1901
	square_note 2, 14, 8, 0
	square_note 2, 12, 8, 1483
	square_note 1, 5, 8, 1596
	sound_ret

Cry_Rhyperior_Ch6:
	duty_cycle_pattern 0, 1, 0, 1
	square_note 2, 12, 8, 1839
	square_note 2, 12, 8, 1946
	square_note 2, 11, 8, 1914
	square_note 2, 11, 8, 1944
	square_note 2, 11, 8, 1943
	square_note 2, 11, 8, 1784
	square_note 2, 10, 8, 1690
	square_note 2, 11, 8, 1685
	square_note 2, 12, 8, 1682
	square_note 2, 11, 8, 1928
	square_note 2, 11, 8, 1893
	square_note 2, 12, 8, 1661
	square_note 2, 11, 8, 1268
	square_note 2, 11, 8, 1676
	square_note 2, 11, 8, 1811
	square_note 2, 11, 8, 1910
	square_note 2, 12, 8, 1909
	square_note 2, 11, 8, 1874
	square_note 2, 12, 8, 1869
	square_note 2, 12, 8, 1876
	square_note 2, 9, 8, 1620
	square_note 1, 4, 8, 1636
	sound_ret

Cry_Rhyperior_Ch7:
	square_note 2, 2, 3, 1906
	square_note 2, 2, 2, 1915
	square_note 2, 2, 7, 1766
	square_note 2, 2, 3, 1912
	square_note 2, 2, 6, 1790
	square_note 2, 2, 7, 1024
	square_note 2, 2, 7, 1861
	square_note 2, 2, 7, 1658
	square_note 2, 2, 2, 1912
	square_note 2, 2, 6, 1911
	square_note 2, 2, 6, 1911
	square_note 2, 2, 4, 1903
	square_note 2, 2, 7, 1084
	square_note 2, 2, 2, 1905
	square_note 2, 2, 2, 1908
	square_note 2, 2, 5, 1845
	square_note 2, 2, 4, 1848
	square_note 2, 2, 5, 1979
	square_note 2, 2, 1, 1975
	square_note 2, 2, 7, 1024
	square_note 2, 2, 7, 1766
	square_note 1, 3, 3, 1822
	sound_ret

Cry_Rhyperior_Ch8:
	noise_note 5, 14, 3, 92
	noise_note 5, 14, 4, 92
	noise_note 5, 14, 5, 76
	noise_note 5, 14, 4, 68
	noise_note 5, 13, 3, 68
	noise_note 5, 14, 8, 84
	noise_note 5, 14, 8, 84
	noise_note 5, 14, 8, 68
	noise_note 5, 13, 8, 68
	noise_note 5, 13, 5, 92
	noise_note 4, 10, 1, 92
	sound_ret
