; Generated by Siren
; Source: 865.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Sirfetch_d:
	channel_count 4
	channel 5, Cry_Sirfetch_d_Ch5
	channel 6, Cry_Sirfetch_d_Ch6
	channel 7, Cry_Sirfetch_d_Ch7
	channel 8, Cry_Sirfetch_d_Ch8

Cry_Sirfetch_d_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 13, 8, 1609
	square_note 2, 14, 8, 1590
	square_note 2, 15, 8, 1110
	square_note 2, 14, 8, 1868
	square_note 2, 14, 8, 1843
	square_note 2, 13, 8, 360
	square_note 2, 14, 8, 1049
	square_note 2, 14, 8, 1565
	square_note 2, 13, 8, 803
	square_note 2, 12, 8, 1281
	square_note 0, 11, 8, 842
	square_note 0, 10, 8, 842
	square_note 0, 9, 8, 842
	square_note 0, 6, 8, 760
	square_note 0, 5, 8, 760
	square_note 0, 4, 8, 760
	square_note 1, 2, 8, 0
	square_note 0, 1, 8, 0
	square_note 0, 0, 8, 0
	sound_ret

Cry_Sirfetch_d_Ch6:
	duty_cycle_pattern 0, 1, 0, 1
	square_note 2, 14, 8, 1816
	square_note 2, 15, 8, 1658
	square_note 2, 15, 8, 1786
	square_note 2, 15, 8, 1854
	square_note 2, 15, 8, 1824
	square_note 2, 15, 8, 1834
	square_note 2, 15, 8, 1766
	square_note 2, 15, 8, 1858
	square_note 2, 14, 8, 1851
	square_note 2, 12, 8, 1857
	square_note 0, 11, 8, 1854
	square_note 0, 10, 8, 1854
	square_note 0, 9, 8, 1854
	square_note 0, 6, 8, 1590
	square_note 0, 5, 8, 1590
	square_note 0, 4, 8, 1590
	square_note 1, 2, 8, 1654
	square_note 0, 1, 8, 1654
	square_note 0, 0, 8, 0
	sound_ret

Cry_Sirfetch_d_Ch7:
	square_note 2, 1, 1, 1829
	square_note 2, 1, 3, 1820
	square_note 2, 1, 7, 1580
	square_note 2, 1, 1, 1959
	square_note 2, 1, 0, 1946
	square_note 2, 1, 7, 1204
	square_note 2, 1, 5, 1548
	square_note 2, 1, 3, 1807
	square_note 2, 1, 7, 1425
	square_note 2, 1, 7, 1664
	square_note 2, 1, 7, 1445
	square_note 2, 2, 6, 1405
	square_note 0, 3, 7, 861
	square_note 2, 0, 7, 861
	sound_ret

Cry_Sirfetch_d_Ch8:
	noise_note 5, 13, 8, 108
	noise_note 5, 13, 8, 92
	noise_note 5, 14, 8, 92
	noise_note 5, 13, 5, 92
	noise_note 5, 13, 3, 92
	noise_note 0, 10, 2, 92
	noise_note 0, 9, 2, 92
	noise_note 0, 8, 2, 92
	noise_note 0, 7, 2, 92
	noise_note 0, 6, 2, 92
	noise_note 0, 4, 2, 92
	noise_note 0, 2, 1, 92
	noise_note 1, 1, 1, 92
	noise_note 0, 0, 1, 92
	sound_ret
