; Generated by Siren
; Source: 903.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Sneasler:
	channel_count 4
	channel 5, Cry_Sneasler_Ch5
	channel 6, Cry_Sneasler_Ch6
	channel 7, Cry_Sneasler_Ch7
	channel 8, Cry_Sneasler_Ch8

Cry_Sneasler_Ch5:
	duty_cycle_pattern 1, 1, 0, 0
	square_note 2, 14, 8, 0
	square_note 2, 15, 8, 991
	square_note 2, 13, 8, 1320
	square_note 2, 12, 8, 0
	square_note 2, 14, 8, 1801
	square_note 2, 14, 8, 1365
	square_note 2, 13, 8, 1544
	square_note 0, 13, 8, 1967
	square_note 0, 11, 8, 1967
	square_note 0, 9, 8, 1967
	square_note 0, 5, 8, 1880
	square_note 0, 3, 8, 1880
	square_note 0, 2, 8, 1880
	square_note 0, 0, 8, 0
	sound_ret

Cry_Sneasler_Ch6:
	duty_cycle_pattern 0, 1, 0, 1
	square_note 2, 13, 8, 1488
	square_note 2, 15, 8, 1286
	square_note 2, 13, 8, 1040
	square_note 2, 12, 8, 0
	square_note 2, 13, 8, 1839
	square_note 2, 13, 8, 1854
	square_note 2, 13, 8, 1885
	square_note 0, 12, 8, 1939
	square_note 0, 10, 8, 1939
	square_note 0, 8, 8, 1939
	square_note 0, 5, 8, 1945
	square_note 0, 3, 8, 1945
	square_note 0, 2, 8, 1945
	square_note 0, 0, 8, 0
	sound_ret

Cry_Sneasler_Ch7:
	square_note 2, 1, 6, 1024
	square_note 2, 1, 7, 1520
	square_note 2, 1, 4, 1684
	square_note 2, 1, 7, 1024
	square_note 2, 1, 4, 1925
	square_note 2, 1, 8, 1707
	square_note 2, 1, 7, 1796
	square_note 1, 1, 1, 2008
	square_note 0, 2, 1, 2008
	square_note 0, 2, 4, 1964
	square_note 1, 3, 4, 1964
	square_note 0, 0, 4, 1964
	sound_ret

Cry_Sneasler_Ch8:
	noise_note 5, 15, 8, 76
	noise_note 5, 14, 2, 108
	noise_note 5, 15, 5, 76
	noise_note 3, 14, 4, 76
	noise_note 0, 12, 4, 76
	noise_note 0, 9, 4, 76
	noise_note 0, 7, 1, 76
	noise_note 0, 4, 1, 76
	noise_note 0, 2, 1, 76
	noise_note 0, 0, 1, 76
	sound_ret
