; Generated by Siren
; Source: 465.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Tangrowth:
	channel_count 3
	channel 5, Cry_Tangrowth_Ch5
	channel 6, Cry_Tangrowth_Ch6
	channel 8, Cry_Tangrowth_Ch8

Cry_Tangrowth_Ch5:
	square_note 0, 0, 8, 0
	duty_cycle 1
	square_note 1, 1, 8, 813
	duty_cycle 0
	square_note 0, 2, 8, 861
	duty_cycle 2
	square_note 0, 3, 8, 846
	square_note 0, 4, 8, 968
	square_note 0, 4, 8, 1094
	square_note 0, 5, 8, 1133
	square_note 0, 6, 8, 1140
	square_note 1, 7, 8, 1154
	square_note 0, 8, 8, 1221
	square_note 0, 8, 8, 1103
	square_note 0, 9, 8, 1001
	duty_cycle 3
	square_note 0, 10, 8, 813
	duty_cycle 2
	square_note 0, 11, 8, 904
	square_note 0, 12, 8, 956
	square_note 0, 12, 8, 1174
	square_note 0, 12, 8, 1337
	square_note 0, 12, 8, 1330
	square_note 0, 13, 8, 1181
	square_note 0, 13, 8, 846
	square_note 0, 13, 8, 813
	duty_cycle 3
	square_note 0, 13, 8, 813
	duty_cycle 1
	square_note 0, 13, 8, 813
	duty_cycle 2
	square_note 0, 13, 8, 1205
	square_note 0, 10, 8, 1227
	square_note 0, 11, 8, 1293
	square_note 0, 11, 8, 1310
	square_note 0, 13, 8, 1318
	square_note 0, 12, 8, 1314
	duty_cycle 3
	square_note 0, 4, 8, 1357
	duty_cycle 2
	square_note 0, 5, 8, 813
	duty_cycle 3
	square_note 0, 7, 8, 1001
	duty_cycle 2
	square_note 0, 8, 8, 813
	square_note 0, 7, 8, 1298
	square_note 0, 8, 8, 1103
	square_note 0, 6, 8, 1126
	square_note 0, 5, 8, 1205
	duty_cycle 3
	square_note 0, 10, 8, 956
	duty_cycle 2
	square_note 0, 8, 8, 813
	duty_cycle 1
	square_note 0, 4, 8, 1322
	duty_cycle 0
	square_note 0, 3, 8, 813
	duty_cycle 2
	square_note 0, 3, 8, 1330
	duty_cycle 1
	square_note 0, 4, 8, 1354
	duty_cycle 0
	square_note 0, 3, 8, 1350
	duty_cycle 2
	square_note 0, 4, 8, 1591
	square_note 0, 4, 8, 1094
	square_note 0, 6, 8, 1655
	duty_cycle 0
	square_note 0, 6, 8, 1094
	duty_cycle 2
	square_note 0, 8, 8, 1444
	square_note 0, 10, 8, 956
	duty_cycle 1
	square_note 0, 9, 8, 1276
	duty_cycle 0
	square_note 0, 5, 8, 1510
	duty_cycle 1
	square_note 0, 7, 8, 1472
	duty_cycle 2
	square_note 0, 9, 8, 904
	duty_cycle 0
	square_note 0, 9, 8, 1001
	square_note 0, 7, 8, 1086
	duty_cycle 3
	square_note 0, 9, 8, 1668
	duty_cycle 0
	square_note 0, 3, 8, 1289
	duty_cycle 3
	square_note 0, 8, 8, 1060
	duty_cycle 2
	square_note 0, 12, 8, 1704
	square_note 0, 13, 8, 1022
	duty_cycle 3
	square_note 0, 3, 8, 1435
	duty_cycle 2
	square_note 0, 11, 8, 1379
	square_note 1, 9, 8, 1258
	square_note 0, 9, 8, 1464
	square_note 0, 6, 8, 1447
	square_note 0, 6, 8, 1472
	square_note 0, 7, 8, 1470
	square_note 0, 7, 8, 1462
	square_note 0, 8, 8, 1430
	duty_cycle 3
	square_note 0, 6, 8, 1133
	duty_cycle 1
	square_note 0, 2, 8, 1205
	square_note 0, 0, 8, 0
	sound_ret

Cry_Tangrowth_Ch6:
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 1, 8, 1503
	duty_cycle 3
	square_note 0, 1, 8, 1216
	square_note 0, 0, 8, 0
	duty_cycle 2
	square_note 0, 2, 8, 1348
	square_note 0, 2, 8, 1376
	square_note 0, 3, 8, 1376
	square_note 1, 3, 8, 1385
	square_note 0, 4, 8, 1299
	square_note 0, 4, 8, 1353
	duty_cycle 3
	square_note 0, 4, 8, 1293
	duty_cycle 2
	square_note 0, 5, 8, 1416
	square_note 0, 0, 8, 0
	square_note 0, 5, 8, 1268
	square_note 0, 6, 8, 1247
	square_note 0, 6, 8, 1420
	square_note 0, 6, 8, 1409
	square_note 0, 6, 8, 1247
	square_note 0, 5, 8, 1216
	square_note 0, 0, 8, 0
	square_note 0, 6, 8, 1416
	square_note 0, 6, 8, 1274
	square_note 0, 5, 8, 1281
	square_note 0, 5, 8, 1305
	duty_cycle 3
	square_note 0, 5, 8, 1371
	duty_cycle 2
	square_note 0, 5, 8, 1485
	square_note 0, 6, 8, 1491
	square_note 0, 6, 8, 1488
	duty_cycle 0
	square_note 0, 2, 8, 1517
	duty_cycle 2
	square_note 0, 3, 8, 1463
	square_note 0, 3, 8, 1293
	square_note 0, 3, 8, 1466
	duty_cycle 1
	square_note 0, 3, 8, 1380
	duty_cycle 2
	square_note 0, 3, 8, 1353
	square_note 0, 2, 8, 1367
	square_note 0, 2, 8, 1468
	square_note 0, 4, 8, 1480
	duty_cycle 3
	square_note 0, 4, 8, 1191
	duty_cycle 2
	square_note 0, 2, 8, 1299
	duty_cycle 3
	square_note 0, 2, 8, 1466
	duty_cycle 2
	square_note 0, 2, 8, 1735
	duty_cycle 3
	square_note 0, 2, 8, 1716
	duty_cycle 2
	square_note 0, 2, 8, 1741
	square_note 0, 2, 8, 1723
	square_note 0, 2, 8, 1712
	duty_cycle 0
	square_note 0, 3, 8, 1645
	square_note 0, 3, 8, 1568
	duty_cycle 2
	square_note 0, 3, 8, 1578
	duty_cycle 3
	square_note 0, 5, 8, 1544
	duty_cycle 2
	square_note 0, 4, 8, 1566
	duty_cycle 3
	square_note 0, 2, 8, 1531
	duty_cycle 2
	square_note 0, 3, 8, 1656
	duty_cycle 3
	square_note 0, 4, 8, 1706
	duty_cycle 2
	square_note 0, 5, 8, 1735
	square_note 0, 4, 8, 1721
	square_note 0, 6, 8, 1685
	square_note 0, 2, 8, 1704
	duty_cycle 0
	square_note 0, 3, 8, 1706
	square_note 0, 6, 8, 1663
	square_note 0, 6, 8, 1606
	square_note 0, 2, 8, 1590
	duty_cycle 3
	square_note 0, 5, 8, 1581
	square_note 0, 4, 8, 1573
	square_note 0, 5, 8, 1520
	square_note 0, 5, 8, 1594
	duty_cycle 2
	square_note 0, 3, 8, 1642
	duty_cycle 3
	square_note 0, 2, 8, 1666
	duty_cycle 2
	square_note 0, 3, 8, 1548
	square_note 0, 3, 8, 1542
	square_note 0, 4, 8, 1513
	duty_cycle 3
	square_note 0, 3, 8, 1447
	duty_cycle 2
	square_note 0, 1, 8, 1416
	square_note 0, 0, 8, 0
	sound_ret

Cry_Tangrowth_Ch8:
	noise_note 2, 0, 8, 75
	noise_note 6, 1, 8, 75
	noise_note 2, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 4, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 2, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 2, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 2, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 2, 2, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 1, 3, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 0, 2, 8, 75
	noise_note 1, 4, 8, 75
	noise_note 0, 1, 8, 75
	noise_note 1, 2, 8, 75
	noise_note 0, 3, 8, 75
	noise_note 5, 2, 8, 75
	noise_note 1, 1, 8, 75
	noise_note 0, 0, 8, 75
	sound_ret
