; Generated by Siren
; Source: 901-0.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Ursaluna:
	channel_count 4
	channel 5, Cry_Ursaluna_Ch5
	channel 6, Cry_Ursaluna_Ch6
	channel 7, Cry_Ursaluna_Ch7
	channel 8, Cry_Ursaluna_Ch8

Cry_Ursaluna_Ch5:
	duty_cycle_pattern 2, 2, 1, 1
	square_note 2, 13, 8, 1347
	square_note 2, 14, 8, 928
	square_note 2, 15, 8, 1278
	square_note 2, 14, 8, 1269
	square_note 2, 15, 8, 1183
	square_note 2, 14, 8, 1357
	square_note 2, 14, 8, 973
	square_note 2, 14, 8, 1404
	square_note 2, 14, 8, 1191
	square_note 2, 14, 8, 1263
	square_note 0, 12, 8, 1384
	square_note 0, 10, 8, 1384
	square_note 0, 9, 8, 1384
	square_note 0, 4, 8, 1400
	square_note 0, 3, 8, 1400
	square_note 0, 2, 8, 1400
	square_note 0, 2, 8, 1588
	square_note 0, 1, 8, 1588
	square_note 0, 0, 8, 0
	sound_ret

Cry_Ursaluna_Ch6:
	duty_cycle_pattern 0, 3, 0, 3
	square_note 2, 14, 8, 1709
	square_note 2, 15, 8, 1621
	square_note 2, 15, 8, 1671
	square_note 2, 15, 8, 1682
	square_note 2, 15, 8, 1646
	square_note 2, 15, 8, 1642
	square_note 2, 15, 8, 1668
	square_note 2, 15, 8, 1691
	square_note 2, 15, 8, 1561
	square_note 2, 15, 8, 1367
	square_note 0, 12, 8, 1644
	square_note 0, 11, 8, 1644
	square_note 0, 9, 8, 1644
	square_note 1, 4, 8, 1562
	square_note 0, 3, 8, 1562
	square_note 0, 2, 8, 1608
	square_note 0, 1, 8, 1608
	square_note 0, 0, 8, 0
	sound_ret

Cry_Ursaluna_Ch7:
	square_note 2, 1, 4, 1698
	square_note 2, 1, 7, 1489
	square_note 2, 1, 2, 1664
	square_note 2, 1, 4, 1659
	square_note 2, 1, 6, 1616
	square_note 2, 1, 0, 1703
	square_note 2, 1, 7, 1511
	square_note 2, 1, 7, 1727
	square_note 2, 1, 5, 1620
	square_note 2, 1, 6, 1656
	square_note 1, 1, 1, 1717
	square_note 0, 2, 1, 1717
	square_note 2, 3, 1, 1725
	square_note 2, 0, 1, 1819
	sound_ret

Cry_Ursaluna_Ch8:
	noise_note 5, 13, 8, 92
	noise_note 5, 14, 8, 92
	noise_note 5, 15, 4, 92
	noise_note 5, 15, 8, 92
	noise_note 5, 14, 8, 92
	noise_note 0, 12, 1, 92
	noise_note 0, 10, 1, 92
	noise_note 0, 9, 1, 92
	noise_note 0, 7, 1, 92
	noise_note 0, 6, 1, 92
	noise_note 0, 4, 1, 92
	noise_note 1, 1, 8, 92
	noise_note 0, 0, 8, 92
	sound_ret
