; Generated by Siren
; Source: 461.wav
; Play with pitch 0, length 256.
; Approximation with two PSG square channels and PSG noise.

Cry_Weavile:
	channel_count 3
	channel 5, Cry_Weavile_Ch5
	channel 6, Cry_Weavile_Ch6
	channel 8, Cry_Weavile_Ch8

Cry_Weavile_Ch5:
	duty_cycle 2
	square_note 1, 13, 8, 1943
	square_note 1, 15, 8, 1943
	square_note 1, 13, 8, 1973
	duty_cycle 1
	square_note 1, 10, 8, 1959
	square_note 1, 6, 8, 1964
	duty_cycle 2
	square_note 1, 7, 8, 1964
	square_note 1, 8, 8, 1964
	square_note 1, 10, 8, 1964
	square_note 1, 11, 8, 1965
	duty_cycle 1
	square_note 1, 9, 8, 1962
	duty_cycle 2
	square_note 1, 9, 8, 1928
	square_note 1, 13, 8, 1671
	square_note 1, 14, 8, 1312
	square_note 1, 10, 8, 1312
	duty_cycle 3
	square_note 1, 10, 8, 1312
	duty_cycle 2
	square_note 1, 9, 8, 1286
	duty_cycle 3
	square_note 1, 8, 8, 1365
	duty_cycle 2
	square_note 1, 5, 8, 1218
	square_note 1, 0, 8, 0
	sound_ret

Cry_Weavile_Ch6:
	duty_cycle 3
	square_note 1, 11, 8, 1893
	duty_cycle 1
	square_note 1, 15, 8, 1891
	duty_cycle 3
	square_note 1, 11, 8, 1919
	duty_cycle 0
	square_note 1, 11, 8, 1948
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 0, 8, 0
	square_note 1, 9, 8, 1931
	square_note 1, 6, 8, 1919
	duty_cycle 3
	square_note 1, 9, 8, 1964
	duty_cycle 2
	square_note 1, 11, 8, 1911
	square_note 1, 0, 8, 0
	square_note 1, 9, 8, 1858
	square_note 1, 9, 8, 1866
	duty_cycle 1
	square_note 1, 6, 8, 1885
	duty_cycle 3
	square_note 1, 6, 8, 1880
	duty_cycle 2
	square_note 1, 4, 8, 1883
	square_note 1, 0, 8, 0
	sound_ret

Cry_Weavile_Ch8:
	noise_note 1, 11, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 15, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 7, 8, 44
	noise_note 1, 0, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 4, 8, 44
	noise_note 1, 0, 8, 44
	sound_ret
