; Generated by Siren
; Source: 469.wav
; Play with pitch 0, length 256.
; Stock PSG approximation using square, built-in wave and noise channels.

Cry_Yanmega:
	channel_count 4
	channel 5, Cry_Yanmega_Ch5
	channel 6, Cry_Yanmega_Ch6
	channel 7, Cry_Yanmega_Ch7
	channel 8, Cry_Yanmega_Ch8

Cry_Yanmega_Ch5:
	duty_cycle_pattern 2, 2, 1, 1
	square_note 2, 8, 8, 1224
	square_note 2, 11, 8, 1224
	square_note 2, 10, 8, 1356
	square_note 2, 9, 8, 1301
	square_note 2, 14, 8, 1255
	square_note 2, 11, 8, 1111
	square_note 2, 9, 8, 1245
	square_note 2, 14, 8, 1224
	square_note 2, 8, 8, 1178
	square_note 2, 8, 8, 1166
	square_note 2, 11, 8, 1245
	square_note 2, 9, 8, 1334
	square_note 2, 8, 8, 1827
	square_note 2, 8, 8, 1823
	square_note 2, 8, 8, 1816
	square_note 2, 8, 8, 1823
	square_note 2, 8, 8, 1833
	square_note 2, 7, 8, 1837
	square_note 2, 8, 8, 1843
	square_note 5, 8, 8, 1851
	square_note 2, 9, 8, 1868
	square_note 2, 10, 8, 1944
	square_note 2, 10, 8, 1867
	square_note 2, 9, 8, 1871
	square_note 2, 8, 8, 1873
	square_note 0, 6, 8, 1202
	square_note 1, 5, 8, 1202
	square_note 2, 4, 8, 1882
	square_note 2, 3, 8, 1887
	square_note 2, 1, 8, 1889
	square_note 2, 0, 8, 0
	square_note 2, 0, 8, 0
	square_note 4, 0, 8, 0
	sound_ret

Cry_Yanmega_Ch6:
	duty_cycle_pattern 0, 3, 0, 3
	square_note 2, 6, 8, 1143
	square_note 2, 9, 8, 1235
	square_note 2, 8, 8, 1427
	square_note 2, 7, 8, 1360
	square_note 2, 11, 8, 1331
	square_note 2, 9, 8, 1235
	square_note 2, 7, 8, 1103
	square_note 2, 12, 8, 1331
	square_note 2, 6, 8, 1316
	square_note 2, 6, 8, 950
	square_note 2, 9, 8, 1346
	square_note 2, 7, 8, 1849
	square_note 2, 6, 8, 1777
	square_note 2, 6, 8, 1945
	square_note 2, 6, 8, 1915
	square_note 2, 6, 8, 1760
	square_note 2, 6, 8, 1819
	square_note 2, 6, 8, 1785
	square_note 2, 7, 8, 1829
	square_note 2, 6, 8, 1797
	square_note 2, 7, 8, 1853
	square_note 2, 7, 8, 1935
	square_note 2, 8, 8, 1915
	square_note 5, 7, 8, 1945
	square_note 2, 6, 8, 1824
	square_note 0, 5, 8, 1872
	square_note 1, 4, 8, 1872
	square_note 2, 3, 8, 1838
	square_note 2, 2, 8, 1841
	square_note 2, 1, 8, 1863
	square_note 2, 0, 8, 0
	square_note 2, 0, 8, 0
	square_note 4, 0, 8, 0
	sound_ret

Cry_Yanmega_Ch7:
	square_note 2, 3, 1, 1637
	square_note 2, 2, 1, 1637
	square_note 2, 2, 1, 1702
	square_note 2, 3, 1, 1675
	square_note 2, 2, 1, 1652
	square_note 2, 2, 9, 1580
	square_note 2, 2, 1, 1647
	square_note 2, 2, 1, 1637
	square_note 2, 3, 3, 1613
	square_note 2, 3, 3, 1608
	square_note 2, 2, 1, 1647
	square_note 2, 2, 9, 1691
	square_note 2, 3, 4, 1938
	square_note 2, 3, 4, 1936
	square_note 2, 3, 5, 1933
	square_note 2, 3, 4, 1936
	square_note 2, 3, 4, 1941
	square_note 2, 3, 3, 1943
	square_note 2, 3, 4, 1946
	square_note 2, 3, 4, 1949
	square_note 2, 3, 1, 1949
	square_note 2, 2, 2, 1958
	square_note 2, 2, 1, 1996
	square_note 2, 2, 2, 1957
	square_note 2, 3, 2, 1959
	square_note 2, 3, 2, 1961
	square_note 2, 3, 8, 1625
	square_note 2, 3, 1, 1965
	square_note 2, 3, 0, 1968
	square_note 0, 3, 2, 1969
	square_note 1, 0, 2, 1969
	square_note 2, 0, 3, 1967
	square_note 2, 0, 8, 1657
	square_note 4, 0, 0, 0
	sound_ret

Cry_Yanmega_Ch8:
	noise_note 5, 9, 2, 124
	noise_note 5, 8, 8, 124
	noise_note 5, 8, 4, 124
	noise_note 5, 9, 8, 124
	noise_note 5, 7, 3, 124
	noise_note 5, 9, 3, 124
	noise_note 5, 7, 8, 52
	noise_note 5, 6, 6, 52
	noise_note 5, 7, 4, 52
	noise_note 11, 6, 8, 52
	noise_note 5, 5, 8, 52
	noise_note 5, 5, 4, 36
	noise_note 1, 4, 3, 36
	noise_note 3, 3, 3, 36
	noise_note 4, 2, 3, 36
	noise_note 0, 1, 3, 36
	noise_note 10, 0, 8, 52
	sound_ret
