
	add_pic KayPic
	add_pic CalPic
	add_pic FalknerPic
	add_pic BugsyPic
	add_pic WhitneyPic
	add_pic MortyPic
	add_pic ChuckPic
	add_pic JasminePic
	add_pic PrycePic
	add_pic ClairPic
	add_pic WillPic
	add_pic KogaPic
	add_pic BrunoPic
	add_pic KarenPic
	add_pic ChampionPic
	add_pic BrockPic
	add_pic MistyPic
	add_pic LtSurgePic
	add_pic ErikaPic
	add_pic JaninePic
	add_pic SabrinaPic
	add_pic BlainePic
	add_pic BluePic
	add_pic RedPic
	add_pic LeafPic
	add_pic Rival0Pic
	add_pic Rival1Pic
	add_pic Rival2Pic
	add_pic Lyra1Pic
	add_pic Lyra2Pic
	add_pic YoungsterPic
	add_pic BugCatcherPic
	add_pic CamperPic
	add_pic PicnickerPic
	add_pic TwinsPic
	add_pic FisherPic
	add_pic BirdKeeperPic
	add_pic HikerPic
	add_pic GruntmPic
	add_pic GruntfPic
	add_pic PokefanmPic
	add_pic PokefanfPic
	add_pic OfficermPic
	add_pic OfficerfPic
	add_pic PokemaniacPic
	add_pic CosplayerPic
	add_pic SuperNerdPic
	add_pic LassPic
	add_pic BeautyPic
	add_pic BugManiacPic
	add_pic RuinManiacPic
	add_pic FirebreatherPic
	add_pic JugglerPic
	add_pic SchoolboyPic
	add_pic SchoolgirlPic
	add_pic PsychicTPic
	add_pic HexManiacPic
	add_pic SagePic
	add_pic MediumPic
	add_pic KimonoGirlPic
	add_pic ElderPic
	add_pic SrAndJrPic
	add_pic CouplePic
	add_pic GentlemanPic
	add_pic RichBoyPic
	add_pic LadyPic
	add_pic BreederPic
	add_pic BakerPic
	add_pic CowgirlPic
	add_pic SailorPic
	add_pic SwimmermPic
	add_pic SwimmerfPic
	add_pic BurglarPic
	add_pic PIPic
	add_pic ScientistPic
	add_pic BoarderPic
	add_pic SkierPic
	add_pic BlackbeltTPic
	add_pic BattleGirlPic
	add_pic DragonTamerPic
	add_pic EngineerPic
	add_pic TeacherPic
	add_pic GuitaristmPic
	add_pic GuitaristfPic
	add_pic BikerPic
	add_pic RoughneckPic
	add_pic TamerPic
	add_pic ArtistPic
	add_pic AromaLadyPic
	add_pic SightseermPic
	add_pic SightseerfPic
	add_pic CooltrainermPic
	add_pic CooltrainerfPic
	add_pic AceDuoPic
	add_pic VeteranmPic
	add_pic VeteranfPic
	add_pic ProtonPic
	add_pic PetrelPic
	add_pic ArcherPic
	add_pic ArianaPic
	add_pic GiovanniPic
	add_pic ProfOakPic
	add_pic ProfElmPic
	add_pic ProfIvyPic
	add_pic MysticalmanPic
	add_pic KarateKingPic
	add_pic TowerTycoonPic
	add_pic JessieJamesPic
	add_pic LoreleiPic
	add_pic AgathaPic
	add_pic StevenPic
	add_pic CynthiaPic
	add_pic InverPic
	add_pic CherylPic
	add_pic RileyPic
	add_pic BuckPic
	add_pic MarleyPic
	add_pic MiraPic
	add_pic AnabelPic
	add_pic DarachPic
	add_pic CaitlinPic
	add_pic CandelaPic
	add_pic BlanchePic
	add_pic SparkPic
	add_pic FlanneryPic
	add_pic MaylenePic
	add_pic SkylaPic
	add_pic ValeriePic
	add_pic BillPic
	add_pic YellowPic
	add_pic WalkerPic
	add_pic ImakuniPic
	add_pic LawrencePic
	add_pic ReiPic
	add_pic OmastarFossilPic
	add_pic KabutopsFossilPic
	add_pic AerodactylFossilPic
	add_pic CuboneArmorPic
	add_pic MeteoritePic
	add_pic SilhouettePic
