	db "# Ball@"
	db "Great Ball@"
	db "Ultra Ball@"
	db "Master Ball@"
	db "Safari Ball@"
	db "Level Ball@"
	db "Lure Ball@"
	db "Moon Ball@"
	db "Friend Ball@"
	db "Fast Ball@"
	db "Heavy Ball@"
	db "Love Ball@"
	db "Park Ball@"
	db "Repeat Ball@"
	db "Timer Ball@"
	db "Nest Ball@"
	db "Net Ball@"
	db "Dive Ball@"
	db "Luxury Ball@"
	db "Heal Ball@"
	db "Quick Ball@"
	db "Dusk Ball@"
	db "Premier Ball@"
	db "Cherish Ball@"
	db "Potion@"
	db "Super Potion@"
	db "Hyper Potion@"
	db "Max Potion@"
	db "Antidote@"
	db "Burn Heal@"
	db "ParalyzeHeal@"
	db "Awakening@"
	db "Ice Heal@"
	db "Full Heal@"
	db "Full Restore@"
	db "Revive@"
	db "Max Revive@"
	db "Ether@"
	db "Max Ether@"
	db "Elixir@"
	db "Max Elixir@"
	db "HP Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "Zinc@"
	db "Rare Candy@"
	db "PP Up@"
	db "PP Max@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "Moomoo Milk@"
if DEF(FAITHFUL)
	db "RageCandyBar@"
else
	db "Cake of Rage@"
endc
	db "Sacred Ash@"
	db "EnergyPowder@"
	db "Energy Root@"
	db "Heal Powder@"
	db "Revival Herb@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Spcl.Atk@"
	db "X Spcl.Def@"
	db "Dire Hit@"
if DEF(FAITHFUL)
	db "Guard Spec.@"
else
	db "Guard Stats@"
endc
	db "X Accuracy@"
	db "Repel@"
	db "Super Repel@"
	db "Max Repel@"
	db "Escape Rope@"
	db "# Doll@"
	db "Ability Cap@"
	db "Leaf Stone@"
	db "Fire Stone@"
	db "Water Stone@"
	db "ThunderStone@"
	db "Moon Stone@"
	db "Sun Stone@"
	db "Dusk Stone@"
	db "Shiny Stone@"
	db "Ice Stone@"
	db "Everstone@"
	db "Bicycle@"
	db "Old Rod@"
	db "Good Rod@"
	db "Super Rod@"
	db "Coin Case@"
	db "Itemfinder@"
	db "Exp.Share@"
	db "Mystery Egg@"
	db "SquirtBottle@"
	db "SecretPotion@"
	db "Red Scale@"
	db "Card Key@"
	db "Basement Key@"
	db "S.S.Ticket@"
	db "Pass@"
	db "Machine Part@"
	db "Lost Item@"
	db "Rainbow Wing@"
	db "Silver Wing@"
	db "Clear Bell@"
	db "GS Ball@"
	db "Blue Card@"
	db "OrangeTicket@"
	db "MysticTicket@"
	db "Old Sea Map@"
	db "Shiny Charm@"
	db "Oval Charm@"
	db "SilphScope2@"
	db "Cheri Berry@"
	db "Chesto Berry@"
	db "Pecha Berry@"
	db "Rawst Berry@"
	db "Aspear Berry@"
	db "Leppa Berry@"
	db "Oran Berry@"
	db "Persim Berry@"
	db "Lum Berry@"
	db "Sitrus Berry@"
	db "Figy Berry@"
	db "Liechi Berry@"
	db "Ganlon Berry@"
	db "Salac Berry@"
	db "Petaya Berry@"
	db "Apicot Berry@"
	db "Red Apricorn@"
	db "Blu Apricorn@"
	db "Ylw Apricorn@"
	db "Grn Apricorn@"
	db "Wht Apricorn@"
	db "Blk Apricorn@"
	db "Pnk Apricorn@"
	db "Silk Scarf@"
	db "Black Belt@"
	db "Sharp Beak@"
	db "Poison Barb@"
	db "Soft Sand@"
	db "Hard Stone@"
	db "SilverPowder@"
	db "Spell Tag@"
	db "Metal Coat@"
	db "Charcoal@"
	db "Mystic Water@"
	db "Miracle Seed@"
	db "Magnet@"
	db "TwistedSpoon@"
	db "NeverMeltIce@"
	db "Dragon Fang@"
	db "BlackGlasses@"
	db "Pink Bow@"
	db "BrightPowder@"
	db "Scope Lens@"
	db "Quick Claw@"
	db "King's Rock@"
	db "Focus Band@"
	db "Leftovers@"
	db "Lucky Egg@"
	db "Amulet Coin@"
	db "Cleanse Tag@"
	db "Smoke Ball@"
	db "Berserk Gene@"
	db "Light Ball@"
	db "Stick@"
	db "Thick Club@"
	db "Lucky Punch@"
	db "Metal Powder@"
	db "Quick Powder@"
	db "Armor Suit@"
	db "Air Balloon@"
	db "Assault Vest@"
	db "Big Root@"
	db "Binding Band@"
	db "Destiny Knot@"
	db "Eviolite@"
	db "Expert Belt@"
	db "Focus Sash@"
	db "Grip Claw@"
	db "Life Orb@"
	db "Light Clay@"
	db "Metronome@"
	db "Muscle Band@"
	db "Protect Pads@"
	db "Rocky Helmet@"
	db "Safe Goggles@"
	db "Shed Shell@"
	db "Shell Bell@"
	db "Soothe Bell@"
	db "Weak Policy@"
	db "Wide Lens@"
	db "Wise Glasses@"
	db "Zoom Lens@"
	db "Mental Herb@"
	db "Power Herb@"
	db "White Herb@"
	db "Damp Rock@"
	db "Heat Rock@"
	db "Smooth Rock@"
	db "Icy Rock@"
	db "Choice Band@"
	db "Choice Scarf@"
	db "Choice Specs@"
	db "Flame Orb@"
	db "Toxic Orb@"
	db "Black Sludge@"
	db "Macho Brace@"
	db "Power Weight@"
	db "Power Bracer@"
	db "Power Belt@"
	db "Power Lens@"
	db "Power Band@"
	db "Power Anklet@"
	db "Dragon Scale@"
	db "Up-Grade@"
	db "Dubious Disc@"
	db "Protector@"
	db "Electirizer@"
	db "Magmarizer@"
	db "Razor Fang@"
	db "Razor Claw@"
	db "Odd Souvenir@"
	db "Nugget@"
	db "Big Nugget@"
	db "TinyMushroom@"
	db "Big Mushroom@"
	db "BalmMushroom@"
	db "Pearl@"
	db "Big Pearl@"
	db "Pearl String@"
	db "Stardust@"
	db "Star Piece@"
	db "Brick Piece@"
	db "Rare Bone@"
	db "Silver Leaf@"
	db "Gold Leaf@"
	db "SlowpokeTail@"
	db "Bottle Cap@"
	db "Helix Fossil@"
	db "Dome Fossil@"
	db "Old Amber@"
	db "Mulch@"
	db "Sweet Honey@"
	db "Flower Mail@"
	db "Surf Mail@"
	db "LiteBlueMail@"
	db "PortraitMail@"
	db "Lovely Mail@"
	db "Eon Mail@"
	db "Morph Mail@"
	db "BlueSky Mail@"
	db "Music Mail@"
	db "Mirage Mail@"
	db "?@"
