	db "# Ball@"
	db "Great Ball@"
	db "Ultra Ball@"
	db "Master Ball@"
	db "Potion@"
	db "Super Potion@"
	db "Hyper Potion@"
	db "Max Potion@"
	db "Antidote@"
	db "Burn Heal@"
	db "ParalyzHeal@"
	db "Awakening@"
	db "Ice Heal@"
	db "Full Heal@"
	db "Full Restore@"
	db "Revive@"
	db "Max Revive@"
	db "Ether@"
	db "Max Ether@"
	db "Elixir@"
	db "Max Elixir@"
	db "X Attack@"
	db "X Defend@"
	db "X Speed@"
	db "X Spcl.Atk@"
	db "X Spcl.Def@"
	db "Dire Hit@"
	db "Guard Spec.@"
	db "X Accuracy@"
	db "HP Up@"
	db "Protein@"
	db "Iron@"
	db "Carbos@"
	db "Calcium@"
	db "Rare Candy@"
	db "PP Up@"
	db "Fresh Water@"
	db "Soda Pop@"
	db "Lemonade@"
	db "Moomoo Milk@"
	db "RageCandyBar@"
	db "Sacred Ash@"
	db "EnergyPowder@"
	db "Energy Root@"
	db "Heal Powder@"
	db "Revival Herb@"
	db "Repel@"
	db "Super Repel@"
	db "Max Repel@"
	db "Escape Rope@"
	db "# Doll@"
	db "Leaf Stone@"
	db "Fire Stone@"
	db "Water Stone@"
	db "ThunderStone@"
	db "Moon Stone@"
	db "Sun Stone@"
	db "Dusk Stone@"
	db "Shiny Stone@"
	db "Everstone@"
	db "Bicycle@"
	db "Old Rod@"
	db "Good Rod@"
	db "Super Rod@"
	db "Coin Case@"
	db "Itemfinder@"
	db "Exp.Share@"
	db "Mystery Egg@"
	db "SquirtBottle@"
	db "SecretPotion@"
	db "Red Scale@"
	db "Card Key@"
	db "Basement Key@"
	db "S.S.Ticket@"
	db "Pass@"
	db "Machine Part@"
	db "Lost Item@"
	db "Rainbow Wing@"
	db "Silver Wing@"
	db "Clear Bell@"
	db "GS Ball@"
	db "Blue Card@"
	db "MysticTicket@"
	db "Old Sea Map@"
	db "Oran Berry@"
	db "Sitrus Berry@"
	db "Pecha Berry@"
	db "Rawst Berry@"
	db "Cheri Berry@"
	db "Chesto Berry@"
	db "Aspear Berry@"
	db "Persim Berry@"
	db "Lum Berry@"
	db "Leppa Berry@"
	db "Red Apricorn@"
	db "Blu Apricorn@"
	db "Ylw Apricorn@"
	db "Grn Apricorn@"
	db "Wht Apricorn@"
	db "Blk Apricorn@"
	db "Pnk Apricorn@"
	db "Heavy Ball@"
	db "Level Ball@"
	db "Lure Ball@"
	db "Fast Ball@"
	db "Friend Ball@"
	db "Moon Ball@"
	db "Love Ball@"
	db "Silk Scarf@"
	db "Black Belt@"
	db "Sharp Beak@"
	db "Poison Barb@"
	db "Soft Sand@"
	db "Hard Stone@"
	db "SilverPowder@"
	db "Spell Tag@"
	db "Metal Coat@"
	db "Charcoal@"
	db "Mystic Water@"
	db "Miracle Seed@"
	db "Magnet@"
	db "TwistedSpoon@"
	db "NeverMeltIce@"
	db "Dragon Fang@"
	db "BlackGlasses@"
	db "Pink Bow@"
	db "BrightPowder@"
	db "Scope Lens@"
	db "Quick Claw@"
	db "King's Rock@"
	db "Focus Band@"
	db "Leftovers@"
	db "Lucky Egg@"
	db "Amulet Coin@"
	db "Cleanse Tag@"
	db "Smoke Ball@"
	db "Light Ball@"
	db "Stick@"
	db "Thick Club@"
	db "Lucky Punch@"
	db "Metal Powder@"
	db "Berserk Gene@"
	db "Eviolite@"
	db "Life Orb@"
	db "Dragon Scale@"
	db "Up-Grade@"
	db "Dubious Disc@"
	db "Razor Fang@"
	db "Razor Claw@"
	db "Nugget@"
	db "TinyMushroom@"
	db "Big Mushroom@"
	db "Pearl@"
	db "Big Pearl@"
	db "Stardust@"
	db "Star Piece@"
	db "Silver Leaf@"
	db "Gold Leaf@"
	db "SlowpokeTail@"
	db "Park Ball@"
	db "Repeat Ball@"
	db "Timer Ball@"
	db "Quick Ball@"
	db "Dusk Ball@"
	db "Helix Fossil@"
	db "Dome Fossil@"
	db "Old Amber@"
	db "Flower Mail@"
	db "Surf Mail@"
	db "LiteBlueMail@"
	db "PortraitMail@"
	db "Lovely Mail@"
	db "Eon Mail@"
	db "Morph Mail@"
	db "BlueSky Mail@"
	db "Music Mail@"
	db "Mirage Mail@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "Teru-sama@"
	db "TM01@"
	db "TM02@"
	db "TM03@"
	db "TM04@"
	db "TM05@"
	db "TM06@"
	db "TM07@"
	db "TM08@"
	db "TM09@"
	db "TM10@"
	db "TM11@"
	db "TM12@"
	db "TM13@"
	db "TM14@"
	db "TM15@"
	db "TM16@"
	db "TM17@"
	db "TM18@"
	db "TM19@"
	db "TM20@"
	db "TM21@"
	db "TM22@"
	db "TM23@"
	db "TM24@"
	db "TM25@"
	db "TM26@"
	db "TM27@"
	db "TM28@"
	db "TM29@"
	db "TM30@"
	db "TM31@"
	db "TM32@"
	db "TM33@"
	db "TM34@"
	db "TM35@"
	db "TM36@"
	db "TM37@"
	db "TM38@"
	db "TM39@"
	db "TM40@"
	db "TM41@"
	db "TM42@"
	db "TM43@"
	db "TM44@"
	db "TM45@"
	db "TM46@"
	db "TM47@"
	db "TM48@"
	db "TM49@"
	db "TM50@"
	db "TM51@"
	db "TM52@"
	db "TM53@"
	db "TM54@"
	db "TM55@"
	db "TM56@"
	db "TM57@"
	db "TM58@"
	db "TM59@"
	db "TM60@"
	db "TM61@"
	db "TM62@"
	db "TM63@"
	db "TM64@"
	db "TM65@"
	db "HM01@"
	db "HM02@"
	db "HM03@"
	db "HM04@"
	db "HM05@"
	db "HM06@"
	db "HM07@"
	db "HM08@"
	db "Teru-sama@"
	db "?@"
