EmotePalTable:
	table_width 1, EmotePalTable
	db PAL_OW_EMOTE_WWBB ; EMOTE_SHOCK
	db PAL_OW_EMOTE_WWBB ; EMOTE_QUESTION
	db PAL_OW_EMOTE_WWGB ; EMOTE_HAPPY
	db PAL_OW_EMOTE_WWPB ; EMOTE_SAD
	db PAL_OW_EMOTE_WWRB ; EMOTE_HEART
	db PAL_OW_EMOTE_WWOB ; EMOTE_BOLT
	db PAL_OW_EMOTE_WWUB ; EMOTE_SLEEP
	db PAL_OW_EMOTE_WWUB ; EMOTE_FISH
	assert_table_length NUM_EMOTES
