	tilepal 0, GRAY, ROOF, RED, RED, RED, ROOF, ROOF, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, WATER, RED
	tilepal 0, GRAY, WATER, WATER, WATER, RED, ROOF, ROOF, BROWN
	tilepal 0, BROWN, RED, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 0, GRAY, RED, GRAY, GRAY, GRAY, ROOF, GREEN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 0, RED, WATER, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, WATER, GREEN, GREEN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, RED, WATER, WATER, ROOF, ROOF
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, TEXT
	tilepal 1, ROOF, RED, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
