	tilepal 0, GRAY, WATER, WATER, WATER, BROWN, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, BROWN, ROOF, RED, RED, RED
	tilepal 0, ROOF, WATER, ROOF, BROWN, ROOF, WATER, WATER, RED
	tilepal 0, RED, ROOF, ROOF, WATER, ROOF, RED, RED, RED
	tilepal 0, ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, ROOF, ROOF, WATER, WATER, RED, ROOF, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, BROWN, WATER
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, GREEN, GREEN, ROOF, GRAY
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal 0, RED, RED, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY
	tilepal 0, BROWN, BROWN, ROOF, GRAY, GRAY, BROWN, BROWN, RED
	tilepal 0, RED, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, GRAY, GRAY
