	tilepal 0, GRAY, GREEN, GREEN, RED, GRAY, RED, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, GRAY, GRAY, GRAY, WATER
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN
	tilepal 0, BROWN, BROWN, WATER, WATER, GRAY, GRAY, GRAY, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN
