Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 2
	farbank "Cries"
	fardw Cry_Nidoran_M
	fardw Cry_Nidoran_F
	fardw Cry_Slowpoke
	fardw Cry_Kangaskhan
	fardw Cry_Charmander
	fardw Cry_Grimer
	fardw Cry_Voltorb
	fardw Cry_Muk
	fardw Cry_Oddish
	fardw Cry_Raichu
	fardw Cry_Nidoqueen
	fardw Cry_Diglett
	fardw Cry_Seel
	fardw Cry_Drowzee
	fardw Cry_Pidgey
	fardw Cry_Bulbasaur
	fardw Cry_Farfetch_d
	fardw Cry_Rhydon
	fardw Cry_Golem
	fardw Cry_Blastoise
	fardw Cry_Pidgeotto
	fardw Cry_Weedle
	fardw Cry_Caterpie
	fardw Cry_Ekans
	fardw Cry_Shellder
	fardw Cry_Clefairy
	fardw Cry_Venonat
	fardw Cry_Lapras
	fardw Cry_Metapod
	fardw Cry_Squirtle
	fardw Cry_Paras
	fardw Cry_Growlithe
	fardw Cry_Krabby
	fardw Cry_Psyduck
	fardw Cry_Rattata
	fardw Cry_Vileplume
	fardw Cry_Vulpix
	fardw Cry_Weepinbell
	fardw Cry_Marill
	fardw Cry_Spinarak
	fardw Cry_Togepi
	fardw Cry_Girafarig
	fardw Cry_Raikou
	fardw Cry_Mareep
	fardw Cry_Togetic
	fardw Cry_Hoothoot
	fardw Cry_Sentret
	fardw Cry_Slowking
	fardw Cry_Cyndaquil
	fardw Cry_Chikorita
	fardw Cry_Totodile
	fardw Cry_Gligar
	fardw Cry_Bellossom
	fardw Cry_Slugma
	fardw Cry_Ledyba
	fardw Cry_Entei
	fardw Cry_Wooper
	fardw Cry_Mantine
	fardw Cry_Typhlosion
	fardw Cry_Natu
	fardw Cry_Teddiursa
	fardw Cry_Remoraid
	fardw Cry_Ampharos
	fardw Cry_Magcargo
	fardw Cry_Pichu
	fardw Cry_Tyrogue
	fardw Cry_Dunsparce
	fardw Cry_Donphan
	assert_table_length NUM_CRIES
