Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Farfetch_d
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Shellder
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Bellossom
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Remoraid
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Tyrogue
	dba Cry_Dunsparce
	dba Cry_Donphan
	dba Cry_Azurill
	dba Cry_Wynaut
	dba Cry_Ambipom
	dba Cry_Mismagius
	dba Cry_Honchkrow
	dba Cry_Bonsly
	dba Cry_Mime_Jr
	dba Cry_Happiny
	dba Cry_Munchlax
	dba Cry_Mantyke
	dba Cry_Weavile
	dba Cry_Magnezone
	dba Cry_Lickilicky
	dba Cry_Rhyperior
	dba Cry_Tangrowth
	dba Cry_Electivire
	dba Cry_Magmortar
	dba Cry_Togekiss
	dba Cry_Yanmega
	dba Cry_Leafeon
	dba Cry_Glaceon
	dba Cry_Gliscor
	dba Cry_Mamoswine
	dba Cry_Porygon_Z
	dba Cry_Sylveon
	dba Cry_Perrserker
	dba Cry_Cursola
	dba Cry_Sirfetch_d
	dba Cry_Mr_Rime
	dba Cry_Wyrdeer
	dba Cry_Kleavor
	dba Cry_Ursaluna
	dba Cry_Sneasler
	dba Cry_Overqwil
	dba Cry_Dudunsparce
	dba Cry_Farigiraf
	dba Cry_Clodsire
	dba Cry_Annihilape
	assert_table_length NUM_CRIES
