Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Farfetch_d
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Shellder
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Bellossom
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Remoraid
	dba Cry_Ampharos
	dba Cry_Magcargo
	dba Cry_Pichu
	dba Cry_Tyrogue
	dba Cry_Dunsparce
	dba Cry_Donphan
	dba Cry_azurill
	dba Cry_wynaut
	dba Cry_Custom_424
	dba Cry_Custom_429
	dba Cry_Custom_430
	dba Cry_Custom_438
	dba Cry_Custom_439
	dba Cry_Custom_440
	dba Cry_Custom_446
	dba Cry_Custom_458
	dba Cry_Custom_461
	dba Cry_Custom_462
	dba Cry_Custom_463
	dba Cry_Custom_464
	dba Cry_Custom_465
	dba Cry_Custom_466
	dba Cry_Custom_467
	dba Cry_Custom_468
	dba Cry_Custom_469
	dba Cry_Custom_470
	dba Cry_Custom_471
	dba Cry_Custom_472
	dba Cry_Custom_473
	dba Cry_Custom_474
	dba Cry_Custom_700
	dba Cry_Custom_863
	dba Cry_Custom_864
	dba Cry_Custom_865
	dba Cry_Custom_866
	dba Cry_Custom_899
	dba Cry_Custom_900
	dba Cry_Custom_901_0
	dba Cry_Custom_903
	dba Cry_Custom_904
	dba Cry_Custom_917
	dba Cry_Custom_928
	dba Cry_Custom_1009
	dba Cry_Custom_1010
	assert_table_length NUM_CRIES
