Music:
	table_width 3, Music
	dba Music_Nothing
	dba Music_CrystalOpening
	dba Music_TitleScreen
	dba Music_MainMenu
	dba Music_NewBarkTown
	dba Music_Mom
	dba Music_ElmsLab
	dba Music_LyraEncounterHGSS
	dba Music_RivalBattleXY
	dba Music_LyraDepartureHGSS
	dba Music_Route29
	dba Music_JohtoWildBattle
	dba Music_JohtoWildBattleNight
	dba Music_WildPokemonVictory
	dba Music_CherrygroveCity
	dba Music_ShowMeAround
	dba Music_PokemonCenter
	dba Music_HealPokemon
	dba Music_SuccessfulCapture
	dba Music_LookYoungster
	dba Music_JohtoTrainerBattle
	dba Music_TrainerVictory
	dba Music_Route30
	dba Music_VioletCity
	dba Music_SproutTower
	dba Music_LookSage
	dba Music_MartHGSS
	dba Music_HiddenGrottoB2W2
	dba Music_UnionCave
	dba Music_RuinsOfAlphInterior
	dba Music_RuinsOfAlphRadio
	dba Music_AzaleaTown
	dba Music_LookRocket
	dba Music_RocketBattle
	dba Music_Route36
	dba Music_LookRival
	dba Music_RivalBattle
	dba Music_AfterTheRivalFight
	dba Music_Evolution
	dba Music_GoldenrodCity
	dba Music_PokeComCenter
	dba Music_Gym
	dba Music_JohtoGymBattle
	dba Music_FinalPokemonBW
	dba Music_GymLeaderVictory
	dba Music_PokemonChannel
	dba Music_BuenasPassword
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_LookLass
	dba Music_NationalPark
	dba Music_BugCatchingContest
	dba Music_ContestResults
	dba Music_EcruteakCity
	dba Music_DancingHall
	dba Music_LookKimonoGirl
	dba Music_BurnedTower
	dba Music_LookMysticalMan
	dba Music_ProfOaksPokemonTalk
	dba Music_Route37
	dba Music_PokemonMarch
	dba Music_Lighthouse
	dba Music_Surf
	dba Music_CianwoodCityHGSS
	dba Music_Route47HGSS
	dba Music_LookJessieJames
	dba Music_SafariZoneGateHGSS
	dba Music_SurfingPikachu
	dba Music_LakeOfRage
	dba Music_StarkMountainDPPt
	dba Music_LakeOfRageRocketRadio
	dba Music_RocketHideout
	dba Music_LookPokemaniac
	dba Music_RocketTheme
	dba Music_DarkCave
	dba Music_DragonsDen
	dba Music_Clair
	dba Music_Route4BW
	dba Music_TinTower
	dba Music_SuicuneBattle
	dba Music_Route26
	dba Music_IndigoPlateauRBY
	dba Music_VictoryRoad
	dba Music_IndigoPlateau
	dba Music_EliteFourBattleSM
	dba Music_ChampionBattle
	dba Music_HallOfFame
	dba Music_SSAqua
	dba Music_SurfingRBY
	dba Music_VermilionCity
	dba Music_KantoGymBattle
	dba Music_LavenderTownRBY
	dba Music_PokemonTowerRBY
	dba Music_LavenderTown
	dba Music_KantoWildBattle
	dba Music_KantoWildBattleNight
	dba Music_CeruleanCityHGSS
	dba Music_BicycleRB
	dba Music_NuggetBridgeHGSS
	dba Music_MagnetTrain
	dba Music_BlackCityBW
	dba Music_PokemonLullaby
	dba Music_CeladonCity
	dba Music_GameCornerDPPt
	dba Music_CanalaveCityDPPt
	dba Music_BicycleXY
	dba Music_Route12
	dba Music_PokeFluteChannel
	dba Music_Route209DPPt
	dba Music_Route210DPPt
	dba Music_Route225DPPt
	dba Music_WildBattleGo
	dba Music_DiglettsCaveRBY
	dba Music_ViridianForest
	dba Music_LookHiker
	dba Music_ViridianCity
	dba Music_Route3
	dba Music_LookOfficer
	dba Music_MtMoon
	dba Music_MtMoonSquare
	dba Music_Route1
	dba Music_PalletTown
	dba Music_ProfOak
	dba Music_LookBeauty
	dba Music_KantoTrainerBattle
	dba Music_CinnabarIslandHGSS
	dba Music_CinnabarMansionRBY
	dba Music_TrainerBattleDPPt
	dba Music_ScaryHouseXY
	dba Music_EternaForestDPPt
	dba Music_MountChimneyRSE
	dba Music_MountPyreRSE
	dba Music_BattleTowerTheme
	dba Music_BattleTowerLobby
	dba Music_BattleFactoryRSE
	dba Music_TrainerBattleBW
	dba Music_FrontierBrainBattleRSE
	dba Music_ZinniaEncounterORAS
	dba Music_Route205DPPt
	dba Music_SurfRSE
	dba Music_BicycleRSE
	dba Music_WildBattleSM
	dba Music_SunyshoreCityDPPt
	dba Music_TrainerBattleSM
	dba Music_Route203DPPt
	dba Music_WhiteTreehollowWhite2
	dba Music_LaverreCityXY
	dba Music_Route101RSE
	dba Music_EverGrandeCityRSE
	dba Music_OreburghGateDPPt
	dba Music_Route12BW
	dba Music_RoadToReversalMountainB2W2
	dba Music_ZinniaBattleORAS
	dba Music_WallyEncounterORAS
	dba Music_WallyBattleORAS
	dba Music_SpikyEaredPichuHGSS
	dba Music_MotherBeastBattleSM
	dba Music_FrostCavernXY
	dba Music_PowerPlantXY
	dba Music_ReversalMountainWhite2
	dba Music_MeteorFallsRSE
	dba Music_LugiasSong2000_NoIntro
	dba Music_LugiaBattleHGSS
	dba Music_SummoningDanceHGSS
	dba Music_HoOhBattleHGSS
	dba Music_CeruleanCaveRBY
	dba Music_MewtwoBattleStadium
	dba Music_AbandonedShipRSE
	dba Music_KantoLegendBattleXY
	dba Music_GymLeaderBattleRSE
	dba Music_GymLeaderBattleDPPt
	dba Music_GymLeaderBattleBW
	dba Music_GymLeaderBattleXY
	dba Music_GymLeaderBattleGo
	dba Music_EliteFourBattleBW
	dba Music_CelestialTowerBW_NoIntro
	dba Music_ChampionBattleRSE
	dba Music_MountCoronetDPPt
	dba Music_ChampionBattleDPPt
	dba Music_WCSBattleBW
	dba Music_ChampionBattleB2W2
	dba Music_Credits
	dba Music_PostCredits
	dba Music_TitleScreenXY
	dba Music_DewfordTownRSE
	dba Music_MarineTubeB2W2
	dba Music_LegendaryBattleXY
	dba Music_WildBattlePrism
	dba Music_TrainerBattlePrism
	dba Music_GymLeaderBattlePrism
	dba Music_PaletteBattlePrism
	dba Music_Megalovania
	assert_table_length NUM_MUSIC_SONGS
