SFX:
; entries correspond to SFX_* constants
	table_width 2
	farbank "Sound Effects"
	fardw Sfx_DexFanfare5079
	fardw Sfx_Item
	fardw Sfx_CaughtMon
	fardw Sfx_PokeballsPlacedOnTable
	fardw Sfx_Potion
	fardw Sfx_FullHeal
	fardw Sfx_Menu
	fardw Sfx_ReadText
	fardw Sfx_ReadText2
	fardw Sfx_DexFanfare2049
	fardw Sfx_DexFanfare80109
	fardw Sfx_Poison
	fardw Sfx_GotSafariBalls
	fardw Sfx_BootPc
	fardw Sfx_ShutDownPc
	fardw Sfx_ChoosePcOption
	fardw Sfx_EscapeRope
	fardw Sfx_PushButton
	fardw Sfx_SecondPartOfItemfinder
	fardw Sfx_WarpTo
	fardw Sfx_WarpFrom
	fardw Sfx_ChangeDexMode
	fardw Sfx_JumpOverLedge
	fardw Sfx_GrassRustle
	fardw Sfx_Fly
	fardw Sfx_Wrong
	fardw Sfx_Squeak
	fardw Sfx_Strength
	fardw Sfx_Boat
	fardw Sfx_WallOpen
	fardw Sfx_PlacePuzzlePieceDown
	fardw Sfx_EnterDoor
	fardw Sfx_SwitchPokemon
	fardw Sfx_Tally
	fardw Sfx_Transaction
	fardw Sfx_ExitBuilding
	fardw Sfx_Bump
	fardw Sfx_Thunder_OW
	fardw Sfx_Save
	fardw Sfx_Pokeflute
	fardw Sfx_ElevatorEnd
	fardw Sfx_ThrowBall
	fardw Sfx_BallPoof
	fardw Sfx_Faint
	fardw Sfx_Run
	fardw Sfx_SlotMachineStart
	fardw Sfx_Fanfare
	fardw Sfx_Peck
	fardw Sfx_Kinesis
	fardw Sfx_Lick
	fardw Sfx_Pound
	fardw Sfx_MovePuzzlePiece
	fardw Sfx_CometPunch
	fardw Sfx_MegaPunch
	fardw Sfx_Scratch
	fardw Sfx_Vicegrip
	fardw Sfx_RazorWind
	fardw Sfx_Cut
	fardw Sfx_WingAttack
	fardw Sfx_Whirlwind
	fardw Sfx_Bind
	fardw Sfx_VineWhip
	fardw Sfx_DoubleKick
	fardw Sfx_MegaKick
	fardw Sfx_Headbutt
	fardw Sfx_HornAttack
	fardw Sfx_Tackle
	fardw Sfx_PoisonSting
	fardw Sfx_Powder
	fardw Sfx_DoubleSlap
	fardw Sfx_Bite
	fardw Sfx_JumpKick
	fardw Sfx_Stomp
	fardw Sfx_TailWhip
	fardw Sfx_KarateChop
	fardw Sfx_Submission
	fardw Sfx_WaterGun
	fardw Sfx_SwordsDance
	fardw Sfx_Thunder
	fardw Sfx_Supersonic
	fardw Sfx_Leer
	fardw Sfx_Ember
	fardw Sfx_BubbleBeam
	fardw Sfx_HydroPump
	fardw Sfx_Surf
	fardw Sfx_Psybeam
	fardw Sfx_Charge
	fardw Sfx_Thundershock
	fardw Sfx_Psychic
	fardw Sfx_Screech
	fardw Sfx_BoneClub
	fardw Sfx_Sharpen
	fardw Sfx_EggBomb
	fardw Sfx_Sing
	fardw Sfx_HyperBeam
	fardw Sfx_Shine
	fardw Sfx_Unknown5F
	fardw Sfx_Unknown60
	fardw Sfx_Unknown61
	fardw Sfx_SwitchPockets
	fardw Sfx_Unknown63
	fardw Sfx_Burn
	fardw Sfx_TitleScreenEntrance
	fardw Sfx_Unknown66
	fardw Sfx_GetCoinFromSlots
	fardw Sfx_PayDay
	fardw Sfx_Metronome
	fardw Sfx_Call
	fardw Sfx_HangUp
	fardw Sfx_NoSignal
	fardw Sfx_Sandstorm
	fardw Sfx_Elevator
	fardw Sfx_Protect
	fardw Sfx_Sketch
	fardw Sfx_RainDance
	fardw Sfx_Aeroblast
	fardw Sfx_Spark
	fardw Sfx_Curse
	fardw Sfx_Rage
	fardw Sfx_Thief
	fardw Sfx_Thief2
	fardw Sfx_SpiderWeb
	fardw Sfx_MindReader
	fardw Sfx_Nightmare
	fardw Sfx_Snore
	fardw Sfx_SweetKiss
	fardw Sfx_SweetKiss2
	fardw Sfx_BellyDrum
	fardw Sfx_Toxic
	fardw Sfx_SludgeBomb
	fardw Sfx_Foresight
	fardw Sfx_Spite
	fardw Sfx_Outrage
	fardw Sfx_PerishSong
	fardw Sfx_GigaDrain
	fardw Sfx_Attract
	fardw Sfx_Kinesis2
	fardw Sfx_ZapCannon
	fardw Sfx_MeanLook
	fardw Sfx_HealBell
	fardw Sfx_Return
	fardw Sfx_ExpBar
	fardw Sfx_MilkDrink
	fardw Sfx_Present
	fardw Sfx_MorningSun
	fardw Sfx_LevelUp
	fardw Sfx_KeyItem
	fardw Sfx_Fanfare2
	fardw Sfx_RegisterPhoneNumber
	fardw Sfx_3RdPlace
	fardw Sfx_GetEggFromDayCareMan
	fardw Sfx_GetEggFromDayCareLady
	fardw Sfx_MoveDeleted
	fardw Sfx_2ndPlace
	fardw Sfx_1stPlace
	fardw Sfx_ChooseACard
	fardw Sfx_GetTm
	fardw Sfx_GetBadge
	fardw Sfx_QuitSlots
	fardw Sfx_EggCrack
	fardw Sfx_DexFanfareLessThan20
	fardw Sfx_DexFanfare140169
	fardw Sfx_DexFanfare170199
	fardw Sfx_DexFanfare200229
	fardw Sfx_DexFanfare230Plus
	fardw Sfx_Evolved
	fardw Sfx_MasterBall
	fardw Sfx_EggHatch
	fardw Sfx_GsIntroCharizardFireball
	fardw Sfx_GsIntroPokemonAppears
	fardw Sfx_Flash
	fardw Sfx_GameFreakLogoGs
	fardw Sfx_NotVeryEffective
	fardw Sfx_Damage
	fardw Sfx_SuperEffective
	fardw Sfx_BallBounce
	fardw Sfx_Moonlight
	fardw Sfx_Encore
	fardw Sfx_BeatUp
	fardw Sfx_BatonPass
	fardw Sfx_BallWiggle
	fardw Sfx_SweetScent
	fardw Sfx_SweetScent2
	fardw Sfx_HitEndOfExpBar
	fardw Sfx_GiveTrademon
	fardw Sfx_GetTrademon
	fardw Sfx_TrainArrived
	fardw Sfx_StopSlot
	fardw Sfx_2Boops
	fardw Sfx_GlassTing
	fardw Sfx_GlassTing2
	fardw Sfx_IntroUnown1
	fardw Sfx_IntroUnown2
	fardw Sfx_IntroUnown3
	fardw Sfx_DittoPopUp
	fardw Sfx_DittoTransform
	fardw Sfx_IntroSuicune1
	fardw Sfx_IntroPichu
	fardw Sfx_IntroSuicune2
	fardw Sfx_IntroSuicune3
	fardw Sfx_DittoBounce
	fardw Sfx_IntroSuicune4
	fardw Sfx_GameFreakPresents
	fardw Sfx_Tingle
	fardw Sfx_TitleScreenIntro
	fardw Sfx_TwoPcBeeps
	fardw Sfx_4NoteDitty
	fardw Sfx_Twinkle
	fardw Sfx_Puddle
	fardw Sfx_AbilitySlideout
	fardw Sfx_CriticalCapture
	fardw Sfx_StatUp
	fardw Sfx_StatDown
	fardw Sfx_Gravity
	fardw Sfx_OWWhirlpool
	fardw Sfx_Thunderbolt
	assert_table_length NUM_SFX
