SFX: ; far-ok
; entries correspond to SFX_* constants
	table_width 2, SFX
	dw Sfx_DexFanfare5079
	dw Sfx_Item
	dw Sfx_CaughtMon
	dw Sfx_PokeballsPlacedOnTable
	dw Sfx_Potion
	dw Sfx_FullHeal
	dw Sfx_Menu
	dw Sfx_ReadText
	dw Sfx_ReadText2
	dw Sfx_DexFanfare2049
	dw Sfx_DexFanfare80109
	dw Sfx_Poison
	dw Sfx_GotSafariBalls
	dw Sfx_BootPc
	dw Sfx_ShutDownPc
	dw Sfx_ChoosePcOption
	dw Sfx_EscapeRope
	dw Sfx_PushButton
	dw Sfx_SecondPartOfItemfinder
	dw Sfx_WarpTo
	dw Sfx_WarpFrom
	dw Sfx_ChangeDexMode
	dw Sfx_JumpOverLedge
	dw Sfx_GrassRustle
	dw Sfx_Fly
	dw Sfx_Wrong
	dw Sfx_Squeak
	dw Sfx_Strength
	dw Sfx_Boat
	dw Sfx_WallOpen
	dw Sfx_PlacePuzzlePieceDown
	dw Sfx_EnterDoor
	dw Sfx_SwitchPokemon
	dw Sfx_Tally
	dw Sfx_Transaction
	dw Sfx_ExitBuilding
	dw Sfx_Bump
	dw Sfx_Save
	dw Sfx_Pokeflute
	dw Sfx_ElevatorEnd
	dw Sfx_ThrowBall
	dw Sfx_BallPoof
	dw Sfx_Faint
	dw Sfx_Run
	dw Sfx_SlotMachineStart
	dw Sfx_Fanfare
	dw Sfx_Peck
	dw Sfx_Kinesis
	dw Sfx_Lick
	dw Sfx_Pound
	dw Sfx_MovePuzzlePiece
	dw Sfx_CometPunch
	dw Sfx_MegaPunch
	dw Sfx_Scratch
	dw Sfx_Vicegrip
	dw Sfx_RazorWind
	dw Sfx_Cut
	dw Sfx_WingAttack
	dw Sfx_Whirlwind
	dw Sfx_Bind
	dw Sfx_VineWhip
	dw Sfx_DoubleKick
	dw Sfx_MegaKick
	dw Sfx_Headbutt
	dw Sfx_HornAttack
	dw Sfx_Tackle
	dw Sfx_PoisonSting
	dw Sfx_Powder
	dw Sfx_DoubleSlap
	dw Sfx_Bite
	dw Sfx_JumpKick
	dw Sfx_Stomp
	dw Sfx_TailWhip
	dw Sfx_KarateChop
	dw Sfx_Submission
	dw Sfx_WaterGun
	dw Sfx_SwordsDance
	dw Sfx_Thunder
	dw Sfx_Supersonic
	dw Sfx_Leer
	dw Sfx_Ember
	dw Sfx_BubbleBeam
	dw Sfx_HydroPump
	dw Sfx_Surf
	dw Sfx_Psybeam
	dw Sfx_Charge
	dw Sfx_Thundershock
	dw Sfx_Psychic
	dw Sfx_Screech
	dw Sfx_BoneClub
	dw Sfx_Sharpen
	dw Sfx_EggBomb
	dw Sfx_Sing
	dw Sfx_HyperBeam
	dw Sfx_Shine
	dw Sfx_Unknown5F
	dw Sfx_Unknown60
	dw Sfx_Unknown61
	dw Sfx_SwitchPockets
	dw Sfx_Unknown63
	dw Sfx_Burn
	dw Sfx_TitleScreenEntrance
	dw Sfx_Unknown66
	dw Sfx_GetCoinFromSlots
	dw Sfx_PayDay
	dw Sfx_Metronome
	dw Sfx_Call
	dw Sfx_HangUp
	dw Sfx_NoSignal
	dw Sfx_Sandstorm
	dw Sfx_Elevator
	dw Sfx_Protect
	dw Sfx_Sketch
	dw Sfx_RainDance
	dw Sfx_Aeroblast
	dw Sfx_Spark
	dw Sfx_Curse
	dw Sfx_Rage
	dw Sfx_Thief
	dw Sfx_Thief2
	dw Sfx_SpiderWeb
	dw Sfx_MindReader
	dw Sfx_Nightmare
	dw Sfx_Snore
	dw Sfx_SweetKiss
	dw Sfx_SweetKiss2
	dw Sfx_BellyDrum
	dw Sfx_Toxic
	dw Sfx_SludgeBomb
	dw Sfx_Foresight
	dw Sfx_Spite
	dw Sfx_Outrage
	dw Sfx_PerishSong
	dw Sfx_GigaDrain
	dw Sfx_Attract
	dw Sfx_Kinesis2
	dw Sfx_ZapCannon
	dw Sfx_MeanLook
	dw Sfx_HealBell
	dw Sfx_Return
	dw Sfx_ExpBar
	dw Sfx_MilkDrink
	dw Sfx_Present
	dw Sfx_MorningSun
	dw Sfx_LevelUp
	dw Sfx_KeyItem
	dw Sfx_Fanfare2
	dw Sfx_RegisterPhoneNumber
	dw Sfx_3RdPlace
	dw Sfx_GetEggFromDayCareMan
	dw Sfx_GetEggFromDayCareLady
	dw Sfx_MoveDeleted
	dw Sfx_2ndPlace
	dw Sfx_1stPlace
	dw Sfx_ChooseACard
	dw Sfx_GetTm
	dw Sfx_GetBadge
	dw Sfx_QuitSlots
	dw Sfx_EggCrack
	dw Sfx_DexFanfareLessThan20
	dw Sfx_DexFanfare140169
	dw Sfx_DexFanfare170199
	dw Sfx_DexFanfare200229
	dw Sfx_DexFanfare230Plus
	dw Sfx_Evolved
	dw Sfx_MasterBall
	dw Sfx_EggHatch
	dw Sfx_GsIntroCharizardFireball
	dw Sfx_GsIntroPokemonAppears
	dw Sfx_Flash
	dw Sfx_GameFreakLogoGs
	dw Sfx_NotVeryEffective
	dw Sfx_Damage
	dw Sfx_SuperEffective
	dw Sfx_BallBounce
	dw Sfx_Moonlight
	dw Sfx_Encore
	dw Sfx_BeatUp
	dw Sfx_BatonPass
	dw Sfx_BallWiggle
	dw Sfx_SweetScent
	dw Sfx_SweetScent2
	dw Sfx_HitEndOfExpBar
	dw Sfx_GiveTrademon
	dw Sfx_GetTrademon
	dw Sfx_TrainArrived
	dw Sfx_StopSlot
	dw Sfx_2Boops
	dw Sfx_GlassTing
	dw Sfx_GlassTing2
	dw Sfx_IntroUnown1
	dw Sfx_IntroUnown2
	dw Sfx_IntroUnown3
	dw Sfx_DittoPopUp
	dw Sfx_DittoTransform
	dw Sfx_IntroSuicune1
	dw Sfx_IntroPichu
	dw Sfx_IntroSuicune2
	dw Sfx_IntroSuicune3
	dw Sfx_DittoBounce
	dw Sfx_IntroSuicune4
	dw Sfx_GameFreakPresents
	dw Sfx_Tingle
	dw Sfx_TitleScreenIntro
	dw Sfx_TwoPcBeeps
	dw Sfx_4NoteDitty
	dw Sfx_Twinkle
	dw Sfx_Puddle
	dw Sfx_AbilitySlideout
	assert_table_length NUM_SFX
