
TrainerPalettes: ; b0ce

PlayerPalette: ; b0ce
; The player's palette
;	RGB 25, 18, 12
;	RGB 22, 09, 05
	INCLUDE "gfx/trainers/cal.pal"

KrisPalette: ; b0d0
; Kris uses Falkner's palette
;	RGB 27, 17, 14
;	RGB 07, 05, 31

FalknerPalette:      INCLUDE "gfx/trainers/falkner.pal"
BugsyPalette:        INCLUDE "gfx/trainers/bugsy.pal"
WhitneyPalette:      INCLUDE "gfx/trainers/whitney.pal"
MortyPalette:        INCLUDE "gfx/trainers/morty.pal"
ChuckPalette:        INCLUDE "gfx/trainers/chuck.pal"
JasminePalette:      INCLUDE "gfx/trainers/jasmine.pal"
PrycePalette:        INCLUDE "gfx/trainers/pryce.pal"
ClairPalette:        INCLUDE "gfx/trainers/clair.pal"
WillPalette:         INCLUDE "gfx/trainers/will.pal"
KogaPalette:         INCLUDE "gfx/trainers/koga.pal"
BrunoPalette:        INCLUDE "gfx/trainers/bruno.pal"
KarenPalette:        INCLUDE "gfx/trainers/karen.pal"
ChampionPalette:     INCLUDE "gfx/trainers/champion.pal"
BrockPalette:        INCLUDE "gfx/trainers/brock.pal"
MistyPalette:        INCLUDE "gfx/trainers/misty.pal"
LtSurgePalette:      INCLUDE "gfx/trainers/lt_surge.pal"
ErikaPalette:        INCLUDE "gfx/trainers/erika.pal"
JaninePalette:       INCLUDE "gfx/trainers/janine.pal"
SabrinaPalette:      INCLUDE "gfx/trainers/sabrina.pal"
BlainePalette:       INCLUDE "gfx/trainers/blaine.pal"
BluePalette:         INCLUDE "gfx/trainers/blue.pal"
RedPalette:          INCLUDE "gfx/trainers/red.pal"
LeafPalette:         INCLUDE "gfx/trainers/leaf.pal"
Rival1Palette:       INCLUDE "gfx/trainers/rival1.pal"
Rival2Palette:       INCLUDE "gfx/trainers/rival2.pal"
CalPalette:          INCLUDE "gfx/trainers/cal.pal"
YoungsterPalette:    INCLUDE "gfx/trainers/youngster.pal"
BugCatcherPalette:   INCLUDE "gfx/trainers/bug_catcher.pal"
CamperPalette:       INCLUDE "gfx/trainers/camper.pal"
PicnickerPalette:    INCLUDE "gfx/trainers/picnicker.pal"
TwinsPalette:        INCLUDE "gfx/trainers/twins.pal"
FisherPalette:       INCLUDE "gfx/trainers/fisher.pal"
BirdKeeperPalette:   INCLUDE "gfx/trainers/bird_keeper.pal"
HikerPalette:        INCLUDE "gfx/trainers/hiker.pal"
GruntmPalette:       INCLUDE "gfx/trainers/grunt_m.pal"
GruntfPalette:       INCLUDE "gfx/trainers/grunt_f.pal"
ForeignGruntPalette: INCLUDE "gfx/trainers/foreigngrunt.pal"
PokefanmPalette:     INCLUDE "gfx/trainers/pokefan_m.pal"
PokefanfPalette:     INCLUDE "gfx/trainers/pokefan_f.pal"
OfficerPalette:      INCLUDE "gfx/trainers/officer.pal"
PokemaniacPalette:   INCLUDE "gfx/trainers/pokemaniac.pal"
SuperNerdPalette:    INCLUDE "gfx/trainers/super_nerd.pal"
LassPalette:         INCLUDE "gfx/trainers/lass.pal"
BeautyPalette:       INCLUDE "gfx/trainers/beauty.pal"
FirebreatherPalette: INCLUDE "gfx/trainers/firebreather.pal"
JugglerPalette:      INCLUDE "gfx/trainers/juggler.pal"
SchoolboyPalette:    INCLUDE "gfx/trainers/schoolboy.pal"
PsychicTPalette:     INCLUDE "gfx/trainers/psychic_t.pal"
SagePalette:         INCLUDE "gfx/trainers/sage.pal"
MediumPalette:       INCLUDE "gfx/trainers/medium.pal"
KimonoGirlPalette:   INCLUDE "gfx/trainers/kimono_girl.pal"
ElderPalette:        INCLUDE "gfx/trainers/elder.pal"
GentlemanPalette:    INCLUDE "gfx/trainers/gentleman.pal"
SailorPalette:       INCLUDE "gfx/trainers/sailor.pal"
SwimmermPalette:     INCLUDE "gfx/trainers/swimmer_m.pal"
SwimmerfPalette:     INCLUDE "gfx/trainers/swimmer_f.pal"
BurglarPalette:      INCLUDE "gfx/trainers/burglar.pal"
ScientistPalette:    INCLUDE "gfx/trainers/scientist.pal"
BoarderPalette:      INCLUDE "gfx/trainers/boarder.pal"
SkierPalette:        INCLUDE "gfx/trainers/skier.pal"
BlackbeltTPalette:   INCLUDE "gfx/trainers/blackbelt_t.pal"
TeacherPalette:      INCLUDE "gfx/trainers/teacher.pal"
GuitaristPalette:    INCLUDE "gfx/trainers/guitarist.pal"
BikerPalette:        INCLUDE "gfx/trainers/biker.pal"
CooltrainermPalette: INCLUDE "gfx/trainers/cooltrainer_m.pal"
CooltrainerfPalette: INCLUDE "gfx/trainers/cooltrainer_f.pal"
ExecutivemPalette:   INCLUDE "gfx/trainers/executive_m.pal"
ExecutivefPalette:   INCLUDE "gfx/trainers/executive_f.pal"
PokemonProfPalette:  INCLUDE "gfx/trainers/oak.pal"
GameFreakPalette:    INCLUDE "gfx/trainers/cooltrainer_m.pal"
MysticalmanPalette:  INCLUDE "gfx/trainers/mysticalman.pal"
LoreleiPalette:      INCLUDE "gfx/trainers/lorelei.pal"
AgathaPalette:       INCLUDE "gfx/trainers/agatha.pal"
YellowPalette:       INCLUDE "gfx/trainers/yellow.pal"
BillPalette:         INCLUDE "gfx/trainers/bill.pal"
LawrencePalette:     INCLUDE "gfx/trainers/lawrence.pal"
