	db "Pound@"
	db "Karate Chop@"
	db "DoubleSlap@"
	db "Comet Punch@"
	db "Dragon Claw@"
	db "Pay Day@"
	db "Fire Punch@"
	db "Ice Punch@"
	db "ThunderPunch@"
	db "Scratch@"
	db "X-Scissor@"
	db "Guillotine@"
	db "Air Slash@"
	db "Swords Dance@"
	db "Cut@"
	db "Gust@"
	db "Wing Attack@"
	db "Whirlwind@"
	db "Fly@"
	db "DazzlinGleam@"
	db "Slam@"
	db "Vine Whip@"
	db "Stomp@"
	db "Double Kick@"
	db "Flare Blitz@"
	db "Jump Kick@"
	db "Focus Blast@"
	db "Sand Attack@"
	db "Headbutt@"
	db "Horn Attack@"
	db "Fury Attack@"
	db "Horn Drill@"
	db "Tackle@"
	db "Body Slam@"
	db "Wrap@"
	db "Take Down@"
	db "Thrash@"
	db "Double-Edge@"
	db "Tail Whip@"
	db "Poison Sting@"
	db "Twineedle@"
	db "Pin Missile@"
	db "Leer@"
	db "Bite@"
	db "Growl@"
	db "Roar@"
	db "Sing@"
	db "Supersonic@"
	db "Sonic Boom@"
	db "Disable@"
	db "Acid@"
	db "Ember@"
	db "Flamethrower@"
	db "Mist@"
	db "Water Gun@"
	db "Hydro Pump@"
	db "Surf@"
	db "Ice Beam@"
	db "Blizzard@"
	db "Psybeam@"
	db "Bubble Beam@"
	db "Aurora Beam@"
	db "Hyper Beam@"
	db "Peck@"
	db "Drill Peck@"
	db "Submission@"
	db "Low Kick@"
	db "Counter@"
	db "Seismic Toss@"
	db "Strength@"
	db "Absorb@"
	db "Mega Drain@"
	db "Leech Seed@"
	db "Growth@"
	db "Razor Leaf@"
	db "Solar Beam@"
	db "PoisonPowder@"
	db "Stun Spore@"
	db "Sleep Powder@"
	db "Petal Dance@"
	db "String Shot@"
	db "Dragon Rage@"
	db "Fire Spin@"
	db "ThunderShock@"
	db "Thunderbolt@"
	db "Thunder Wave@"
	db "Thunder@"
	db "Rock Throw@"
	db "Earthquake@"
	db "Fissure@"
	db "Dig@"
	db "Toxic@"
	db "Confusion@"
	db "Psychic@"
	db "Hypnosis@"
	db "Meditate@"
	db "Agility@"
	db "Quick Attack@"
	db "Rage@"
	db "Teleport@"
	db "Night Shade@"
	db "Dragon Pulse@"
	db "Screech@"
	db "Double Team@"
	db "Recover@"
	db "Harden@"
	db "Minimize@"
	db "Smokescreen@"
	db "Confuse Ray@"
	db "Aqua Tail@"
	db "Defense Curl@"
	db "Barrier@"
	db "Light Screen@"
	db "Haze@"
	db "Reflect@"
	db "Focus Energy@"
	db "Flash Cannon@"
	db "Metronome@"
	db "Mirror Move@"
	db "SelfDestruct@"
	db "Egg Bomb@"
	db "Lick@"
	db "Gunk Shot@"
	db "Sludge@"
	db "Earth Power@"
	db "Fire Blast@"
	db "Waterfall@"
	db "Clamp@"
	db "Swift@"
	db "Iron Head@"
	db "Spike Cannon@"
	db "Fairy Wind@"
	db "Calm Mind@"
	db "Metal Sound@"
	db "Softboiled@"
	db "Hi Jump Kick@"
	db "Glare@"
	db "Dream Eater@"
	db "Poison Jab@"
	db "Bullet Punch@"
	db "Leech Life@"
	db "Drain Kiss@"
	db "Sky Attack@"
	db "Transform@"
	db "Bubble@"
	db "Dizzy Punch@"
	db "Spore@"
	db "Flash@"
	db "Extrasensory@"
	db "Splash@"
	db "Dragon Dance@"
	db "Crabhammer@"
	db "Explosion@"
	db "Fury Swipes@"
	db "Bonemerang@"
	db "Rest@"
	db "Rock Slide@"
	db "Hyper Fang@"
	db "Bulk Up@"
	db "Conversion@"
	db "Tri Attack@"
	db "Super Fang@"
	db "Slash@"
	db "Substitute@"
	db "Struggle@"
	db "Sketch@"
	db "Triple Kick@"
	db "Thief@"
	db "Will-O-Wisp@"
	db "Zen Headbutt@"
	db "Nightmare@"
	db "Flame Wheel@"
	db "Hyper Voice@"
	db "Curse@"
	db "Flail@"
	db "Conversion 2@"
	db "Aeroblast@"
	db "Seed Bomb@"
	db "Reversal@"
	db "Astonish@"
	db "Powder Snow@"
	db "Protect@"
	db "Mach Punch@"
	db "Scary Face@"
	db "Feint Attack@"
	db "Sweet Kiss@"
	db "Belly Drum@"
	db "Sludge Bomb@"
	db "Mud-Slap@"
	db "Octazooka@"
	db "Spikes@"
	db "Zap Cannon@"
	db "Foresight@"
	db "Destiny Bond@"
	db "Perish Song@"
	db "Icy Wind@"
	db "Power Gem@"
	db "Wild Charge@"
	db "Lock-On@"
	db "Outrage@"
	db "Sandstorm@"
	db "Giga Drain@"
	db "Endure@"
	db "Charm@"
	db "Rollout@"
	db "False Swipe@"
	db "Swagger@"
	db "Milk Drink@"
	db "Spark@"
	db "Fury Cutter@"
	db "Steel Wing@"
	db "Mean Look@"
	db "Attract@"
	db "Sleep Talk@"
	db "Heal Bell@"
	db "Return@"
	db "Psystrike@"
	db "Bug Buzz@"
	db "Safeguard@"
	db "Pain Split@"
	db "Sacred Fire@"
	db "Magnitude@"
	db "DynamicPunch@"
	db "Megahorn@"
	db "DragonBreath@"
	db "Baton Pass@"
	db "Encore@"
	db "Pursuit@"
	db "Rapid Spin@"
	db "Sweet Scent@"
	db "Iron Tail@"
	db "Metal Claw@"
	db "Vital Throw@"
	db "Morning Sun@"
	db "Synthesis@"
	db "Moonlight@"
	db "Hidden Power@"
	db "Cross Chop@"
	db "Twister@"
	db "Rain Dance@"
	db "Sunny Day@"
	db "Crunch@"
	db "Mirror Coat@"
	db "Psych Up@"
	db "ExtremeSpeed@"
	db "AncientPower@"
	db "Shadow Ball@"
	db "Future Sight@"
	db "Rock Smash@"
	db "Whirlpool@"
	db "Dark Pulse@"
	db "Moonblast@"
	db "Play Rough@"
	db "Disarm Voice@"
