MapGroupPointers::
; pointers to the first map header of each map group
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3
	dw MapGroup4
	dw MapGroup5
	dw MapGroup6
	dw MapGroup7
	dw MapGroup8
	dw MapGroup9
	dw MapGroup10
	dw MapGroup11
	dw MapGroup12
	dw MapGroup13
	dw MapGroup14
	dw MapGroup15
	dw MapGroup16
	dw MapGroup17
	dw MapGroup18
	dw MapGroup19
	dw MapGroup20
	dw MapGroup21
	dw MapGroup22
	dw MapGroup23
	dw MapGroup24
	dw MapGroup25
	dw MapGroup26
	dw MapGroup27
	dw MapGroup28
	dw MapGroup29
	dw MapGroup30
	dw MapGroup31
	dw MapGroup32
	dw MapGroup33
	dw MapGroup34
	dw MapGroup35
	dw MapGroup36

MapGroup1:
	map_header OlivinePokeCenter1F, TILESET_POKECENTER, INDOOR, OLIVINE_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineGym, TILESET_CHAMPIONS_ROOM, INDOOR, OLIVINE_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineTimsHouse, TILESET_JOHTO_HOUSE, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivinePunishmentSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineGoodRodHouse, TILESET_JOHTO_HOUSE, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineCafe, TILESET_GAME_CORNER, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineMart, TILESET_MART, INDOOR, OLIVINE_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route38EcruteakGate, TILESET_GATE, GATE, ROUTE_38, MUSIC_ROUTE_37, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route39Barn, TILESET_TRADITIONAL_HOUSE, INDOOR, ROUTE_39, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route39Farmhouse, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_39, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route38, TILESET_JOHTO_MODERN, ROUTE, ROUTE_38, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route39, TILESET_JOHTO_MODERN, ROUTE, ROUTE_39, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header OlivineCity, TILESET_JOHTO_MODERN, TOWN, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route35Coast, TILESET_JOHTO_MODERN, ROUTE, ROUTE_35_COAST, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup2:
	map_header MahoganyRedGyaradosSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MahoganyGym, TILESET_GYM, INDOOR, MAHOGANY_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header MahoganyPokeCenter1F, TILESET_POKECENTER, INDOOR, MAHOGANY_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route42EcruteakGate, TILESET_GATE, GATE, ROUTE_42, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route42, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_42, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route44, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_44, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header MahoganyTown, TILESET_JOHTO_TRADITIONAL, TOWN, MAHOGANY_TOWN, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup3:
	map_header SproutTower1F, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SproutTower2F, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SproutTower3F, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower1F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower2F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower3F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower4F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower5F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower6F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower7F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower8F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower9F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTower10F, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BurnedTower1F, TILESET_SPROUT_TOWER, DUNGEON, BURNED_TOWER, MUSIC_BURNED_TOWER, 1, PALETTE_AUTO, FISHGROUP_SHORE
	map_header BurnedTowerB1F, TILESET_CAVE, CAVE, BURNED_TOWER, MUSIC_BURNED_TOWER, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header NationalPark, TILESET_PARK, ROUTE, NATIONAL_PARK, MUSIC_NATIONAL_PARK, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header NationalParkBugContest, TILESET_PARK, ROUTE, NATIONAL_PARK, MUSIC_BUG_CATCHING_CONTEST, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header RadioTower1F, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, MUSIC_RADIO_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RadioTower2F, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, MUSIC_RADIO_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RadioTower3F, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, MUSIC_RADIO_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RadioTower4F, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, MUSIC_RADIO_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RadioTower5F, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, MUSIC_RADIO_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header UnionCave1F, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header UnionCaveB1FNorth, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header UnionCaveB1FSouth, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header UnionCaveB2F, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header SlowpokeWellB1F, TILESET_CAVE, CAVE, SLOWPOKE_WELL, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header SlowpokeWellB2F, TILESET_CAVE, CAVE, SLOWPOKE_WELL, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header OlivineLighthouse1F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouse2F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouse3F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouse4F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouse5F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouse6F, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivineLighthouseRoof, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MahoganyMart1F, TILESET_TRADITIONAL_HOUSE, INDOOR, MAHOGANY_TOWN, MUSIC_MAHOGANY_MART, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TeamRocketBaseB1F, TILESET_UNDERGROUND, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TeamRocketBaseB2F, TILESET_FACILITY, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TeamRocketBaseB3F, TILESET_FACILITY, DUNGEON, MAHOGANY_TOWN, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header IlexForest, TILESET_FOREST, CAVE, ILEX_FOREST, MUSIC_UNION_CAVE, 0, PALETTE_NITE, FISHGROUP_POND
	map_header WarehouseEntrance, TILESET_GATE, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header UndergroundPathSwitchRoomEntrances, TILESET_GYM, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStoreB1F, TILESET_UNDERGROUND, DUNGEON, GOLDENROD_CITY, MUSIC_MART_HGSS, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header UndergroundWarehouse, TILESET_UNDERGROUND, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header MountMortar1FOutside, TILESET_CAVE, CAVE, MT_MORTAR, MUSIC_STARK_MOUNTAIN_DPPT, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header MountMortar1FInside, TILESET_CAVE, CAVE, MT_MORTAR, MUSIC_STARK_MOUNTAIN_DPPT, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header MountMortar2FInside, TILESET_CAVE, CAVE, MT_MORTAR, MUSIC_STARK_MOUNTAIN_DPPT, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header MountMortarB1F, TILESET_CAVE, CAVE, MT_MORTAR, MUSIC_STARK_MOUNTAIN_DPPT, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header IcePath1F, TILESET_ICE_PATH, CAVE, ICE_PATH, MUSIC_DARK_CAVE, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header IcePathB1F, TILESET_ICE_PATH, CAVE, ICE_PATH, MUSIC_DARK_CAVE, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header IcePathB2FMahoganySide, TILESET_ICE_PATH, CAVE, ICE_PATH, MUSIC_DARK_CAVE, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header IcePathB2FBlackthornSide, TILESET_ICE_PATH, CAVE, ICE_PATH, MUSIC_DARK_CAVE, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header IcePathB3F, TILESET_ICE_PATH, CAVE, ICE_PATH, MUSIC_DARK_CAVE, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header WhirlIslandNW, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandNE, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandSW, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandCave, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandSE, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandB1F, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandB2F, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_METEOR_FALLS_RSE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header WhirlIslandLugiaChamber, TILESET_CAVE, CAVE, WHIRL_ISLANDS, MUSIC_LUGIAS_SONG_2000, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header SilverCaveRoom1, TILESET_CAVE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header SilverCaveRoom2, TILESET_CAVE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header SilverCaveRoom3, TILESET_CAVE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header SilverCaveItemRooms, TILESET_CAVE, CAVE, SILVER_CAVE, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DarkCaveVioletEntrance, TILESET_CAVE, CAVE, DARK_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header DarkCaveBlackthornEntrance, TILESET_CAVE, CAVE, DARK_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header DragonsDen1F, TILESET_CAVE, CAVE, DRAGONS_DEN, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header DragonsDenB1F, TILESET_JOHTO_TRADITIONAL, CAVE, DRAGONS_DEN, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header DragonShrine, TILESET_LAB, INDOOR, DRAGONS_DEN, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header TohjoFalls, TILESET_CAVE, CAVE, TOHJO_FALLS, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header GiovannisCave, TILESET_CAVE, CAVE, TOHJO_FALLS, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DiglettsCave, TILESET_CAVE, CAVE, DIGLETTS_CAVE, MUSIC_DIGLETTS_CAVE_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header MountMoon1F, TILESET_CAVE, CAVE, MT_MOON, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header MountMoonB1F, TILESET_CAVE, CAVE, MT_MOON, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header MountMoonB2F, TILESET_CAVE, CAVE, MT_MOON, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header Underground, TILESET_UNDERGROUND, GATE, UNDERGROUND, MUSIC_MT_MOON, 0, PALETTE_NITE, FISHGROUP_SHORE
	map_header RockTunnel1F, TILESET_TUNNEL, CAVE, ROCK_TUNNEL, MUSIC_POWER_PLANT_XY, 1, PALETTE_DARK, FISHGROUP_SHORE
	map_header RockTunnelB1F, TILESET_TUNNEL, CAVE, ROCK_TUNNEL, MUSIC_POWER_PLANT_XY, 1, PALETTE_DARK, FISHGROUP_SHORE
	map_header RockTunnel2F, TILESET_TUNNEL, CAVE, ROCK_TUNNEL, MUSIC_POWER_PLANT_XY, 1, PALETTE_DARK, FISHGROUP_SHORE
	map_header VictoryRoad1F, TILESET_CAVE, CAVE, VICTORY_ROAD, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header VictoryRoad2F, TILESET_CAVE, CAVE, VICTORY_ROAD, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header VictoryRoad3F, TILESET_CAVE, CAVE, VICTORY_ROAD, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_SHORE

MapGroup4:
	map_header EcruteakHouse, TILESET_SPROUT_TOWER, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header WiseTriosRoom, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakPokeCenter1F, TILESET_POKECENTER, INDOOR, ECRUTEAK_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakLugiaSpeechHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header DanceTheatre, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_DANCING_HALL, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakMart, TILESET_MART, INDOOR, ECRUTEAK_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakGym, TILESET_SPROUT_TOWER, INDOOR, ECRUTEAK_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header EcruteakItemfinderHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakCity, TILESET_JOHTO_TRADITIONAL, TOWN, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route37, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_37, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header ValeriesHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakCherishBallHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header EcruteakDestinyKnotHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup5:
	map_header BlackthornGym1F, TILESET_GYM, INDOOR, BLACKTHORN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BlackthornGym2F, TILESET_GYM, INDOOR, BLACKTHORN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BlackthornDragonSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BlackthornEmysHouse, TILESET_JOHTO_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BlackthornMart, TILESET_MART, INDOOR, BLACKTHORN_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BlackthornPokeCenter1F, TILESET_POKECENTER, INDOOR, BLACKTHORN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MoveDeletersHouse, TILESET_JOHTO_HOUSE, INDOOR, BLACKTHORN_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route45, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_45, MUSIC_ROUTE_4_BW, 0, PALETTE_AUTO, FISHGROUP_DRATINI_2
	map_header Route46, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_46, MUSIC_ROUTE_4_BW, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header BlackthornCity, TILESET_JOHTO_OVERCAST, TOWN, BLACKTHORN_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_POND

MapGroup6:
	map_header CinnabarPokeCenter1F, TILESET_POKECENTER, INDOOR, CINNABAR_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SeafoamIslands1F, TILESET_CAVE, CAVE, SEAFOAM_ISLANDS, MUSIC_FROST_CAVERN_XY, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header SeafoamGym, TILESET_CAVE, CAVE, SEAFOAM_ISLANDS, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header SeafoamIslandsB1F, TILESET_ICE_PATH, CAVE, SEAFOAM_ISLANDS, MUSIC_FROST_CAVERN_XY, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header SeafoamIslandsB2F, TILESET_ICE_PATH, CAVE, SEAFOAM_ISLANDS, MUSIC_FROST_CAVERN_XY, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header SeafoamIslandsB3F, TILESET_ICE_PATH, CAVE, SEAFOAM_ISLANDS, MUSIC_FROST_CAVERN_XY, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header SeafoamIslandsB4F, TILESET_ICE_PATH, CAVE, SEAFOAM_ISLANDS, MUSIC_FROST_CAVERN_XY, 1, PALETTE_DAY, FISHGROUP_DRATINI
	map_header Route19, TILESET_KANTO, ROUTE, ROUTE_19, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route20, TILESET_KANTO, ROUTE, ROUTE_20, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route21, TILESET_KANTO, ROUTE, ROUTE_21, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header UragaChannelWest, TILESET_KANTO, ROUTE, URAGA_CHANNEL, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header CinnabarIsland, TILESET_KANTO, TOWN, CINNABAR_ISLAND, MUSIC_CINNABAR_ISLAND_HGSS, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header CinnabarVolcano1F, TILESET_CAVE, CAVE, CINNABAR_VOLCANO, MUSIC_REVERSAL_MOUNTAIN_W2, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header CinnabarVolcanoB1F, TILESET_CAVE, CAVE, CINNABAR_VOLCANO, MUSIC_REVERSAL_MOUNTAIN_W2, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header CinnabarVolcanoB2F, TILESET_CAVE, CAVE, CINNABAR_VOLCANO, MUSIC_REVERSAL_MOUNTAIN_W2, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header PokemonMansion1F, TILESET_POKEMON_MANSION, CAVE, POKEMON_MANSION, MUSIC_CINNABAR_MANSION_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header PokemonMansionB1F, TILESET_POKEMON_MANSION, CAVE, POKEMON_MANSION, MUSIC_CINNABAR_MANSION_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header CinnabarLab, TILESET_POKEMON_MANSION, PERM_5, CINNABAR_LAB, MUSIC_CINNABAR_MANSION_RBY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header ScaryCave1F, TILESET_CAVE, CAVE, SCARY_CAVE, MUSIC_MOUNT_PYRE_RSE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header ScaryCaveB1F, TILESET_CAVE, CAVE, SCARY_CAVE, MUSIC_MOUNT_PYRE_RSE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header ScaryCaveShipwreck, TILESET_CAVE, CAVE, SCARY_CAVE, MUSIC_MOUNT_PYRE_RSE, 1, PALETTE_DARK, FISHGROUP_DRATINI
	map_header Route19BeachHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_19, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup7:
	map_header CeruleanGymBadgeSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanPoliceStation, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanTradeSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanPokeCenter1F, TILESET_POKECENTER, INDOOR, CERULEAN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanGym, TILESET_PORT, INDOOR, CERULEAN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CeruleanMart, TILESET_MART, INDOOR, CERULEAN_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route10PokeCenter1F, TILESET_POKECENTER, INDOOR, ROUTE_10, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PowerPlant, TILESET_FACILITY, INDOOR, POWER_PLANT, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BillsHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CAPE, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route4, TILESET_KANTO, ROUTE, ROUTE_4, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route24, TILESET_KANTO, ROUTE, ROUTE_24, MUSIC_NUGGET_BRIDGE_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route25, TILESET_KANTO, ROUTE, ROUTE_25, MUSIC_NUGGET_BRIDGE_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header CeruleanCape, TILESET_KANTO, ROUTE, CERULEAN_CAPE, MUSIC_NUGGET_BRIDGE_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header CeruleanCity, TILESET_KANTO, TOWN, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CeruleanCave1F, TILESET_CAVE, CAVE, CERULEAN_CAVE, MUSIC_CERULEAN_CAVE_RBY, 1, PALETTE_NITE, FISHGROUP_GYARADOS
	map_header CeruleanCave2F, TILESET_CAVE, CAVE, CERULEAN_CAVE, MUSIC_CERULEAN_CAVE_RBY, 1, PALETTE_NITE, FISHGROUP_GYARADOS
	map_header CeruleanCaveB1F, TILESET_CAVE, CAVE, CERULEAN_CAVE, MUSIC_CERULEAN_CAVE_RBY, 1, PALETTE_NITE, FISHGROUP_GYARADOS
	map_header CeruleanBikeShop, TILESET_CHAMPIONS_ROOM, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanBerryPowderHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanCoupleHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeruleanWaterShowSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, CERULEAN_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup8:
	map_header AzaleaPokeCenter1F, TILESET_POKECENTER, INDOOR, AZALEA_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CharcoalKiln, TILESET_TRADITIONAL_HOUSE, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AzaleaMart, TILESET_MART, INDOOR, AZALEA_TOWN, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KurtsHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header AzaleaGym, TILESET_GYM, INDOOR, AZALEA_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route33, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_33, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header AzaleaTown, TILESET_JOHTO_OVERCAST, TOWN, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup9:
	map_header LakeofRageHiddenPowerHouse, TILESET_JOHTO_HOUSE, INDOOR, LAKE_OF_RAGE, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LakeofRageMagikarpHouse, TILESET_JOHTO_HOUSE, INDOOR, LAKE_OF_RAGE, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route43MahoganyGate, TILESET_GATE, GATE, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route43Gate, TILESET_GATE, GATE, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route43, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header LakeofRage, TILESET_JOHTO_OVERCAST, TOWN, LAKE_OF_RAGE, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_GYARADOS

MapGroup10:
	map_header Route32, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_32, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_QWILFISH
	map_header Route32Coast, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_32_COAST, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header VioletCity, TILESET_JOHTO_TRADITIONAL, TOWN, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header VioletMart, TILESET_MART, INDOOR, VIOLET_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VioletGym, TILESET_GYM, INDOOR, VIOLET_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header EarlsPokemonAcademy, TILESET_LAB, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VioletNicknameSpeechHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VioletPokeCenter1F, TILESET_POKECENTER, INDOOR, VIOLET_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VioletOnixTradeHouse, TILESET_TRADITIONAL_HOUSE, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route32RuinsofAlphGate, TILESET_GATE, GATE, ROUTE_32, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route32PokeCenter1F, TILESET_POKECENTER, INDOOR, ROUTE_32, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route32CoastHouse, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_32_COAST, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MagnetTunnelEast, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_32, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_QWILFISH
	map_header VioletOutskirts, TILESET_JOHTO_TRADITIONAL, ROUTE, VIOLET_OUTSKIRTS, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_QWILFISH

MapGroup11:
	map_header Route34, TILESET_JOHTO_MODERN, ROUTE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route34Coast, TILESET_JOHTO_MODERN, ROUTE, ROUTE_34_COAST, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header StormyBeach, TILESET_JOHTO_MODERN, ROUTE, STORMY_BEACH, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MurkySwamp, TILESET_FOREST, CAVE, MURKY_SWAMP, MUSIC_ETERNA_FOREST_DPPT, 0, PALETTE_NITE, FISHGROUP_POND
	map_header GoldenrodCity, TILESET_JOHTO_MODERN, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header GoldenrodGym, TILESET_GYM, INDOOR, GOLDENROD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodBikeShop, TILESET_CHAMPIONS_ROOM, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodHappinessRater, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodBillsHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodMagnetTrainStation, TILESET_MAGNET_TRAIN, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodFlowerShop, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodPPSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodNameRater, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore1F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore2F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore3F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore4F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore5F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStore6F, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStoreElevator, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodDeptStoreRoof, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header GoldenrodGameCorner, TILESET_GAME_CORNER, INDOOR, GOLDENROD_CITY, MUSIC_GAME_CORNER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodPokeComCenter1F, TILESET_POKECOM_CENTER, INDOOR, GOLDENROD_CITY, MUSIC_POKECOM_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodPokeComCenterOffice, TILESET_POKECOM_CENTER, INDOOR, GOLDENROD_CITY, MUSIC_POKECOM_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header IlexForestAzaleaGate, TILESET_GATE, GATE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route34IlexForestGate, TILESET_GATE, GATE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header DayCare, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_34, MUSIC_AZALEA_TOWN, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodHPUpHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodNetBallHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodBandHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GoldenrodSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MagnetTunnelWest, TILESET_JOHTO_MODERN, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MagnetTunnelInside, TILESET_TUNNEL, CAVE, MAGNET_TUNNEL, MUSIC_POWER_PLANT_XY, 0, PALETTE_NITE, FISHGROUP_POND

MapGroup12:
	map_header Route6, TILESET_KANTO, ROUTE, ROUTE_6, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route11, TILESET_KANTO, ROUTE, ROUTE_11, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header VermilionCity, TILESET_KANTO, TOWN, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header VermilionHouseFishingSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionPokeCenter1F, TILESET_POKECENTER, INDOOR, VERMILION_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PokemonFanClub, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionMagnetTrainSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionMart, TILESET_MART, INDOOR, VERMILION_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionHouseDiglettsCaveSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionGym, TILESET_GAME_CORNER, INDOOR, VERMILION_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route6SaffronGate, TILESET_GATE, GATE, ROUTE_6, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route6UndergroundEntrance, TILESET_FACILITY, GATE, ROUTE_6, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route11Gate, TILESET_GATE, GATE, ROUTE_11, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route11Gate2F, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionPollutionSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionSSAnneSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup13:
	map_header Route1, TILESET_KANTO, ROUTE, ROUTE_1, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header PalletTown, TILESET_KANTO, TOWN, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header RedsHouse1F, TILESET_KANTO_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header RedsHouse2F, TILESET_KANTO_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BluesHouse1F, TILESET_KANTO_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BluesHouse2F, TILESET_KANTO_HOUSE, INDOOR, PALLET_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OaksLab, TILESET_LAB, INDOOR, PALLET_TOWN, MUSIC_POKEMON_TALK, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup14:
	map_header Route2North, TILESET_KANTO, ROUTE, ROUTE_2, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route3, TILESET_KANTO, ROUTE, ROUTE_3, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route3PokeCenter1F, TILESET_POKECENTER, INDOOR, ROUTE_3, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterCity, TILESET_KANTO, TOWN, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header PewterNidoranSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterGym, TILESET_SPROUT_TOWER, INDOOR, PEWTER_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterMart, TILESET_MART, INDOOR, PEWTER_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterPokeCenter1F, TILESET_POKECENTER, INDOOR, PEWTER_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterSnoozeSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterMuseumOfScience1F, TILESET_MUSEUM, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PewterMuseumOfScience2F, TILESET_MUSEUM, INDOOR, PEWTER_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup15:
	map_header OlivinePort, TILESET_PORT, ROUTE, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header VermilionPort, TILESET_PORT, ROUTE, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header FastShip1F, TILESET_LIGHTHOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FastShipCabins_NNW_NNE_NE, TILESET_LIGHTHOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FastShipCabins_SW_SSW_NW, TILESET_LIGHTHOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FastShipCabins_SE_SSE_CaptainsCabin, TILESET_LIGHTHOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FastShipB1F, TILESET_LIGHTHOUSE, INDOOR, FAST_SHIP, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header OlivinePortPassage, TILESET_UNDERGROUND, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header VermilionPortPassage, TILESET_UNDERGROUND, INDOOR, VERMILION_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MountMoonSquare, TILESET_KANTO, ROUTE, MT_MOON, MUSIC_MT_MOON_SQUARE, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MountMoonGiftShop, TILESET_TRADITIONAL_HOUSE, INDOOR, MT_MOON, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TinTowerRoof, TILESET_SPROUT_TOWER, INDOOR, TIN_TOWER, MUSIC_SUMMONING_DANCE_HGSS, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup16:
	map_header Route23, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_23, MUSIC_INDIGO_PLATEAU_RBY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header IndigoPlateau, TILESET_INDIGO_PLATEAU, ROUTE, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU_RBY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header IndigoPlateauPokeCenter1F, TILESET_POKECENTER, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header WillsRoom, TILESET_GYM, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header KogasRoom, TILESET_GYM, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BrunosRoom, TILESET_GYM, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header KarensRoom, TILESET_GYM, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header LancesRoom, TILESET_CHAMPIONS_ROOM, INDOOR, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header HallOfFame, TILESET_ICE_PATH, INDOOR, INDIGO_PLATEAU, MUSIC_WALLY_ENCOUNTER_ORAS, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BellchimeTrail, TILESET_JOHTO_TRADITIONAL, ROUTE, BELLCHIME_TRAIL, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_POND

MapGroup17:
	map_header Route12South, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_12, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header Route13East, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_13, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header Route13West, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_13, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header Route14, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_14, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route15, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_15, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route18East, TILESET_KANTO, ROUTE, ROUTE_18, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header FuchsiaCity, TILESET_KANTO, TOWN, FUCHSIA_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_AUTO, FISHGROUP_GYARADOS
	map_header FuchsiaMart, TILESET_MART, INDOOR, FUCHSIA_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FuchsiaGym, TILESET_UNDERGROUND, INDOOR, FUCHSIA_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header FuchsiaBillSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FuchsiaSafariBallHouse, TILESET_KANTO_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FuchsiaPokeCenter1F, TILESET_POKECENTER, INDOOR, FUCHSIA_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneWardensHome, TILESET_KANTO_HOUSE, INDOOR, FUCHSIA_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneFuchsiaGate, TILESET_GATE, GATE, FUCHSIA_CITY, MUSIC_CERULEAN_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route12Gate, TILESET_GATE, GATE, ROUTE_12, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route12Gate2F, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route15FuchsiaGate, TILESET_GATE, GATE, ROUTE_15, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route15FuchsiaGate2F, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route19FuchsiaGate, TILESET_GATE, GATE, ROUTE_19, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route12SuperRodHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_12, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LuckyIsland, TILESET_INDIGO_PLATEAU, ROUTE, LUCKY_ISLAND, MUSIC_ROUTE_209_DPPT, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM

MapGroup18:
	map_header Route8, TILESET_KANTO, ROUTE, ROUTE_8, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route8SaffronGate, TILESET_GATE, GATE, ROUTE_8, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route10South, TILESET_KANTO, ROUTE, ROUTE_10, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route12North, TILESET_KANTO, ROUTE, ROUTE_12, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header LavenderTown, TILESET_KANTO, TOWN, LAVENDER_TOWN, MUSIC_LAVENDER, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header LavenderPokeCenter1F, TILESET_POKECENTER, INDOOR, LAVENDER_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MrFujisHouse, TILESET_KANTO_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavenderTownSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavenderNameRater, TILESET_KANTO_HOUSE, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavenderMart, TILESET_MART, INDOOR, LAVENDER_TOWN, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SoulHouse, TILESET_KANTO_HOUSE, INDOOR, SOUL_HOUSE, MUSIC_LAVENDER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SoulHouseB1F, TILESET_LIGHTHOUSE, DUNGEON, SOUL_HOUSE, MUSIC_CELESTIAL_TOWER_BW, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header SoulHouseB2F, TILESET_LIGHTHOUSE, DUNGEON, SOUL_HOUSE, MUSIC_CELESTIAL_TOWER_BW, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header SoulHouseB3F, TILESET_LIGHTHOUSE, DUNGEON, SOUL_HOUSE, MUSIC_CELESTIAL_TOWER_BW, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavRadioTower1F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavRadioTower2F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavRadioTower3F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavRadioTower4F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LavRadioTower5F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header HauntedRadioTower2F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_TOWER_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header HauntedRadioTower3F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_TOWER_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header HauntedRadioTower4F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_TOWER_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header HauntedRadioTower5F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_TOWER_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header HauntedRadioTower6F, TILESET_RADIO_TOWER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_TOWER_RBY, 1, PALETTE_NITE, FISHGROUP_SHORE

MapGroup19:
	map_header Route28, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_28, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header SilverCaveOutside, TILESET_JOHTO_TRADITIONAL, TOWN, SILVER_CAVE, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header SilverCavePokeCenter1F, TILESET_POKECENTER, INDOOR, SILVER_CAVE, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route28FamousSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_28, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header NavelRockOutside, TILESET_SHAMOUTI_ISLAND, PERM_5, NAVEL_ROCK, MUSIC_LAKE_OF_RAGE, 1, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header NavelRockInside, TILESET_CAVE, CAVE, NAVEL_ROCK, MUSIC_MT_MOON, 1, PALETTE_DAY, FISHGROUP_OCEAN
	map_header NavelRockRoof, TILESET_CAVE, PERM_5, NAVEL_ROCK, MUSIC_NONE, 1, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header FarawayIsland, TILESET_FARAWAY_ISLAND, PERM_5, FARAWAY_ISLAND, MUSIC_ABANDONED_SHIP_RSE, 1, PALETTE_AUTO, FISHGROUP_SHORE
	map_header FarawayJungle, TILESET_FARAWAY_ISLAND, PERM_5, FARAWAY_ISLAND, MUSIC_ABANDONED_SHIP_RSE, 1, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SeagallopFerryVermilionGate, TILESET_PORT, GATE, VERMILION_CITY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_OCEAN
	map_header SeagallopFerryNavelGate, TILESET_PORT, GATE, NAVEL_ROCK, MUSIC_LAKE_OF_RAGE, 1, PALETTE_DAY, FISHGROUP_OCEAN
	map_header SeagallopFerryShamoutiGate, TILESET_PORT, GATE, BEAUTIFUL_BEACH, MUSIC_ROUTE_205_DPPT, 1, PALETTE_DAY, FISHGROUP_OCEAN

MapGroup20:
	map_header PokeCenter2F, TILESET_POKECENTER, INDOOR, SPECIAL_MAP, MUSIC_POKEMON_CENTER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header TradeCenter, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Colosseum, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header HiddenTreeGrotto, TILESET_FOREST, CAVE, SPECIAL_MAP, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header HiddenCaveGrotto, TILESET_CAVE, CAVE, SPECIAL_MAP, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header YellowForestGate, TILESET_GATE, GATE, ROUTE_48, MUSIC_ROUTE_47_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header YellowForest, TILESET_FOREST, ROUTE, YELLOW_FOREST, MUSIC_SAFARI_ZONE_GATE_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header EcruteakShrineOutside, TILESET_JOHTO_TRADITIONAL, ROUTE, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header EcruteakShrineInside, TILESET_TRADITIONAL_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_DANCING_HALL, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup21:
	map_header Route7, TILESET_KANTO, ROUTE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route16Northeast, TILESET_KANTO, ROUTE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route16South, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route17, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_17, MUSIC_BICYCLE_XY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route18West, TILESET_INDIGO_PLATEAU, ROUTE, ROUTE_18, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header UragaChannelEast, TILESET_INDIGO_PLATEAU, ROUTE, URAGA_CHANNEL, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header CeladonCity, TILESET_KANTO, TOWN, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header CeladonDeptStore1F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStore2F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStore3F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStore4F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStore5F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStore6F, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDeptStoreElevator, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonMansion1F, TILESET_CELADON_MANSION, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonMansion2F, TILESET_CELADON_MANSION, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonMansion3F, TILESET_CELADON_MANSION, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonMansionRoof, TILESET_CELADON_MANSION, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header CeladonMansionRoofHouse, TILESET_KANTO_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonPokeCenter1F, TILESET_POKECENTER, INDOOR, CELADON_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonGameCorner, TILESET_GAME_CORNER, INDOOR, CELADON_CITY, MUSIC_GAME_CORNER_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonGameCornerPrizeRoom, TILESET_GAME_CORNER, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonGym, TILESET_MAGNET_TRAIN, INDOOR, CELADON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonCafe, TILESET_GAME_CORNER, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonChiefHouse, TILESET_KANTO_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotel1F, TILESET_HOTEL, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotel2F, TILESET_HOTEL, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotelRoom1, TILESET_HOTEL, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotelRoom2, TILESET_HOTEL, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotelRoom3, TILESET_HOTEL, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHotelPool, TILESET_PORT, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header EusinesHouse, TILESET_KANTO_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PsychicInversHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route16FuchsiaSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_16, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route16Gate, TILESET_GATE, GATE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route1617Gate, TILESET_GATE, GATE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route1617Gate2F, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route7SaffronGate, TILESET_GATE, GATE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route18Gate, TILESET_GATE, GATE, ROUTE_18, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route18Gate2F, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHomeDecorStore1F, TILESET_HOME_DECOR_STORE, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHomeDecorStore2F, TILESET_HOME_DECOR_STORE, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHomeDecorStore3F, TILESET_HOME_DECOR_STORE, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonHomeDecorStore4F, TILESET_HOME_DECOR_STORE, INDOOR, CELADON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversity1F, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversity2F, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityLibrary1F, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityLibrary2F, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityPrincipalsOffice, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityWestwoodsOffice, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityWillowsOffice, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityLounge, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityCafeteria, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityHyperTestRoom, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityPool, TILESET_PORT, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header CeladonUniversityClassroom1, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityClassroom2, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityClassroom3, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonUniversityClassroom4, TILESET_MUSEUM, INDOOR, CELADON_CITY, MUSIC_CANALAVE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonOldManSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonDevelopmentSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, CELADON_CITY, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CeladonOutskirts, TILESET_KANTO, ROUTE, CELADON_OUTSKIRTS, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup22:
	map_header Route40, TILESET_JOHTO_MODERN, ROUTE, ROUTE_40, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route41, TILESET_JOHTO_MODERN, ROUTE, ROUTE_41, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header CianwoodCity, TILESET_JOHTO_MODERN, TOWN, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header ManiasHouse, TILESET_JOHTO_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CianwoodGym, TILESET_SPROUT_TOWER, INDOOR, CIANWOOD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header CianwoodPokeCenter1F, TILESET_POKECENTER, INDOOR, CIANWOOD_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CianwoodPharmacy, TILESET_TRADITIONAL_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CianwoodCityPhotoStudio, TILESET_JOHTO_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CianwoodLugiaSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header StatsJudgesHouse, TILESET_JOHTO_HOUSE, INDOOR, CIANWOOD_CITY, MUSIC_CIANWOOD_CITY_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTower1F, TILESET_BATTLE_TOWER_INSIDE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_LOBBY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTower2F, TILESET_BATTLE_TOWER_INSIDE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_LOBBY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTowerBattleRoom, TILESET_BATTLE_TOWER_INSIDE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTowerElevator, TILESET_BATTLE_TOWER_INSIDE, INDOOR, BATTLE_TOWER, MUSIC_NONE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTowerHallway, TILESET_BATTLE_TOWER_INSIDE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route40BattleTowerGate, TILESET_GATE, GATE, BATTLE_TOWER, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BattleTowerOutside, TILESET_BATTLE_TOWER_OUTSIDE, ROUTE, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup23:
	map_header Route2South, TILESET_KANTO, ROUTE, ROUTE_2, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route22, TILESET_KANTO, ROUTE, ROUTE_22, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header ViridianCity, TILESET_KANTO, TOWN, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header ViridianGym, TILESET_MAGNET_TRAIN, INDOOR, VIRIDIAN_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianNicknameSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianSchoolHouse, TILESET_KANTO_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrainerHouse1F, TILESET_KANTO_HOUSE, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header TrainerHouseB1F, TILESET_FACILITY, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianMart, TILESET_MART, INDOOR, VIRIDIAN_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianPokeCenter1F, TILESET_POKECENTER, INDOOR, VIRIDIAN_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route2NuggetSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route2Gate, TILESET_GATE, GATE, ROUTE_2, MUSIC_ROUTE_1, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PokemonLeagueGate, TILESET_GATE, GATE, POKEMON_LEAGUE, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianForest, TILESET_FOREST, ROUTE, VIRIDIAN_FOREST, MUSIC_VIRIDIAN_FOREST, 0, PALETTE_NITE, FISHGROUP_POND
	map_header ViridianForestViridianGate, TILESET_GATE, GATE, ROUTE_2, MUSIC_ROUTE_1, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ViridianForestPewterGate, TILESET_GATE, GATE, ROUTE_2, MUSIC_ROUTE_1, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route1ViridianGate, TILESET_GATE, GATE, ROUTE_1, MUSIC_ROUTE_1, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route16Northwest, TILESET_KANTO, ROUTE, ROUTE_16, MUSIC_ROUTE_225_DPPT, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route16West, TILESET_KANTO, ROUTE, ROUTE_16, MUSIC_ROUTE_225_DPPT, 0, PALETTE_AUTO, FISHGROUP_SHORE

MapGroup24:
	map_header Route26, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_26, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route27, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_27, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route29, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_29, MUSIC_ROUTE_29, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header NewBarkTown, TILESET_JOHTO_TRADITIONAL, TOWN, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header ElmsLab, TILESET_LAB, INDOOR, NEW_BARK_TOWN, MUSIC_PROF_ELM, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissHouse1F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissHouse2F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header KrissNeighborsHouse, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LyrasHouse1F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header LyrasHouse2F, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ElmsHouse, TILESET_JOHTO_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route26HealSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_26, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route26DayofWeekSiblingsHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_26, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route27RestHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_27, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route2946Gate, TILESET_GATE, GATE, ROUTE_29, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup25:
	map_header FightingDojo, TILESET_MAGNET_TRAIN, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronGym, TILESET_GAME_CORNER, INDOOR, SAFFRON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronMart, TILESET_MART, INDOOR, SAFFRON_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronPokeCenter1F, TILESET_POKECENTER, INDOOR, SAFFRON_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MrPsychicsHouse, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronTrainStation, TILESET_MAGNET_TRAIN, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SilphCo1F, TILESET_FACILITY, INDOOR, SAFFRON_CITY, MUSIC_BLACK_CITY_BW, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SilphCo2F, TILESET_CELADON_MANSION, INDOOR, SAFFRON_CITY, MUSIC_BLACK_CITY_BW, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SilphCo3F, TILESET_CELADON_MANSION, INDOOR, SAFFRON_CITY, MUSIC_BLACK_CITY_BW, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CopycatsHouse1F, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CopycatsHouse2F, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route5, TILESET_KANTO, ROUTE, ROUTE_5, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route5UndergroundEntrance, TILESET_FACILITY, GATE, ROUTE_5, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route5SaffronCityGate, TILESET_GATE, GATE, ROUTE_5, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route5CleanseTagSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, ROUTE_5, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header PokemonTrainerFanClub, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronHitmontopKidHouse, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronBookSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronOrreSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SaffronRichSpeechHouse, TILESET_KANTO_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup26:
	map_header Route30, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_30, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route31, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_31, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header CherrygroveBay, TILESET_JOHTO_TRADITIONAL, ROUTE, CHERRYGROVE_BAY, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header CherrygroveCity, TILESET_JOHTO_TRADITIONAL, TOWN, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header CherrygroveMart, TILESET_MART, INDOOR, CHERRYGROVE_CITY, MUSIC_MART_HGSS, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CherrygrovePokeCenter1F, TILESET_POKECENTER, INDOOR, CHERRYGROVE_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CherrygroveGymSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header GuideGentsHouse, TILESET_JOHTO_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header CherrygroveEvolutionSpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route30BerrySpeechHouse, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_30, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header MrPokemonsHouse, TILESET_JOHTO_HOUSE, INDOOR, ROUTE_30, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route31VioletGate, TILESET_GATE, GATE, ROUTE_31, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup27:
	map_header CliffEdgeGate, TILESET_CAVE, CAVE, CLIFF_EDGE_GATE, MUSIC_ROUTE_36, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header CliffCave, TILESET_CAVE, CAVE, CLIFF_CAVE, MUSIC_ROUTE_47_HGSS, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header Route47, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_47, MUSIC_ROUTE_47_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route48, TILESET_JOHTO_OVERCAST, ROUTE, ROUTE_48, MUSIC_ROUTE_47_HGSS, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header QuietCave1F, TILESET_QUIET_CAVE, CAVE, QUIET_CAVE, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header QuietCaveB1F, TILESET_QUIET_CAVE, CAVE, QUIET_CAVE, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header QuietCaveB2F, TILESET_QUIET_CAVE, CAVE, QUIET_CAVE, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header QuietCaveB3F, TILESET_QUIET_CAVE, CAVE, QUIET_CAVE, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_LAKE

MapGroup28:
	map_header Route9, TILESET_KANTO, ROUTE, ROUTE_9, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route10North, TILESET_KANTO, ROUTE, ROUTE_10, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header DimCave1F, TILESET_CAVE, CAVE, DIM_CAVE, MUSIC_MOUNT_CHIMNEY_RSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DimCave2F, TILESET_CAVE, CAVE, DIM_CAVE, MUSIC_MOUNT_CHIMNEY_RSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DimCave3F, TILESET_CAVE, CAVE, DIM_CAVE, MUSIC_MOUNT_CHIMNEY_RSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DimCave4F, TILESET_CAVE, CAVE, DIM_CAVE, MUSIC_MOUNT_CHIMNEY_RSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header DimCave5F, TILESET_CAVE, CAVE, DIM_CAVE, MUSIC_MOUNT_CHIMNEY_RSE, 1, PALETTE_NITE, FISHGROUP_LAKE

MapGroup29:
	map_header GoldenrodHarbor, TILESET_JOHTO_MODERN, ROUTE, GOLDENROD_HARBOR, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header GoldenrodHarborGate, TILESET_GATE, GATE, GOLDENROD_CITY, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup30:
	map_header RuinsofAlphOutside, TILESET_JOHTO_OVERCAST, ROUTE, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header RuinsofAlphHoOhChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphKabutoChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphOmanyteChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphAerodactylChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphEntranceChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_RUINS_OF_ALPH_INTERIOR, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphInnerChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_RUINS_OF_ALPH_INTERIOR, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphResearchCenter, TILESET_FACILITY, INDOOR, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphHoOhItemRoom, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphKabutoItemRoom, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphOmanyteItemRoom, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphAerodactylItemRoom, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphHoOhWordRoom, TILESET_ALPH_WORD_ROOM, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphKabutoWordRoom, TILESET_ALPH_WORD_ROOM, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphOmanyteWordRoom, TILESET_ALPH_WORD_ROOM, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphAerodactylWordRoom, TILESET_ALPH_WORD_ROOM, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header RuinsofAlphSinjohChamber, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route22Past, TILESET_KANTO, PERM_5, ROUTE_22, MUSIC_ROUTE_3, 1, PALETTE_NITE, FISHGROUP_POND

MapGroup31:
	map_header ShamoutiIsland, TILESET_SHAMOUTI_ISLAND, TOWN, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header BeautifulBeach, TILESET_SHAMOUTI_ISLAND, ROUTE, BEAUTIFUL_BEACH, MUSIC_ROUTE_205_DPPT, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header WarmBeach, TILESET_SHAMOUTI_ISLAND, ROUTE, WARM_BEACH, MUSIC_ROUTE_12_BW, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header ShamoutiCoast, TILESET_SHAMOUTI_ISLAND, ROUTE, SHAMOUTI_COAST, MUSIC_ROUTE_12_BW, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header RockyBeach, TILESET_SHAMOUTI_ISLAND, ROUTE, ROCKY_BEACH, MUSIC_ROUTE_203_DPPT, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header ShamoutiTunnel, TILESET_TUNNEL, CAVE, SHAMOUTI_TUNNEL, MUSIC_OREBURGH_GATE_DPPT, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header NoisyForest, TILESET_SHAMOUTI_ISLAND, CAVE, NOISY_FOREST, MUSIC_WHITE_TREEHOLLOW_W2, 0, PALETTE_NITE, FISHGROUP_POND
	map_header ShamoutiPokeCenter1F, TILESET_POKECENTER, INDOOR, SHAMOUTI_ISLAND, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotel1F, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotel2F, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotel3F, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotelRoom2A, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotelRoom2B, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotelRoom3B, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotelRoom3C, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHotelRestaurant, TILESET_HOTEL, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiTouristCenter, TILESET_JOHTO_HOUSE, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiMerchant, TILESET_JOHTO_HOUSE, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ShamoutiHouse, TILESET_JOHTO_HOUSE, INDOOR, SHAMOUTI_ISLAND, MUSIC_SUNYSHORE_CITY_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header BeautifulBeachVilla, TILESET_JOHTO_HOUSE, INDOOR, BEAUTIFUL_BEACH, MUSIC_ROUTE_205_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header WarmBeachShack, TILESET_JOHTO_HOUSE, INDOOR, WARM_BEACH, MUSIC_ROUTE_12_BW, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header WarmBeachHouse, TILESET_JOHTO_HOUSE, INDOOR, WARM_BEACH, MUSIC_ROUTE_12_BW, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header RockyBeachHouse, TILESET_JOHTO_HOUSE, INDOOR, ROCKY_BEACH, MUSIC_ROUTE_203_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header FireIsland, TILESET_QUIET_CAVE, CAVE, FIRE_ISLAND, MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header FireIslandRoof, TILESET_SHAMOUTI_ISLAND, ROUTE, FIRE_ISLAND, MUSIC_LAVERRE_CITY_XY, 1, PALETTE_AUTO, FISHGROUP_LAKE
	map_header IceIsland, TILESET_ICE_PATH, CAVE, ICE_ISLAND, MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header IceIslandRoof, TILESET_SHAMOUTI_ISLAND, ROUTE, ICE_ISLAND, MUSIC_LAVERRE_CITY_XY, 1, PALETTE_AUTO, FISHGROUP_LAKE
	map_header LightningIsland, TILESET_TUNNEL, CAVE, LIGHTNING_ISLAND, MUSIC_ROAD_TO_REVERSAL_MOUNTAIN_B2W2, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header LightningIslandRoof, TILESET_SHAMOUTI_ISLAND, ROUTE, LIGHTNING_ISLAND, MUSIC_LAVERRE_CITY_XY, 1, PALETTE_AUTO, FISHGROUP_LAKE

MapGroup32:
	map_header SafariZoneHub, TILESET_SAFARI_ZONE, ROUTE, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_AUTO, FISHGROUP_DRATINI
	map_header SafariZoneEast, TILESET_SAFARI_ZONE, ROUTE, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_AUTO, FISHGROUP_DRATINI
	map_header SafariZoneNorth, TILESET_SAFARI_ZONE, ROUTE, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_AUTO, FISHGROUP_DRATINI
	map_header SafariZoneWest, TILESET_SAFARI_ZONE, ROUTE, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_AUTO, FISHGROUP_DRATINI
	map_header SafariZoneHubRestHouse, TILESET_FACILITY, INDOOR, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneEastRestHouse, TILESET_FACILITY, INDOOR, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneNorthRestHouse, TILESET_FACILITY, INDOOR, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneWestRestHouse1, TILESET_FACILITY, INDOOR, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header SafariZoneWestRestHouse2, TILESET_FACILITY, INDOOR, SAFARI_ZONE, MUSIC_ROUTE_210_DPPT, 0, PALETTE_DAY, FISHGROUP_SHORE

MapGroup33:
	map_header ValenciaIsland, TILESET_VALENCIA_ISLAND, TOWN, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY_RSE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route49, TILESET_VALENCIA_ISLAND, ROUTE, ROUTE_49, MUSIC_ROUTE_101_RSE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header IvysLab, TILESET_LAB, INDOOR, VALENCIA_ISLAND, MUSIC_PROF_ELM, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header IvysHouse, TILESET_JOHTO_HOUSE, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY_RSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ValenciaHouse, TILESET_JOHTO_HOUSE, INDOOR, VALENCIA_ISLAND, MUSIC_EVER_GRANDE_CITY_RSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header ValenciaPort, TILESET_PORT, GATE, ROUTE_49, MUSIC_ROUTE_101_RSE, 0, PALETTE_DAY, FISHGROUP_OCEAN

MapGroup34:
	map_header SinjohRuins, TILESET_JOHTO_OVERCAST, PERM_5, SINJOH_RUINS, MUSIC_MOUNT_CORONET_DPPT, 1, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SinjohRuinsHouse, TILESET_JOHTO_HOUSE, INDOOR, SINJOH_RUINS, MUSIC_MOUNT_CORONET_DPPT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header MystriStage, TILESET_SPROUT_TOWER, DUNGEON, MYSTRI_STAGE, MUSIC_MOUNT_CORONET_DPPT, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header EmbeddedTower, TILESET_SPROUT_TOWER, DUNGEON, ROUTE_47, MUSIC_CELESTIAL_TOWER_BW, 1, PALETTE_NITE, FISHGROUP_SHORE

MapGroup35:
	map_header SaffronCity, TILESET_KANTO, TOWN, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header ShamoutiShrineRuins, TILESET_SHAMOUTI_ISLAND, ROUTE, SHRINE_RUINS, MUSIC_LAVERRE_CITY_XY, 0, PALETTE_AUTO, FISHGROUP_OCEAN

MapGroup36:
	map_header Route35, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_35, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route36, TILESET_JOHTO_TRADITIONAL, ROUTE, ROUTE_36, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route35GoldenrodGate, TILESET_GATE, GATE, ROUTE_35, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route35NationalParkGate, TILESET_GATE, INDOOR, ROUTE_35, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route36RuinsofAlphGate, TILESET_GATE, GATE, ROUTE_36, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route36NationalParkGate, TILESET_GATE, INDOOR, ROUTE_36, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header Route36VioletGate, TILESET_GATE, GATE, ROUTE_36, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
