SeafoamIslandsB1F_MapScriptHeader:

.MapTriggers: db 0

.MapCallbacks: db 0

SeafoamIslandsB1F_MapEventHeader:

.Warps: db 6
	warp_def $f, $23, 3, SEAFOAM_ISLANDS_1F
	warp_def $3, $3, 5, SEAFOAM_ISLANDS_1F
	warp_def $f, $1b, 1, SEAFOAM_ISLANDS_B2F
	warp_def $5, $12, 2, SEAFOAM_ISLANDS_B2F
	warp_def $b, $f, 3, SEAFOAM_ISLANDS_B2F
	warp_def $f, $7, 4, SEAFOAM_ISLANDS_B2F

.XYTriggers: db 0

.Signposts: db 1
	signpost 11, 20, SIGNPOST_ITEM, SeafoamIslandsB1FHiddenIceHeal

.PersonEvents: db 8
	person_event SPRITE_BALL_CUT_FRUIT, 3, 20, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, (1 << 3) | PAL_OW_RED, PERSONTYPE_POKEBALL, PLAYEREVENT_ITEMBALL, GRIP_CLAW, 1, EVENT_SEAFOAM_ISLANDS_B1F_GRIP_CLAW
	person_event SPRITE_BALL_CUT_FRUIT, 5, 24, SPRITEMOVEDATA_STANDING_DOWN, 0, 0, -1, -1, (1 << 3) | PAL_OW_RED, PERSONTYPE_POKEBALL, PLAYEREVENT_ITEMBALL, ICE_HEAL, 1, EVENT_SEAFOAM_ISLANDS_B1F_ICE_HEAL
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 9, 30, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 9, 31, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 10, 32, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 8, 12, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 11, 7, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1
	person_event SPRITE_ROCK_BOULDER_FOSSIL, 15, 13, SPRITEMOVEDATA_STRENGTH_BOULDER, 0, 0, -1, -1, 0, PERSONTYPE_COMMAND, jumpstd, strengthboulder, 0, -1

SeafoamIslandsB1FHiddenIceHeal:
	dwb EVENT_SEAFOAM_ISLANDS_B1F_HIDDEN_ICE_HEAL, ICE_HEAL
