	dw NormalHit
	dw NormalHit
	dw NormalHit
	dw LeechHit
	dw MultiHit
	dw MultiHit
	dw RecoilHit
	dw FlinchHit
	dw PoisonHit
	dw BurnHit
	dw ParalyzeHit
	dw SleepHit
	dw FreezeHit
	dw ConfuseHit
	dw AttackUpHit
	dw DefenseUpHit
	dw AllUpHit
	dw AttackDownHit
	dw DefenseDownHit
	dw SpeedDownHit
	dw SpecialAttackDownHit
	dw SpecialDefenseDownHit
	dw AccuracyDownHit
	dw EvasionDownHit
	dw StaticDamage
	dw StaticDamage
	dw OHKOHit
	dw DoPoison
	dw DoBurn
	dw DoParalyze
	dw DoSleep
	dw DoFreeze
	dw DoConfuse
	dw Toxic
	dw AttackUp
	dw DefenseUp
	dw SpeedUp
	dw SpecialAttackUp
	dw SpecialDefenseUp
	dw AccuracyUp
	dw EvasionUp
	dw FocusEnergy
	dw AttackUp2
	dw DefenseUp2
	dw SpeedUp2
	dw SpecialAttackUp2
	dw SpecialDefenseUp2
	dw AccuracyUp2
	dw EvasionUp2
	dw BulkUp
	dw CalmMind
	dw Growth
	dw DragonDance
	dw AttackDown
	dw DefenseDown
	dw StringShot
	dw SpecialAttackDown
	dw SpecialDefenseDown
	dw AccuracyDown
	dw EvasionDown
	dw AttackDown2
	dw DefenseDown2
	dw SpeedDown2
	dw SpecialAttackDown2
	dw SpecialDefenseDown2
	dw AccuracyDown2
	dw EvasionDown2
	dw ResetStats
	dw Mist
	dw Safeguard
	dw Reflect
	dw LightScreen
	dw Heal
	dw Rampage
	dw Trap
	dw Explosion
	dw DreamEater
	dw MirrorMove
	dw Whirlwind
	dw Conversion
	dw PayDay
	dw TriAttack
	dw SuperFang
	dw Transform
	dw SkyAttack
	dw Twineedle
	dw Substitute
	dw HyperBeam
	dw Rage
	dw Metronome
	dw LeechSeed
	dw Splash
	dw Disable
	dw Counter
	dw Encore
	dw PainSplit
	dw Conversion2
	dw LockOn
	dw Sketch
	dw SleepTalk
	dw DestinyBond
	dw Reversal
	dw FalseSwipe
	dw HealBell
	dw TripleKick
	dw Thief
	dw MeanLook
	dw Nightmare
	dw FlameWheel
	dw Curse
	dw Protect
	dw Spikes
	dw Foresight
	dw PerishSong
	dw Sandstorm
	dw Endure
	dw Rollout
	dw Swagger
	dw FuryCutter
	dw Attract
	dw Return
	dw SacredFire
	dw Magnitude
	dw BatonPass
	dw Pursuit
	dw RapidSpin
	dw MorningSun
	dw Synthesis
	dw Moonlight
	dw HiddenPower
	dw RainDance
	dw SunnyDay
	dw BellyDrum
	dw MirrorCoat
	dw Twister
	dw Earthquake
	dw FutureSight
	dw Gust
	dw Stomp
	dw Solarbeam
	dw Thunder
	dw Teleport
	dw Fly
	dw DefenseCurl
	dw NormalHit
	dw Bide
	dw RazorWind
	dw Mimic
	dw Psywave
	dw Snore
	dw DefrostOpponent
	dw Spite
	dw Present
	dw Frustration
	dw FakeOut
	dw PsychUp
	dw SkullBash
	dw BeatUp
