ChrisSpriteGFX:        INCBIN "gfx/overworld/chris.2bpp" ; c0000
ChrisBikeSpriteGFX:    INCBIN "gfx/overworld/chris_bike.2bpp" ; c0180
GameboyKidSpriteGFX:   INCBIN "gfx/overworld/gameboy_kid.2bpp" ; c0300
SilverSpriteGFX:       INCBIN "gfx/overworld/silver.2bpp" ; c03c0
OakSpriteGFX:          INCBIN "gfx/overworld/oak.2bpp" ; c0540
RedSpriteGFX:          INCBIN "gfx/overworld/red.2bpp" ; c06c0
BlueSpriteGFX:         INCBIN "gfx/overworld/blue.2bpp" ; c0840
BillSpriteGFX:         INCBIN "gfx/overworld/bill.2bpp" ; c09c0
ElderSpriteGFX:        INCBIN "gfx/overworld/elder.2bpp" ; c0b40
JanineSpriteGFX:       INCBIN "gfx/overworld/janine.2bpp" ; c0cc0
KurtSpriteGFX:         INCBIN "gfx/overworld/kurt.2bpp" ; c0e40
MomSpriteGFX:          INCBIN "gfx/overworld/mom.2bpp" ; c0fc0
BlaineSpriteGFX:       INCBIN "gfx/overworld/blaine.2bpp" ; c1140
RedsMomSpriteGFX:      INCBIN "gfx/overworld/reds_mom.2bpp" ; c12c0
DaisySpriteGFX:        INCBIN "gfx/overworld/daisy.2bpp" ; c1440
ElmSpriteGFX:          INCBIN "gfx/overworld/elm.2bpp" ; c15c0
WillSpriteGFX:         INCBIN "gfx/overworld/will.2bpp" ; c1740
FalknerSpriteGFX:      INCBIN "gfx/overworld/falkner.2bpp" ; c1800
WhitneySpriteGFX:      INCBIN "gfx/overworld/whitney.2bpp" ; c1980
BugsySpriteGFX:        INCBIN "gfx/overworld/bugsy.2bpp" ; c1b00
MortySpriteGFX:        INCBIN "gfx/overworld/morty.2bpp" ; c1c80
ChuckSpriteGFX:        INCBIN "gfx/overworld/chuck.2bpp" ; c1e00
JasmineSpriteGFX:      INCBIN "gfx/overworld/jasmine.2bpp" ; c1f80
PryceSpriteGFX:        INCBIN "gfx/overworld/pryce.2bpp" ; c2100
ClairSpriteGFX:        INCBIN "gfx/overworld/clair.2bpp" ; c2280
BrockSpriteGFX:        INCBIN "gfx/overworld/brock.2bpp" ; c2400
KarenSpriteGFX:        INCBIN "gfx/overworld/karen.2bpp" ; c2580
BrunoSpriteGFX:        INCBIN "gfx/overworld/bruno.2bpp" ; c2640
MistySpriteGFX:        INCBIN "gfx/overworld/misty.2bpp" ; c27c0
LanceSpriteGFX:        INCBIN "gfx/overworld/lance.2bpp" ; c2940
SurgeSpriteGFX:        INCBIN "gfx/overworld/surge.2bpp" ; c2ac0
ErikaSpriteGFX:        INCBIN "gfx/overworld/erika.2bpp" ; c2c40
KogaSpriteGFX:         INCBIN "gfx/overworld/koga.2bpp" ; c2dc0
SabrinaSpriteGFX:      INCBIN "gfx/overworld/sabrina.2bpp" ; c2f40
CooltrainerMSpriteGFX: INCBIN "gfx/overworld/cooltrainer_m.2bpp" ; c30c0
CooltrainerFSpriteGFX: INCBIN "gfx/overworld/cooltrainer_f.2bpp" ; c3240
BugCatcherSpriteGFX:   INCBIN "gfx/overworld/bug_catcher.2bpp" ; c33c0
TwinSpriteGFX:         INCBIN "gfx/overworld/twin.2bpp" ; c3540
YoungsterSpriteGFX:    INCBIN "gfx/overworld/youngster.2bpp" ; c36c0
LassSpriteGFX:         INCBIN "gfx/overworld/lass.2bpp" ; c3840
TeacherSpriteGFX:      INCBIN "gfx/overworld/teacher.2bpp" ; c39c0
BuenaSpriteGFX:        INCBIN "gfx/overworld/buena.2bpp" ; c3b40
SuperNerdSpriteGFX:    INCBIN "gfx/overworld/super_nerd.2bpp" ; c3cc0
RockerSpriteGFX:       INCBIN "gfx/overworld/rocker.2bpp" ; c3e40
