LoreleiSpriteGFX:             INCBIN "gfx/overworld/102.2bpp"
AgathaSpriteGFX:              INCBIN "gfx/overworld/103.2bpp"
YellowSpriteGFX:              INCBIN "gfx/overworld/104.2bpp"
LeafSpriteGFX:                INCBIN "gfx/overworld/105.2bpp"
LawrenceSpriteGFX:            INCBIN "gfx/overworld/106.2bpp"
