BakerSpriteGFX:               INCBIN "gfx/overworld/pokefan_f.2bpp" ; TODO
BeautySpriteGFX:              INCBIN "gfx/overworld/beauty.2bpp"
BoarderSpriteGFX:             INCBIN "gfx/overworld/boarder.2bpp"
BreederSpriteGFX:             INCBIN "gfx/overworld/breeder.2bpp"
BugManiacSpriteGFX:           INCBIN "gfx/overworld/bug_maniac.2bpp"
ChildSpriteGFX:               INCBIN "gfx/overworld/child.2bpp"
CosplayerSpriteGFX:           INCBIN "gfx/overworld/lady.2bpp" ; TODO
EngineerSpriteGFX:            INCBIN "gfx/overworld/engineer.2bpp"
OfficerFSpriteGFX:            INCBIN "gfx/overworld/officer_f.2bpp"
SilphEmployeeSpriteGFX:       INCBIN "gfx/overworld/silph_employee.2bpp"
SwimmingOfficerFSpriteGFX:    INCBIN "gfx/overworld/swimming_officer_f.2bpp"
SwimmingOfficerSpriteGFX:     INCBIN "gfx/overworld/swimming_officer.2bpp"
ArmoredMewtwoSpriteGFX:       INCBIN "gfx/overworld/armored_mewtwo.2bpp"
CelebiSpriteGFX:              INCBIN "gfx/overworld/celebi.2bpp"
EeveeSpriteGFX:               INCBIN "gfx/overworld/eevee.2bpp"
MewSpriteGFX:                 INCBIN "gfx/overworld/mew.2bpp"
UnownWSpriteGFX:              INCBIN "gfx/overworld/unown_w.2bpp"
UnownASpriteGFX:              INCBIN "gfx/overworld/unown_a.2bpp"
UnownRSpriteGFX:              INCBIN "gfx/overworld/unown_r.2bpp"
UnownPSpriteGFX:              INCBIN "gfx/overworld/unown_p.2bpp"
SignSpriteGFX:                INCBIN "gfx/overworld/sign.2bpp"
GyaradosTopLeftSpriteGFX:     INCBIN "gfx/overworld/gyarados_top_left.2bpp"
GyaradosTopRightSpriteGFX:    INCBIN "gfx/overworld/gyarados_top_right.2bpp"
GyaradosBottomLeftSpriteGFX:  INCBIN "gfx/overworld/gyarados_bottom_left.2bpp"
GyaradosBottomRightSpriteGFX: INCBIN "gfx/overworld/gyarados_bottom_right.2bpp"
ElectricFenceLeftSpriteGFX:   INCBIN "gfx/overworld/electric_fence_left.2bpp"
ElectricFenceRightSpriteGFX:  INCBIN "gfx/overworld/electric_fence_right.2bpp"
