#!/usr/bin/env python3
"""Generate the capped byte-Huffman map used by streamed music data."""

from __future__ import annotations

import argparse
import heapq
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


ESCAPE_SYMBOL = 0x100
DIRECT_LEAVES = 127
CORPUS_RE = re.compile(r"^\$([0-9a-fA-F]{2})$")


@dataclass
class Node:
	frequency: int
	symbol: int | None = None
	left: "Node | None" = None
	right: "Node | None" = None


def read_frequencies(path: Path) -> Counter[int]:
	frequencies: Counter[int] = Counter()
	for line in path.read_text(encoding="utf-8").splitlines():
		match = CORPUS_RE.match(line.strip())
		if match:
			frequencies[int(match.group(1), 16)] += 1
	if not frequencies:
		raise SystemExit("music corpus has no $xx byte lines")
	return frequencies


def make_codes(frequencies: Counter[int]) -> dict[int, str]:
	heap: list[tuple[int, int, Node]] = []
	for serial, symbol in enumerate(sorted(frequencies)):
		heap.append((frequencies[symbol], serial, Node(frequencies[symbol], symbol)))
	heapq.heapify(heap)
	serial = len(heap)
	while len(heap) > 1:
		left_frequency, _, left = heapq.heappop(heap)
		right_frequency, _, right = heapq.heappop(heap)
		heapq.heappush(
			heap,
			(
				left_frequency + right_frequency,
				serial,
				Node(left_frequency + right_frequency, left=left, right=right),
			),
		)
		serial += 1
	codes: dict[int, str] = {}
	stack = [(heap[0][2], "")]
	while stack:
		node, prefix = stack.pop()
		if node.symbol is not None:
			codes[node.symbol] = prefix or "0"
			continue
		assert node.left is not None and node.right is not None
		stack.append((node.right, prefix + "1"))
		stack.append((node.left, prefix + "0"))
	return codes


def render(frequencies: Counter[int]) -> str:
	direct = sorted(
		(
			value
			for value, _ in sorted(
				frequencies.items(), key=lambda item: (-item[1], item[0])
			)[:DIRECT_LEAVES]
		)
	)
	direct_set = set(direct)
	tree_frequencies = Counter({value: frequencies[value] for value in direct})
	tree_frequencies[ESCAPE_SYMBOL] = sum(
		frequency
		for value, frequency in frequencies.items()
		if value not in direct_set
	)
	codes = make_codes(tree_frequencies)
	escape_code = codes[ESCAPE_SYMBOL]
	max_length = max(
		len(codes[value]) if value in direct_set else len(escape_code) + 8
		for value in range(0x100)
	)
	if max_length > 31:
		raise SystemExit(f"longest generated music code is {max_length} bits")
	lines = [
		"; Generated by utils/music_huffman.py; do not edit manually.",
		"; Source corpus: MUSIC_HUFFMAN byte log from the assembled music streams.",
		f"; {DIRECT_LEAVES} direct leaves plus one raw-byte escape leaf.",
		f"; Longest encoded byte: {max_length} bits.",
		"",
		f"musichuffleaf {escape_code}",
	]
	for leaf, value in enumerate(direct):
		lines.append(
			f"musichuffmap ${value:02x}, {leaf}, {codes[value]} ; {frequencies[value]}"
		)
	for value in range(0x100):
		if value in direct_set:
			continue
		code = escape_code + f"{value:08b}"
		lines.append(
			f"musichuffesc ${value:02x}, {code} ; {frequencies[value]}"
		)
	lines.append("")
	return "\n".join(lines)


def main() -> None:
	parser = argparse.ArgumentParser()
	parser.add_argument("corpus", type=Path)
	parser.add_argument("output", type=Path, nargs="?")
	args = parser.parse_args()
	output = render(read_frequencies(args.corpus))
	if args.output:
		args.output.write_text(output, encoding="utf-8")
	else:
		print(output, end="")


if __name__ == "__main__":
	main()
