BulbasaurAnimation:  INCLUDE "gfx/pokemon/bulbasaur/anim.asm"
IvysaurAnimation:    INCLUDE "gfx/pokemon/ivysaur/anim.asm"
VenusaurAnimation:   INCLUDE "gfx/pokemon/venusaur/anim.asm"
CharmanderAnimation: INCLUDE "gfx/pokemon/charmander/anim.asm"
CharmeleonAnimation: INCLUDE "gfx/pokemon/charmeleon/anim.asm"
CharizardAnimation:  INCLUDE "gfx/pokemon/charizard/anim.asm"
SquirtleAnimation:   INCLUDE "gfx/pokemon/squirtle/anim.asm"
WartortleAnimation:  INCLUDE "gfx/pokemon/wartortle/anim.asm"
BlastoiseAnimation:  INCLUDE "gfx/pokemon/blastoise/anim.asm"
CaterpieAnimation:   INCLUDE "gfx/pokemon/caterpie/anim.asm"
MetapodAnimation:    INCLUDE "gfx/pokemon/metapod/anim.asm"
ButterfreeAnimation: INCLUDE "gfx/pokemon/butterfree/anim.asm"
WeedleAnimation:     INCLUDE "gfx/pokemon/weedle/anim.asm"
KakunaAnimation:     INCLUDE "gfx/pokemon/kakuna/anim.asm"
BeedrillAnimation:   INCLUDE "gfx/pokemon/beedrill/anim.asm"
PidgeyAnimation:     INCLUDE "gfx/pokemon/pidgey/anim.asm"
PidgeottoAnimation:  INCLUDE "gfx/pokemon/pidgeotto/anim.asm"
PidgeotAnimation:    INCLUDE "gfx/pokemon/pidgeot/anim.asm"
SpearowAnimation:    INCLUDE "gfx/pokemon/spearow/anim.asm"
FearowAnimation:     INCLUDE "gfx/pokemon/fearow/anim.asm"
EkansAnimation:      INCLUDE "gfx/pokemon/ekans/anim.asm"
NidoranFAnimation:   INCLUDE "gfx/pokemon/nidoran_f/anim.asm"
NidorinaAnimation:   INCLUDE "gfx/pokemon/nidorina/anim.asm"
NidoqueenAnimation:  INCLUDE "gfx/pokemon/nidoqueen/anim.asm"
NidoranMAnimation:   INCLUDE "gfx/pokemon/nidoran_m/anim.asm"
NidorinoAnimation:   INCLUDE "gfx/pokemon/nidorino/anim.asm"
NidokingAnimation:   INCLUDE "gfx/pokemon/nidoking/anim.asm"
ClefairyAnimation:   INCLUDE "gfx/pokemon/clefairy/anim.asm"
ClefableAnimation:   INCLUDE "gfx/pokemon/clefable/anim.asm"
JigglypuffAnimation: INCLUDE "gfx/pokemon/jigglypuff/anim.asm"
WigglytuffAnimation: INCLUDE "gfx/pokemon/wigglytuff/anim.asm"
ZubatAnimation:      INCLUDE "gfx/pokemon/zubat/anim.asm"
GolbatAnimation:     INCLUDE "gfx/pokemon/golbat/anim.asm"
OddishAnimation:     INCLUDE "gfx/pokemon/oddish/anim.asm"
GloomAnimation:      INCLUDE "gfx/pokemon/gloom/anim.asm"
VileplumeAnimation:  INCLUDE "gfx/pokemon/vileplume/anim.asm"
ParasAnimation:      INCLUDE "gfx/pokemon/paras/anim.asm"
ParasectAnimation:   INCLUDE "gfx/pokemon/parasect/anim.asm"
VenonatAnimation:    INCLUDE "gfx/pokemon/venonat/anim.asm"
VenomothAnimation:   INCLUDE "gfx/pokemon/venomoth/anim.asm"
PsyduckAnimation:    INCLUDE "gfx/pokemon/psyduck/anim.asm"
GolduckAnimation:    INCLUDE "gfx/pokemon/golduck/anim.asm"
MankeyAnimation:     INCLUDE "gfx/pokemon/mankey/anim.asm"
PrimeapeAnimation:   INCLUDE "gfx/pokemon/primeape/anim.asm"
PoliwagAnimation:    INCLUDE "gfx/pokemon/poliwag/anim.asm"
PoliwhirlAnimation:  INCLUDE "gfx/pokemon/poliwhirl/anim.asm"
PoliwrathAnimation:  INCLUDE "gfx/pokemon/poliwrath/anim.asm"
AbraAnimation:       INCLUDE "gfx/pokemon/abra/anim.asm"
KadabraAnimation:    INCLUDE "gfx/pokemon/kadabra/anim.asm"
AlakazamAnimation:   INCLUDE "gfx/pokemon/alakazam/anim.asm"
MachopAnimation:     INCLUDE "gfx/pokemon/machop/anim.asm"
MachokeAnimation:    INCLUDE "gfx/pokemon/machoke/anim.asm"
MachampAnimation:    INCLUDE "gfx/pokemon/machamp/anim.asm"
BellsproutAnimation: INCLUDE "gfx/pokemon/bellsprout/anim.asm"
WeepinbellAnimation: INCLUDE "gfx/pokemon/weepinbell/anim.asm"
VictreebelAnimation: INCLUDE "gfx/pokemon/victreebel/anim.asm"
TentacoolAnimation:  INCLUDE "gfx/pokemon/tentacool/anim.asm"
TentacruelAnimation: INCLUDE "gfx/pokemon/tentacruel/anim.asm"
MagnemiteAnimation:  INCLUDE "gfx/pokemon/magnemite/anim.asm"
MagnetonAnimation:   INCLUDE "gfx/pokemon/magneton/anim.asm"
DoduoAnimation:      INCLUDE "gfx/pokemon/doduo/anim.asm"
DodrioAnimation:     INCLUDE "gfx/pokemon/dodrio/anim.asm"
SeelAnimation:       INCLUDE "gfx/pokemon/seel/anim.asm"
DewgongAnimation:    INCLUDE "gfx/pokemon/dewgong/anim.asm"
ShellderAnimation:   INCLUDE "gfx/pokemon/shellder/anim.asm"
CloysterAnimation:   INCLUDE "gfx/pokemon/cloyster/anim.asm"
GastlyAnimation:     INCLUDE "gfx/pokemon/gastly/anim.asm"
HaunterAnimation:    INCLUDE "gfx/pokemon/haunter/anim.asm"
GengarAnimation:     INCLUDE "gfx/pokemon/gengar/anim.asm"
OnixAnimation:       INCLUDE "gfx/pokemon/onix/anim.asm"
DrowzeeAnimation:    INCLUDE "gfx/pokemon/drowzee/anim.asm"
HypnoAnimation:      INCLUDE "gfx/pokemon/hypno/anim.asm"
KrabbyAnimation:     INCLUDE "gfx/pokemon/krabby/anim.asm"
KinglerAnimation:    INCLUDE "gfx/pokemon/kingler/anim.asm"
ExeggcuteAnimation:  INCLUDE "gfx/pokemon/exeggcute/anim.asm"
CuboneAnimation:     INCLUDE "gfx/pokemon/cubone/anim.asm"
HitmonleeAnimation:  INCLUDE "gfx/pokemon/hitmonlee/anim.asm"
HitmonchanAnimation: INCLUDE "gfx/pokemon/hitmonchan/anim.asm"
LickitungAnimation:  INCLUDE "gfx/pokemon/lickitung/anim.asm"
KoffingAnimation:    INCLUDE "gfx/pokemon/koffing/anim.asm"
RhyhornAnimation:    INCLUDE "gfx/pokemon/rhyhorn/anim.asm"
RhydonAnimation:     INCLUDE "gfx/pokemon/rhydon/anim.asm"
ChanseyAnimation:    INCLUDE "gfx/pokemon/chansey/anim.asm"
TangelaAnimation:    INCLUDE "gfx/pokemon/tangela/anim.asm"
KangaskhanAnimation: INCLUDE "gfx/pokemon/kangaskhan/anim.asm"
HorseaAnimation:     INCLUDE "gfx/pokemon/horsea/anim.asm"
SeadraAnimation:     INCLUDE "gfx/pokemon/seadra/anim.asm"
GoldeenAnimation:    INCLUDE "gfx/pokemon/goldeen/anim.asm"
SeakingAnimation:    INCLUDE "gfx/pokemon/seaking/anim.asm"
StaryuAnimation:     INCLUDE "gfx/pokemon/staryu/anim.asm"
StarmieAnimation:    INCLUDE "gfx/pokemon/starmie/anim.asm"
ScytherAnimation:    INCLUDE "gfx/pokemon/scyther/anim.asm"
JynxAnimation:       INCLUDE "gfx/pokemon/jynx/anim.asm"
ElectabuzzAnimation: INCLUDE "gfx/pokemon/electabuzz/anim.asm"
MagmarAnimation:     INCLUDE "gfx/pokemon/magmar/anim.asm"
PinsirAnimation:     INCLUDE "gfx/pokemon/pinsir/anim.asm"
LaprasAnimation:     INCLUDE "gfx/pokemon/lapras/anim.asm"
DittoAnimation:      INCLUDE "gfx/pokemon/ditto/anim.asm"
EeveeAnimation:      INCLUDE "gfx/pokemon/eevee/anim.asm"
VaporeonAnimation:   INCLUDE "gfx/pokemon/vaporeon/anim.asm"
JolteonAnimation:    INCLUDE "gfx/pokemon/jolteon/anim.asm"
FlareonAnimation:    INCLUDE "gfx/pokemon/flareon/anim.asm"
PorygonAnimation:    INCLUDE "gfx/pokemon/porygon/anim.asm"
OmanyteAnimation:    INCLUDE "gfx/pokemon/omanyte/anim.asm"
OmastarAnimation:    INCLUDE "gfx/pokemon/omastar/anim.asm"
KabutoAnimation:     INCLUDE "gfx/pokemon/kabuto/anim.asm"
KabutopsAnimation:   INCLUDE "gfx/pokemon/kabutops/anim.asm"
AerodactylAnimation: INCLUDE "gfx/pokemon/aerodactyl/anim.asm"
SnorlaxAnimation:    INCLUDE "gfx/pokemon/snorlax/anim.asm"
DratiniAnimation:    INCLUDE "gfx/pokemon/dratini/anim.asm"
DragonairAnimation:  INCLUDE "gfx/pokemon/dragonair/anim.asm"
DragoniteAnimation:  INCLUDE "gfx/pokemon/dragonite/anim.asm"
MewAnimation:        INCLUDE "gfx/pokemon/mew/anim.asm"
ChikoritaAnimation:  INCLUDE "gfx/pokemon/chikorita/anim.asm"
BayleefAnimation:    INCLUDE "gfx/pokemon/bayleef/anim.asm"
MeganiumAnimation:   INCLUDE "gfx/pokemon/meganium/anim.asm"
CyndaquilAnimation:  INCLUDE "gfx/pokemon/cyndaquil/anim.asm"
QuilavaAnimation:    INCLUDE "gfx/pokemon/quilava/anim.asm"
TotodileAnimation:   INCLUDE "gfx/pokemon/totodile/anim.asm"
CroconawAnimation:   INCLUDE "gfx/pokemon/croconaw/anim.asm"
FeraligatrAnimation: INCLUDE "gfx/pokemon/feraligatr/anim.asm"
SentretAnimation:    INCLUDE "gfx/pokemon/sentret/anim.asm"
FurretAnimation:     INCLUDE "gfx/pokemon/furret/anim.asm"
HoothootAnimation:   INCLUDE "gfx/pokemon/hoothoot/anim.asm"
NoctowlAnimation:    INCLUDE "gfx/pokemon/noctowl/anim.asm"
LedybaAnimation:     INCLUDE "gfx/pokemon/ledyba/anim.asm"
LedianAnimation:     INCLUDE "gfx/pokemon/ledian/anim.asm"
SpinarakAnimation:   INCLUDE "gfx/pokemon/spinarak/anim.asm"
AriadosAnimation:    INCLUDE "gfx/pokemon/ariados/anim.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim.asm"
CleffaAnimation:     INCLUDE "gfx/pokemon/cleffa/anim.asm"
IgglybuffAnimation:  INCLUDE "gfx/pokemon/igglybuff/anim.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim.asm"
NatuAnimation:       INCLUDE "gfx/pokemon/natu/anim.asm"
XatuAnimation:       INCLUDE "gfx/pokemon/xatu/anim.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim.asm"
BellossomAnimation:  INCLUDE "gfx/pokemon/bellossom/anim.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim.asm"
HoppipAnimation:     INCLUDE "gfx/pokemon/hoppip/anim.asm"
SkiploomAnimation:   INCLUDE "gfx/pokemon/skiploom/anim.asm"
JumpluffAnimation:   INCLUDE "gfx/pokemon/jumpluff/anim.asm"
AipomAnimation:      INCLUDE "gfx/pokemon/aipom/anim.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim.asm"
QuagsireAnimation:   INCLUDE "gfx/pokemon/quagsire/anim.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim.asm"
WobbuffetAnimation:  INCLUDE "gfx/pokemon/wobbuffet/anim.asm"
GirafarigAnimation:  INCLUDE "gfx/pokemon/girafarig/anim.asm"
PinecoAnimation:     INCLUDE "gfx/pokemon/pineco/anim.asm"
ForretressAnimation: INCLUDE "gfx/pokemon/forretress/anim.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim.asm"
TeddiursaAnimation:  INCLUDE "gfx/pokemon/teddiursa/anim.asm"
UrsaringAnimation:   INCLUDE "gfx/pokemon/ursaring/anim.asm"
SlugmaAnimation:     INCLUDE "gfx/pokemon/slugma/anim.asm"
MagcargoAnimation:   INCLUDE "gfx/pokemon/magcargo/anim.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim.asm"
DelibirdAnimation:   INCLUDE "gfx/pokemon/delibird/anim.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim.asm"
PhanpyAnimation:     INCLUDE "gfx/pokemon/phanpy/anim.asm"
DonphanAnimation:    INCLUDE "gfx/pokemon/donphan/anim.asm"
Porygon2Animation:   INCLUDE "gfx/pokemon/porygon2/anim.asm"
StantlerAnimation:   INCLUDE "gfx/pokemon/stantler/anim.asm"
SmeargleAnimation:   INCLUDE "gfx/pokemon/smeargle/anim.asm"
TyrogueAnimation:    INCLUDE "gfx/pokemon/tyrogue/anim.asm"
HitmontopAnimation:  INCLUDE "gfx/pokemon/hitmontop/anim.asm"
SmoochumAnimation:   INCLUDE "gfx/pokemon/smoochum/anim.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim.asm"
MiltankAnimation:    INCLUDE "gfx/pokemon/miltank/anim.asm"
BlisseyAnimation:    INCLUDE "gfx/pokemon/blissey/anim.asm"
RaikouAnimation:     INCLUDE "gfx/pokemon/raikou/anim.asm"
EnteiAnimation:      INCLUDE "gfx/pokemon/entei/anim.asm"
SuicuneAnimation:    INCLUDE "gfx/pokemon/suicune/anim.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim.asm"
AzurillAnimation:    INCLUDE "gfx/pokemon/azurill/anim.asm"
WynautAnimation:     INCLUDE "gfx/pokemon/wynaut/anim.asm"
AmbipomAnimation:    INCLUDE "gfx/pokemon/ambipom/anim.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim.asm"
BonslyAnimation:     INCLUDE "gfx/pokemon/bonsly/anim.asm"
MimeJrAnimation:     INCLUDE "gfx/pokemon/mime_jr_/anim.asm"
HappinyAnimation:    INCLUDE "gfx/pokemon/happiny/anim.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim.asm"
MantykeAnimation:    INCLUDE "gfx/pokemon/mantyke/anim.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim.asm"
LickilickyAnimation: INCLUDE "gfx/pokemon/lickilicky/anim.asm"
RhyperiorAnimation:  INCLUDE "gfx/pokemon/rhyperior/anim.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim.asm"
PorygonZAnimation:   INCLUDE "gfx/pokemon/porygon_z/anim.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim.asm"
PerrserkerAnimation: INCLUDE "gfx/pokemon/perrserker/anim.asm"
CursolaAnimation:    INCLUDE "gfx/pokemon/cursola/anim.asm"
SirfetchDAnimation:  INCLUDE "gfx/pokemon/sirfetch_d/anim.asm"
MrRimeAnimation:     INCLUDE "gfx/pokemon/mr__rime/anim.asm"
WyrdeerAnimation:    INCLUDE "gfx/pokemon/wyrdeer/anim.asm"
KleavorAnimation:    INCLUDE "gfx/pokemon/kleavor/anim.asm"
SneaslerAnimation:   INCLUDE "gfx/pokemon/sneasler/anim.asm"
OverqwilAnimation:   INCLUDE "gfx/pokemon/overqwil/anim.asm"
FarigirafAnimation:  INCLUDE "gfx/pokemon/farigiraf/anim.asm"
ClodsireAnimation:   INCLUDE "gfx/pokemon/clodsire/anim.asm"
AnnihilapeAnimation: INCLUDE "gfx/pokemon/annihilape/anim.asm"

EggAnimation:        INCLUDE "gfx/pokemon/egg/anim.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim.asm"

PikachuPlainAnimation:  INCLUDE "gfx/pokemon/pikachu_plain/anim.asm"
PikachuFlyAnimation:    INCLUDE "gfx/pokemon/pikachu_fly/anim.asm"
PikachuSurfAnimation:   INCLUDE "gfx/pokemon/pikachu_surf/anim.asm"
PikachuPikaAnimation:   INCLUDE "gfx/pokemon/pikachu_pika/anim.asm"
PikachuChuchuAnimation: INCLUDE "gfx/pokemon/pikachu_chuchu/anim.asm"
PikachuSparkAnimation:  INCLUDE "gfx/pokemon/pikachu_spark/anim.asm"

ArbokJohtoAnimation:  INCLUDE "gfx/pokemon/arbok_johto/anim.asm"
ArbokKantoAnimation:  INCLUDE "gfx/pokemon/arbok_kanto/anim.asm"
ArbokKogaAnimation:   INCLUDE "gfx/pokemon/arbok_koga/anim.asm"
ArbokAgathaAnimation: INCLUDE "gfx/pokemon/arbok_agatha/anim.asm"
ArbokArianaAnimation: INCLUDE "gfx/pokemon/arbok_ariana/anim.asm"

MagikarpPlainAnimation:
MagikarpSkellyAnimation:
MagikarpCalico1Animation:
MagikarpCalico2Animation:
MagikarpCalico3Animation:
MagikarpTwoToneAnimation:
MagikarpOrcaAnimation:
MagikarpDapplesAnimation:
MagikarpTigerAnimation:
MagikarpZebraAnimation:
MagikarpStripeAnimation:
MagikarpBubblesAnimation:
MagikarpDiamondsAnimation:
MagikarpPatchesAnimation:
MagikarpForehead1Animation:
MagikarpMask1Animation:
MagikarpForehead2Animation:
MagikarpMask2Animation:
MagikarpSaucyAnimation:
MagikarpRaindropAnimation: INCLUDE "gfx/pokemon/magikarp/anim.asm"

DudunsparceTwoSegmentAnimation:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim.asm"
DudunsparceThreeSegmentAnimation: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim.asm"

GyaradosPlainAnimation: INCLUDE "gfx/pokemon/gyarados_plain/anim.asm"
GyaradosRedAnimation:   INCLUDE "gfx/pokemon/gyarados_red/anim.asm"

MewtwoPlainAnimation:   INCLUDE "gfx/pokemon/mewtwo_plain/anim.asm"
MewtwoArmoredAnimation: INCLUDE "gfx/pokemon/mewtwo_armored/anim.asm"

RattataPlainAnimation:  INCLUDE "gfx/pokemon/rattata_plain/anim.asm"
RattataAlolanAnimation: INCLUDE "gfx/pokemon/rattata_alolan/anim.asm"

RaticatePlainAnimation:  INCLUDE "gfx/pokemon/raticate_plain/anim.asm"
RaticateAlolanAnimation: INCLUDE "gfx/pokemon/raticate_alolan/anim.asm"

RaichuPlainAnimation:  INCLUDE "gfx/pokemon/raichu_plain/anim.asm"
RaichuAlolanAnimation: INCLUDE "gfx/pokemon/raichu_alolan/anim.asm"

SandshrewPlainAnimation:  INCLUDE "gfx/pokemon/sandshrew_plain/anim.asm"
SandshrewAlolanAnimation: INCLUDE "gfx/pokemon/sandshrew_alolan/anim.asm"

SandslashPlainAnimation:  INCLUDE "gfx/pokemon/sandslash_plain/anim.asm"
SandslashAlolanAnimation: INCLUDE "gfx/pokemon/sandslash_alolan/anim.asm"

VulpixPlainAnimation:  INCLUDE "gfx/pokemon/vulpix_plain/anim.asm"
VulpixAlolanAnimation: INCLUDE "gfx/pokemon/vulpix_alolan/anim.asm"

NinetalesPlainAnimation:  INCLUDE "gfx/pokemon/ninetales_plain/anim.asm"
NinetalesAlolanAnimation: INCLUDE "gfx/pokemon/ninetales_alolan/anim.asm"

DiglettPlainAnimation:  INCLUDE "gfx/pokemon/diglett_plain/anim.asm"
DiglettAlolanAnimation: INCLUDE "gfx/pokemon/diglett_alolan/anim.asm"

DugtrioPlainAnimation:  INCLUDE "gfx/pokemon/dugtrio_plain/anim.asm"
DugtrioAlolanAnimation: INCLUDE "gfx/pokemon/dugtrio_alolan/anim.asm"

MeowthPlainAnimation:    INCLUDE "gfx/pokemon/meowth_plain/anim.asm"
MeowthAlolanAnimation:   INCLUDE "gfx/pokemon/meowth_alolan/anim.asm"
MeowthGalarianAnimation: INCLUDE "gfx/pokemon/meowth_galarian/anim.asm"

PersianPlainAnimation:  INCLUDE "gfx/pokemon/persian_plain/anim.asm"
PersianAlolanAnimation: INCLUDE "gfx/pokemon/persian_alolan/anim.asm"

GeodudePlainAnimation:  INCLUDE "gfx/pokemon/geodude_plain/anim.asm"
GeodudeAlolanAnimation: INCLUDE "gfx/pokemon/geodude_alolan/anim.asm"

GravelerPlainAnimation:  INCLUDE "gfx/pokemon/graveler_plain/anim.asm"
GravelerAlolanAnimation: INCLUDE "gfx/pokemon/graveler_alolan/anim.asm"

GolemPlainAnimation:  INCLUDE "gfx/pokemon/golem_plain/anim.asm"
GolemAlolanAnimation: INCLUDE "gfx/pokemon/golem_alolan/anim.asm"

GrimerPlainAnimation:  INCLUDE "gfx/pokemon/grimer_plain/anim.asm"
GrimerAlolanAnimation: INCLUDE "gfx/pokemon/grimer_alolan/anim.asm"

MukPlainAnimation:  INCLUDE "gfx/pokemon/muk_plain/anim.asm"
MukAlolanAnimation: INCLUDE "gfx/pokemon/muk_alolan/anim.asm"

ExeggutorPlainAnimation:  INCLUDE "gfx/pokemon/exeggutor_plain/anim.asm"
ExeggutorAlolanAnimation: INCLUDE "gfx/pokemon/exeggutor_alolan/anim.asm"

MarowakPlainAnimation:  INCLUDE "gfx/pokemon/marowak_plain/anim.asm"
MarowakAlolanAnimation: INCLUDE "gfx/pokemon/marowak_alolan/anim.asm"

PonytaPlainAnimation:    INCLUDE "gfx/pokemon/ponyta_plain/anim.asm"
PonytaGalarianAnimation: INCLUDE "gfx/pokemon/ponyta_galarian/anim.asm"

RapidashPlainAnimation:    INCLUDE "gfx/pokemon/rapidash_plain/anim.asm"
RapidashGalarianAnimation: INCLUDE "gfx/pokemon/rapidash_galarian/anim.asm"

SlowpokePlainAnimation:    INCLUDE "gfx/pokemon/slowpoke_plain/anim.asm"
SlowpokeGalarianAnimation: INCLUDE "gfx/pokemon/slowpoke_galarian/anim.asm"

SlowbroPlainAnimation:    INCLUDE "gfx/pokemon/slowbro_plain/anim.asm"
SlowbroGalarianAnimation: INCLUDE "gfx/pokemon/slowbro_galarian/anim.asm"

FarfetchDPlainAnimation:    INCLUDE "gfx/pokemon/farfetch_d_plain/anim.asm"
FarfetchDGalarianAnimation: INCLUDE "gfx/pokemon/farfetch_d_galarian/anim.asm"

WeezingPlainAnimation:    INCLUDE "gfx/pokemon/weezing_plain/anim.asm"
WeezingGalarianAnimation: INCLUDE "gfx/pokemon/weezing_galarian/anim.asm"

MrMimePlainAnimation:    INCLUDE "gfx/pokemon/mr__mime_plain/anim.asm"
MrMimeGalarianAnimation: INCLUDE "gfx/pokemon/mr__mime_galarian/anim.asm"

ArticunoPlainAnimation:    INCLUDE "gfx/pokemon/articuno_plain/anim.asm"
ArticunoGalarianAnimation: INCLUDE "gfx/pokemon/articuno_galarian/anim.asm"

ZapdosPlainAnimation:    INCLUDE "gfx/pokemon/zapdos_plain/anim.asm"
ZapdosGalarianAnimation: INCLUDE "gfx/pokemon/zapdos_galarian/anim.asm"

MoltresPlainAnimation:    INCLUDE "gfx/pokemon/moltres_plain/anim.asm"
MoltresGalarianAnimation: INCLUDE "gfx/pokemon/moltres_galarian/anim.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim.asm"

CorsolaPlainAnimation:    INCLUDE "gfx/pokemon/corsola_plain/anim.asm"
CorsolaGalarianAnimation: INCLUDE "gfx/pokemon/corsola_galarian/anim.asm"

GrowlithePlainAnimation:   INCLUDE "gfx/pokemon/growlithe_plain/anim.asm"
GrowlitheHisuianAnimation: INCLUDE "gfx/pokemon/growlithe_hisuian/anim.asm"

ArcaninePlainAnimation:   INCLUDE "gfx/pokemon/arcanine_plain/anim.asm"
ArcanineHisuianAnimation: INCLUDE "gfx/pokemon/arcanine_hisuian/anim.asm"

VoltorbPlainAnimation:   INCLUDE "gfx/pokemon/voltorb_plain/anim.asm"
VoltorbHisuianAnimation: INCLUDE "gfx/pokemon/voltorb_hisuian/anim.asm"

ElectrodePlainAnimation:   INCLUDE "gfx/pokemon/electrode_plain/anim.asm"
ElectrodeHisuianAnimation: INCLUDE "gfx/pokemon/electrode_hisuian/anim.asm"

TyphlosionPlainAnimation:   INCLUDE "gfx/pokemon/typhlosion_plain/anim.asm"
TyphlosionHisuianAnimation: INCLUDE "gfx/pokemon/typhlosion_hisuian/anim.asm"

QwilfishPlainAnimation:   INCLUDE "gfx/pokemon/qwilfish_plain/anim.asm"
QwilfishHisuianAnimation: INCLUDE "gfx/pokemon/qwilfish_hisuian/anim.asm"

SneaselPlainAnimation:   INCLUDE "gfx/pokemon/sneasel_plain/anim.asm"
SneaselHisuianAnimation: INCLUDE "gfx/pokemon/sneasel_hisuian/anim.asm"

WooperPlainAnimation:   INCLUDE "gfx/pokemon/wooper_plain/anim.asm"
WooperPaldeanAnimation: INCLUDE "gfx/pokemon/wooper_paldean/anim.asm"

TaurosPlainAnimation:        INCLUDE "gfx/pokemon/tauros_plain/anim.asm"
TaurosPaldeanAnimation:      INCLUDE "gfx/pokemon/tauros_paldean/anim.asm"
TaurosPaldeanFireAnimation:  INCLUDE "gfx/pokemon/tauros_paldean_fire/anim.asm"
TaurosPaldeanWaterAnimation: INCLUDE "gfx/pokemon/tauros_paldean_water/anim.asm"

UrsalunaPlainAnimation:     INCLUDE "gfx/pokemon/ursaluna_plain/anim.asm"
UrsalunaBloodmoonAnimation: INCLUDE "gfx/pokemon/ursaluna_bloodmoon/anim.asm"
