PicAnimations:

BulbasaurAnimation:  INCLUDE "gfx/pokemon/bulbasaur/anim0.asm"
IvysaurAnimation:    INCLUDE "gfx/pokemon/ivysaur/anim0.asm"
VenusaurAnimation:   INCLUDE "gfx/pokemon/venusaur/anim0.asm"
CharmanderAnimation: INCLUDE "gfx/pokemon/charmander/anim0.asm"
CharmeleonAnimation: INCLUDE "gfx/pokemon/charmeleon/anim0.asm"
CharizardAnimation:  INCLUDE "gfx/pokemon/charizard/anim0.asm"
SquirtleAnimation:   INCLUDE "gfx/pokemon/squirtle/anim0.asm"
WartortleAnimation:  INCLUDE "gfx/pokemon/wartortle/anim0.asm"
BlastoiseAnimation:  INCLUDE "gfx/pokemon/blastoise/anim0.asm"
CaterpieAnimation:   INCLUDE "gfx/pokemon/caterpie/anim0.asm"
MetapodAnimation:    INCLUDE "gfx/pokemon/metapod/anim0.asm"
ButterfreeAnimation: INCLUDE "gfx/pokemon/butterfree/anim0.asm"
WeedleAnimation:     INCLUDE "gfx/pokemon/weedle/anim0.asm"
KakunaAnimation:     INCLUDE "gfx/pokemon/kakuna/anim0.asm"
BeedrillAnimation:   INCLUDE "gfx/pokemon/beedrill/anim0.asm"
PidgeyAnimation:     INCLUDE "gfx/pokemon/pidgey/anim0.asm"
PidgeottoAnimation:  INCLUDE "gfx/pokemon/pidgeotto/anim0.asm"
PidgeotAnimation:    INCLUDE "gfx/pokemon/pidgeot/anim0.asm"
MarillAnimation:     INCLUDE "gfx/pokemon/marill/anim0.asm"
AzumarillAnimation:  INCLUDE "gfx/pokemon/azumarill/anim0.asm"
EkansAnimation:      INCLUDE "gfx/pokemon/ekans/anim0.asm"
NidoranFAnimation:   INCLUDE "gfx/pokemon/nidoran_f/anim0.asm"
NidorinaAnimation:   INCLUDE "gfx/pokemon/nidorina/anim0.asm"
NidoqueenAnimation:  INCLUDE "gfx/pokemon/nidoqueen/anim0.asm"
NidoranMAnimation:   INCLUDE "gfx/pokemon/nidoran_m/anim0.asm"
NidorinoAnimation:   INCLUDE "gfx/pokemon/nidorino/anim0.asm"
NidokingAnimation:   INCLUDE "gfx/pokemon/nidoking/anim0.asm"
ClefairyAnimation:   INCLUDE "gfx/pokemon/clefairy/anim0.asm"
ClefableAnimation:   INCLUDE "gfx/pokemon/clefable/anim0.asm"
JigglypuffAnimation: INCLUDE "gfx/pokemon/jigglypuff/anim0.asm"
WigglytuffAnimation: INCLUDE "gfx/pokemon/wigglytuff/anim0.asm"
ZubatAnimation:      INCLUDE "gfx/pokemon/zubat/anim0.asm"
GolbatAnimation:     INCLUDE "gfx/pokemon/golbat/anim0.asm"
OddishAnimation:     INCLUDE "gfx/pokemon/oddish/anim0.asm"
GloomAnimation:      INCLUDE "gfx/pokemon/gloom/anim0.asm"
VileplumeAnimation:  INCLUDE "gfx/pokemon/vileplume/anim0.asm"
ParasAnimation:      INCLUDE "gfx/pokemon/paras/anim0.asm"
ParasectAnimation:   INCLUDE "gfx/pokemon/parasect/anim0.asm"
VenonatAnimation:    INCLUDE "gfx/pokemon/venonat/anim0.asm"
VenomothAnimation:   INCLUDE "gfx/pokemon/venomoth/anim0.asm"
PsyduckAnimation:    INCLUDE "gfx/pokemon/psyduck/anim0.asm"
GolduckAnimation:    INCLUDE "gfx/pokemon/golduck/anim0.asm"
MankeyAnimation:     INCLUDE "gfx/pokemon/mankey/anim0.asm"
PrimeapeAnimation:   INCLUDE "gfx/pokemon/primeape/anim0.asm"
GrowlitheAnimation:  INCLUDE "gfx/pokemon/growlithe/anim0.asm"
ArcanineAnimation:   INCLUDE "gfx/pokemon/arcanine/anim0.asm"
PoliwagAnimation:    INCLUDE "gfx/pokemon/poliwag/anim0.asm"
PoliwhirlAnimation:  INCLUDE "gfx/pokemon/poliwhirl/anim0.asm"
PoliwrathAnimation:  INCLUDE "gfx/pokemon/poliwrath/anim0.asm"
AbraAnimation:       INCLUDE "gfx/pokemon/abra/anim0.asm"
KadabraAnimation:    INCLUDE "gfx/pokemon/kadabra/anim0.asm"
AlakazamAnimation:   INCLUDE "gfx/pokemon/alakazam/anim0.asm"
MachopAnimation:     INCLUDE "gfx/pokemon/machop/anim0.asm"
MachokeAnimation:    INCLUDE "gfx/pokemon/machoke/anim0.asm"
MachampAnimation:    INCLUDE "gfx/pokemon/machamp/anim0.asm"
BellsproutAnimation: INCLUDE "gfx/pokemon/bellsprout/anim0.asm"
WeepinbellAnimation: INCLUDE "gfx/pokemon/weepinbell/anim0.asm"
VictreebelAnimation: INCLUDE "gfx/pokemon/victreebel/anim0.asm"
TentacoolAnimation:  INCLUDE "gfx/pokemon/tentacool/anim0.asm"
TentacruelAnimation: INCLUDE "gfx/pokemon/tentacruel/anim0.asm"
MagnemiteAnimation:  INCLUDE "gfx/pokemon/magnemite/anim0.asm"
MagnetonAnimation:   INCLUDE "gfx/pokemon/magneton/anim0.asm"
FarfetchDAnimation:  INCLUDE "gfx/pokemon/farfetch_d/anim0.asm"
DoduoAnimation:      INCLUDE "gfx/pokemon/doduo/anim0.asm"
DodrioAnimation:     INCLUDE "gfx/pokemon/dodrio/anim0.asm"
SeelAnimation:       INCLUDE "gfx/pokemon/seel/anim0.asm"
DewgongAnimation:    INCLUDE "gfx/pokemon/dewgong/anim0.asm"
ShellderAnimation:   INCLUDE "gfx/pokemon/shellder/anim0.asm"
CloysterAnimation:   INCLUDE "gfx/pokemon/cloyster/anim0.asm"
GastlyAnimation:     INCLUDE "gfx/pokemon/gastly/anim0.asm"
HaunterAnimation:    INCLUDE "gfx/pokemon/haunter/anim0.asm"
GengarAnimation:     INCLUDE "gfx/pokemon/gengar/anim0.asm"
OnixAnimation:       INCLUDE "gfx/pokemon/onix/anim0.asm"
DrowzeeAnimation:    INCLUDE "gfx/pokemon/drowzee/anim0.asm"
HypnoAnimation:      INCLUDE "gfx/pokemon/hypno/anim0.asm"
KrabbyAnimation:     INCLUDE "gfx/pokemon/krabby/anim0.asm"
KinglerAnimation:    INCLUDE "gfx/pokemon/kingler/anim0.asm"
VoltorbAnimation:    INCLUDE "gfx/pokemon/voltorb/anim0.asm"
ElectrodeAnimation:  INCLUDE "gfx/pokemon/electrode/anim0.asm"
ExeggcuteAnimation:  INCLUDE "gfx/pokemon/exeggcute/anim0.asm"
CuboneAnimation:     INCLUDE "gfx/pokemon/cubone/anim0.asm"
HitmonleeAnimation:  INCLUDE "gfx/pokemon/hitmonlee/anim0.asm"
HitmonchanAnimation: INCLUDE "gfx/pokemon/hitmonchan/anim0.asm"
KoffingAnimation:    INCLUDE "gfx/pokemon/koffing/anim0.asm"
RhyhornAnimation:    INCLUDE "gfx/pokemon/rhyhorn/anim0.asm"
RhydonAnimation:     INCLUDE "gfx/pokemon/rhydon/anim0.asm"
ChanseyAnimation:    INCLUDE "gfx/pokemon/chansey/anim0.asm"
TangelaAnimation:    INCLUDE "gfx/pokemon/tangela/anim0.asm"
KangaskhanAnimation: INCLUDE "gfx/pokemon/kangaskhan/anim0.asm"
HorseaAnimation:     INCLUDE "gfx/pokemon/horsea/anim0.asm"
SeadraAnimation:     INCLUDE "gfx/pokemon/seadra/anim0.asm"
TogepiAnimation:     INCLUDE "gfx/pokemon/togepi/anim0.asm"
TogeticAnimation:    INCLUDE "gfx/pokemon/togetic/anim0.asm"
TogekissAnimation:   INCLUDE "gfx/pokemon/togekiss/anim0.asm"
StaryuAnimation:     INCLUDE "gfx/pokemon/staryu/anim0.asm"
StarmieAnimation:    INCLUDE "gfx/pokemon/starmie/anim0.asm"
MrMimeAnimation:     INCLUDE "gfx/pokemon/mr__mime/anim0.asm"
ScytherAnimation:    INCLUDE "gfx/pokemon/scyther/anim0.asm"
JynxAnimation:       INCLUDE "gfx/pokemon/jynx/anim0.asm"
ElectabuzzAnimation: INCLUDE "gfx/pokemon/electabuzz/anim0.asm"
MagmarAnimation:     INCLUDE "gfx/pokemon/magmar/anim0.asm"
PinsirAnimation:     INCLUDE "gfx/pokemon/pinsir/anim0.asm"
TaurosAnimation:     INCLUDE "gfx/pokemon/tauros/anim0.asm"
LaprasAnimation:     INCLUDE "gfx/pokemon/lapras/anim0.asm"
DittoAnimation:      INCLUDE "gfx/pokemon/ditto/anim0.asm"
EeveeAnimation:      INCLUDE "gfx/pokemon/eevee/anim0.asm"
VaporeonAnimation:   INCLUDE "gfx/pokemon/vaporeon/anim0.asm"
JolteonAnimation:    INCLUDE "gfx/pokemon/jolteon/anim0.asm"
FlareonAnimation:    INCLUDE "gfx/pokemon/flareon/anim0.asm"
PorygonAnimation:    INCLUDE "gfx/pokemon/porygon/anim0.asm"
OmanyteAnimation:    INCLUDE "gfx/pokemon/omanyte/anim0.asm"
OmastarAnimation:    INCLUDE "gfx/pokemon/omastar/anim0.asm"
KabutoAnimation:     INCLUDE "gfx/pokemon/kabuto/anim0.asm"
KabutopsAnimation:   INCLUDE "gfx/pokemon/kabutops/anim0.asm"
AerodactylAnimation: INCLUDE "gfx/pokemon/aerodactyl/anim0.asm"
SnorlaxAnimation:    INCLUDE "gfx/pokemon/snorlax/anim0.asm"
DratiniAnimation:    INCLUDE "gfx/pokemon/dratini/anim0.asm"
DragonairAnimation:  INCLUDE "gfx/pokemon/dragonair/anim0.asm"
DragoniteAnimation:  INCLUDE "gfx/pokemon/dragonite/anim0.asm"
MewAnimation:        INCLUDE "gfx/pokemon/mew/anim0.asm"
ChikoritaAnimation:  INCLUDE "gfx/pokemon/chikorita/anim0.asm"
BayleefAnimation:    INCLUDE "gfx/pokemon/bayleef/anim0.asm"
MeganiumAnimation:   INCLUDE "gfx/pokemon/meganium/anim0.asm"
CyndaquilAnimation:  INCLUDE "gfx/pokemon/cyndaquil/anim0.asm"
QuilavaAnimation:    INCLUDE "gfx/pokemon/quilava/anim0.asm"
TyphlosionAnimation: INCLUDE "gfx/pokemon/typhlosion/anim0.asm"
TotodileAnimation:   INCLUDE "gfx/pokemon/totodile/anim0.asm"
CroconawAnimation:   INCLUDE "gfx/pokemon/croconaw/anim0.asm"
FeraligatrAnimation: INCLUDE "gfx/pokemon/feraligatr/anim0.asm"
SentretAnimation:    INCLUDE "gfx/pokemon/sentret/anim0.asm"
FurretAnimation:     INCLUDE "gfx/pokemon/furret/anim0.asm"
HoothootAnimation:   INCLUDE "gfx/pokemon/hoothoot/anim0.asm"
NoctowlAnimation:    INCLUDE "gfx/pokemon/noctowl/anim0.asm"
LedybaAnimation:     INCLUDE "gfx/pokemon/ledyba/anim0.asm"
LedianAnimation:     INCLUDE "gfx/pokemon/ledian/anim0.asm"
SpinarakAnimation:   INCLUDE "gfx/pokemon/spinarak/anim0.asm"
AriadosAnimation:    INCLUDE "gfx/pokemon/ariados/anim0.asm"
CrobatAnimation:     INCLUDE "gfx/pokemon/crobat/anim0.asm"
ChinchouAnimation:   INCLUDE "gfx/pokemon/chinchou/anim0.asm"
LanturnAnimation:    INCLUDE "gfx/pokemon/lanturn/anim0.asm"
MunchlaxAnimation:   INCLUDE "gfx/pokemon/munchlax/anim0.asm"
MagnezoneAnimation:  INCLUDE "gfx/pokemon/magnezone/anim0.asm"
RhyperiorAnimation:  INCLUDE "gfx/pokemon/rhyperior/anim0.asm"
TangrowthAnimation:  INCLUDE "gfx/pokemon/tangrowth/anim0.asm"
NatuAnimation:       INCLUDE "gfx/pokemon/natu/anim0.asm"
XatuAnimation:       INCLUDE "gfx/pokemon/xatu/anim0.asm"
MareepAnimation:     INCLUDE "gfx/pokemon/mareep/anim0.asm"
FlaaffyAnimation:    INCLUDE "gfx/pokemon/flaaffy/anim0.asm"
AmpharosAnimation:   INCLUDE "gfx/pokemon/ampharos/anim0.asm"
BellossomAnimation:  INCLUDE "gfx/pokemon/bellossom/anim0.asm"
SudowoodoAnimation:  INCLUDE "gfx/pokemon/sudowoodo/anim0.asm"
PolitoedAnimation:   INCLUDE "gfx/pokemon/politoed/anim0.asm"
SunkernAnimation:    INCLUDE "gfx/pokemon/sunkern/anim0.asm"
SunfloraAnimation:   INCLUDE "gfx/pokemon/sunflora/anim0.asm"
YanmaAnimation:      INCLUDE "gfx/pokemon/yanma/anim0.asm"
YanmegaAnimation:    INCLUDE "gfx/pokemon/yanmega/anim0.asm"
WooperAnimation:     INCLUDE "gfx/pokemon/wooper/anim0.asm"
QuagsireAnimation:   INCLUDE "gfx/pokemon/quagsire/anim0.asm"
EspeonAnimation:     INCLUDE "gfx/pokemon/espeon/anim0.asm"
UmbreonAnimation:    INCLUDE "gfx/pokemon/umbreon/anim0.asm"
MurkrowAnimation:    INCLUDE "gfx/pokemon/murkrow/anim0.asm"
HonchkrowAnimation:  INCLUDE "gfx/pokemon/honchkrow/anim0.asm"
MisdreavusAnimation: INCLUDE "gfx/pokemon/misdreavus/anim0.asm"
MismagiusAnimation:  INCLUDE "gfx/pokemon/mismagius/anim0.asm"
WobbuffetAnimation:  INCLUDE "gfx/pokemon/wobbuffet/anim0.asm"
GirafarigAnimation:  INCLUDE "gfx/pokemon/girafarig/anim0.asm"
PinecoAnimation:     INCLUDE "gfx/pokemon/pineco/anim0.asm"
ForretressAnimation: INCLUDE "gfx/pokemon/forretress/anim0.asm"
DunsparceAnimation:  INCLUDE "gfx/pokemon/dunsparce/anim0.asm"
GligarAnimation:     INCLUDE "gfx/pokemon/gligar/anim0.asm"
GliscorAnimation:    INCLUDE "gfx/pokemon/gliscor/anim0.asm"
SteelixAnimation:    INCLUDE "gfx/pokemon/steelix/anim0.asm"
SnubbullAnimation:   INCLUDE "gfx/pokemon/snubbull/anim0.asm"
GranbullAnimation:   INCLUDE "gfx/pokemon/granbull/anim0.asm"
QwilfishAnimation:   INCLUDE "gfx/pokemon/qwilfish/anim0.asm"
ScizorAnimation:     INCLUDE "gfx/pokemon/scizor/anim0.asm"
ShuckleAnimation:    INCLUDE "gfx/pokemon/shuckle/anim0.asm"
HeracrossAnimation:  INCLUDE "gfx/pokemon/heracross/anim0.asm"
SneaselAnimation:    INCLUDE "gfx/pokemon/sneasel/anim0.asm"
WeavileAnimation:    INCLUDE "gfx/pokemon/weavile/anim0.asm"
TeddiursaAnimation:  INCLUDE "gfx/pokemon/teddiursa/anim0.asm"
UrsaringAnimation:   INCLUDE "gfx/pokemon/ursaring/anim0.asm"
SlugmaAnimation:     INCLUDE "gfx/pokemon/slugma/anim0.asm"
MagcargoAnimation:   INCLUDE "gfx/pokemon/magcargo/anim0.asm"
SwinubAnimation:     INCLUDE "gfx/pokemon/swinub/anim0.asm"
PiloswineAnimation:  INCLUDE "gfx/pokemon/piloswine/anim0.asm"
MamoswineAnimation:  INCLUDE "gfx/pokemon/mamoswine/anim0.asm"
CorsolaAnimation:    INCLUDE "gfx/pokemon/corsola/anim0.asm"
RemoraidAnimation:   INCLUDE "gfx/pokemon/remoraid/anim0.asm"
OctilleryAnimation:  INCLUDE "gfx/pokemon/octillery/anim0.asm"
MantineAnimation:    INCLUDE "gfx/pokemon/mantine/anim0.asm"
SkarmoryAnimation:   INCLUDE "gfx/pokemon/skarmory/anim0.asm"
HoundourAnimation:   INCLUDE "gfx/pokemon/houndour/anim0.asm"
HoundoomAnimation:   INCLUDE "gfx/pokemon/houndoom/anim0.asm"
KingdraAnimation:    INCLUDE "gfx/pokemon/kingdra/anim0.asm"
PhanpyAnimation:     INCLUDE "gfx/pokemon/phanpy/anim0.asm"
DonphanAnimation:    INCLUDE "gfx/pokemon/donphan/anim0.asm"
Porygon2Animation:   INCLUDE "gfx/pokemon/porygon2/anim0.asm"
PorygonZAnimation:   INCLUDE "gfx/pokemon/porygon_z/anim0.asm"
SmeargleAnimation:   INCLUDE "gfx/pokemon/smeargle/anim0.asm"
TyrogueAnimation:    INCLUDE "gfx/pokemon/tyrogue/anim0.asm"
HitmontopAnimation:  INCLUDE "gfx/pokemon/hitmontop/anim0.asm"
ElekidAnimation:     INCLUDE "gfx/pokemon/elekid/anim0.asm"
ElectivireAnimation: INCLUDE "gfx/pokemon/electivire/anim0.asm"
MagbyAnimation:      INCLUDE "gfx/pokemon/magby/anim0.asm"
MagmortarAnimation:  INCLUDE "gfx/pokemon/magmortar/anim0.asm"
MiltankAnimation:    INCLUDE "gfx/pokemon/miltank/anim0.asm"
BlisseyAnimation:    INCLUDE "gfx/pokemon/blissey/anim0.asm"
RaikouAnimation:     INCLUDE "gfx/pokemon/raikou/anim0.asm"
EnteiAnimation:      INCLUDE "gfx/pokemon/entei/anim0.asm"
SuicuneAnimation:    INCLUDE "gfx/pokemon/suicune/anim0.asm"
LarvitarAnimation:   INCLUDE "gfx/pokemon/larvitar/anim0.asm"
PupitarAnimation:    INCLUDE "gfx/pokemon/pupitar/anim0.asm"
TyranitarAnimation:  INCLUDE "gfx/pokemon/tyranitar/anim0.asm"
LugiaAnimation:      INCLUDE "gfx/pokemon/lugia/anim0.asm"
HoOhAnimation:       INCLUDE "gfx/pokemon/ho_oh/anim0.asm"
CelebiAnimation:     INCLUDE "gfx/pokemon/celebi/anim0.asm"
LeafeonAnimation:    INCLUDE "gfx/pokemon/leafeon/anim0.asm"
GlaceonAnimation:    INCLUDE "gfx/pokemon/glaceon/anim0.asm"
SylveonAnimation:    INCLUDE "gfx/pokemon/sylveon/anim0.asm"
EggAnimation:        INCLUDE "gfx/pokemon/egg/anim0.asm"

UnownAAnimation: INCLUDE "gfx/pokemon/unown_a/anim0.asm"
UnownBAnimation: INCLUDE "gfx/pokemon/unown_b/anim0.asm"
UnownCAnimation: INCLUDE "gfx/pokemon/unown_c/anim0.asm"
UnownDAnimation: INCLUDE "gfx/pokemon/unown_d/anim0.asm"
UnownEAnimation: INCLUDE "gfx/pokemon/unown_e/anim0.asm"
UnownFAnimation: INCLUDE "gfx/pokemon/unown_f/anim0.asm"
UnownGAnimation: INCLUDE "gfx/pokemon/unown_g/anim0.asm"
UnownHAnimation: INCLUDE "gfx/pokemon/unown_h/anim0.asm"
UnownIAnimation: INCLUDE "gfx/pokemon/unown_i/anim0.asm"
UnownJAnimation: INCLUDE "gfx/pokemon/unown_j/anim0.asm"
UnownKAnimation: INCLUDE "gfx/pokemon/unown_k/anim0.asm"
UnownLAnimation: INCLUDE "gfx/pokemon/unown_l/anim0.asm"
UnownMAnimation: INCLUDE "gfx/pokemon/unown_m/anim0.asm"
UnownNAnimation: INCLUDE "gfx/pokemon/unown_n/anim0.asm"
UnownOAnimation: INCLUDE "gfx/pokemon/unown_o/anim0.asm"
UnownPAnimation: INCLUDE "gfx/pokemon/unown_p/anim0.asm"
UnownQAnimation: INCLUDE "gfx/pokemon/unown_q/anim0.asm"
UnownRAnimation: INCLUDE "gfx/pokemon/unown_r/anim0.asm"
UnownSAnimation: INCLUDE "gfx/pokemon/unown_s/anim0.asm"
UnownTAnimation: INCLUDE "gfx/pokemon/unown_t/anim0.asm"
UnownUAnimation: INCLUDE "gfx/pokemon/unown_u/anim0.asm"
UnownVAnimation: INCLUDE "gfx/pokemon/unown_v/anim0.asm"
UnownWAnimation: INCLUDE "gfx/pokemon/unown_w/anim0.asm"
UnownXAnimation: INCLUDE "gfx/pokemon/unown_x/anim0.asm"
UnownYAnimation: INCLUDE "gfx/pokemon/unown_y/anim0.asm"
UnownZAnimation: INCLUDE "gfx/pokemon/unown_z/anim0.asm"
UnownExclamationAnimation: INCLUDE "gfx/pokemon/unown_exclamation/anim0.asm"
UnownQuestionAnimation:    INCLUDE "gfx/pokemon/unown_question/anim0.asm"

PikachuPlainAnimation:  INCLUDE "gfx/pokemon/pikachu_plain/anim0.asm"
PikachuFlyAnimation:    INCLUDE "gfx/pokemon/pikachu_fly/anim0.asm"
PikachuSurfAnimation:   INCLUDE "gfx/pokemon/pikachu_surf/anim0.asm"
PikachuPikaAnimation:   INCLUDE "gfx/pokemon/pikachu_pika/anim0.asm"
PikachuChuchuAnimation: INCLUDE "gfx/pokemon/pikachu_chuchu/anim0.asm"
PikachuSparkAnimation:  INCLUDE "gfx/pokemon/pikachu_spark/anim0.asm"

PichuPlainAnimation: INCLUDE "gfx/pokemon/pichu_plain/anim0.asm"
PichuSpikyAnimation: INCLUDE "gfx/pokemon/pichu_spiky/anim0.asm"

ArbokJohtoAnimation:  INCLUDE "gfx/pokemon/arbok_johto/anim0.asm"
ArbokKantoAnimation:  INCLUDE "gfx/pokemon/arbok_kanto/anim0.asm"
ArbokKogaAnimation:   INCLUDE "gfx/pokemon/arbok_koga/anim0.asm"
ArbokAgathaAnimation: INCLUDE "gfx/pokemon/arbok_agatha/anim0.asm"
ArbokArianaAnimation: INCLUDE "gfx/pokemon/arbok_ariana/anim0.asm"

MagikarpPlainAnimation:
MagikarpSkellyAnimation:
MagikarpCalico1Animation:
MagikarpCalico2Animation:
MagikarpCalico3Animation:
MagikarpTwoToneAnimation:
MagikarpOrcaAnimation:
MagikarpDapplesAnimation:
MagikarpTigerAnimation:
MagikarpZebraAnimation:
MagikarpStripeAnimation:
MagikarpBubblesAnimation:
MagikarpForeheadAnimation:
MagikarpMaskAnimation:
MagikarpSaucyAnimation:
MagikarpRaindropAnimation: INCLUDE "gfx/pokemon/magikarp/anim0.asm"

GyaradosPlainAnimation: INCLUDE "gfx/pokemon/gyarados_plain/anim0.asm"
GyaradosRedAnimation:   INCLUDE "gfx/pokemon/gyarados_red/anim0.asm"

MewtwoPlainAnimation:   INCLUDE "gfx/pokemon/mewtwo_plain/anim0.asm"
MewtwoArmoredAnimation: INCLUDE "gfx/pokemon/mewtwo_armored/anim0.asm"

RattataPlainAnimation:  INCLUDE "gfx/pokemon/rattata_plain/anim0.asm"
RattataAlolanAnimation: INCLUDE "gfx/pokemon/rattata_alolan/anim0.asm"

RaticatePlainAnimation:  INCLUDE "gfx/pokemon/raticate_plain/anim0.asm"
RaticateAlolanAnimation: INCLUDE "gfx/pokemon/raticate_alolan/anim0.asm"

SandshrewPlainAnimation:  INCLUDE "gfx/pokemon/sandshrew_plain/anim0.asm"
SandshrewAlolanAnimation: INCLUDE "gfx/pokemon/sandshrew_alolan/anim0.asm"

SandslashPlainAnimation:  INCLUDE "gfx/pokemon/sandslash_plain/anim0.asm"
SandslashAlolanAnimation: INCLUDE "gfx/pokemon/sandslash_alolan/anim0.asm"

VulpixPlainAnimation:  INCLUDE "gfx/pokemon/vulpix_plain/anim0.asm"
VulpixAlolanAnimation: INCLUDE "gfx/pokemon/vulpix_alolan/anim0.asm"

NinetalesPlainAnimation:  INCLUDE "gfx/pokemon/ninetales_plain/anim0.asm"
NinetalesAlolanAnimation: INCLUDE "gfx/pokemon/ninetales_alolan/anim0.asm"

DiglettPlainAnimation:  INCLUDE "gfx/pokemon/diglett_plain/anim0.asm"
DiglettAlolanAnimation: INCLUDE "gfx/pokemon/diglett_alolan/anim0.asm"

DugtrioPlainAnimation:  INCLUDE "gfx/pokemon/dugtrio_plain/anim0.asm"
DugtrioAlolanAnimation: INCLUDE "gfx/pokemon/dugtrio_alolan/anim0.asm"

MeowthPlainAnimation:  INCLUDE "gfx/pokemon/meowth_plain/anim0.asm"
MeowthAlolanAnimation: INCLUDE "gfx/pokemon/meowth_alolan/anim0.asm"

PersianPlainAnimation:  INCLUDE "gfx/pokemon/persian_plain/anim0.asm"
PersianAlolanAnimation: INCLUDE "gfx/pokemon/persian_alolan/anim0.asm"

GeodudePlainAnimation:  INCLUDE "gfx/pokemon/geodude_plain/anim0.asm"
GeodudeAlolanAnimation: INCLUDE "gfx/pokemon/geodude_alolan/anim0.asm"

GravelerPlainAnimation:  INCLUDE "gfx/pokemon/graveler_plain/anim0.asm"
GravelerAlolanAnimation: INCLUDE "gfx/pokemon/graveler_alolan/anim0.asm"

GolemPlainAnimation:  INCLUDE "gfx/pokemon/golem_plain/anim0.asm"
GolemAlolanAnimation: INCLUDE "gfx/pokemon/golem_alolan/anim0.asm"

GrimerPlainAnimation:  INCLUDE "gfx/pokemon/grimer_plain/anim0.asm"
GrimerAlolanAnimation: INCLUDE "gfx/pokemon/grimer_alolan/anim0.asm"

MukPlainAnimation:  INCLUDE "gfx/pokemon/muk_plain/anim0.asm"
MukAlolanAnimation: INCLUDE "gfx/pokemon/muk_alolan/anim0.asm"

RaichuPlainAnimation:  INCLUDE "gfx/pokemon/raichu_plain/anim0.asm"
RaichuAlolanAnimation: INCLUDE "gfx/pokemon/raichu_alolan/anim0.asm"

ExeggutorPlainAnimation:  INCLUDE "gfx/pokemon/exeggutor_plain/anim0.asm"
ExeggutorAlolanAnimation: INCLUDE "gfx/pokemon/exeggutor_alolan/anim0.asm"

MarowakPlainAnimation:  INCLUDE "gfx/pokemon/marowak_plain/anim0.asm"
MarowakAlolanAnimation: INCLUDE "gfx/pokemon/marowak_alolan/anim0.asm"

PonytaPlainAnimation:    INCLUDE "gfx/pokemon/ponyta_plain/anim0.asm"
PonytaGalarianAnimation: INCLUDE "gfx/pokemon/ponyta_galarian/anim0.asm"

RapidashPlainAnimation:    INCLUDE "gfx/pokemon/rapidash_plain/anim0.asm"
RapidashGalarianAnimation: INCLUDE "gfx/pokemon/rapidash_galarian/anim0.asm"

SlowpokePlainAnimation:   INCLUDE "gfx/pokemon/slowpoke_plain/anim0.asm"
SlowpokeGalarianAnimation: INCLUDE "gfx/pokemon/slowpoke_galarian/anim0.asm"

SlowbroPlainAnimation:    INCLUDE "gfx/pokemon/slowbro_plain/anim0.asm"
SlowbroGalarianAnimation: INCLUDE "gfx/pokemon/slowbro_galarian/anim0.asm"

SlowkingPlainAnimation:    INCLUDE "gfx/pokemon/slowking_plain/anim0.asm"
SlowkingGalarianAnimation: INCLUDE "gfx/pokemon/slowking_galarian/anim0.asm"

WeezingPlainAnimation:    INCLUDE "gfx/pokemon/weezing_plain/anim0.asm"
WeezingGalarianAnimation: INCLUDE "gfx/pokemon/weezing_galarian/anim0.asm"

ArticunoPlainAnimation:    INCLUDE "gfx/pokemon/articuno_plain/anim0.asm"
ArticunoGalarianAnimation: INCLUDE "gfx/pokemon/articuno_galarian/anim0.asm"

ZapdosPlainAnimation:    INCLUDE "gfx/pokemon/zapdos_plain/anim0.asm"
ZapdosGalarianAnimation: INCLUDE "gfx/pokemon/zapdos_galarian/anim0.asm"

MoltresPlainAnimation:    INCLUDE "gfx/pokemon/moltres_plain/anim0.asm"
MoltresGalarianAnimation: INCLUDE "gfx/pokemon/moltres_galarian/anim0.asm"
