AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw WeedleAnimation
	dw KakunaAnimation
	dw BeedrillAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw RattataPlainAnimation
	dw RaticatePlainAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw EkansAnimation
	dw ArbokJohtoAnimation
	dw PikachuPlainAnimation
	dw RaichuPlainAnimation
	dw SandshrewPlainAnimation
	dw SandslashPlainAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixPlainAnimation
	dw NinetalesPlainAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw DiglettPlainAnimation
	dw DugtrioPlainAnimation
	dw MeowthPlainAnimation
	dw PersianPlainAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudePlainAnimation
	dw GravelerPlainAnimation
	dw GolemPlainAnimation
	dw PonytaPlainAnimation
	dw RapidashPlainAnimation
	dw SlowpokePlainAnimation
	dw SlowbroPlainAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw FarfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerPlainAnimation
	dw MukPlainAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorPlainAnimation
	dw CuboneAnimation
	dw MarowakPlainAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw KoffingAnimation
	dw WeezingPlainAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpPlainAnimation
	dw GyaradosPlainAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoPlainAnimation
	dw ZapdosPlainAnimation
	dw MoltresPlainAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoPlainAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuPlainAnimation
	dw MunchlaxAnimation
	dw MagnezoneAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw HonchkrowAnimation
	dw SlowkingPlainAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw UnownAAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw ElekidAnimation
	dw ElectivireAnimation
	dw MagbyAnimation
	dw MagmortarAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw SylveonAnimation
	assert_table_length NUM_POKEMON

	dw EggAnimation

	dw UnownBAnimation
	dw UnownCAnimation
	dw UnownDAnimation
	dw UnownEAnimation
	dw UnownFAnimation
	dw UnownGAnimation
	dw UnownHAnimation
	dw UnownIAnimation
	dw UnownJAnimation
	dw UnownKAnimation
	dw UnownLAnimation
	dw UnownMAnimation
	dw UnownNAnimation
	dw UnownOAnimation
	dw UnownPAnimation
	dw UnownQAnimation
	dw UnownRAnimation
	dw UnownSAnimation
	dw UnownTAnimation
	dw UnownUAnimation
	dw UnownVAnimation
	dw UnownWAnimation
	dw UnownXAnimation
	dw UnownYAnimation
	dw UnownZAnimation
	dw UnownExclamationAnimation
	dw UnownQuestionAnimation

	dw ArbokKantoAnimation
	dw ArbokKogaAnimation
	dw ArbokAgathaAnimation
	dw ArbokArianaAnimation

	dw PikachuFlyAnimation
	dw PikachuSurfAnimation
	dw PikachuPikaAnimation
	dw PikachuChuchuAnimation
	dw PikachuSparkAnimation

	dw PichuSpikyAnimation

	dw MagikarpSkellyAnimation
	dw MagikarpCalico1Animation
	dw MagikarpCalico2Animation
	dw MagikarpCalico3Animation
	dw MagikarpTwoToneAnimation
	dw MagikarpOrcaAnimation
	dw MagikarpDapplesAnimation
	dw MagikarpTigerAnimation
	dw MagikarpZebraAnimation
	dw MagikarpStripeAnimation
	dw MagikarpBubblesAnimation
	dw MagikarpForeheadAnimation
	dw MagikarpMaskAnimation
	dw MagikarpSaucyAnimation
	dw MagikarpRaindropAnimation

	dw GyaradosRedAnimation
	dw MewtwoArmoredAnimation
	dw RattataAlolanAnimation
	dw RaticateAlolanAnimation
	dw SandshrewAlolanAnimation
	dw SandslashAlolanAnimation
	dw VulpixAlolanAnimation
	dw NinetalesAlolanAnimation
	dw DiglettAlolanAnimation
	dw DugtrioAlolanAnimation
	dw MeowthAlolanAnimation
	dw PersianAlolanAnimation
	dw GeodudeAlolanAnimation
	dw GravelerAlolanAnimation
	dw GolemAlolanAnimation
	dw GrimerAlolanAnimation
	dw MukAlolanAnimation
	dw RaichuAlolanAnimation
	dw ExeggutorAlolanAnimation
	dw MarowakAlolanAnimation
	dw PonytaGalarianAnimation
	dw RapidashGalarianAnimation
	dw SlowpokeGalarianAnimation
	dw SlowbroGalarianAnimation
	dw SlowkingGalarianAnimation
	dw WeezingGalarianAnimation
	dw ArticunoGalarianAnimation
	dw ZapdosGalarianAnimation
	dw MoltresGalarianAnimation

	assert_table_length NUM_UNIQUE_POKEMON
