BitmasksPointers:
	table_width 2
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw WeedleBitmasks
	dw KakunaBitmasks
	dw BeedrillBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw RattataPlainBitmasks
	dw RaticatePlainBitmasks
	dw SpearowBitmasks
	dw FearowBitmasks
	dw EkansBitmasks
	dw ArbokJohtoBitmasks
	dw PikachuPlainBitmasks
	dw RaichuPlainBitmasks
	dw SandshrewPlainBitmasks
	dw SandslashPlainBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixPlainBitmasks
	dw NinetalesPlainBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw ParasBitmasks
	dw ParasectBitmasks
	dw VenonatBitmasks
	dw VenomothBitmasks
	dw DiglettPlainBitmasks
	dw DugtrioPlainBitmasks
	dw MeowthPlainBitmasks
	dw PersianPlainBitmasks
	dw PsyduckBitmasks
	dw GolduckBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlithePlainBitmasks
	dw ArcaninePlainBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudePlainBitmasks
	dw GravelerPlainBitmasks
	dw GolemPlainBitmasks
	dw PonytaPlainBitmasks
	dw RapidashPlainBitmasks
	dw SlowpokePlainBitmasks
	dw SlowbroPlainBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw FarfetchDPlainBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerPlainBitmasks
	dw MukPlainBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw KrabbyBitmasks
	dw KinglerBitmasks
	dw VoltorbPlainBitmasks
	dw ElectrodePlainBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorPlainBitmasks
	dw CuboneBitmasks
	dw MarowakPlainBitmasks
	dw HitmonleeBitmasks
	dw HitmonchanBitmasks
	dw LickitungBitmasks
	dw KoffingBitmasks
	dw WeezingPlainBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw GoldeenBitmasks
	dw SeakingBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimePlainBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw PinsirBitmasks
	dw TaurosPlainBitmasks
	dw MagikarpPlainBitmasks
	dw GyaradosPlainBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoPlainBitmasks
	dw ZapdosPlainBitmasks
	dw MoltresPlainBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoPlainBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionPlainBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuPlainBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperPlainBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingPlainBitmasks
	dw MisdreavusBitmasks
	dw UnownABitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishPlainBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselPlainBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaPlainBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw TyrogueBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw AzurillBitmasks
	dw WynautBitmasks
	dw AmbipomBitmasks
	dw EggBitmasks
	dw EggBitmasks ; $100
	dw MismagiusBitmasks
	dw HonchkrowBitmasks
	dw BonslyBitmasks
	dw MimeJrBitmasks
	dw HappinyBitmasks
	dw MunchlaxBitmasks
	dw MantykeBitmasks
	dw WeavileBitmasks
	dw MagnezoneBitmasks
	dw LickilickyBitmasks
	dw RhyperiorBitmasks
	dw TangrowthBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw TogekissBitmasks
	dw YanmegaBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw GliscorBitmasks
	dw MamoswineBitmasks
	dw PorygonZBitmasks
	dw SylveonBitmasks
	dw PerrserkerBitmasks
	dw CursolaBitmasks
	dw SirfetchDBitmasks
	dw MrRimeBitmasks
	dw WyrdeerBitmasks
	dw KleavorBitmasks
	dw UrsalunaPlainBitmasks
	dw SneaslerBitmasks
	dw OverqwilBitmasks
	dw DudunsparceTwoSegmentBitmasks
	dw FarigirafBitmasks
	dw ClodsireBitmasks
	dw AnnihilapeBitmasks
	assert_table_length NUM_SPECIES

	dw UnownBBitmasks
	dw UnownCBitmasks
	dw UnownDBitmasks
	dw UnownEBitmasks
	dw UnownFBitmasks
	dw UnownGBitmasks
	dw UnownHBitmasks
	dw UnownIBitmasks
	dw UnownJBitmasks
	dw UnownKBitmasks
	dw UnownLBitmasks
	dw UnownMBitmasks
	dw UnownNBitmasks
	dw UnownOBitmasks
	dw UnownPBitmasks
	dw UnownQBitmasks
	dw UnownRBitmasks
	dw UnownSBitmasks
	dw UnownTBitmasks
	dw UnownUBitmasks
	dw UnownVBitmasks
	dw UnownWBitmasks
	dw UnownXBitmasks
	dw UnownYBitmasks
	dw UnownZBitmasks
	dw UnownExclamationBitmasks
	dw UnownQuestionBitmasks

	dw ArbokKantoBitmasks
	dw ArbokOrangeBitmasks
	dw ArbokKogaBitmasks
	dw ArbokAgathaBitmasks
	dw ArbokArianaBitmasks

	dw PikachuFlyBitmasks
	dw PikachuSurfBitmasks
	dw PikachuPikaBitmasks
	dw PikachuChuchuBitmasks
	dw PikachuSparkBitmasks

	dw PichuSpikyBitmasks

	dw MagikarpSkellyBitmasks
	dw MagikarpCalico1Bitmasks
	dw MagikarpCalico2Bitmasks
	dw MagikarpCalico3Bitmasks
	dw MagikarpTwoToneBitmasks
	dw MagikarpOrcaBitmasks
	dw MagikarpDapplesBitmasks
	dw MagikarpTigerBitmasks
	dw MagikarpZebraBitmasks
	dw MagikarpStripeBitmasks
	dw MagikarpBubblesBitmasks
	dw MagikarpDiamondsBitmasks
	dw MagikarpPatchesBitmasks
	dw MagikarpForehead1Bitmasks
	dw MagikarpMask1Bitmasks
	dw MagikarpForehead2Bitmasks
	dw MagikarpMask2Bitmasks
	dw MagikarpSaucyBitmasks
	dw MagikarpRaindropBitmasks

	assert_table_length NUM_SPECIES + NUM_COSMETIC_FORMS

	dw GyaradosRedBitmasks

	dw MewtwoArmoredBitmasks

	dw DudunsparceThreeSegmentBitmasks

	dw RattataAlolanBitmasks
	dw RaticateAlolanBitmasks
	dw RaichuAlolanBitmasks
	dw SandshrewAlolanBitmasks
	dw SandslashAlolanBitmasks
	dw VulpixAlolanBitmasks
	dw NinetalesAlolanBitmasks
	dw DiglettAlolanBitmasks
	dw DugtrioAlolanBitmasks
	dw MeowthAlolanBitmasks
	dw PersianAlolanBitmasks
	dw GeodudeAlolanBitmasks
	dw GravelerAlolanBitmasks
	dw GolemAlolanBitmasks
	dw GrimerAlolanBitmasks
	dw MukAlolanBitmasks
	dw ExeggutorAlolanBitmasks
	dw MarowakAlolanBitmasks

	dw MeowthGalarianBitmasks
	dw PonytaGalarianBitmasks
	dw RapidashGalarianBitmasks
	dw SlowpokeGalarianBitmasks
	dw SlowbroGalarianBitmasks
	dw FarfetchDGalarianBitmasks
	dw WeezingGalarianBitmasks
	dw MrMimeGalarianBitmasks
	dw ArticunoGalarianBitmasks
	dw ZapdosGalarianBitmasks
	dw MoltresGalarianBitmasks
	dw SlowkingGalarianBitmasks
	dw CorsolaGalarianBitmasks

	dw GrowlitheHisuianBitmasks
	dw ArcanineHisuianBitmasks
	dw VoltorbHisuianBitmasks
	dw ElectrodeHisuianBitmasks
	dw TyphlosionHisuianBitmasks
	dw QwilfishHisuianBitmasks
	dw SneaselHisuianBitmasks

	dw WooperPaldeanBitmasks
	dw TaurosPaldeanBitmasks
	dw TaurosPaldeanFireBitmasks
	dw TaurosPaldeanWaterBitmasks

	dw UrsalunaBloodmoonBitmasks

	assert_table_length NUM_UNIQUE_POKEMON
