BulbasaurAnimationExtra:  INCLUDE "gfx/pokemon/bulbasaur/anim_idle.asm"
IvysaurAnimationExtra:    INCLUDE "gfx/pokemon/ivysaur/anim_idle.asm"
VenusaurAnimationExtra:   INCLUDE "gfx/pokemon/venusaur/anim_idle.asm"
CharmanderAnimationExtra: INCLUDE "gfx/pokemon/charmander/anim_idle.asm"
CharmeleonAnimationExtra: INCLUDE "gfx/pokemon/charmeleon/anim_idle.asm"
CharizardAnimationExtra:  INCLUDE "gfx/pokemon/charizard/anim_idle.asm"
SquirtleAnimationExtra:   INCLUDE "gfx/pokemon/squirtle/anim_idle.asm"
WartortleAnimationExtra:  INCLUDE "gfx/pokemon/wartortle/anim_idle.asm"
BlastoiseAnimationExtra:  INCLUDE "gfx/pokemon/blastoise/anim_idle.asm"
CaterpieAnimationExtra:   INCLUDE "gfx/pokemon/caterpie/anim_idle.asm"
MetapodAnimationExtra:    INCLUDE "gfx/pokemon/metapod/anim_idle.asm"
ButterfreeAnimationExtra: INCLUDE "gfx/pokemon/butterfree/anim_idle.asm"
WeedleAnimationExtra:     INCLUDE "gfx/pokemon/weedle/anim_idle.asm"
KakunaAnimationExtra:     INCLUDE "gfx/pokemon/kakuna/anim_idle.asm"
BeedrillAnimationExtra:   INCLUDE "gfx/pokemon/beedrill/anim_idle.asm"
PidgeyAnimationExtra:     INCLUDE "gfx/pokemon/pidgey/anim_idle.asm"
PidgeottoAnimationExtra:  INCLUDE "gfx/pokemon/pidgeotto/anim_idle.asm"
PidgeotAnimationExtra:    INCLUDE "gfx/pokemon/pidgeot/anim_idle.asm"
SpearowAnimationExtra:    INCLUDE "gfx/pokemon/spearow/anim_idle.asm"
FearowAnimationExtra:     INCLUDE "gfx/pokemon/fearow/anim_idle.asm"
EkansAnimationExtra:      INCLUDE "gfx/pokemon/ekans/anim_idle.asm"
NidoranFAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_f/anim_idle.asm"
NidorinaAnimationExtra:   INCLUDE "gfx/pokemon/nidorina/anim_idle.asm"
NidoqueenAnimationExtra:  INCLUDE "gfx/pokemon/nidoqueen/anim_idle.asm"
NidoranMAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_m/anim_idle.asm"
NidorinoAnimationExtra:   INCLUDE "gfx/pokemon/nidorino/anim_idle.asm"
NidokingAnimationExtra:   INCLUDE "gfx/pokemon/nidoking/anim_idle.asm"
ClefairyAnimationExtra:   INCLUDE "gfx/pokemon/clefairy/anim_idle.asm"
ClefableAnimationExtra:   INCLUDE "gfx/pokemon/clefable/anim_idle.asm"
JigglypuffAnimationExtra: INCLUDE "gfx/pokemon/jigglypuff/anim_idle.asm"
WigglytuffAnimationExtra: INCLUDE "gfx/pokemon/wigglytuff/anim_idle.asm"
ZubatAnimationExtra:      INCLUDE "gfx/pokemon/zubat/anim_idle.asm"
GolbatAnimationExtra:     INCLUDE "gfx/pokemon/golbat/anim_idle.asm"
OddishAnimationExtra:     INCLUDE "gfx/pokemon/oddish/anim_idle.asm"
GloomAnimationExtra:      INCLUDE "gfx/pokemon/gloom/anim_idle.asm"
VileplumeAnimationExtra:  INCLUDE "gfx/pokemon/vileplume/anim_idle.asm"
ParasAnimationExtra:      INCLUDE "gfx/pokemon/paras/anim_idle.asm"
ParasectAnimationExtra:   INCLUDE "gfx/pokemon/parasect/anim_idle.asm"
VenonatAnimationExtra:    INCLUDE "gfx/pokemon/venonat/anim_idle.asm"
VenomothAnimationExtra:   INCLUDE "gfx/pokemon/venomoth/anim_idle.asm"
PsyduckAnimationExtra:    INCLUDE "gfx/pokemon/psyduck/anim_idle.asm"
GolduckAnimationExtra:    INCLUDE "gfx/pokemon/golduck/anim_idle.asm"
MankeyAnimationExtra:     INCLUDE "gfx/pokemon/mankey/anim_idle.asm"
PrimeapeAnimationExtra:   INCLUDE "gfx/pokemon/primeape/anim_idle.asm"
PoliwagAnimationExtra:    INCLUDE "gfx/pokemon/poliwag/anim_idle.asm"
PoliwhirlAnimationExtra:  INCLUDE "gfx/pokemon/poliwhirl/anim_idle.asm"
PoliwrathAnimationExtra:  INCLUDE "gfx/pokemon/poliwrath/anim_idle.asm"
AbraAnimationExtra:       INCLUDE "gfx/pokemon/abra/anim_idle.asm"
KadabraAnimationExtra:    INCLUDE "gfx/pokemon/kadabra/anim_idle.asm"
AlakazamAnimationExtra:   INCLUDE "gfx/pokemon/alakazam/anim_idle.asm"
MachopAnimationExtra:     INCLUDE "gfx/pokemon/machop/anim_idle.asm"
MachokeAnimationExtra:    INCLUDE "gfx/pokemon/machoke/anim_idle.asm"
MachampAnimationExtra:    INCLUDE "gfx/pokemon/machamp/anim_idle.asm"
BellsproutAnimationExtra: INCLUDE "gfx/pokemon/bellsprout/anim_idle.asm"
WeepinbellAnimationExtra: INCLUDE "gfx/pokemon/weepinbell/anim_idle.asm"
VictreebelAnimationExtra: INCLUDE "gfx/pokemon/victreebel/anim_idle.asm"
TentacoolAnimationExtra:  INCLUDE "gfx/pokemon/tentacool/anim_idle.asm"
TentacruelAnimationExtra: INCLUDE "gfx/pokemon/tentacruel/anim_idle.asm"
MagnemiteAnimationExtra:  INCLUDE "gfx/pokemon/magnemite/anim_idle.asm"
MagnetonAnimationExtra:   INCLUDE "gfx/pokemon/magneton/anim_idle.asm"
DoduoAnimationExtra:      INCLUDE "gfx/pokemon/doduo/anim_idle.asm"
DodrioAnimationExtra:     INCLUDE "gfx/pokemon/dodrio/anim_idle.asm"
SeelAnimationExtra:       INCLUDE "gfx/pokemon/seel/anim_idle.asm"
DewgongAnimationExtra:    INCLUDE "gfx/pokemon/dewgong/anim_idle.asm"
ShellderAnimationExtra:   INCLUDE "gfx/pokemon/shellder/anim_idle.asm"
CloysterAnimationExtra:   INCLUDE "gfx/pokemon/cloyster/anim_idle.asm"
GastlyAnimationExtra:     INCLUDE "gfx/pokemon/gastly/anim_idle.asm"
HaunterAnimationExtra:    INCLUDE "gfx/pokemon/haunter/anim_idle.asm"
GengarAnimationExtra:     INCLUDE "gfx/pokemon/gengar/anim_idle.asm"
OnixAnimationExtra:       INCLUDE "gfx/pokemon/onix/anim_idle.asm"
DrowzeeAnimationExtra:    INCLUDE "gfx/pokemon/drowzee/anim_idle.asm"
HypnoAnimationExtra:      INCLUDE "gfx/pokemon/hypno/anim_idle.asm"
KrabbyAnimationExtra:     INCLUDE "gfx/pokemon/krabby/anim_idle.asm"
KinglerAnimationExtra:    INCLUDE "gfx/pokemon/kingler/anim_idle.asm"
ExeggcuteAnimationExtra:  INCLUDE "gfx/pokemon/exeggcute/anim_idle.asm"
CuboneAnimationExtra:     INCLUDE "gfx/pokemon/cubone/anim_idle.asm"
HitmonleeAnimationExtra:  INCLUDE "gfx/pokemon/hitmonlee/anim_idle.asm"
HitmonchanAnimationExtra: INCLUDE "gfx/pokemon/hitmonchan/anim_idle.asm"
LickitungAnimationExtra:  INCLUDE "gfx/pokemon/lickitung/anim_idle.asm"
KoffingAnimationExtra:    INCLUDE "gfx/pokemon/koffing/anim_idle.asm"
RhyhornAnimationExtra:    INCLUDE "gfx/pokemon/rhyhorn/anim_idle.asm"
RhydonAnimationExtra:     INCLUDE "gfx/pokemon/rhydon/anim_idle.asm"
ChanseyAnimationExtra:    INCLUDE "gfx/pokemon/chansey/anim_idle.asm"
TangelaAnimationExtra:    INCLUDE "gfx/pokemon/tangela/anim_idle.asm"
KangaskhanAnimationExtra: INCLUDE "gfx/pokemon/kangaskhan/anim_idle.asm"
HorseaAnimationExtra:     INCLUDE "gfx/pokemon/horsea/anim_idle.asm"
SeadraAnimationExtra:     INCLUDE "gfx/pokemon/seadra/anim_idle.asm"
GoldeenAnimationExtra:    INCLUDE "gfx/pokemon/goldeen/anim_idle.asm"
SeakingAnimationExtra:    INCLUDE "gfx/pokemon/seaking/anim_idle.asm"
StaryuAnimationExtra:     INCLUDE "gfx/pokemon/staryu/anim_idle.asm"
StarmieAnimationExtra:    INCLUDE "gfx/pokemon/starmie/anim_idle.asm"
ScytherAnimationExtra:    INCLUDE "gfx/pokemon/scyther/anim_idle.asm"
JynxAnimationExtra:       INCLUDE "gfx/pokemon/jynx/anim_idle.asm"
ElectabuzzAnimationExtra: INCLUDE "gfx/pokemon/electabuzz/anim_idle.asm"
MagmarAnimationExtra:     INCLUDE "gfx/pokemon/magmar/anim_idle.asm"
PinsirAnimationExtra:     INCLUDE "gfx/pokemon/pinsir/anim_idle.asm"
LaprasAnimationExtra:     INCLUDE "gfx/pokemon/lapras/anim_idle.asm"
DittoAnimationExtra:      INCLUDE "gfx/pokemon/ditto/anim_idle.asm"
EeveeAnimationExtra:      INCLUDE "gfx/pokemon/eevee/anim_idle.asm"
VaporeonAnimationExtra:   INCLUDE "gfx/pokemon/vaporeon/anim_idle.asm"
JolteonAnimationExtra:    INCLUDE "gfx/pokemon/jolteon/anim_idle.asm"
FlareonAnimationExtra:    INCLUDE "gfx/pokemon/flareon/anim_idle.asm"
PorygonAnimationExtra:    INCLUDE "gfx/pokemon/porygon/anim_idle.asm"
OmanyteAnimationExtra:    INCLUDE "gfx/pokemon/omanyte/anim_idle.asm"
OmastarAnimationExtra:    INCLUDE "gfx/pokemon/omastar/anim_idle.asm"
KabutoAnimationExtra:     INCLUDE "gfx/pokemon/kabuto/anim_idle.asm"
KabutopsAnimationExtra:   INCLUDE "gfx/pokemon/kabutops/anim_idle.asm"
AerodactylAnimationExtra: INCLUDE "gfx/pokemon/aerodactyl/anim_idle.asm"
SnorlaxAnimationExtra:    INCLUDE "gfx/pokemon/snorlax/anim_idle.asm"
DratiniAnimationExtra:    INCLUDE "gfx/pokemon/dratini/anim_idle.asm"
DragonairAnimationExtra:  INCLUDE "gfx/pokemon/dragonair/anim_idle.asm"
DragoniteAnimationExtra:  INCLUDE "gfx/pokemon/dragonite/anim_idle.asm"
MewAnimationExtra:        INCLUDE "gfx/pokemon/mew/anim_idle.asm"
ChikoritaAnimationExtra:  INCLUDE "gfx/pokemon/chikorita/anim_idle.asm"
BayleefAnimationExtra:    INCLUDE "gfx/pokemon/bayleef/anim_idle.asm"
MeganiumAnimationExtra:   INCLUDE "gfx/pokemon/meganium/anim_idle.asm"
CyndaquilAnimationExtra:  INCLUDE "gfx/pokemon/cyndaquil/anim_idle.asm"
QuilavaAnimationExtra:    INCLUDE "gfx/pokemon/quilava/anim_idle.asm"
TotodileAnimationExtra:   INCLUDE "gfx/pokemon/totodile/anim_idle.asm"
CroconawAnimationExtra:   INCLUDE "gfx/pokemon/croconaw/anim_idle.asm"
FeraligatrAnimationExtra: INCLUDE "gfx/pokemon/feraligatr/anim_idle.asm"
SentretAnimationExtra:    INCLUDE "gfx/pokemon/sentret/anim_idle.asm"
FurretAnimationExtra:     INCLUDE "gfx/pokemon/furret/anim_idle.asm"
HoothootAnimationExtra:   INCLUDE "gfx/pokemon/hoothoot/anim_idle.asm"
NoctowlAnimationExtra:    INCLUDE "gfx/pokemon/noctowl/anim_idle.asm"
LedybaAnimationExtra:     INCLUDE "gfx/pokemon/ledyba/anim_idle.asm"
LedianAnimationExtra:     INCLUDE "gfx/pokemon/ledian/anim_idle.asm"
SpinarakAnimationExtra:   INCLUDE "gfx/pokemon/spinarak/anim_idle.asm"
AriadosAnimationExtra:    INCLUDE "gfx/pokemon/ariados/anim_idle.asm"
CrobatAnimationExtra:     INCLUDE "gfx/pokemon/crobat/anim_idle.asm"
ChinchouAnimationExtra:   INCLUDE "gfx/pokemon/chinchou/anim_idle.asm"
LanturnAnimationExtra:    INCLUDE "gfx/pokemon/lanturn/anim_idle.asm"
CleffaAnimationExtra:     INCLUDE "gfx/pokemon/cleffa/anim_idle.asm"
IgglybuffAnimationExtra:  INCLUDE "gfx/pokemon/igglybuff/anim_idle.asm"
TogepiAnimationExtra:     INCLUDE "gfx/pokemon/togepi/anim_idle.asm"
TogeticAnimationExtra:    INCLUDE "gfx/pokemon/togetic/anim_idle.asm"
NatuAnimationExtra:       INCLUDE "gfx/pokemon/natu/anim_idle.asm"
XatuAnimationExtra:       INCLUDE "gfx/pokemon/xatu/anim_idle.asm"
MareepAnimationExtra:     INCLUDE "gfx/pokemon/mareep/anim_idle.asm"
FlaaffyAnimationExtra:    INCLUDE "gfx/pokemon/flaaffy/anim_idle.asm"
AmpharosAnimationExtra:   INCLUDE "gfx/pokemon/ampharos/anim_idle.asm"
BellossomAnimationExtra:  INCLUDE "gfx/pokemon/bellossom/anim_idle.asm"
SudowoodoAnimationExtra:  INCLUDE "gfx/pokemon/sudowoodo/anim_idle.asm"
MarillAnimationExtra:     INCLUDE "gfx/pokemon/marill/anim_idle.asm"
AzumarillAnimationExtra:  INCLUDE "gfx/pokemon/azumarill/anim_idle.asm"
PolitoedAnimationExtra:   INCLUDE "gfx/pokemon/politoed/anim_idle.asm"
HoppipAnimationExtra:     INCLUDE "gfx/pokemon/hoppip/anim_idle.asm"
SkiploomAnimationExtra:   INCLUDE "gfx/pokemon/skiploom/anim_idle.asm"
JumpluffAnimationExtra:   INCLUDE "gfx/pokemon/jumpluff/anim_idle.asm"
AipomAnimationExtra:      INCLUDE "gfx/pokemon/aipom/anim_idle.asm"
SunkernAnimationExtra:    INCLUDE "gfx/pokemon/sunkern/anim_idle.asm"
SunfloraAnimationExtra:   INCLUDE "gfx/pokemon/sunflora/anim_idle.asm"
YanmaAnimationExtra:      INCLUDE "gfx/pokemon/yanma/anim_idle.asm"
QuagsireAnimationExtra:   INCLUDE "gfx/pokemon/quagsire/anim_idle.asm"
EspeonAnimationExtra:     INCLUDE "gfx/pokemon/espeon/anim_idle.asm"
UmbreonAnimationExtra:    INCLUDE "gfx/pokemon/umbreon/anim_idle.asm"
MurkrowAnimationExtra:    INCLUDE "gfx/pokemon/murkrow/anim_idle.asm"
MisdreavusAnimationExtra: INCLUDE "gfx/pokemon/misdreavus/anim_idle.asm"
WobbuffetAnimationExtra:  INCLUDE "gfx/pokemon/wobbuffet/anim_idle.asm"
GirafarigAnimationExtra:  INCLUDE "gfx/pokemon/girafarig/anim_idle.asm"
PinecoAnimationExtra:     INCLUDE "gfx/pokemon/pineco/anim_idle.asm"
ForretressAnimationExtra: INCLUDE "gfx/pokemon/forretress/anim_idle.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim_idle.asm"
GligarAnimationExtra:     INCLUDE "gfx/pokemon/gligar/anim_idle.asm"
SteelixAnimationExtra:    INCLUDE "gfx/pokemon/steelix/anim_idle.asm"
SnubbullAnimationExtra:   INCLUDE "gfx/pokemon/snubbull/anim_idle.asm"
GranbullAnimationExtra:   INCLUDE "gfx/pokemon/granbull/anim_idle.asm"
ScizorAnimationExtra:     INCLUDE "gfx/pokemon/scizor/anim_idle.asm"
ShuckleAnimationExtra:    INCLUDE "gfx/pokemon/shuckle/anim_idle.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim_idle.asm"
TeddiursaAnimationExtra:  INCLUDE "gfx/pokemon/teddiursa/anim_idle.asm"
UrsaringAnimationExtra:   INCLUDE "gfx/pokemon/ursaring/anim_idle.asm"
SlugmaAnimationExtra:     INCLUDE "gfx/pokemon/slugma/anim_idle.asm"
MagcargoAnimationExtra:   INCLUDE "gfx/pokemon/magcargo/anim_idle.asm"
SwinubAnimationExtra:     INCLUDE "gfx/pokemon/swinub/anim_idle.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim_idle.asm"
RemoraidAnimationExtra:   INCLUDE "gfx/pokemon/remoraid/anim_idle.asm"
OctilleryAnimationExtra:  INCLUDE "gfx/pokemon/octillery/anim_idle.asm"
DelibirdAnimationExtra:   INCLUDE "gfx/pokemon/delibird/anim_idle.asm"
MantineAnimationExtra:    INCLUDE "gfx/pokemon/mantine/anim_idle.asm"
SkarmoryAnimationExtra:   INCLUDE "gfx/pokemon/skarmory/anim_idle.asm"
HoundourAnimationExtra:   INCLUDE "gfx/pokemon/houndour/anim_idle.asm"
HoundoomAnimationExtra:   INCLUDE "gfx/pokemon/houndoom/anim_idle.asm"
KingdraAnimationExtra:    INCLUDE "gfx/pokemon/kingdra/anim_idle.asm"
PhanpyAnimationExtra:     INCLUDE "gfx/pokemon/phanpy/anim_idle.asm"
DonphanAnimationExtra:    INCLUDE "gfx/pokemon/donphan/anim_idle.asm"
Porygon2AnimationExtra:   INCLUDE "gfx/pokemon/porygon2/anim_idle.asm"
StantlerAnimationExtra:   INCLUDE "gfx/pokemon/stantler/anim_idle.asm"
SmeargleAnimationExtra:   INCLUDE "gfx/pokemon/smeargle/anim_idle.asm"
TyrogueAnimationExtra:    INCLUDE "gfx/pokemon/tyrogue/anim_idle.asm"
HitmontopAnimationExtra:  INCLUDE "gfx/pokemon/hitmontop/anim_idle.asm"
SmoochumAnimationExtra:   INCLUDE "gfx/pokemon/smoochum/anim_idle.asm"
ElekidAnimationExtra:     INCLUDE "gfx/pokemon/elekid/anim_idle.asm"
MagbyAnimationExtra:      INCLUDE "gfx/pokemon/magby/anim_idle.asm"
MiltankAnimationExtra:    INCLUDE "gfx/pokemon/miltank/anim_idle.asm"
BlisseyAnimationExtra:    INCLUDE "gfx/pokemon/blissey/anim_idle.asm"
RaikouAnimationExtra:     INCLUDE "gfx/pokemon/raikou/anim_idle.asm"
EnteiAnimationExtra:      INCLUDE "gfx/pokemon/entei/anim_idle.asm"
SuicuneAnimationExtra:    INCLUDE "gfx/pokemon/suicune/anim_idle.asm"
LarvitarAnimationExtra:   INCLUDE "gfx/pokemon/larvitar/anim_idle.asm"
PupitarAnimationExtra:    INCLUDE "gfx/pokemon/pupitar/anim_idle.asm"
TyranitarAnimationExtra:  INCLUDE "gfx/pokemon/tyranitar/anim_idle.asm"
LugiaAnimationExtra:      INCLUDE "gfx/pokemon/lugia/anim_idle.asm"
HoOhAnimationExtra:       INCLUDE "gfx/pokemon/ho_oh/anim_idle.asm"
CelebiAnimationExtra:     INCLUDE "gfx/pokemon/celebi/anim_idle.asm"
AzurillAnimationExtra:    INCLUDE "gfx/pokemon/azurill/anim_idle.asm"
WynautAnimationExtra:     INCLUDE "gfx/pokemon/wynaut/anim_idle.asm"
AmbipomAnimationExtra:    INCLUDE "gfx/pokemon/ambipom/anim_idle.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim_idle.asm"
HonchkrowAnimationExtra:  INCLUDE "gfx/pokemon/honchkrow/anim_idle.asm"
BonslyAnimationExtra:     INCLUDE "gfx/pokemon/bonsly/anim_idle.asm"
MimeJrAnimationExtra:     INCLUDE "gfx/pokemon/mime_jr_/anim_idle.asm"
HappinyAnimationExtra:    INCLUDE "gfx/pokemon/happiny/anim_idle.asm"
MunchlaxAnimationExtra:   INCLUDE "gfx/pokemon/munchlax/anim_idle.asm"
MantykeAnimationExtra:    INCLUDE "gfx/pokemon/mantyke/anim_idle.asm"
WeavileAnimationExtra:    INCLUDE "gfx/pokemon/weavile/anim_idle.asm"
MagnezoneAnimationExtra:  INCLUDE "gfx/pokemon/magnezone/anim_idle.asm"
LickilickyAnimationExtra: INCLUDE "gfx/pokemon/lickilicky/anim_idle.asm"
RhyperiorAnimationExtra:  INCLUDE "gfx/pokemon/rhyperior/anim_idle.asm"
TangrowthAnimationExtra:  INCLUDE "gfx/pokemon/tangrowth/anim_idle.asm"
ElectivireAnimationExtra: INCLUDE "gfx/pokemon/electivire/anim_idle.asm"
MagmortarAnimationExtra:  INCLUDE "gfx/pokemon/magmortar/anim_idle.asm"
TogekissAnimationExtra:   INCLUDE "gfx/pokemon/togekiss/anim_idle.asm"
YanmegaAnimationExtra:    INCLUDE "gfx/pokemon/yanmega/anim_idle.asm"
LeafeonAnimationExtra:    INCLUDE "gfx/pokemon/leafeon/anim_idle.asm"
GlaceonAnimationExtra:    INCLUDE "gfx/pokemon/glaceon/anim_idle.asm"
GliscorAnimationExtra:    INCLUDE "gfx/pokemon/gliscor/anim_idle.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim_idle.asm"
PorygonZAnimationExtra:   INCLUDE "gfx/pokemon/porygon_z/anim_idle.asm"
SylveonAnimationExtra:    INCLUDE "gfx/pokemon/sylveon/anim_idle.asm"
PerrserkerAnimationExtra: INCLUDE "gfx/pokemon/perrserker/anim_idle.asm"
CursolaAnimationExtra:    INCLUDE "gfx/pokemon/cursola/anim_idle.asm"
SirfetchDAnimationExtra:  INCLUDE "gfx/pokemon/sirfetch_d/anim_idle.asm"
MrRimeAnimationExtra:     INCLUDE "gfx/pokemon/mr__rime/anim_idle.asm"
WyrdeerAnimationExtra:    INCLUDE "gfx/pokemon/wyrdeer/anim_idle.asm"
KleavorAnimationExtra:    INCLUDE "gfx/pokemon/kleavor/anim_idle.asm"
SneaslerAnimationExtra:   INCLUDE "gfx/pokemon/sneasler/anim_idle.asm"
OverqwilAnimationExtra:   INCLUDE "gfx/pokemon/overqwil/anim_idle.asm"
FarigirafAnimationExtra:  INCLUDE "gfx/pokemon/farigiraf/anim_idle.asm"
ClodsireAnimationExtra:   INCLUDE "gfx/pokemon/clodsire/anim_idle.asm"
AnnihilapeAnimationExtra: INCLUDE "gfx/pokemon/annihilape/anim_idle.asm"

EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim_idle.asm"

UnownAAnimationExtra: INCLUDE "gfx/pokemon/unown_a/anim_idle.asm"
UnownBAnimationExtra: INCLUDE "gfx/pokemon/unown_b/anim_idle.asm"
UnownCAnimationExtra: INCLUDE "gfx/pokemon/unown_c/anim_idle.asm"
UnownDAnimationExtra: INCLUDE "gfx/pokemon/unown_d/anim_idle.asm"
UnownEAnimationExtra: INCLUDE "gfx/pokemon/unown_e/anim_idle.asm"
UnownFAnimationExtra: INCLUDE "gfx/pokemon/unown_f/anim_idle.asm"
UnownGAnimationExtra: INCLUDE "gfx/pokemon/unown_g/anim_idle.asm"
UnownHAnimationExtra: INCLUDE "gfx/pokemon/unown_h/anim_idle.asm"
UnownIAnimationExtra: INCLUDE "gfx/pokemon/unown_i/anim_idle.asm"
UnownJAnimationExtra: INCLUDE "gfx/pokemon/unown_j/anim_idle.asm"
UnownKAnimationExtra: INCLUDE "gfx/pokemon/unown_k/anim_idle.asm"
UnownLAnimationExtra: INCLUDE "gfx/pokemon/unown_l/anim_idle.asm"
UnownMAnimationExtra: INCLUDE "gfx/pokemon/unown_m/anim_idle.asm"
UnownNAnimationExtra: INCLUDE "gfx/pokemon/unown_n/anim_idle.asm"
UnownOAnimationExtra: INCLUDE "gfx/pokemon/unown_o/anim_idle.asm"
UnownPAnimationExtra: INCLUDE "gfx/pokemon/unown_p/anim_idle.asm"
UnownQAnimationExtra: INCLUDE "gfx/pokemon/unown_q/anim_idle.asm"
UnownRAnimationExtra: INCLUDE "gfx/pokemon/unown_r/anim_idle.asm"
UnownSAnimationExtra: INCLUDE "gfx/pokemon/unown_s/anim_idle.asm"
UnownTAnimationExtra: INCLUDE "gfx/pokemon/unown_t/anim_idle.asm"
UnownUAnimationExtra: INCLUDE "gfx/pokemon/unown_u/anim_idle.asm"
UnownVAnimationExtra: INCLUDE "gfx/pokemon/unown_v/anim_idle.asm"
UnownWAnimationExtra: INCLUDE "gfx/pokemon/unown_w/anim_idle.asm"
UnownXAnimationExtra: INCLUDE "gfx/pokemon/unown_x/anim_idle.asm"
UnownYAnimationExtra: INCLUDE "gfx/pokemon/unown_y/anim_idle.asm"
UnownZAnimationExtra: INCLUDE "gfx/pokemon/unown_z/anim_idle.asm"
UnownExclamationAnimationExtra: INCLUDE "gfx/pokemon/unown_exclamation/anim_idle.asm"
UnownQuestionAnimationExtra:    INCLUDE "gfx/pokemon/unown_question/anim_idle.asm"

PichuPlainAnimationExtra: INCLUDE "gfx/pokemon/pichu_plain/anim_idle.asm"
PichuSpikyAnimationExtra: INCLUDE "gfx/pokemon/pichu_spiky/anim_idle.asm"

PikachuSparkAnimationExtra:
PikachuPlainAnimationExtra:  INCLUDE "gfx/pokemon/pikachu_plain/anim_idle.asm"
PikachuFlyAnimationExtra:    INCLUDE "gfx/pokemon/pikachu_fly/anim_idle.asm"
PikachuSurfAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_surf/anim_idle.asm"
PikachuPikaAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_pika/anim_idle.asm"
PikachuChuchuAnimationExtra: INCLUDE "gfx/pokemon/pikachu_chuchu/anim_idle.asm"

ArbokJohtoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_johto/anim_idle.asm"
ArbokKantoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_kanto/anim_idle.asm"
ArbokOrangeAnimationExtra: INCLUDE "gfx/pokemon/arbok_orange/anim_idle.asm"
ArbokKogaAnimationExtra:   INCLUDE "gfx/pokemon/arbok_koga/anim_idle.asm"
ArbokAgathaAnimationExtra: INCLUDE "gfx/pokemon/arbok_agatha/anim_idle.asm"
ArbokArianaAnimationExtra: INCLUDE "gfx/pokemon/arbok_ariana/anim_idle.asm"

MagikarpPlainAnimationExtra:
MagikarpSkellyAnimationExtra:
MagikarpCalico1AnimationExtra:
MagikarpCalico2AnimationExtra:
MagikarpCalico3AnimationExtra:
MagikarpTwoToneAnimationExtra:
MagikarpOrcaAnimationExtra:
MagikarpDapplesAnimationExtra:
MagikarpTigerAnimationExtra:
MagikarpZebraAnimationExtra:
MagikarpStripeAnimationExtra:
MagikarpBubblesAnimationExtra:
MagikarpDiamondsAnimationExtra:
MagikarpPatchesAnimationExtra:
MagikarpForehead1AnimationExtra:
MagikarpMask1AnimationExtra:
MagikarpForehead2AnimationExtra:
MagikarpMask2AnimationExtra:
MagikarpSaucyAnimationExtra:
MagikarpRaindropAnimationExtra: INCLUDE "gfx/pokemon/magikarp/anim_idle.asm"

DudunsparceTwoSegmentAnimationExtra:   INCLUDE "gfx/pokemon/dudunsparce_two_segment/anim_idle.asm"
DudunsparceThreeSegmentAnimationExtra: INCLUDE "gfx/pokemon/dudunsparce_three_segment/anim_idle.asm"

GyaradosPlainAnimationExtra: INCLUDE "gfx/pokemon/gyarados_plain/anim_idle.asm"
GyaradosRedAnimationExtra:   INCLUDE "gfx/pokemon/gyarados_red/anim_idle.asm"

MewtwoPlainAnimationExtra:   INCLUDE "gfx/pokemon/mewtwo_plain/anim_idle.asm"
MewtwoArmoredAnimationExtra: INCLUDE "gfx/pokemon/mewtwo_armored/anim_idle.asm"

RattataPlainAnimationExtra:  INCLUDE "gfx/pokemon/rattata_plain/anim_idle.asm"
RattataAlolanAnimationExtra: INCLUDE "gfx/pokemon/rattata_alolan/anim_idle.asm"

RaticatePlainAnimationExtra:  INCLUDE "gfx/pokemon/raticate_plain/anim_idle.asm"
RaticateAlolanAnimationExtra: INCLUDE "gfx/pokemon/raticate_alolan/anim_idle.asm"

RaichuPlainAnimationExtra:  INCLUDE "gfx/pokemon/raichu_plain/anim_idle.asm"
RaichuAlolanAnimationExtra: INCLUDE "gfx/pokemon/raichu_alolan/anim_idle.asm"

SandshrewPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandshrew_plain/anim_idle.asm"
SandshrewAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandshrew_alolan/anim_idle.asm"

SandslashPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandslash_plain/anim_idle.asm"
SandslashAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandslash_alolan/anim_idle.asm"

VulpixPlainAnimationExtra:  INCLUDE "gfx/pokemon/vulpix_plain/anim_idle.asm"
VulpixAlolanAnimationExtra: INCLUDE "gfx/pokemon/vulpix_alolan/anim_idle.asm"

NinetalesPlainAnimationExtra:  INCLUDE "gfx/pokemon/ninetales_plain/anim_idle.asm"
NinetalesAlolanAnimationExtra: INCLUDE "gfx/pokemon/ninetales_alolan/anim_idle.asm"

DiglettPlainAnimationExtra:  INCLUDE "gfx/pokemon/diglett_plain/anim_idle.asm"
DiglettAlolanAnimationExtra: INCLUDE "gfx/pokemon/diglett_alolan/anim_idle.asm"

DugtrioPlainAnimationExtra:  INCLUDE "gfx/pokemon/dugtrio_plain/anim_idle.asm"
DugtrioAlolanAnimationExtra: INCLUDE "gfx/pokemon/dugtrio_alolan/anim_idle.asm"

MeowthPlainAnimationExtra:  INCLUDE "gfx/pokemon/meowth_plain/anim_idle.asm"
MeowthAlolanAnimationExtra: INCLUDE "gfx/pokemon/meowth_alolan/anim_idle.asm"
MeowthGalarianAnimationExtra: INCLUDE "gfx/pokemon/meowth_galarian/anim_idle.asm"

PersianPlainAnimationExtra:  INCLUDE "gfx/pokemon/persian_plain/anim_idle.asm"
PersianAlolanAnimationExtra: INCLUDE "gfx/pokemon/persian_alolan/anim_idle.asm"

GeodudePlainAnimationExtra:  INCLUDE "gfx/pokemon/geodude_plain/anim_idle.asm"
GeodudeAlolanAnimationExtra: INCLUDE "gfx/pokemon/geodude_alolan/anim_idle.asm"

GravelerPlainAnimationExtra:  INCLUDE "gfx/pokemon/graveler_plain/anim_idle.asm"
GravelerAlolanAnimationExtra: INCLUDE "gfx/pokemon/graveler_alolan/anim_idle.asm"

GolemPlainAnimationExtra:  INCLUDE "gfx/pokemon/golem_plain/anim_idle.asm"
GolemAlolanAnimationExtra: INCLUDE "gfx/pokemon/golem_alolan/anim_idle.asm"

GrimerPlainAnimationExtra:  INCLUDE "gfx/pokemon/grimer_plain/anim_idle.asm"
GrimerAlolanAnimationExtra: INCLUDE "gfx/pokemon/grimer_alolan/anim_idle.asm"

MukPlainAnimationExtra:  INCLUDE "gfx/pokemon/muk_plain/anim_idle.asm"
MukAlolanAnimationExtra: INCLUDE "gfx/pokemon/muk_alolan/anim_idle.asm"

ExeggutorPlainAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor_plain/anim_idle.asm"
ExeggutorAlolanAnimationExtra: INCLUDE "gfx/pokemon/exeggutor_alolan/anim_idle.asm"

MarowakPlainAnimationExtra:  INCLUDE "gfx/pokemon/marowak_plain/anim_idle.asm"
MarowakAlolanAnimationExtra: INCLUDE "gfx/pokemon/marowak_alolan/anim_idle.asm"

PonytaPlainAnimationExtra:    INCLUDE "gfx/pokemon/ponyta_plain/anim_idle.asm"
PonytaGalarianAnimationExtra: INCLUDE "gfx/pokemon/ponyta_galarian/anim_idle.asm"

RapidashPlainAnimationExtra:    INCLUDE "gfx/pokemon/rapidash_plain/anim_idle.asm"
RapidashGalarianAnimationExtra: INCLUDE "gfx/pokemon/rapidash_galarian/anim_idle.asm"

SlowpokePlainAnimationExtra:   INCLUDE "gfx/pokemon/slowpoke_plain/anim_idle.asm"
SlowpokeGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowpoke_galarian/anim_idle.asm"

SlowbroPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowbro_plain/anim_idle.asm"
SlowbroGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowbro_galarian/anim_idle.asm"

FarfetchDPlainAnimationExtra:     INCLUDE "gfx/pokemon/farfetch_d_plain/anim_idle.asm"
FarfetchDGalarianAnimationExtra:  INCLUDE "gfx/pokemon/farfetch_d_galarian/anim_idle.asm"

WeezingPlainAnimationExtra:    INCLUDE "gfx/pokemon/weezing_plain/anim_idle.asm"
WeezingGalarianAnimationExtra: INCLUDE "gfx/pokemon/weezing_galarian/anim_idle.asm"

MrMimePlainAnimationExtra:    INCLUDE "gfx/pokemon/mr__mime_plain/anim_idle.asm"
MrMimeGalarianAnimationExtra: INCLUDE "gfx/pokemon/mr__mime_galarian/anim_idle.asm"

ArticunoPlainAnimationExtra:    INCLUDE "gfx/pokemon/articuno_plain/anim_idle.asm"
ArticunoGalarianAnimationExtra: INCLUDE "gfx/pokemon/articuno_galarian/anim_idle.asm"

ZapdosPlainAnimationExtra:    INCLUDE "gfx/pokemon/zapdos_plain/anim_idle.asm"
ZapdosGalarianAnimationExtra: INCLUDE "gfx/pokemon/zapdos_galarian/anim_idle.asm"

MoltresPlainAnimationExtra:    INCLUDE "gfx/pokemon/moltres_plain/anim_idle.asm"
MoltresGalarianAnimationExtra: INCLUDE "gfx/pokemon/moltres_galarian/anim_idle.asm"

SlowkingPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowking_plain/anim_idle.asm"
SlowkingGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowking_galarian/anim_idle.asm"

CorsolaPlainAnimationExtra:    INCLUDE "gfx/pokemon/corsola_plain/anim_idle.asm"
CorsolaGalarianAnimationExtra: INCLUDE "gfx/pokemon/corsola_galarian/anim_idle.asm"

GrowlithePlainAnimationExtra:   INCLUDE "gfx/pokemon/growlithe_plain/anim_idle.asm"
GrowlitheHisuianAnimationExtra: INCLUDE "gfx/pokemon/growlithe_hisuian/anim_idle.asm"

ArcaninePlainAnimationExtra:   INCLUDE "gfx/pokemon/arcanine_plain/anim_idle.asm"
ArcanineHisuianAnimationExtra: INCLUDE "gfx/pokemon/arcanine_hisuian/anim_idle.asm"

VoltorbPlainAnimationExtra:   INCLUDE "gfx/pokemon/voltorb_plain/anim_idle.asm"
VoltorbHisuianAnimationExtra: INCLUDE "gfx/pokemon/voltorb_hisuian/anim_idle.asm"

ElectrodePlainAnimationExtra:   INCLUDE "gfx/pokemon/electrode_plain/anim_idle.asm"
ElectrodeHisuianAnimationExtra: INCLUDE "gfx/pokemon/electrode_hisuian/anim_idle.asm"

TyphlosionPlainAnimationExtra:   INCLUDE "gfx/pokemon/typhlosion_plain/anim_idle.asm"
TyphlosionHisuianAnimationExtra: INCLUDE "gfx/pokemon/typhlosion_hisuian/anim_idle.asm"

QwilfishPlainAnimationExtra:   INCLUDE "gfx/pokemon/qwilfish_plain/anim_idle.asm"
QwilfishHisuianAnimationExtra: INCLUDE "gfx/pokemon/qwilfish_hisuian/anim_idle.asm"

SneaselPlainAnimationExtra:   INCLUDE "gfx/pokemon/sneasel_plain/anim_idle.asm"
SneaselHisuianAnimationExtra: INCLUDE "gfx/pokemon/sneasel_hisuian/anim_idle.asm"

WooperPlainAnimationExtra:   INCLUDE "gfx/pokemon/wooper_plain/anim_idle.asm"
WooperPaldeanAnimationExtra: INCLUDE "gfx/pokemon/wooper_paldean/anim_idle.asm"

TaurosPlainAnimationExtra:        INCLUDE "gfx/pokemon/tauros_plain/anim_idle.asm"
TaurosPaldeanAnimationExtra:      INCLUDE "gfx/pokemon/tauros_paldean/anim_idle.asm"
TaurosPaldeanFireAnimationExtra:  INCLUDE "gfx/pokemon/tauros_paldean_fire/anim_idle.asm"
TaurosPaldeanWaterAnimationExtra: INCLUDE "gfx/pokemon/tauros_paldean_water/anim_idle.asm"

UrsalunaPlainAnimationExtra:     INCLUDE "gfx/pokemon/ursaluna_plain/anim_idle.asm"
UrsalunaBloodmoonAnimationExtra: INCLUDE "gfx/pokemon/ursaluna_bloodmoon/anim_idle.asm"
