AnimationExtraPointers:
	dw BulbasaurAnimationExtra
	dw IvysaurAnimationExtra
	dw VenusaurAnimationExtra
	dw CharmanderAnimationExtra
	dw CharmeleonAnimationExtra
	dw CharizardAnimationExtra
	dw SquirtleAnimationExtra
	dw WartortleAnimationExtra
	dw BlastoiseAnimationExtra
	dw CaterpieAnimationExtra
	dw MetapodAnimationExtra
	dw ButterfreeAnimationExtra
	dw WeedleAnimationExtra
	dw KakunaAnimationExtra
	dw BeedrillAnimationExtra
	dw PidgeyAnimationExtra
	dw PidgeottoAnimationExtra
	dw PidgeotAnimationExtra
	dw RattataPlainAnimationExtra
	dw RaticatePlainAnimationExtra
	dw MarillAnimationExtra
	dw AzumarillAnimationExtra
	dw EkansAnimationExtra
	dw ArbokJohtoAnimationExtra
	dw PikachuPlainAnimationExtra
	dw RaichuPlainAnimationExtra
	dw SandshrewPlainAnimationExtra
	dw SandslashPlainAnimationExtra
	dw NidoranFAnimationExtra
	dw NidorinaAnimationExtra
	dw NidoqueenAnimationExtra
	dw NidoranMAnimationExtra
	dw NidorinoAnimationExtra
	dw NidokingAnimationExtra
	dw ClefairyAnimationExtra
	dw ClefableAnimationExtra
	dw VulpixPlainAnimationExtra
	dw NinetalesPlainAnimationExtra
	dw JigglypuffAnimationExtra
	dw WigglytuffAnimationExtra
	dw ZubatAnimationExtra
	dw GolbatAnimationExtra
	dw OddishAnimationExtra
	dw GloomAnimationExtra
	dw VileplumeAnimationExtra
	dw ParasAnimationExtra
	dw ParasectAnimationExtra
	dw VenonatAnimationExtra
	dw VenomothAnimationExtra
	dw DiglettPlainAnimationExtra
	dw DugtrioPlainAnimationExtra
	dw MeowthPlainAnimationExtra
	dw PersianPlainAnimationExtra
	dw PsyduckAnimationExtra
	dw GolduckAnimationExtra
	dw MankeyAnimationExtra
	dw PrimeapeAnimationExtra
	dw GrowlitheAnimationExtra
	dw ArcanineAnimationExtra
	dw PoliwagAnimationExtra
	dw PoliwhirlAnimationExtra
	dw PoliwrathAnimationExtra
	dw AbraAnimationExtra
	dw KadabraAnimationExtra
	dw AlakazamAnimationExtra
	dw MachopAnimationExtra
	dw MachokeAnimationExtra
	dw MachampAnimationExtra
	dw BellsproutAnimationExtra
	dw WeepinbellAnimationExtra
	dw VictreebelAnimationExtra
	dw TentacoolAnimationExtra
	dw TentacruelAnimationExtra
	dw GeodudePlainAnimationExtra
	dw GravelerPlainAnimationExtra
	dw GolemPlainAnimationExtra
	dw PonytaPlainAnimationExtra
	dw RapidashPlainAnimationExtra
	dw SlowpokePlainAnimationExtra
	dw SlowbroPlainAnimationExtra
	dw MagnemiteAnimationExtra
	dw MagnetonAnimationExtra
	dw FarfetchDAnimationExtra
	dw DoduoAnimationExtra
	dw DodrioAnimationExtra
	dw SeelAnimationExtra
	dw DewgongAnimationExtra
	dw GrimerPlainAnimationExtra
	dw MukPlainAnimationExtra
	dw ShellderAnimationExtra
	dw CloysterAnimationExtra
	dw GastlyAnimationExtra
	dw HaunterAnimationExtra
	dw GengarAnimationExtra
	dw OnixAnimationExtra
	dw DrowzeeAnimationExtra
	dw HypnoAnimationExtra
	dw KrabbyAnimationExtra
	dw KinglerAnimationExtra
	dw VoltorbAnimationExtra
	dw ElectrodeAnimationExtra
	dw ExeggcuteAnimationExtra
	dw ExeggutorPlainAnimationExtra
	dw CuboneAnimationExtra
	dw MarowakPlainAnimationExtra
	dw HitmonleeAnimationExtra
	dw HitmonchanAnimationExtra
	dw KoffingAnimationExtra
	dw WeezingPlainAnimationExtra
	dw RhyhornAnimationExtra
	dw RhydonAnimationExtra
	dw ChanseyAnimationExtra
	dw TangelaAnimationExtra
	dw KangaskhanAnimationExtra
	dw HorseaAnimationExtra
	dw SeadraAnimationExtra
	dw TogepiAnimationExtra
	dw TogeticAnimationExtra
	dw TogekissAnimationExtra
	dw StaryuAnimationExtra
	dw StarmieAnimationExtra
	dw MrMimeAnimationExtra
	dw ScytherAnimationExtra
	dw JynxAnimationExtra
	dw ElectabuzzAnimationExtra
	dw MagmarAnimationExtra
	dw PinsirAnimationExtra
	dw TaurosAnimationExtra
	dw MagikarpPlainAnimationExtra
	dw GyaradosPlainAnimationExtra
	dw LaprasAnimationExtra
	dw DittoAnimationExtra
	dw EeveeAnimationExtra
	dw VaporeonAnimationExtra
	dw JolteonAnimationExtra
	dw FlareonAnimationExtra
	dw PorygonAnimationExtra
	dw OmanyteAnimationExtra
	dw OmastarAnimationExtra
	dw KabutoAnimationExtra
	dw KabutopsAnimationExtra
	dw AerodactylAnimationExtra
	dw SnorlaxAnimationExtra
	dw ArticunoPlainAnimationExtra
	dw ZapdosPlainAnimationExtra
	dw MoltresPlainAnimationExtra
	dw DratiniAnimationExtra
	dw DragonairAnimationExtra
	dw DragoniteAnimationExtra
	dw MewtwoPlainAnimationExtra
	dw MewAnimationExtra
	dw ChikoritaAnimationExtra
	dw BayleefAnimationExtra
	dw MeganiumAnimationExtra
	dw CyndaquilAnimationExtra
	dw QuilavaAnimationExtra
	dw TyphlosionAnimationExtra
	dw TotodileAnimationExtra
	dw CroconawAnimationExtra
	dw FeraligatrAnimationExtra
	dw SentretAnimationExtra
	dw FurretAnimationExtra
	dw HoothootAnimationExtra
	dw NoctowlAnimationExtra
	dw LedybaAnimationExtra
	dw LedianAnimationExtra
	dw SpinarakAnimationExtra
	dw AriadosAnimationExtra
	dw CrobatAnimationExtra
	dw ChinchouAnimationExtra
	dw LanturnAnimationExtra
	dw PichuPlainAnimationExtra
	dw MunchlaxAnimationExtra
	dw MagnezoneAnimationExtra
	dw RhyperiorAnimationExtra
	dw TangrowthAnimationExtra
	dw NatuAnimationExtra
	dw XatuAnimationExtra
	dw MareepAnimationExtra
	dw FlaaffyAnimationExtra
	dw AmpharosAnimationExtra
	dw BellossomAnimationExtra
	dw SudowoodoAnimationExtra
	dw PolitoedAnimationExtra
	dw SunkernAnimationExtra
	dw SunfloraAnimationExtra
	dw YanmaAnimationExtra
	dw YanmegaAnimationExtra
	dw WooperAnimationExtra
	dw QuagsireAnimationExtra
	dw EspeonAnimationExtra
	dw UmbreonAnimationExtra
	dw MurkrowAnimationExtra
	dw HonchkrowAnimationExtra
	dw SlowkingPlainAnimationExtra
	dw MisdreavusAnimationExtra
	dw MismagiusAnimationExtra
	dw UnownAAnimationExtra
	dw WobbuffetAnimationExtra
	dw GirafarigAnimationExtra
	dw PinecoAnimationExtra
	dw ForretressAnimationExtra
	dw DunsparceAnimationExtra
	dw GligarAnimationExtra
	dw GliscorAnimationExtra
	dw SteelixAnimationExtra
	dw SnubbullAnimationExtra
	dw GranbullAnimationExtra
	dw QwilfishAnimationExtra
	dw ScizorAnimationExtra
	dw ShuckleAnimationExtra
	dw HeracrossAnimationExtra
	dw SneaselAnimationExtra
	dw WeavileAnimationExtra
	dw TeddiursaAnimationExtra
	dw UrsaringAnimationExtra
	dw SlugmaAnimationExtra
	dw MagcargoAnimationExtra
	dw SwinubAnimationExtra
	dw PiloswineAnimationExtra
	dw MamoswineAnimationExtra
	dw CorsolaAnimationExtra
	dw RemoraidAnimationExtra
	dw OctilleryAnimationExtra
	dw MantineAnimationExtra
	dw SkarmoryAnimationExtra
	dw HoundourAnimationExtra
	dw HoundoomAnimationExtra
	dw KingdraAnimationExtra
	dw PhanpyAnimationExtra
	dw DonphanAnimationExtra
	dw Porygon2AnimationExtra
	dw PorygonZAnimationExtra
	dw SmeargleAnimationExtra
	dw TyrogueAnimationExtra
	dw HitmontopAnimationExtra
	dw ElekidAnimationExtra
	dw ElectivireAnimationExtra
	dw MagbyAnimationExtra
	dw MagmortarAnimationExtra
	dw MiltankAnimationExtra
	dw BlisseyAnimationExtra
	dw RaikouAnimationExtra
	dw EnteiAnimationExtra
	dw SuicuneAnimationExtra
	dw LarvitarAnimationExtra
	dw PupitarAnimationExtra
	dw TyranitarAnimationExtra
	dw LugiaAnimationExtra
	dw HoOhAnimationExtra
	dw CelebiAnimationExtra
	dw LeafeonAnimationExtra
	dw GlaceonAnimationExtra
	dw SylveonAnimationExtra
	dw EggAnimationExtra

	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

	dw ArbokKantoAnimationExtra
	dw ArbokKogaAnimationExtra
	dw ArbokAgathaAnimationExtra
	dw ArbokArianaAnimationExtra

	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra
	dw PikachuSparkAnimationExtra

	dw PichuSpikyAnimationExtra

	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpForeheadAnimationExtra
	dw MagikarpMaskAnimationExtra
	dw MagikarpSaucyAnimationExtra
	dw MagikarpRaindropAnimationExtra

	dw GyaradosRedAnimationExtra
	dw MewtwoArmoredAnimationExtra
	dw RattataAlolanAnimationExtra
	dw RaticateAlolanAnimationExtra
	dw SandshrewAlolanAnimationExtra
	dw SandslashAlolanAnimationExtra
	dw VulpixAlolanAnimationExtra
	dw NinetalesAlolanAnimationExtra
	dw DiglettAlolanAnimationExtra
	dw DugtrioAlolanAnimationExtra
	dw MeowthAlolanAnimationExtra
	dw PersianAlolanAnimationExtra
	dw GeodudeAlolanAnimationExtra
	dw GravelerAlolanAnimationExtra
	dw GolemAlolanAnimationExtra
	dw GrimerAlolanAnimationExtra
	dw MukAlolanAnimationExtra
	dw RaichuAlolanAnimationExtra
	dw ExeggutorAlolanAnimationExtra
	dw MarowakAlolanAnimationExtra
	dw PonytaGalarianAnimationExtra
	dw RapidashGalarianAnimationExtra
	dw SlowpokeGalarianAnimationExtra
	dw SlowbroGalarianAnimationExtra
	dw SlowkingGalarianAnimationExtra
	dw WeezingGalarianAnimationExtra
	dw ArticunoGalarianAnimationExtra
	dw ZapdosGalarianAnimationExtra
	dw MoltresGalarianAnimationExtra
