BulbasaurAnimationExtra:  INCLUDE "gfx/pokemon/bulbasaur/anim1.asm"
IvysaurAnimationExtra:    INCLUDE "gfx/pokemon/ivysaur/anim1.asm"
VenusaurAnimationExtra:   INCLUDE "gfx/pokemon/venusaur/anim1.asm"
CharmanderAnimationExtra: INCLUDE "gfx/pokemon/charmander/anim1.asm"
CharmeleonAnimationExtra: INCLUDE "gfx/pokemon/charmeleon/anim1.asm"
CharizardAnimationExtra:  INCLUDE "gfx/pokemon/charizard/anim1.asm"
SquirtleAnimationExtra:   INCLUDE "gfx/pokemon/squirtle/anim1.asm"
WartortleAnimationExtra:  INCLUDE "gfx/pokemon/wartortle/anim1.asm"
BlastoiseAnimationExtra:  INCLUDE "gfx/pokemon/blastoise/anim1.asm"
CaterpieAnimationExtra:   INCLUDE "gfx/pokemon/caterpie/anim1.asm"
MetapodAnimationExtra:    INCLUDE "gfx/pokemon/metapod/anim1.asm"
ButterfreeAnimationExtra: INCLUDE "gfx/pokemon/butterfree/anim1.asm"
WeedleAnimationExtra:     INCLUDE "gfx/pokemon/weedle/anim1.asm"
KakunaAnimationExtra:     INCLUDE "gfx/pokemon/kakuna/anim1.asm"
BeedrillAnimationExtra:   INCLUDE "gfx/pokemon/beedrill/anim1.asm"
PidgeyAnimationExtra:     INCLUDE "gfx/pokemon/pidgey/anim1.asm"
PidgeottoAnimationExtra:  INCLUDE "gfx/pokemon/pidgeotto/anim1.asm"
PidgeotAnimationExtra:    INCLUDE "gfx/pokemon/pidgeot/anim1.asm"
MarillAnimationExtra:     INCLUDE "gfx/pokemon/marill/anim1.asm"
AzumarillAnimationExtra:  INCLUDE "gfx/pokemon/azumarill/anim1.asm"
EkansAnimationExtra:      INCLUDE "gfx/pokemon/ekans/anim1.asm"
NidoranFAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_f/anim1.asm"
NidorinaAnimationExtra:   INCLUDE "gfx/pokemon/nidorina/anim1.asm"
NidoqueenAnimationExtra:  INCLUDE "gfx/pokemon/nidoqueen/anim1.asm"
NidoranMAnimationExtra:   INCLUDE "gfx/pokemon/nidoran_m/anim1.asm"
NidorinoAnimationExtra:   INCLUDE "gfx/pokemon/nidorino/anim1.asm"
NidokingAnimationExtra:   INCLUDE "gfx/pokemon/nidoking/anim1.asm"
ClefairyAnimationExtra:   INCLUDE "gfx/pokemon/clefairy/anim1.asm"
ClefableAnimationExtra:   INCLUDE "gfx/pokemon/clefable/anim1.asm"
JigglypuffAnimationExtra: INCLUDE "gfx/pokemon/jigglypuff/anim1.asm"
WigglytuffAnimationExtra: INCLUDE "gfx/pokemon/wigglytuff/anim1.asm"
ZubatAnimationExtra:      INCLUDE "gfx/pokemon/zubat/anim1.asm"
GolbatAnimationExtra:     INCLUDE "gfx/pokemon/golbat/anim1.asm"
OddishAnimationExtra:     INCLUDE "gfx/pokemon/oddish/anim1.asm"
GloomAnimationExtra:      INCLUDE "gfx/pokemon/gloom/anim1.asm"
VileplumeAnimationExtra:  INCLUDE "gfx/pokemon/vileplume/anim1.asm"
ParasAnimationExtra:      INCLUDE "gfx/pokemon/paras/anim1.asm"
ParasectAnimationExtra:   INCLUDE "gfx/pokemon/parasect/anim1.asm"
VenonatAnimationExtra:    INCLUDE "gfx/pokemon/venonat/anim1.asm"
VenomothAnimationExtra:   INCLUDE "gfx/pokemon/venomoth/anim1.asm"
PsyduckAnimationExtra:    INCLUDE "gfx/pokemon/psyduck/anim1.asm"
GolduckAnimationExtra:    INCLUDE "gfx/pokemon/golduck/anim1.asm"
MankeyAnimationExtra:     INCLUDE "gfx/pokemon/mankey/anim1.asm"
PrimeapeAnimationExtra:   INCLUDE "gfx/pokemon/primeape/anim1.asm"
GrowlitheAnimationExtra:  INCLUDE "gfx/pokemon/growlithe/anim1.asm"
ArcanineAnimationExtra:   INCLUDE "gfx/pokemon/arcanine/anim1.asm"
PoliwagAnimationExtra:    INCLUDE "gfx/pokemon/poliwag/anim1.asm"
PoliwhirlAnimationExtra:  INCLUDE "gfx/pokemon/poliwhirl/anim1.asm"
PoliwrathAnimationExtra:  INCLUDE "gfx/pokemon/poliwrath/anim1.asm"
AbraAnimationExtra:       INCLUDE "gfx/pokemon/abra/anim1.asm"
KadabraAnimationExtra:    INCLUDE "gfx/pokemon/kadabra/anim1.asm"
AlakazamAnimationExtra:   INCLUDE "gfx/pokemon/alakazam/anim1.asm"
MachopAnimationExtra:     INCLUDE "gfx/pokemon/machop/anim1.asm"
MachokeAnimationExtra:    INCLUDE "gfx/pokemon/machoke/anim1.asm"
MachampAnimationExtra:    INCLUDE "gfx/pokemon/machamp/anim1.asm"
BellsproutAnimationExtra: INCLUDE "gfx/pokemon/bellsprout/anim1.asm"
WeepinbellAnimationExtra: INCLUDE "gfx/pokemon/weepinbell/anim1.asm"
VictreebelAnimationExtra: INCLUDE "gfx/pokemon/victreebel/anim1.asm"
TentacoolAnimationExtra:  INCLUDE "gfx/pokemon/tentacool/anim1.asm"
TentacruelAnimationExtra: INCLUDE "gfx/pokemon/tentacruel/anim1.asm"
MagnemiteAnimationExtra:  INCLUDE "gfx/pokemon/magnemite/anim1.asm"
MagnetonAnimationExtra:   INCLUDE "gfx/pokemon/magneton/anim1.asm"
FarfetchDAnimationExtra:  INCLUDE "gfx/pokemon/farfetch_d/anim1.asm"
DoduoAnimationExtra:      INCLUDE "gfx/pokemon/doduo/anim1.asm"
DodrioAnimationExtra:     INCLUDE "gfx/pokemon/dodrio/anim1.asm"
SeelAnimationExtra:       INCLUDE "gfx/pokemon/seel/anim1.asm"
DewgongAnimationExtra:    INCLUDE "gfx/pokemon/dewgong/anim1.asm"
ShellderAnimationExtra:   INCLUDE "gfx/pokemon/shellder/anim1.asm"
CloysterAnimationExtra:   INCLUDE "gfx/pokemon/cloyster/anim1.asm"
GastlyAnimationExtra:     INCLUDE "gfx/pokemon/gastly/anim1.asm"
HaunterAnimationExtra:    INCLUDE "gfx/pokemon/haunter/anim1.asm"
GengarAnimationExtra:     INCLUDE "gfx/pokemon/gengar/anim1.asm"
OnixAnimationExtra:       INCLUDE "gfx/pokemon/onix/anim1.asm"
DrowzeeAnimationExtra:    INCLUDE "gfx/pokemon/drowzee/anim1.asm"
HypnoAnimationExtra:      INCLUDE "gfx/pokemon/hypno/anim1.asm"
KrabbyAnimationExtra:     INCLUDE "gfx/pokemon/krabby/anim1.asm"
KinglerAnimationExtra:    INCLUDE "gfx/pokemon/kingler/anim1.asm"
VoltorbAnimationExtra:    INCLUDE "gfx/pokemon/voltorb/anim1.asm"
ElectrodeAnimationExtra:  INCLUDE "gfx/pokemon/electrode/anim1.asm"
ExeggcuteAnimationExtra:  INCLUDE "gfx/pokemon/exeggcute/anim1.asm"
CuboneAnimationExtra:     INCLUDE "gfx/pokemon/cubone/anim1.asm"
HitmonleeAnimationExtra:  INCLUDE "gfx/pokemon/hitmonlee/anim1.asm"
HitmonchanAnimationExtra: INCLUDE "gfx/pokemon/hitmonchan/anim1.asm"
KoffingAnimationExtra:    INCLUDE "gfx/pokemon/koffing/anim1.asm"
RhyhornAnimationExtra:    INCLUDE "gfx/pokemon/rhyhorn/anim1.asm"
RhydonAnimationExtra:     INCLUDE "gfx/pokemon/rhydon/anim1.asm"
ChanseyAnimationExtra:    INCLUDE "gfx/pokemon/chansey/anim1.asm"
TangelaAnimationExtra:    INCLUDE "gfx/pokemon/tangela/anim1.asm"
KangaskhanAnimationExtra: INCLUDE "gfx/pokemon/kangaskhan/anim1.asm"
HorseaAnimationExtra:     INCLUDE "gfx/pokemon/horsea/anim1.asm"
SeadraAnimationExtra:     INCLUDE "gfx/pokemon/seadra/anim1.asm"
TogepiAnimationExtra:     INCLUDE "gfx/pokemon/togepi/anim1.asm"
TogeticAnimationExtra:    INCLUDE "gfx/pokemon/togetic/anim1.asm"
TogekissAnimationExtra:   INCLUDE "gfx/pokemon/togekiss/anim1.asm"
StaryuAnimationExtra:     INCLUDE "gfx/pokemon/staryu/anim1.asm"
StarmieAnimationExtra:    INCLUDE "gfx/pokemon/starmie/anim1.asm"
MrMimeAnimationExtra:     INCLUDE "gfx/pokemon/mr__mime/anim1.asm"
ScytherAnimationExtra:    INCLUDE "gfx/pokemon/scyther/anim1.asm"
JynxAnimationExtra:       INCLUDE "gfx/pokemon/jynx/anim1.asm"
ElectabuzzAnimationExtra: INCLUDE "gfx/pokemon/electabuzz/anim1.asm"
MagmarAnimationExtra:     INCLUDE "gfx/pokemon/magmar/anim1.asm"
PinsirAnimationExtra:     INCLUDE "gfx/pokemon/pinsir/anim1.asm"
TaurosAnimationExtra:     INCLUDE "gfx/pokemon/tauros/anim1.asm"
LaprasAnimationExtra:     INCLUDE "gfx/pokemon/lapras/anim1.asm"
DittoAnimationExtra:      INCLUDE "gfx/pokemon/ditto/anim1.asm"
EeveeAnimationExtra:      INCLUDE "gfx/pokemon/eevee/anim1.asm"
VaporeonAnimationExtra:   INCLUDE "gfx/pokemon/vaporeon/anim1.asm"
JolteonAnimationExtra:    INCLUDE "gfx/pokemon/jolteon/anim1.asm"
FlareonAnimationExtra:    INCLUDE "gfx/pokemon/flareon/anim1.asm"
PorygonAnimationExtra:    INCLUDE "gfx/pokemon/porygon/anim1.asm"
OmanyteAnimationExtra:    INCLUDE "gfx/pokemon/omanyte/anim1.asm"
OmastarAnimationExtra:    INCLUDE "gfx/pokemon/omastar/anim1.asm"
KabutoAnimationExtra:     INCLUDE "gfx/pokemon/kabuto/anim1.asm"
KabutopsAnimationExtra:   INCLUDE "gfx/pokemon/kabutops/anim1.asm"
AerodactylAnimationExtra: INCLUDE "gfx/pokemon/aerodactyl/anim1.asm"
SnorlaxAnimationExtra:    INCLUDE "gfx/pokemon/snorlax/anim1.asm"
DratiniAnimationExtra:    INCLUDE "gfx/pokemon/dratini/anim1.asm"
DragonairAnimationExtra:  INCLUDE "gfx/pokemon/dragonair/anim1.asm"
DragoniteAnimationExtra:  INCLUDE "gfx/pokemon/dragonite/anim1.asm"
MewAnimationExtra:        INCLUDE "gfx/pokemon/mew/anim1.asm"
ChikoritaAnimationExtra:  INCLUDE "gfx/pokemon/chikorita/anim1.asm"
BayleefAnimationExtra:    INCLUDE "gfx/pokemon/bayleef/anim1.asm"
MeganiumAnimationExtra:   INCLUDE "gfx/pokemon/meganium/anim1.asm"
CyndaquilAnimationExtra:  INCLUDE "gfx/pokemon/cyndaquil/anim1.asm"
QuilavaAnimationExtra:    INCLUDE "gfx/pokemon/quilava/anim1.asm"
TyphlosionAnimationExtra: INCLUDE "gfx/pokemon/typhlosion/anim1.asm"
TotodileAnimationExtra:   INCLUDE "gfx/pokemon/totodile/anim1.asm"
CroconawAnimationExtra:   INCLUDE "gfx/pokemon/croconaw/anim1.asm"
FeraligatrAnimationExtra: INCLUDE "gfx/pokemon/feraligatr/anim1.asm"
SentretAnimationExtra:    INCLUDE "gfx/pokemon/sentret/anim1.asm"
FurretAnimationExtra:     INCLUDE "gfx/pokemon/furret/anim1.asm"
HoothootAnimationExtra:   INCLUDE "gfx/pokemon/hoothoot/anim1.asm"
NoctowlAnimationExtra:    INCLUDE "gfx/pokemon/noctowl/anim1.asm"
LedybaAnimationExtra:     INCLUDE "gfx/pokemon/ledyba/anim1.asm"
LedianAnimationExtra:     INCLUDE "gfx/pokemon/ledian/anim1.asm"
SpinarakAnimationExtra:   INCLUDE "gfx/pokemon/spinarak/anim1.asm"
AriadosAnimationExtra:    INCLUDE "gfx/pokemon/ariados/anim1.asm"
CrobatAnimationExtra:     INCLUDE "gfx/pokemon/crobat/anim1.asm"
ChinchouAnimationExtra:   INCLUDE "gfx/pokemon/chinchou/anim1.asm"
LanturnAnimationExtra:    INCLUDE "gfx/pokemon/lanturn/anim1.asm"
MunchlaxAnimationExtra:   INCLUDE "gfx/pokemon/munchlax/anim1.asm"
MagnezoneAnimationExtra:  INCLUDE "gfx/pokemon/magnezone/anim1.asm"
RhyperiorAnimationExtra:  INCLUDE "gfx/pokemon/rhyperior/anim1.asm"
TangrowthAnimationExtra:  INCLUDE "gfx/pokemon/tangrowth/anim1.asm"
NatuAnimationExtra:       INCLUDE "gfx/pokemon/natu/anim1.asm"
XatuAnimationExtra:       INCLUDE "gfx/pokemon/xatu/anim1.asm"
MareepAnimationExtra:     INCLUDE "gfx/pokemon/mareep/anim1.asm"
FlaaffyAnimationExtra:    INCLUDE "gfx/pokemon/flaaffy/anim1.asm"
AmpharosAnimationExtra:   INCLUDE "gfx/pokemon/ampharos/anim1.asm"
BellossomAnimationExtra:  INCLUDE "gfx/pokemon/bellossom/anim1.asm"
SudowoodoAnimationExtra:  INCLUDE "gfx/pokemon/sudowoodo/anim1.asm"
PolitoedAnimationExtra:   INCLUDE "gfx/pokemon/politoed/anim1.asm"
SunkernAnimationExtra:    INCLUDE "gfx/pokemon/sunkern/anim1.asm"
SunfloraAnimationExtra:   INCLUDE "gfx/pokemon/sunflora/anim1.asm"
YanmaAnimationExtra:      INCLUDE "gfx/pokemon/yanma/anim1.asm"
YanmegaAnimationExtra:    INCLUDE "gfx/pokemon/yanmega/anim1.asm"
WooperAnimationExtra:     INCLUDE "gfx/pokemon/wooper/anim1.asm"
QuagsireAnimationExtra:   INCLUDE "gfx/pokemon/quagsire/anim1.asm"
EspeonAnimationExtra:     INCLUDE "gfx/pokemon/espeon/anim1.asm"
UmbreonAnimationExtra:    INCLUDE "gfx/pokemon/umbreon/anim1.asm"
MurkrowAnimationExtra:    INCLUDE "gfx/pokemon/murkrow/anim1.asm"
HonchkrowAnimationExtra:  INCLUDE "gfx/pokemon/honchkrow/anim1.asm"
MisdreavusAnimationExtra: INCLUDE "gfx/pokemon/misdreavus/anim1.asm"
MismagiusAnimationExtra:  INCLUDE "gfx/pokemon/mismagius/anim1.asm"
WobbuffetAnimationExtra:  INCLUDE "gfx/pokemon/wobbuffet/anim1.asm"
GirafarigAnimationExtra:  INCLUDE "gfx/pokemon/girafarig/anim1.asm"
PinecoAnimationExtra:     INCLUDE "gfx/pokemon/pineco/anim1.asm"
ForretressAnimationExtra: INCLUDE "gfx/pokemon/forretress/anim1.asm"
DunsparceAnimationExtra:  INCLUDE "gfx/pokemon/dunsparce/anim1.asm"
GligarAnimationExtra:     INCLUDE "gfx/pokemon/gligar/anim1.asm"
GliscorAnimationExtra:    INCLUDE "gfx/pokemon/gliscor/anim1.asm"
SteelixAnimationExtra:    INCLUDE "gfx/pokemon/steelix/anim1.asm"
SnubbullAnimationExtra:   INCLUDE "gfx/pokemon/snubbull/anim1.asm"
GranbullAnimationExtra:   INCLUDE "gfx/pokemon/granbull/anim1.asm"
QwilfishAnimationExtra:   INCLUDE "gfx/pokemon/qwilfish/anim1.asm"
ScizorAnimationExtra:     INCLUDE "gfx/pokemon/scizor/anim1.asm"
ShuckleAnimationExtra:    INCLUDE "gfx/pokemon/shuckle/anim1.asm"
HeracrossAnimationExtra:  INCLUDE "gfx/pokemon/heracross/anim1.asm"
SneaselAnimationExtra:    INCLUDE "gfx/pokemon/sneasel/anim1.asm"
WeavileAnimationExtra:    INCLUDE "gfx/pokemon/weavile/anim1.asm"
TeddiursaAnimationExtra:  INCLUDE "gfx/pokemon/teddiursa/anim1.asm"
UrsaringAnimationExtra:   INCLUDE "gfx/pokemon/ursaring/anim1.asm"
SlugmaAnimationExtra:     INCLUDE "gfx/pokemon/slugma/anim1.asm"
MagcargoAnimationExtra:   INCLUDE "gfx/pokemon/magcargo/anim1.asm"
SwinubAnimationExtra:     INCLUDE "gfx/pokemon/swinub/anim1.asm"
PiloswineAnimationExtra:  INCLUDE "gfx/pokemon/piloswine/anim1.asm"
MamoswineAnimationExtra:  INCLUDE "gfx/pokemon/mamoswine/anim1.asm"
CorsolaAnimationExtra:    INCLUDE "gfx/pokemon/corsola/anim1.asm"
RemoraidAnimationExtra:   INCLUDE "gfx/pokemon/remoraid/anim1.asm"
OctilleryAnimationExtra:  INCLUDE "gfx/pokemon/octillery/anim1.asm"
MantineAnimationExtra:    INCLUDE "gfx/pokemon/mantine/anim1.asm"
SkarmoryAnimationExtra:   INCLUDE "gfx/pokemon/skarmory/anim1.asm"
HoundourAnimationExtra:   INCLUDE "gfx/pokemon/houndour/anim1.asm"
HoundoomAnimationExtra:   INCLUDE "gfx/pokemon/houndoom/anim1.asm"
KingdraAnimationExtra:    INCLUDE "gfx/pokemon/kingdra/anim1.asm"
PhanpyAnimationExtra:     INCLUDE "gfx/pokemon/phanpy/anim1.asm"
DonphanAnimationExtra:    INCLUDE "gfx/pokemon/donphan/anim1.asm"
Porygon2AnimationExtra:   INCLUDE "gfx/pokemon/porygon2/anim1.asm"
PorygonZAnimationExtra:   INCLUDE "gfx/pokemon/porygon_z/anim1.asm"
SmeargleAnimationExtra:   INCLUDE "gfx/pokemon/smeargle/anim1.asm"
TyrogueAnimationExtra:    INCLUDE "gfx/pokemon/tyrogue/anim1.asm"
HitmontopAnimationExtra:  INCLUDE "gfx/pokemon/hitmontop/anim1.asm"
ElekidAnimationExtra:     INCLUDE "gfx/pokemon/elekid/anim1.asm"
ElectivireAnimationExtra: INCLUDE "gfx/pokemon/electivire/anim1.asm"
MagbyAnimationExtra:      INCLUDE "gfx/pokemon/magby/anim1.asm"
MagmortarAnimationExtra:  INCLUDE "gfx/pokemon/magmortar/anim1.asm"
MiltankAnimationExtra:    INCLUDE "gfx/pokemon/miltank/anim1.asm"
BlisseyAnimationExtra:    INCLUDE "gfx/pokemon/blissey/anim1.asm"
RaikouAnimationExtra:     INCLUDE "gfx/pokemon/raikou/anim1.asm"
EnteiAnimationExtra:      INCLUDE "gfx/pokemon/entei/anim1.asm"
SuicuneAnimationExtra:    INCLUDE "gfx/pokemon/suicune/anim1.asm"
LarvitarAnimationExtra:   INCLUDE "gfx/pokemon/larvitar/anim1.asm"
PupitarAnimationExtra:    INCLUDE "gfx/pokemon/pupitar/anim1.asm"
TyranitarAnimationExtra:  INCLUDE "gfx/pokemon/tyranitar/anim1.asm"
LugiaAnimationExtra:      INCLUDE "gfx/pokemon/lugia/anim1.asm"
HoOhAnimationExtra:       INCLUDE "gfx/pokemon/ho_oh/anim1.asm"
CelebiAnimationExtra:     INCLUDE "gfx/pokemon/celebi/anim1.asm"
LeafeonAnimationExtra:    INCLUDE "gfx/pokemon/leafeon/anim1.asm"
GlaceonAnimationExtra:    INCLUDE "gfx/pokemon/glaceon/anim1.asm"
SylveonAnimationExtra:    INCLUDE "gfx/pokemon/sylveon/anim1.asm"
EggAnimationExtra:        INCLUDE "gfx/pokemon/egg/anim1.asm"

UnownAAnimationExtra: INCLUDE "gfx/pokemon/unown_a/anim1.asm"
UnownBAnimationExtra: INCLUDE "gfx/pokemon/unown_b/anim1.asm"
UnownCAnimationExtra: INCLUDE "gfx/pokemon/unown_c/anim1.asm"
UnownDAnimationExtra: INCLUDE "gfx/pokemon/unown_d/anim1.asm"
UnownEAnimationExtra: INCLUDE "gfx/pokemon/unown_e/anim1.asm"
UnownFAnimationExtra: INCLUDE "gfx/pokemon/unown_f/anim1.asm"
UnownGAnimationExtra: INCLUDE "gfx/pokemon/unown_g/anim1.asm"
UnownHAnimationExtra: INCLUDE "gfx/pokemon/unown_h/anim1.asm"
UnownIAnimationExtra: INCLUDE "gfx/pokemon/unown_i/anim1.asm"
UnownJAnimationExtra: INCLUDE "gfx/pokemon/unown_j/anim1.asm"
UnownKAnimationExtra: INCLUDE "gfx/pokemon/unown_k/anim1.asm"
UnownLAnimationExtra: INCLUDE "gfx/pokemon/unown_l/anim1.asm"
UnownMAnimationExtra: INCLUDE "gfx/pokemon/unown_m/anim1.asm"
UnownNAnimationExtra: INCLUDE "gfx/pokemon/unown_n/anim1.asm"
UnownOAnimationExtra: INCLUDE "gfx/pokemon/unown_o/anim1.asm"
UnownPAnimationExtra: INCLUDE "gfx/pokemon/unown_p/anim1.asm"
UnownQAnimationExtra: INCLUDE "gfx/pokemon/unown_q/anim1.asm"
UnownRAnimationExtra: INCLUDE "gfx/pokemon/unown_r/anim1.asm"
UnownSAnimationExtra: INCLUDE "gfx/pokemon/unown_s/anim1.asm"
UnownTAnimationExtra: INCLUDE "gfx/pokemon/unown_t/anim1.asm"
UnownUAnimationExtra: INCLUDE "gfx/pokemon/unown_u/anim1.asm"
UnownVAnimationExtra: INCLUDE "gfx/pokemon/unown_v/anim1.asm"
UnownWAnimationExtra: INCLUDE "gfx/pokemon/unown_w/anim1.asm"
UnownXAnimationExtra: INCLUDE "gfx/pokemon/unown_x/anim1.asm"
UnownYAnimationExtra: INCLUDE "gfx/pokemon/unown_y/anim1.asm"
UnownZAnimationExtra: INCLUDE "gfx/pokemon/unown_z/anim1.asm"
UnownExclamationAnimationExtra: INCLUDE "gfx/pokemon/unown_exclamation/anim1.asm"
UnownQuestionAnimationExtra:    INCLUDE "gfx/pokemon/unown_question/anim1.asm"

PichuPlainAnimationExtra: INCLUDE "gfx/pokemon/pichu_plain/anim1.asm"
PichuSpikyAnimationExtra: INCLUDE "gfx/pokemon/pichu_spiky/anim1.asm"

PikachuSparkAnimationExtra:
PikachuPlainAnimationExtra:  INCLUDE "gfx/pokemon/pikachu_plain/anim1.asm"
PikachuFlyAnimationExtra:    INCLUDE "gfx/pokemon/pikachu_fly/anim1.asm"
PikachuSurfAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_surf/anim1.asm"
PikachuPikaAnimationExtra:   INCLUDE "gfx/pokemon/pikachu_pika/anim1.asm"
PikachuChuchuAnimationExtra: INCLUDE "gfx/pokemon/pikachu_chuchu/anim1.asm"

ArbokJohtoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_johto/anim1.asm"
ArbokKantoAnimationExtra:  INCLUDE "gfx/pokemon/arbok_kanto/anim1.asm"
ArbokKogaAnimationExtra:   INCLUDE "gfx/pokemon/arbok_koga/anim1.asm"
ArbokAgathaAnimationExtra: INCLUDE "gfx/pokemon/arbok_agatha/anim1.asm"
ArbokArianaAnimationExtra: INCLUDE "gfx/pokemon/arbok_ariana/anim1.asm"

MagikarpPlainAnimationExtra:
MagikarpSkellyAnimationExtra:
MagikarpCalico1AnimationExtra:
MagikarpCalico2AnimationExtra:
MagikarpCalico3AnimationExtra:
MagikarpTwoToneAnimationExtra:
MagikarpOrcaAnimationExtra:
MagikarpDapplesAnimationExtra:
MagikarpTigerAnimationExtra:
MagikarpZebraAnimationExtra:
MagikarpStripeAnimationExtra:
MagikarpBubblesAnimationExtra:
MagikarpForeheadAnimationExtra:
MagikarpMaskAnimationExtra:
MagikarpSaucyAnimationExtra:
MagikarpRaindropAnimationExtra: INCLUDE "gfx/pokemon/magikarp/anim1.asm"

GyaradosPlainAnimationExtra: INCLUDE "gfx/pokemon/gyarados_plain/anim1.asm"
GyaradosRedAnimationExtra:   INCLUDE "gfx/pokemon/gyarados_red/anim1.asm"

MewtwoPlainAnimationExtra:   INCLUDE "gfx/pokemon/mewtwo_plain/anim1.asm"
MewtwoArmoredAnimationExtra: INCLUDE "gfx/pokemon/mewtwo_armored/anim1.asm"

RattataPlainAnimationExtra:  INCLUDE "gfx/pokemon/rattata_plain/anim1.asm"
RattataAlolanAnimationExtra: INCLUDE "gfx/pokemon/rattata_alolan/anim1.asm"

RaticatePlainAnimationExtra:  INCLUDE "gfx/pokemon/raticate_plain/anim1.asm"
RaticateAlolanAnimationExtra: INCLUDE "gfx/pokemon/raticate_alolan/anim1.asm"

SandshrewPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandshrew_plain/anim1.asm"
SandshrewAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandshrew_alolan/anim1.asm"

SandslashPlainAnimationExtra:  INCLUDE "gfx/pokemon/sandslash_plain/anim1.asm"
SandslashAlolanAnimationExtra: INCLUDE "gfx/pokemon/sandslash_alolan/anim1.asm"

VulpixPlainAnimationExtra:  INCLUDE "gfx/pokemon/vulpix_plain/anim1.asm"
VulpixAlolanAnimationExtra: INCLUDE "gfx/pokemon/vulpix_alolan/anim1.asm"

NinetalesPlainAnimationExtra:  INCLUDE "gfx/pokemon/ninetales_plain/anim1.asm"
NinetalesAlolanAnimationExtra: INCLUDE "gfx/pokemon/ninetales_alolan/anim1.asm"

DiglettPlainAnimationExtra:  INCLUDE "gfx/pokemon/diglett_plain/anim1.asm"
DiglettAlolanAnimationExtra: INCLUDE "gfx/pokemon/diglett_alolan/anim1.asm"

DugtrioPlainAnimationExtra:  INCLUDE "gfx/pokemon/dugtrio_plain/anim1.asm"
DugtrioAlolanAnimationExtra: INCLUDE "gfx/pokemon/dugtrio_alolan/anim1.asm"

MeowthPlainAnimationExtra:  INCLUDE "gfx/pokemon/meowth_plain/anim1.asm"
MeowthAlolanAnimationExtra: INCLUDE "gfx/pokemon/meowth_alolan/anim1.asm"

PersianPlainAnimationExtra:  INCLUDE "gfx/pokemon/persian_plain/anim1.asm"
PersianAlolanAnimationExtra: INCLUDE "gfx/pokemon/persian_alolan/anim1.asm"

GeodudePlainAnimationExtra:  INCLUDE "gfx/pokemon/geodude_plain/anim1.asm"
GeodudeAlolanAnimationExtra: INCLUDE "gfx/pokemon/geodude_alolan/anim1.asm"

GravelerPlainAnimationExtra:  INCLUDE "gfx/pokemon/graveler_plain/anim1.asm"
GravelerAlolanAnimationExtra: INCLUDE "gfx/pokemon/graveler_alolan/anim1.asm"

GolemPlainAnimationExtra:  INCLUDE "gfx/pokemon/golem_plain/anim1.asm"
GolemAlolanAnimationExtra: INCLUDE "gfx/pokemon/golem_alolan/anim1.asm"

GrimerPlainAnimationExtra:  INCLUDE "gfx/pokemon/grimer_plain/anim1.asm"
GrimerAlolanAnimationExtra: INCLUDE "gfx/pokemon/grimer_alolan/anim1.asm"

MukPlainAnimationExtra:  INCLUDE "gfx/pokemon/muk_plain/anim1.asm"
MukAlolanAnimationExtra: INCLUDE "gfx/pokemon/muk_alolan/anim1.asm"

RaichuPlainAnimationExtra:  INCLUDE "gfx/pokemon/raichu_plain/anim1.asm"
RaichuAlolanAnimationExtra: INCLUDE "gfx/pokemon/raichu_alolan/anim1.asm"

ExeggutorPlainAnimationExtra:  INCLUDE "gfx/pokemon/exeggutor_plain/anim1.asm"
ExeggutorAlolanAnimationExtra: INCLUDE "gfx/pokemon/exeggutor_alolan/anim1.asm"

MarowakPlainAnimationExtra:  INCLUDE "gfx/pokemon/marowak_plain/anim1.asm"
MarowakAlolanAnimationExtra: INCLUDE "gfx/pokemon/marowak_alolan/anim1.asm"

PonytaPlainAnimationExtra:    INCLUDE "gfx/pokemon/ponyta_plain/anim1.asm"
PonytaGalarianAnimationExtra: INCLUDE "gfx/pokemon/ponyta_galarian/anim1.asm"

RapidashPlainAnimationExtra:    INCLUDE "gfx/pokemon/rapidash_plain/anim1.asm"
RapidashGalarianAnimationExtra: INCLUDE "gfx/pokemon/rapidash_galarian/anim1.asm"

SlowpokePlainAnimationExtra:   INCLUDE "gfx/pokemon/slowpoke_plain/anim1.asm"
SlowpokeGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowpoke_galarian/anim1.asm"

SlowbroPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowbro_plain/anim1.asm"
SlowbroGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowbro_galarian/anim1.asm"

SlowkingPlainAnimationExtra:    INCLUDE "gfx/pokemon/slowking_plain/anim1.asm"
SlowkingGalarianAnimationExtra: INCLUDE "gfx/pokemon/slowking_galarian/anim1.asm"

WeezingPlainAnimationExtra:    INCLUDE "gfx/pokemon/weezing_plain/anim1.asm"
WeezingGalarianAnimationExtra: INCLUDE "gfx/pokemon/weezing_galarian/anim1.asm"

ArticunoPlainAnimationExtra:    INCLUDE "gfx/pokemon/articuno_plain/anim1.asm"
ArticunoGalarianAnimationExtra: INCLUDE "gfx/pokemon/articuno_galarian/anim1.asm"

ZapdosPlainAnimationExtra:    INCLUDE "gfx/pokemon/zapdos_plain/anim1.asm"
ZapdosGalarianAnimationExtra: INCLUDE "gfx/pokemon/zapdos_galarian/anim1.asm"

MoltresPlainAnimationExtra:    INCLUDE "gfx/pokemon/moltres_plain/anim1.asm"
MoltresGalarianAnimationExtra: INCLUDE "gfx/pokemon/moltres_galarian/anim1.asm"
