FramesPointers:
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw WeedleFrames
	dw KakunaFrames
	dw BeedrillFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw RattataPlainFrames
	dw RaticatePlainFrames
	dw MarillFrames
	dw AzumarillFrames
	dw EkansFrames
	dw ArbokJohtoFrames
	dw PikachuPlainFrames
	dw RaichuPlainFrames
	dw SandshrewPlainFrames
	dw SandslashPlainFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixPlainFrames
	dw NinetalesPlainFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettPlainFrames
	dw DugtrioPlainFrames
	dw MeowthPlainFrames
	dw PersianPlainFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudePlainFrames
	dw GravelerPlainFrames
	dw GolemPlainFrames
	dw PonytaPlainFrames
	dw RapidashPlainFrames
	dw SlowpokePlainFrames
	dw SlowbroPlainFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerPlainFrames
	dw MukPlainFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ExeggcuteFrames
	dw ExeggutorPlainFrames
	dw CuboneFrames
	dw MarowakPlainFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw KoffingFrames
	dw WeezingPlainFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpPlainFrames
	dw GyaradosPlainFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoPlainFrames
	dw ZapdosPlainFrames
	dw MoltresPlainFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoPlainFrames
	dw MewFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuPlainFrames
	dw MunchlaxFrames
	dw MagnezoneFrames
	dw RhyperiorFrames
	dw TangrowthFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw HonchkrowFrames
	dw SlowkingPlainFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw UnownAFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw GliscorFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw WeavileFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw ElekidFrames
	dw ElectivireFrames
	dw MagbyFrames
	dw MagmortarFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw EggFrames

	dw UnownBFrames
	dw UnownCFrames
	dw UnownDFrames
	dw UnownEFrames
	dw UnownFFrames
	dw UnownGFrames
	dw UnownHFrames
	dw UnownIFrames
	dw UnownJFrames
	dw UnownKFrames
	dw UnownLFrames
	dw UnownMFrames
	dw UnownNFrames
	dw UnownOFrames
	dw UnownPFrames
	dw UnownQFrames
	dw UnownRFrames
	dw UnownSFrames
	dw UnownTFrames
	dw UnownUFrames
	dw UnownVFrames
	dw UnownWFrames
	dw UnownXFrames
	dw UnownYFrames
	dw UnownZFrames
	dw UnownExclamationFrames
	dw UnownQuestionFrames

	dw ArbokKantoFrames
	dw ArbokKogaFrames
	dw ArbokAgathaFrames
	dw ArbokArianaFrames

	dw PikachuFlyFrames
	dw PikachuSurfFrames
	dw PikachuPikaFrames
	dw PikachuChuchuFrames
	dw PikachuSparkFrames

	dw PichuSpikyFrames

	dw MagikarpSkellyFrames
	dw MagikarpCalico1Frames
	dw MagikarpCalico2Frames
	dw MagikarpCalico3Frames
	dw MagikarpTwoToneFrames
	dw MagikarpOrcaFrames
	dw MagikarpDapplesFrames
	dw MagikarpTigerFrames
	dw MagikarpZebraFrames
	dw MagikarpStripeFrames
	dw MagikarpBubblesFrames
	dw MagikarpForeheadFrames
	dw MagikarpMaskFrames
	dw MagikarpSaucyFrames
	dw MagikarpRaindropFrames

	dw GyaradosRedFrames
	dw MewtwoArmoredFrames
	dw RattataAlolanFrames
	dw RaticateAlolanFrames
	dw SandshrewAlolanFrames
	dw SandslashAlolanFrames
	dw VulpixAlolanFrames
	dw NinetalesAlolanFrames
	dw DiglettAlolanFrames
	dw DugtrioAlolanFrames
	dw MeowthAlolanFrames
	dw PersianAlolanFrames
	dw GeodudeAlolanFrames
	dw GravelerAlolanFrames
	dw GolemAlolanFrames
	dw GrimerAlolanFrames
	dw MukAlolanFrames
	dw RaichuAlolanFrames
	dw ExeggutorAlolanFrames
	dw MarowakAlolanFrames
	dw PonytaGalarianFrames
	dw RapidashGalarianFrames
	dw SlowpokeGalarianFrames
	dw SlowbroGalarianFrames
	dw SlowkingGalarianFrames
	dw WeezingGalarianFrames
	dw ArticunoGalarianFrames
	dw ZapdosGalarianFrames
	dw MoltresGalarianFrames
