KantoFrames:

BulbasaurFrames:  INCLUDE "gfx/pokemon/bulbasaur/frames.asm"
IvysaurFrames:    INCLUDE "gfx/pokemon/ivysaur/frames.asm"
VenusaurFrames:   INCLUDE "gfx/pokemon/venusaur/frames.asm"
CharmanderFrames: INCLUDE "gfx/pokemon/charmander/frames.asm"
CharmeleonFrames: INCLUDE "gfx/pokemon/charmeleon/frames.asm"
CharizardFrames:  INCLUDE "gfx/pokemon/charizard/frames.asm"
SquirtleFrames:   INCLUDE "gfx/pokemon/squirtle/frames.asm"
WartortleFrames:  INCLUDE "gfx/pokemon/wartortle/frames.asm"
BlastoiseFrames:  INCLUDE "gfx/pokemon/blastoise/frames.asm"
CaterpieFrames:   INCLUDE "gfx/pokemon/caterpie/frames.asm"
MetapodFrames:    INCLUDE "gfx/pokemon/metapod/frames.asm"
ButterfreeFrames: INCLUDE "gfx/pokemon/butterfree/frames.asm"
WeedleFrames:     INCLUDE "gfx/pokemon/weedle/frames.asm"
KakunaFrames:     INCLUDE "gfx/pokemon/kakuna/frames.asm"
BeedrillFrames:   INCLUDE "gfx/pokemon/beedrill/frames.asm"
PidgeyFrames:     INCLUDE "gfx/pokemon/pidgey/frames.asm"
PidgeottoFrames:  INCLUDE "gfx/pokemon/pidgeotto/frames.asm"
PidgeotFrames:    INCLUDE "gfx/pokemon/pidgeot/frames.asm"
MarillFrames:     INCLUDE "gfx/pokemon/marill/frames.asm"
AzumarillFrames:  INCLUDE "gfx/pokemon/azumarill/frames.asm"
EkansFrames:      INCLUDE "gfx/pokemon/ekans/frames.asm"
NidoranFFrames:   INCLUDE "gfx/pokemon/nidoran_f/frames.asm"
NidorinaFrames:   INCLUDE "gfx/pokemon/nidorina/frames.asm"
NidoqueenFrames:  INCLUDE "gfx/pokemon/nidoqueen/frames.asm"
NidoranMFrames:   INCLUDE "gfx/pokemon/nidoran_m/frames.asm"
NidorinoFrames:   INCLUDE "gfx/pokemon/nidorino/frames.asm"
NidokingFrames:   INCLUDE "gfx/pokemon/nidoking/frames.asm"
ClefairyFrames:   INCLUDE "gfx/pokemon/clefairy/frames.asm"
ClefableFrames:   INCLUDE "gfx/pokemon/clefable/frames.asm"
JigglypuffFrames: INCLUDE "gfx/pokemon/jigglypuff/frames.asm"
WigglytuffFrames: INCLUDE "gfx/pokemon/wigglytuff/frames.asm"
ZubatFrames:      INCLUDE "gfx/pokemon/zubat/frames.asm"
GolbatFrames:     INCLUDE "gfx/pokemon/golbat/frames.asm"
OddishFrames:     INCLUDE "gfx/pokemon/oddish/frames.asm"
GloomFrames:      INCLUDE "gfx/pokemon/gloom/frames.asm"
VileplumeFrames:  INCLUDE "gfx/pokemon/vileplume/frames.asm"
ParasFrames:      INCLUDE "gfx/pokemon/paras/frames.asm"
ParasectFrames:   INCLUDE "gfx/pokemon/parasect/frames.asm"
VenonatFrames:    INCLUDE "gfx/pokemon/venonat/frames.asm"
VenomothFrames:   INCLUDE "gfx/pokemon/venomoth/frames.asm"
PsyduckFrames:    INCLUDE "gfx/pokemon/psyduck/frames.asm"
GolduckFrames:    INCLUDE "gfx/pokemon/golduck/frames.asm"
MankeyFrames:     INCLUDE "gfx/pokemon/mankey/frames.asm"
PrimeapeFrames:   INCLUDE "gfx/pokemon/primeape/frames.asm"
GrowlitheFrames:  INCLUDE "gfx/pokemon/growlithe/frames.asm"
ArcanineFrames:   INCLUDE "gfx/pokemon/arcanine/frames.asm"
PoliwagFrames:    INCLUDE "gfx/pokemon/poliwag/frames.asm"
PoliwhirlFrames:  INCLUDE "gfx/pokemon/poliwhirl/frames.asm"
PoliwrathFrames:  INCLUDE "gfx/pokemon/poliwrath/frames.asm"
AbraFrames:       INCLUDE "gfx/pokemon/abra/frames.asm"
KadabraFrames:    INCLUDE "gfx/pokemon/kadabra/frames.asm"
AlakazamFrames:   INCLUDE "gfx/pokemon/alakazam/frames.asm"
MachopFrames:     INCLUDE "gfx/pokemon/machop/frames.asm"
MachokeFrames:    INCLUDE "gfx/pokemon/machoke/frames.asm"
MachampFrames:    INCLUDE "gfx/pokemon/machamp/frames.asm"
BellsproutFrames: INCLUDE "gfx/pokemon/bellsprout/frames.asm"
WeepinbellFrames: INCLUDE "gfx/pokemon/weepinbell/frames.asm"
VictreebelFrames: INCLUDE "gfx/pokemon/victreebel/frames.asm"
TentacoolFrames:  INCLUDE "gfx/pokemon/tentacool/frames.asm"
TentacruelFrames: INCLUDE "gfx/pokemon/tentacruel/frames.asm"
MagnemiteFrames:  INCLUDE "gfx/pokemon/magnemite/frames.asm"
MagnetonFrames:   INCLUDE "gfx/pokemon/magneton/frames.asm"
FarfetchDFrames:  INCLUDE "gfx/pokemon/farfetch_d/frames.asm"
DoduoFrames:      INCLUDE "gfx/pokemon/doduo/frames.asm"
DodrioFrames:     INCLUDE "gfx/pokemon/dodrio/frames.asm"
SeelFrames:       INCLUDE "gfx/pokemon/seel/frames.asm"
DewgongFrames:    INCLUDE "gfx/pokemon/dewgong/frames.asm"
ShellderFrames:   INCLUDE "gfx/pokemon/shellder/frames.asm"
CloysterFrames:   INCLUDE "gfx/pokemon/cloyster/frames.asm"
GastlyFrames:     INCLUDE "gfx/pokemon/gastly/frames.asm"
HaunterFrames:    INCLUDE "gfx/pokemon/haunter/frames.asm"
GengarFrames:     INCLUDE "gfx/pokemon/gengar/frames.asm"
OnixFrames:       INCLUDE "gfx/pokemon/onix/frames.asm"
DrowzeeFrames:    INCLUDE "gfx/pokemon/drowzee/frames.asm"
HypnoFrames:      INCLUDE "gfx/pokemon/hypno/frames.asm"
KrabbyFrames:     INCLUDE "gfx/pokemon/krabby/frames.asm"
KinglerFrames:    INCLUDE "gfx/pokemon/kingler/frames.asm"
VoltorbFrames:    INCLUDE "gfx/pokemon/voltorb/frames.asm"
ElectrodeFrames:  INCLUDE "gfx/pokemon/electrode/frames.asm"
ExeggcuteFrames:  INCLUDE "gfx/pokemon/exeggcute/frames.asm"
CuboneFrames:     INCLUDE "gfx/pokemon/cubone/frames.asm"
HitmonleeFrames:  INCLUDE "gfx/pokemon/hitmonlee/frames.asm"
HitmonchanFrames: INCLUDE "gfx/pokemon/hitmonchan/frames.asm"
KoffingFrames:    INCLUDE "gfx/pokemon/koffing/frames.asm"
RhyhornFrames:    INCLUDE "gfx/pokemon/rhyhorn/frames.asm"
RhydonFrames:     INCLUDE "gfx/pokemon/rhydon/frames.asm"
ChanseyFrames:    INCLUDE "gfx/pokemon/chansey/frames.asm"
TangelaFrames:    INCLUDE "gfx/pokemon/tangela/frames.asm"
KangaskhanFrames: INCLUDE "gfx/pokemon/kangaskhan/frames.asm"
HorseaFrames:     INCLUDE "gfx/pokemon/horsea/frames.asm"
SeadraFrames:     INCLUDE "gfx/pokemon/seadra/frames.asm"
TogepiFrames:     INCLUDE "gfx/pokemon/togepi/frames.asm"
TogeticFrames:    INCLUDE "gfx/pokemon/togetic/frames.asm"
TogekissFrames:   INCLUDE "gfx/pokemon/togekiss/frames.asm"
StaryuFrames:     INCLUDE "gfx/pokemon/staryu/frames.asm"
StarmieFrames:    INCLUDE "gfx/pokemon/starmie/frames.asm"
MrMimeFrames:     INCLUDE "gfx/pokemon/mr__mime/frames.asm"
ScytherFrames:    INCLUDE "gfx/pokemon/scyther/frames.asm"
JynxFrames:       INCLUDE "gfx/pokemon/jynx/frames.asm"
ElectabuzzFrames: INCLUDE "gfx/pokemon/electabuzz/frames.asm"
MagmarFrames:     INCLUDE "gfx/pokemon/magmar/frames.asm"
PinsirFrames:     INCLUDE "gfx/pokemon/pinsir/frames.asm"
TaurosFrames:     INCLUDE "gfx/pokemon/tauros/frames.asm"
LaprasFrames:     INCLUDE "gfx/pokemon/lapras/frames.asm"
DittoFrames:      INCLUDE "gfx/pokemon/ditto/frames.asm"
EeveeFrames:      INCLUDE "gfx/pokemon/eevee/frames.asm"
VaporeonFrames:   INCLUDE "gfx/pokemon/vaporeon/frames.asm"
JolteonFrames:    INCLUDE "gfx/pokemon/jolteon/frames.asm"
FlareonFrames:    INCLUDE "gfx/pokemon/flareon/frames.asm"
PorygonFrames:    INCLUDE "gfx/pokemon/porygon/frames.asm"
OmanyteFrames:    INCLUDE "gfx/pokemon/omanyte/frames.asm"
OmastarFrames:    INCLUDE "gfx/pokemon/omastar/frames.asm"
KabutoFrames:     INCLUDE "gfx/pokemon/kabuto/frames.asm"
KabutopsFrames:   INCLUDE "gfx/pokemon/kabutops/frames.asm"
AerodactylFrames: INCLUDE "gfx/pokemon/aerodactyl/frames.asm"
SnorlaxFrames:    INCLUDE "gfx/pokemon/snorlax/frames.asm"
DratiniFrames:    INCLUDE "gfx/pokemon/dratini/frames.asm"
DragonairFrames:  INCLUDE "gfx/pokemon/dragonair/frames.asm"
DragoniteFrames:  INCLUDE "gfx/pokemon/dragonite/frames.asm"
MewFrames:        INCLUDE "gfx/pokemon/mew/frames.asm"

PikachuPlainFrames:  INCLUDE "gfx/pokemon/pikachu_plain/frames.asm"
PikachuFlyFrames:    INCLUDE "gfx/pokemon/pikachu_fly/frames.asm"
PikachuSurfFrames:   INCLUDE "gfx/pokemon/pikachu_surf/frames.asm"
PikachuPikaFrames:   INCLUDE "gfx/pokemon/pikachu_pika/frames.asm"
PikachuChuchuFrames: INCLUDE "gfx/pokemon/pikachu_chuchu/frames.asm"
PikachuSparkFrames:  INCLUDE "gfx/pokemon/pikachu_spark/frames.asm"

ArbokJohtoFrames:  INCLUDE "gfx/pokemon/arbok_johto/frames.asm"
ArbokKantoFrames:  INCLUDE "gfx/pokemon/arbok_kanto/frames.asm"
ArbokKogaFrames:   INCLUDE "gfx/pokemon/arbok_koga/frames.asm"
ArbokAgathaFrames: INCLUDE "gfx/pokemon/arbok_agatha/frames.asm"
ArbokArianaFrames: INCLUDE "gfx/pokemon/arbok_ariana/frames.asm"

MagikarpPlainFrames:    INCLUDE "gfx/pokemon/magikarp_plain/frames.asm"
MagikarpSkellyFrames:   INCLUDE "gfx/pokemon/magikarp_skelly/frames.asm"
MagikarpCalico1Frames:  INCLUDE "gfx/pokemon/magikarp_calico1/frames.asm"
MagikarpCalico2Frames:  INCLUDE "gfx/pokemon/magikarp_calico2/frames.asm"
MagikarpCalico3Frames:  INCLUDE "gfx/pokemon/magikarp_calico3/frames.asm"
MagikarpTwoToneFrames:  INCLUDE "gfx/pokemon/magikarp_twotone/frames.asm"
MagikarpOrcaFrames:     INCLUDE "gfx/pokemon/magikarp_orca/frames.asm"
MagikarpDapplesFrames:  INCLUDE "gfx/pokemon/magikarp_dapples/frames.asm"
MagikarpTigerFrames:    INCLUDE "gfx/pokemon/magikarp_tiger/frames.asm"
MagikarpZebraFrames:    INCLUDE "gfx/pokemon/magikarp_zebra/frames.asm"
MagikarpStripeFrames:   INCLUDE "gfx/pokemon/magikarp_stripe/frames.asm"
MagikarpBubblesFrames:  INCLUDE "gfx/pokemon/magikarp_bubbles/frames.asm"
MagikarpForeheadFrames: INCLUDE "gfx/pokemon/magikarp_forehead/frames.asm"
MagikarpMaskFrames:     INCLUDE "gfx/pokemon/magikarp_mask/frames.asm"
MagikarpSaucyFrames:    INCLUDE "gfx/pokemon/magikarp_saucy/frames.asm"
MagikarpRaindropFrames: INCLUDE "gfx/pokemon/magikarp_raindrop/frames.asm"

GyaradosPlainFrames: INCLUDE "gfx/pokemon/gyarados_plain/frames.asm"
GyaradosRedFrames:   INCLUDE "gfx/pokemon/gyarados_red/frames.asm"

MewtwoPlainFrames:   INCLUDE "gfx/pokemon/mewtwo_plain/frames.asm"
MewtwoArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"

RattataPlainFrames:  INCLUDE "gfx/pokemon/rattata_plain/frames.asm"
RattataAlolanFrames: INCLUDE "gfx/pokemon/rattata_alolan/frames.asm"

RaticatePlainFrames:  INCLUDE "gfx/pokemon/raticate_plain/frames.asm"
RaticateAlolanFrames: INCLUDE "gfx/pokemon/raticate_alolan/frames.asm"

SandshrewPlainFrames:  INCLUDE "gfx/pokemon/sandshrew_plain/frames.asm"
SandshrewAlolanFrames: INCLUDE "gfx/pokemon/sandshrew_alolan/frames.asm"

SandslashPlainFrames:  INCLUDE "gfx/pokemon/sandslash_plain/frames.asm"
SandslashAlolanFrames: INCLUDE "gfx/pokemon/sandslash_alolan/frames.asm"

VulpixPlainFrames:  INCLUDE "gfx/pokemon/vulpix_plain/frames.asm"
VulpixAlolanFrames: INCLUDE "gfx/pokemon/vulpix_alolan/frames.asm"

NinetalesPlainFrames:  INCLUDE "gfx/pokemon/ninetales_plain/frames.asm"
NinetalesAlolanFrames: INCLUDE "gfx/pokemon/ninetales_alolan/frames.asm"

DiglettPlainFrames:  INCLUDE "gfx/pokemon/diglett_plain/frames.asm"
DiglettAlolanFrames: INCLUDE "gfx/pokemon/diglett_alolan/frames.asm"

DugtrioPlainFrames:  INCLUDE "gfx/pokemon/dugtrio_plain/frames.asm"
DugtrioAlolanFrames: INCLUDE "gfx/pokemon/dugtrio_alolan/frames.asm"

MeowthPlainFrames:  INCLUDE "gfx/pokemon/meowth_plain/frames.asm"
MeowthAlolanFrames: INCLUDE "gfx/pokemon/meowth_alolan/frames.asm"

PersianPlainFrames:  INCLUDE "gfx/pokemon/persian_plain/frames.asm"
PersianAlolanFrames: INCLUDE "gfx/pokemon/persian_alolan/frames.asm"

GeodudePlainFrames:  INCLUDE "gfx/pokemon/geodude_plain/frames.asm"
GeodudeAlolanFrames: INCLUDE "gfx/pokemon/geodude_alolan/frames.asm"

GravelerPlainFrames:  INCLUDE "gfx/pokemon/graveler_plain/frames.asm"
GravelerAlolanFrames: INCLUDE "gfx/pokemon/graveler_alolan/frames.asm"

GolemPlainFrames:  INCLUDE "gfx/pokemon/golem_plain/frames.asm"
GolemAlolanFrames: INCLUDE "gfx/pokemon/golem_alolan/frames.asm"

GrimerPlainFrames:  INCLUDE "gfx/pokemon/grimer_plain/frames.asm"
GrimerAlolanFrames: INCLUDE "gfx/pokemon/grimer_alolan/frames.asm"

MukPlainFrames:  INCLUDE "gfx/pokemon/muk_plain/frames.asm"
MukAlolanFrames: INCLUDE "gfx/pokemon/muk_alolan/frames.asm"

RaichuPlainFrames:  INCLUDE "gfx/pokemon/raichu_plain/frames.asm"
RaichuAlolanFrames: INCLUDE "gfx/pokemon/raichu_alolan/frames.asm"

ExeggutorPlainFrames:  INCLUDE "gfx/pokemon/exeggutor_plain/frames.asm"
ExeggutorAlolanFrames: INCLUDE "gfx/pokemon/exeggutor_alolan/frames.asm"

MarowakPlainFrames:  INCLUDE "gfx/pokemon/marowak_plain/frames.asm"
MarowakAlolanFrames: INCLUDE "gfx/pokemon/marowak_alolan/frames.asm"

PonytaPlainFrames:    INCLUDE "gfx/pokemon/ponyta_plain/frames.asm"
PonytaGalarianFrames: INCLUDE "gfx/pokemon/ponyta_galarian/frames.asm"

RapidashPlainFrames:    INCLUDE "gfx/pokemon/rapidash_plain/frames.asm"
RapidashGalarianFrames: INCLUDE "gfx/pokemon/rapidash_galarian/frames.asm"

SlowpokePlainFrames:   INCLUDE "gfx/pokemon/slowpoke_plain/frames.asm"
SlowpokeGalarianFrames: INCLUDE "gfx/pokemon/slowpoke_galarian/frames.asm"

SlowbroPlainFrames:    INCLUDE "gfx/pokemon/slowbro_plain/frames.asm"
SlowbroGalarianFrames: INCLUDE "gfx/pokemon/slowbro_galarian/frames.asm"

WeezingPlainFrames:    INCLUDE "gfx/pokemon/weezing_plain/frames.asm"
WeezingGalarianFrames: INCLUDE "gfx/pokemon/weezing_galarian/frames.asm"

ArticunoPlainFrames:    INCLUDE "gfx/pokemon/articuno_plain/frames.asm"
ArticunoGalarianFrames: INCLUDE "gfx/pokemon/articuno_galarian/frames.asm"

ZapdosPlainFrames:    INCLUDE "gfx/pokemon/zapdos_plain/frames.asm"
ZapdosGalarianFrames: INCLUDE "gfx/pokemon/zapdos_galarian/frames.asm"

MoltresPlainFrames:    INCLUDE "gfx/pokemon/moltres_plain/frames.asm"
MoltresGalarianFrames: INCLUDE "gfx/pokemon/moltres_galarian/frames.asm"
