UnownsFrames:
UnownAFrames: INCLUDE "gfx/pokemon/unown_a/frames.asm"
UnownBFrames: INCLUDE "gfx/pokemon/unown_b/frames.asm"
UnownCFrames: INCLUDE "gfx/pokemon/unown_c/frames.asm"
UnownDFrames: INCLUDE "gfx/pokemon/unown_d/frames.asm"
UnownEFrames: INCLUDE "gfx/pokemon/unown_e/frames.asm"
UnownFFrames: INCLUDE "gfx/pokemon/unown_f/frames.asm"
UnownGFrames: INCLUDE "gfx/pokemon/unown_g/frames.asm"
UnownHFrames: INCLUDE "gfx/pokemon/unown_h/frames.asm"
UnownIFrames: INCLUDE "gfx/pokemon/unown_i/frames.asm"
UnownJFrames: INCLUDE "gfx/pokemon/unown_j/frames.asm"
UnownKFrames: INCLUDE "gfx/pokemon/unown_k/frames.asm"
UnownLFrames: INCLUDE "gfx/pokemon/unown_l/frames.asm"
UnownMFrames: INCLUDE "gfx/pokemon/unown_m/frames.asm"
UnownNFrames: INCLUDE "gfx/pokemon/unown_n/frames.asm"
UnownOFrames: INCLUDE "gfx/pokemon/unown_o/frames.asm"
UnownPFrames: INCLUDE "gfx/pokemon/unown_p/frames.asm"
UnownQFrames: INCLUDE "gfx/pokemon/unown_q/frames.asm"
UnownRFrames: INCLUDE "gfx/pokemon/unown_r/frames.asm"
UnownSFrames: INCLUDE "gfx/pokemon/unown_s/frames.asm"
UnownTFrames: INCLUDE "gfx/pokemon/unown_t/frames.asm"
UnownUFrames: INCLUDE "gfx/pokemon/unown_u/frames.asm"
UnownVFrames: INCLUDE "gfx/pokemon/unown_v/frames.asm"
UnownWFrames: INCLUDE "gfx/pokemon/unown_w/frames.asm"
UnownXFrames: INCLUDE "gfx/pokemon/unown_x/frames.asm"
UnownYFrames: INCLUDE "gfx/pokemon/unown_y/frames.asm"
UnownZFrames: INCLUDE "gfx/pokemon/unown_z/frames.asm"
UnownExclamationFrames: INCLUDE "gfx/pokemon/unown_exclamation/frames.asm"
UnownQuestionFrames:    INCLUDE "gfx/pokemon/unown_question/frames.asm"

PikachusFrames:
PikachuPlainFrames:  INCLUDE "gfx/pokemon/pikachu_plain/frames.asm"
PikachuFlyFrames:    INCLUDE "gfx/pokemon/pikachu_fly/frames.asm"
PikachuSurfFrames:   INCLUDE "gfx/pokemon/pikachu_surf/frames.asm"
PikachuPikaFrames:   INCLUDE "gfx/pokemon/pikachu_pika/frames.asm"
PikachuChuchuFrames: INCLUDE "gfx/pokemon/pikachu_chuchu/frames.asm"

PichusFrames:
PichuPlainFrames: INCLUDE "gfx/pokemon/pichu_plain/frames.asm"
PichuSpikyFrames: INCLUDE "gfx/pokemon/pichu_spiky/frames.asm"

ArboksFrames:
ArbokJohtoFrames:  INCLUDE "gfx/pokemon/arbok_johto/frames.asm"
ArbokKantoFrames:  INCLUDE "gfx/pokemon/arbok_kanto/frames.asm"
ArbokKogaFrames:   INCLUDE "gfx/pokemon/arbok_koga/frames.asm"
ArbokAgathaFrames: INCLUDE "gfx/pokemon/arbok_agatha/frames.asm"
ArbokArianaFrames: INCLUDE "gfx/pokemon/arbok_ariana/frames.asm"

MagikarpsFrames:
MagikarpPlainFrames:    INCLUDE "gfx/pokemon/magikarp_plain/frames.asm"
MagikarpSkellyFrames:   INCLUDE "gfx/pokemon/magikarp_skelly/frames.asm"
MagikarpCalico1Frames:  INCLUDE "gfx/pokemon/magikarp_calico1/frames.asm"
MagikarpCalico2Frames:  INCLUDE "gfx/pokemon/magikarp_calico2/frames.asm"
MagikarpCalico3Frames:  INCLUDE "gfx/pokemon/magikarp_calico3/frames.asm"
MagikarpTwoToneFrames:  INCLUDE "gfx/pokemon/magikarp_twotone/frames.asm"
MagikarpOrcaFrames:     INCLUDE "gfx/pokemon/magikarp_orca/frames.asm"
MagikarpDapplesFrames:  INCLUDE "gfx/pokemon/magikarp_dapples/frames.asm"
MagikarpTigerFrames:    INCLUDE "gfx/pokemon/magikarp_tiger/frames.asm"
MagikarpZebraFrames:    INCLUDE "gfx/pokemon/magikarp_zebra/frames.asm"
MagikarpStripeFrames:   INCLUDE "gfx/pokemon/magikarp_stripe/frames.asm"
MagikarpBubblesFrames:  INCLUDE "gfx/pokemon/magikarp_bubbles/frames.asm"
MagikarpForeheadFrames: INCLUDE "gfx/pokemon/magikarp_forehead/frames.asm"
MagikarpMaskFrames:     INCLUDE "gfx/pokemon/magikarp_mask/frames.asm"

GyaradossFrames:
GyaradosPlainFrames: INCLUDE "gfx/pokemon/gyarados_plain/frames.asm"
GyaradosRedFrames:   INCLUDE "gfx/pokemon/gyarados_red/frames.asm"

MewtwosFrames:
MewtwoPlainFrames:   INCLUDE "gfx/pokemon/mewtwo_plain/frames.asm"
MewtwoArmoredFrames: INCLUDE "gfx/pokemon/mewtwo_armored/frames.asm"
