UnownAnimationExtraPointers:
	dw UnownAAnimationExtra
	dw UnownBAnimationExtra
	dw UnownCAnimationExtra
	dw UnownDAnimationExtra
	dw UnownEAnimationExtra
	dw UnownFAnimationExtra
	dw UnownGAnimationExtra
	dw UnownHAnimationExtra
	dw UnownIAnimationExtra
	dw UnownJAnimationExtra
	dw UnownKAnimationExtra
	dw UnownLAnimationExtra
	dw UnownMAnimationExtra
	dw UnownNAnimationExtra
	dw UnownOAnimationExtra
	dw UnownPAnimationExtra
	dw UnownQAnimationExtra
	dw UnownRAnimationExtra
	dw UnownSAnimationExtra
	dw UnownTAnimationExtra
	dw UnownUAnimationExtra
	dw UnownVAnimationExtra
	dw UnownWAnimationExtra
	dw UnownXAnimationExtra
	dw UnownYAnimationExtra
	dw UnownZAnimationExtra
	dw UnownExclamationAnimationExtra
	dw UnownQuestionAnimationExtra

PikachuAnimationExtraPointers:
	dw PikachuPlainAnimationExtra
	dw PikachuFlyAnimationExtra
	dw PikachuSurfAnimationExtra
	dw PikachuPikaAnimationExtra
	dw PikachuChuchuAnimationExtra
	dw PikachuSparkAnimationExtra

PichuAnimationExtraPointers:
	dw PichuPlainAnimationExtra
	dw PichuSpikyAnimationExtra

ArbokAnimationExtraPointers:
	dw ArbokJohtoAnimationExtra
	dw ArbokKantoAnimationExtra
	dw ArbokKogaAnimationExtra
	dw ArbokAgathaAnimationExtra
	dw ArbokArianaAnimationExtra

MagikarpAnimationExtraPointers:
	dw MagikarpPlainAnimationExtra
	dw MagikarpSkellyAnimationExtra
	dw MagikarpCalico1AnimationExtra
	dw MagikarpCalico2AnimationExtra
	dw MagikarpCalico3AnimationExtra
	dw MagikarpTwoToneAnimationExtra
	dw MagikarpOrcaAnimationExtra
	dw MagikarpDapplesAnimationExtra
	dw MagikarpTigerAnimationExtra
	dw MagikarpZebraAnimationExtra
	dw MagikarpStripeAnimationExtra
	dw MagikarpBubblesAnimationExtra
	dw MagikarpForeheadAnimationExtra
	dw MagikarpMaskAnimationExtra
	dw MagikarpSaucyAnimationExtra
	dw MagikarpRaindropAnimationExtra

GyaradosAnimationExtraPointers:
rept NUM_MAGIKARP
	dw GyaradosPlainAnimationExtra
endr
	dw GyaradosRedAnimationExtra

MewtwoAnimationExtraPointers:
	dw MewtwoPlainAnimationExtra
	dw MewtwoArmoredAnimationExtra

RattataAnimationExtraPointers:
	dw RattataPlainAnimationExtra
	dw RattataAlolanAnimationExtra

RaticateAnimationExtraPointers:
	dw RaticatePlainAnimationExtra
	dw RaticateAlolanAnimationExtra

SandshrewAnimationExtraPointers:
	dw SandshrewPlainAnimationExtra
	dw SandshrewAlolanAnimationExtra

SandslashAnimationExtraPointers:
	dw SandslashPlainAnimationExtra
	dw SandslashAlolanAnimationExtra

VulpixAnimationExtraPointers:
	dw VulpixPlainAnimationExtra
	dw VulpixAlolanAnimationExtra

NinetalesAnimationExtraPointers:
	dw NinetalesPlainAnimationExtra
	dw NinetalesAlolanAnimationExtra

DiglettAnimationExtraPointers:
	dw DiglettPlainAnimationExtra
	dw DiglettAlolanAnimationExtra

DugtrioAnimationExtraPointers:
	dw DugtrioPlainAnimationExtra
	dw DugtrioAlolanAnimationExtra

MeowthAnimationExtraPointers:
	dw MeowthPlainAnimationExtra
	dw MeowthAlolanAnimationExtra

PersianAnimationExtraPointers:
	dw PersianPlainAnimationExtra
	dw PersianAlolanAnimationExtra

GeodudeAnimationExtraPointers:
	dw GeodudePlainAnimationExtra
	dw GeodudeAlolanAnimationExtra

GravelerAnimationExtraPointers:
	dw GravelerPlainAnimationExtra
	dw GravelerAlolanAnimationExtra

GolemAnimationExtraPointers:
	dw GolemPlainAnimationExtra
	dw GolemAlolanAnimationExtra

GrimerAnimationExtraPointers:
	dw GrimerPlainAnimationExtra
	dw GrimerAlolanAnimationExtra

MukAnimationExtraPointers:
	dw MukPlainAnimationExtra
	dw MukAlolanAnimationExtra

RaichuAnimationExtraPointers:
	dw RaichuPlainAnimationExtra
	dw RaichuAlolanAnimationExtra

ExeggutorAnimationExtraPointers:
	dw ExeggutorPlainAnimationExtra
	dw ExeggutorAlolanAnimationExtra

MarowakAnimationExtraPointers:
	dw MarowakPlainAnimationExtra
	dw MarowakAlolanAnimationExtra

PonytaAnimationExtraPointers:
	dw PonytaPlainAnimationExtra
	dw PonytaGalarianAnimationExtra

RapidashAnimationExtraPointers:
	dw RapidashPlainAnimationExtra
	dw RapidashGalarianAnimationExtra

WeezingAnimationExtraPointers:
	dw WeezingPlainAnimationExtra
	dw WeezingGalarianAnimationExtra
