UnownABitmasks: INCLUDE "gfx/pokemon/unown_a/bitmask.asm"
UnownBBitmasks: INCLUDE "gfx/pokemon/unown_b/bitmask.asm"
UnownCBitmasks: INCLUDE "gfx/pokemon/unown_c/bitmask.asm"
UnownDBitmasks: INCLUDE "gfx/pokemon/unown_d/bitmask.asm"
UnownEBitmasks: INCLUDE "gfx/pokemon/unown_e/bitmask.asm"
UnownFBitmasks: INCLUDE "gfx/pokemon/unown_f/bitmask.asm"
UnownGBitmasks: INCLUDE "gfx/pokemon/unown_g/bitmask.asm"
UnownHBitmasks: INCLUDE "gfx/pokemon/unown_h/bitmask.asm"
UnownIBitmasks: INCLUDE "gfx/pokemon/unown_i/bitmask.asm"
UnownJBitmasks: INCLUDE "gfx/pokemon/unown_j/bitmask.asm"
UnownKBitmasks: INCLUDE "gfx/pokemon/unown_k/bitmask.asm"
UnownLBitmasks: INCLUDE "gfx/pokemon/unown_l/bitmask.asm"
UnownMBitmasks: INCLUDE "gfx/pokemon/unown_m/bitmask.asm"
UnownNBitmasks: INCLUDE "gfx/pokemon/unown_n/bitmask.asm"
UnownOBitmasks: INCLUDE "gfx/pokemon/unown_o/bitmask.asm"
UnownPBitmasks: INCLUDE "gfx/pokemon/unown_p/bitmask.asm"
UnownQBitmasks: INCLUDE "gfx/pokemon/unown_q/bitmask.asm"
UnownRBitmasks: INCLUDE "gfx/pokemon/unown_r/bitmask.asm"
UnownSBitmasks: INCLUDE "gfx/pokemon/unown_s/bitmask.asm"
UnownTBitmasks: INCLUDE "gfx/pokemon/unown_t/bitmask.asm"
UnownUBitmasks: INCLUDE "gfx/pokemon/unown_u/bitmask.asm"
UnownVBitmasks: INCLUDE "gfx/pokemon/unown_v/bitmask.asm"
UnownWBitmasks: INCLUDE "gfx/pokemon/unown_w/bitmask.asm"
UnownXBitmasks: INCLUDE "gfx/pokemon/unown_x/bitmask.asm"
UnownYBitmasks: INCLUDE "gfx/pokemon/unown_y/bitmask.asm"
UnownZBitmasks: INCLUDE "gfx/pokemon/unown_z/bitmask.asm"
UnownExclamationBitmasks: INCLUDE "gfx/pokemon/unown_exclamation/bitmask.asm"
UnownQuestionBitmasks:    INCLUDE "gfx/pokemon/unown_question/bitmask.asm"

PikachuPlainBitmasks:  INCLUDE "gfx/pokemon/pikachu_plain/bitmask.asm"
PikachuFlyBitmasks:    INCLUDE "gfx/pokemon/pikachu_fly/bitmask.asm"
PikachuSurfBitmasks:   INCLUDE "gfx/pokemon/pikachu_surf/bitmask.asm"
PikachuPikaBitmasks:   INCLUDE "gfx/pokemon/pikachu_pika/bitmask.asm"
PikachuChuchuBitmasks: INCLUDE "gfx/pokemon/pikachu_chuchu/bitmask.asm"

PichuPlainBitmasks: INCLUDE "gfx/pokemon/pichu_plain/bitmask.asm"
PichuSpikyBitmasks: INCLUDE "gfx/pokemon/pichu_spiky/bitmask.asm"

ArbokJohtoBitmasks:  INCLUDE "gfx/pokemon/arbok_johto/bitmask.asm"
ArbokKantoBitmasks:  INCLUDE "gfx/pokemon/arbok_kanto/bitmask.asm"
ArbokKogaBitmasks:   INCLUDE "gfx/pokemon/arbok_koga/bitmask.asm"
ArbokAgathaBitmasks: INCLUDE "gfx/pokemon/arbok_agatha/bitmask.asm"
ArbokArianaBitmasks: INCLUDE "gfx/pokemon/arbok_ariana/bitmask.asm"

MagikarpPlainBitmasks:    INCLUDE "gfx/pokemon/magikarp_plain/bitmask.asm"
MagikarpSkellyBitmasks:   INCLUDE "gfx/pokemon/magikarp_skelly/bitmask.asm"
MagikarpCalico1Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico1/bitmask.asm"
MagikarpCalico2Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico2/bitmask.asm"
MagikarpCalico3Bitmasks:  INCLUDE "gfx/pokemon/magikarp_calico3/bitmask.asm"
MagikarpTwoToneBitmasks:  INCLUDE "gfx/pokemon/magikarp_twotone/bitmask.asm"
MagikarpOrcaBitmasks:     INCLUDE "gfx/pokemon/magikarp_orca/bitmask.asm"
MagikarpDapplesBitmasks:  INCLUDE "gfx/pokemon/magikarp_dapples/bitmask.asm"
MagikarpTigerBitmasks:    INCLUDE "gfx/pokemon/magikarp_tiger/bitmask.asm"
MagikarpZebraBitmasks:    INCLUDE "gfx/pokemon/magikarp_zebra/bitmask.asm"
MagikarpStripeBitmasks:   INCLUDE "gfx/pokemon/magikarp_stripe/bitmask.asm"
MagikarpBubblesBitmasks:  INCLUDE "gfx/pokemon/magikarp_bubbles/bitmask.asm"
MagikarpForeheadBitmasks: INCLUDE "gfx/pokemon/magikarp_forehead/bitmask.asm"
MagikarpMaskBitmasks:     INCLUDE "gfx/pokemon/magikarp_mask/bitmask.asm"

GyaradosPlainBitmasks: INCLUDE "gfx/pokemon/gyarados_plain/bitmask.asm"
GyaradosRedBitmasks:   INCLUDE "gfx/pokemon/gyarados_red/bitmask.asm"

MewtwoPlainBitmasks:   INCLUDE "gfx/pokemon/mewtwo_plain/bitmask.asm"
MewtwoArmoredBitmasks: INCLUDE "gfx/pokemon/mewtwo_armored/bitmask.asm"
