; Control characters
	charmap "<START>",  $00
	charmap "<DAY>",    $15
	charmap "¯",        $1f
	charmap "<LNBRK>",  $22
	charmap "<POKE>",   $24
	charmap "%",        $25
	charmap "<ENEMY>",  $3f
	charmap "<PKMN>",   $4a
	charmap "<NEXT>",   $4e
	charmap "<LINE>",   $4f

	charmap "@",        $50
	charmap "<PARA>",   $51
	charmap "<PLAYER>", $52
	charmap "<RIVAL>",  $53
	charmap "#",        $54
	charmap "<CONT>",   $55
	charmap "<......>", $56
	charmap "<DONE>",   $57
	charmap "<PROMPT>", $58
	charmap "<TARGET>", $59
	charmap "<USER>",   $5a
	charmap "<PC>",     $5b
	charmap "<TM>",     $5c
	charmap "<TRNER>",  $5d
	charmap "<ROCKET>", $5e
	charmap "<DEXEND>", $5f

; Actual characters
	charmap "┌",        $79
	charmap "─",        $7a
	charmap "┐",        $7b
	charmap "│",        $7c
	charmap "└",        $7d
	charmap "┘",        $7e
	charmap " ",        $7f

	charmap "A",        $80
	charmap "B",        $81
	charmap "C",        $82
	charmap "D",        $83
	charmap "E",        $84
	charmap "F",        $85
	charmap "G",        $86
	charmap "H",        $87
	charmap "I",        $88
	charmap "J",        $89
	charmap "K",        $8a
	charmap "L",        $8b
	charmap "M",        $8c
	charmap "N",        $8d
	charmap "O",        $8e
	charmap "P",        $8f
	charmap "Q",        $90
	charmap "R",        $91
	charmap "S",        $92
	charmap "T",        $93
	charmap "U",        $94
	charmap "V",        $95
	charmap "W",        $96
	charmap "X",        $97
	charmap "Y",        $98
	charmap "Z",        $99

	charmap "(",        $9a
	charmap ")",        $9b
	charmap ":",        $9c
	charmap ";",        $9d
	charmap "[",        $9e
	charmap "]",        $9f

	charmap "a",        $a0
	charmap "b",        $a1
	charmap "c",        $a2
	charmap "d",        $a3
	charmap "e",        $a4
	charmap "f",        $a5
	charmap "g",        $a6
	charmap "h",        $a7
	charmap "i",        $a8
	charmap "j",        $a9
	charmap "k",        $aa
	charmap "l",        $ab
	charmap "m",        $ac
	charmap "n",        $ad
	charmap "o",        $ae
	charmap "p",        $af
	charmap "q",        $b0
	charmap "r",        $b1
	charmap "s",        $b2
	charmap "t",        $b3
	charmap "u",        $b4
	charmap "v",        $b5
	charmap "w",        $b6
	charmap "x",        $b7
	charmap "y",        $b8
	charmap "z",        $b9

; unused: ba-bf

	charmap "<PO>",     $c0
	charmap "<KE>",     $c1
	charmap "<``>",     $c2
	charmap "<''>",     $c3
	charmap "<LV>",     $c4
	charmap "…",        $c5
	charmap "<SHINY>",  $c6
	charmap "<PCT>",    $c7
	charmap "<BALL>",   $c8
	charmap "<NONO>",   $c9

; unused: ca-cf

	charmap "'d",       $d0
	charmap "'l",       $d1
	charmap "'m",       $d2
	charmap "'r",       $d3
	charmap "'s",       $d4
	charmap "'t",       $d5
	charmap "'v",       $d6

	charmap "_",        $d7
	charmap "<ID>",     $d8
	charmap "№",        $d9
	charmap "′",        $da
	charmap "″",        $db
	charmap "<BOLDP>",  $dc
	charmap "↑",        $dd
	charmap "↓",        $de
	charmap "←",        $df
	charmap "'",        $e0
	charmap "<PK>",     $e1
	charmap "<MN>",     $e2
	charmap "-",        $e3
	charmap "◀",        $e4
	charmap "▲",        $e5
	charmap "?",        $e6
	charmap "!",        $e7
	charmap ".",        $e8
	charmap "&",        $e9
	charmap "é",        $ea
	charmap "→",        $eb
	charmap "▷",        $ec
	charmap "▶",        $ed
	charmap "▼",        $ee
	charmap "♂",        $ef
	charmap "¥",        $f0
	charmap "×",        $f1
	charmap "·",        $f2
	charmap "/",        $f3
	charmap ",",        $f4
	charmap "♀",        $f5

	charmap "0",        $f6
	charmap "1",        $f7
	charmap "2",        $f8
	charmap "3",        $f9
	charmap "4",        $fa
	charmap "5",        $fb
	charmap "6",        $fc
	charmap "7",        $fd
	charmap "8",        $fe
	charmap "9",        $ff
