RGB_MONOCHROME_WHITE EQUS "dw PAL_MONOCHROME_WHITE"
RGB_MONOCHROME_LIGHT EQUS "dw PAL_MONOCHROME_LIGHT"
RGB_MONOCHROME_DARK  EQUS "dw PAL_MONOCHROME_DARK"
RGB_MONOCHROME_BLACK EQUS "dw PAL_MONOCHROME_BLACK"

PAL_MONOCHROME_WHITE EQU (palred 28 + palgreen 31 + palblue 26)
PAL_MONOCHROME_LIGHT EQU (palred 17 + palgreen 24 + palblue 14)
PAL_MONOCHROME_DARK  EQU (palred 06 + palgreen 13 + palblue 10)
PAL_MONOCHROME_BLACK EQU (palred 01 + palgreen 03 + palblue 04)


MACRO MONOCHROME_RGB_FOUR
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_EVE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_NIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_DARKNESS
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_OW
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_WHITE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_OW_NIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_FOUR_OW_DARKNESS
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_BLACK
	RGB_MONOCHROME_BLACK
ENDM

MACRO MONOCHROME_RGB_TWO
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
ENDM

MACRO MONOCHROME_RGB_TWO_NIGHT
	RGB_MONOCHROME_DARK
	RGB_MONOCHROME_DARK
ENDM

MACRO MONOCHROME_RGB_TWO_EVE
	RGB_MONOCHROME_LIGHT
	RGB_MONOCHROME_DARK
ENDM
