command: macro
	enum \1_command
\1 equs "db \1_command"
endm

	enum_start 1

	command checkturn               ; 01
	command checkobedience          ; 02
	command usedmovetext            ; 03
	command doturn                  ; 04
	command critical                ; 05
	command damagestats             ; 06
	command stab                    ; 07
	command damagevariation         ; 08
	command checkhit                ; 09
	command lowersub                ; 0a
	command hittargetnosub          ; 0b
	command raisesub                ; 0c
	command failuretext             ; 0d
	command checkfaint              ; 0e
	command criticaltext            ; 0f
	command supereffectivetext      ; 10
	command checkdestinybond        ; 11
	command buildopponentrage       ; 12
	command poisontarget            ; 13
	command sleeptarget             ; 14
	command draintarget             ; 15
	command eatdream                ; 16
	command burntarget              ; 17
	command freezetarget            ; 18
	command paralyzetarget          ; 19
	command selfdestruct            ; 1a
	command mirrormove              ; 1b
	command statup                  ; 1c
	command statdown                ; 1d
	command payday                  ; 1e
	command conversion              ; 1f
	command resetstats              ; 20
	command storeenergy             ; 21
	command unleashenergy           ; 22
	command forceswitch             ; 23
	command endloop                 ; 24
	command flinchtarget            ; 25
	command ohko                    ; 26
	command recoil                  ; 27
	command mist                    ; 28
	command focusenergy             ; 29
	command confuse                 ; 2a
	command confusetarget           ; 2b
	command heal                    ; 2c
	command transform               ; 2d
	command screen                  ; 2e
	command poison                  ; 2f
	command paralyze                ; 30
	command substitute              ; 31
	command rechargenextturn        ; 32
	command mimic                   ; 33
	command metronome               ; 34
	command leechseed               ; 35
	command splash                  ; 36
	command disable                 ; 37
	command cleartext               ; 38
	command charge                  ; 39
	command checkcharge             ; 3a
	command traptarget              ; 3b
	command growth                  ; 3c
	command rampage                 ; 3d
	command checkrampage            ; 3e
	command constantdamage          ; 3f
	command counter                 ; 40
	command encore                  ; 41
	command painsplit               ; 42
	command snore                   ; 43
	command conversion2             ; 44
	command lockon                  ; 45
	command sketch                  ; 46
	command defrostopponent         ; 47
	command sleeptalk               ; 48
	command destinybond             ; 49
	command spite                   ; 4a
	command falseswipe              ; 4b
	command healbell                ; 4c
	command kingsrock               ; 4d
	command triplekick              ; 4e
	command kickcounter             ; 4f
	command thief                   ; 50
	command arenatrap               ; 51
	command nightmare               ; 52
	command defrost                 ; 53
	command curse                   ; 54
	command protect                 ; 55
	command spikes                  ; 56
	command foresight               ; 57
	command perishsong              ; 58
	command startsandstorm          ; 59
	command endure                  ; 5a
	command checkcurl               ; 5b
	command rolloutpower            ; 5c
	command bulkup                  ; 5d
	command furycutter              ; 5e
	command attract                 ; 5f
	command happinesspower          ; 60
	command present                 ; 61
	command damagecalc              ; 62
	command frustrationpower        ; 63
	command safeguard               ; 64
	command checksafeguard          ; 65
	command getmagnitude            ; 66
	command batonpass               ; 67
	command pursuit                 ; 68
	command clearhazards            ; 69
	command healmornorday           ; 6a
	command healnite                ; 6b
	command hiddenpower             ; 6c
	command startrain               ; 6d
	command startsun                ; 6e
	command attackup                ; 6f
	command defenseup               ; 70
	command speedup                 ; 71
	command specialattackup         ; 72
	command specialdefenseup        ; 73
	command accuracyup              ; 74
	command evasionup               ; 75
	command attackup2               ; 76
	command defenseup2              ; 77
	command speedup2                ; 78
	command specialattackup2        ; 79
	command specialdefenseup2       ; 7a
	command accuracyup2             ; 7b
	command evasionup2              ; 7c
	command attackdown              ; 7d
	command defensedown             ; 7e
	command speeddown               ; 7f
	command specialattackdown       ; 80
	command specialdefensedown      ; 81
	command accuracydown            ; 82
	command evasiondown             ; 83
	command attackdown2             ; 84
	command defensedown2            ; 85
	command speeddown2              ; 86
	command specialattackdown2      ; 87
	command specialdefensedown2     ; 88
	command accuracydown2           ; 89
	command evasiondown2            ; 8a
	command statupmessage           ; 8b
	command statdownmessage         ; 8c
	command statupfailtext          ; 8d
	command statdownfailtext        ; 8e
	command effectchance            ; 8f
	command statdownanim            ; 90
	command statupanim              ; 91
	command switchturn              ; 92
	command bellydrum               ; 93
	command psychup                 ; 94
	command rage                    ; 95
	command doubleflyingdamage      ; 96
	command doubleundergrounddamage ; 97
	command mirrorcoat              ; 98
	command checkfuturesight        ; 99
	command futuresight             ; 9a
	command doubleminimizedamage    ; 9b
	command skipsuncharge           ; 9c
	command thunderaccuracy         ; 9d
	command teleport                ; 9e
	command beatup                  ; 9f
	command ragedamage              ; a0
	command resettypematchup        ; a1
	command allstatsup              ; a2
	command calmmind                ; a3
	command raisesubnoanim          ; a4
	command lowersubnoanim          ; a5
	command dragondance             ; a6
	command clearmissdamage         ; a7
	command movedelay               ; a8
	command hittarget               ; a9
	command tristatuschance         ; aa
	command supereffectivelooptext  ; ab
	command startloop               ; ac
	command curl                    ; ad
	command burn                    ; ae
	command hex                     ; af

	enum_start -1, -1
	command endmove
	command endturn
