INCLUDE "includes.asm"


SECTION "Overworld Sprites 1", ROMX

ChrisSpriteGFX::               INCBIN "gfx/overworld/chris.2bpp"
ChrisBikeSpriteGFX::           INCBIN "gfx/overworld/chris_bike.2bpp"
GameboyKidSpriteGFX::          INCBIN "gfx/overworld/gameboy_kid.2bpp"
SilverSpriteGFX::              INCBIN "gfx/overworld/silver.2bpp"
OakSpriteGFX::                 INCBIN "gfx/overworld/oak.2bpp"
RedSpriteGFX::                 INCBIN "gfx/overworld/red.2bpp"
BlueSpriteGFX::                INCBIN "gfx/overworld/blue.2bpp"
BillSpriteGFX::                INCBIN "gfx/overworld/bill.2bpp"
ElderSpriteGFX::               INCBIN "gfx/overworld/elder.2bpp"
JanineSpriteGFX::              INCBIN "gfx/overworld/janine.2bpp"
KurtSpriteGFX::                INCBIN "gfx/overworld/kurt.2bpp"
MomSpriteGFX::                 INCBIN "gfx/overworld/mom.2bpp"
BlaineSpriteGFX::              INCBIN "gfx/overworld/blaine.2bpp"
RedsMomSpriteGFX::             INCBIN "gfx/overworld/reds_mom.2bpp"
DaisySpriteGFX::               INCBIN "gfx/overworld/daisy.2bpp"
ElmSpriteGFX::                 INCBIN "gfx/overworld/elm.2bpp"
WillSpriteGFX::                INCBIN "gfx/overworld/will.2bpp"
FalknerSpriteGFX::             INCBIN "gfx/overworld/falkner.2bpp"
WhitneySpriteGFX::             INCBIN "gfx/overworld/whitney.2bpp"
BugsySpriteGFX::               INCBIN "gfx/overworld/bugsy.2bpp"
MortySpriteGFX::               INCBIN "gfx/overworld/morty.2bpp"
ChuckSpriteGFX::               INCBIN "gfx/overworld/chuck.2bpp"
JasmineSpriteGFX::             INCBIN "gfx/overworld/jasmine.2bpp"
PryceSpriteGFX::               INCBIN "gfx/overworld/pryce.2bpp"
ClairSpriteGFX::               INCBIN "gfx/overworld/clair.2bpp"
BrockSpriteGFX::               INCBIN "gfx/overworld/brock.2bpp"
KarenSpriteGFX::               INCBIN "gfx/overworld/karen.2bpp"
BrunoSpriteGFX::               INCBIN "gfx/overworld/bruno.2bpp"
MistySpriteGFX::               INCBIN "gfx/overworld/misty.2bpp"
LanceSpriteGFX::               INCBIN "gfx/overworld/lance.2bpp"
SurgeSpriteGFX::               INCBIN "gfx/overworld/surge.2bpp"
ErikaSpriteGFX::               INCBIN "gfx/overworld/erika.2bpp"
KogaSpriteGFX::                INCBIN "gfx/overworld/koga.2bpp"
SabrinaSpriteGFX::             INCBIN "gfx/overworld/sabrina.2bpp"
CooltrainerMSpriteGFX::        INCBIN "gfx/overworld/cooltrainer_m.2bpp"
CooltrainerFSpriteGFX::        INCBIN "gfx/overworld/cooltrainer_f.2bpp"
BugCatcherSpriteGFX::          INCBIN "gfx/overworld/bug_catcher.2bpp"
TwinSpriteGFX::                INCBIN "gfx/overworld/twin.2bpp"
YoungsterSpriteGFX::           INCBIN "gfx/overworld/youngster.2bpp"
LassSpriteGFX::                INCBIN "gfx/overworld/lass.2bpp"
TeacherSpriteGFX::             INCBIN "gfx/overworld/teacher.2bpp"
BuenaSpriteGFX::               INCBIN "gfx/overworld/buena.2bpp"
SuperNerdSpriteGFX::           INCBIN "gfx/overworld/super_nerd.2bpp"
RockerSpriteGFX::              INCBIN "gfx/overworld/rocker.2bpp"


SECTION "Overworld Sprites 2", ROMX

PokefanMSpriteGFX::            INCBIN "gfx/overworld/pokefan_m.2bpp"
PokefanFSpriteGFX::            INCBIN "gfx/overworld/pokefan_f.2bpp"
GrampsSpriteGFX::              INCBIN "gfx/overworld/gramps.2bpp"
GrannySpriteGFX::              INCBIN "gfx/overworld/granny.2bpp"
SwimmerGuySpriteGFX::          INCBIN "gfx/overworld/swimmer_m.2bpp"
SwimmerGirlSpriteGFX::         INCBIN "gfx/overworld/swimmer_f.2bpp"
BigSnorlaxSpriteGFX::          INCBIN "gfx/overworld/big_snorlax.2bpp"
SurfingPikachuSpriteGFX::      INCBIN "gfx/overworld/surf_pikachu.2bpp"
RocketSpriteGFX::              INCBIN "gfx/overworld/rocket.2bpp"
RocketGirlSpriteGFX::          INCBIN "gfx/overworld/rocket_girl.2bpp"
BowingNurseSpriteGFX::         INCBIN "gfx/overworld/bowing_nurse.2bpp"
LinkReceptionistSpriteGFX::    INCBIN "gfx/overworld/link_receptionist.2bpp"
ClerkSpriteGFX::               INCBIN "gfx/overworld/clerk.2bpp"
FisherSpriteGFX::              INCBIN "gfx/overworld/fisher.2bpp"
FishingGuruSpriteGFX::         INCBIN "gfx/overworld/fishing_guru.2bpp"
ScientistSpriteGFX::           INCBIN "gfx/overworld/scientist.2bpp"
KimonoGirlSpriteGFX::          INCBIN "gfx/overworld/kimono_girl.2bpp"
SageSpriteGFX::                INCBIN "gfx/overworld/sage.2bpp"
DadSpriteGFX::                 INCBIN "gfx/overworld/dad.2bpp"
GentlemanSpriteGFX::           INCBIN "gfx/overworld/gentleman.2bpp"
BlackBeltSpriteGFX::           INCBIN "gfx/overworld/black_belt.2bpp"
ReceptionistSpriteGFX::        INCBIN "gfx/overworld/receptionist.2bpp"
OfficerSpriteGFX::             INCBIN "gfx/overworld/officer.2bpp"
CaptainSpriteGFX::             INCBIN "gfx/overworld/captain.2bpp"
BigLaprasSpriteGFX::           INCBIN "gfx/overworld/big_lapras.2bpp"
GymGuySpriteGFX::              INCBIN "gfx/overworld/gym_guy.2bpp"
SailorSpriteGFX::              INCBIN "gfx/overworld/sailor.2bpp"
BikerSpriteGFX::               INCBIN "gfx/overworld/biker.2bpp"
PharmacistSpriteGFX::          INCBIN "gfx/overworld/pharmacist.2bpp"
ClefairyWalkSpriteGFX::        INCBIN "gfx/overworld/clefairy.2bpp"
FarfetchDSpriteGFX::           INCBIN "gfx/overworld/farfetch_d.2bpp"
DragoniteSpriteGFX::           INCBIN "gfx/overworld/dragonite.2bpp"
BigOnixSpriteGFX::             INCBIN "gfx/overworld/big_onix.2bpp"
LaprasSpriteGFX::              INCBIN "gfx/overworld/lapras.2bpp"
SnesSpriteGFX::                INCBIN "gfx/overworld/snes.2bpp"
N64SpriteGFX::                 INCBIN "gfx/overworld/n64.2bpp"
GameCubeSpriteGFX::            INCBIN "gfx/overworld/gamecube.2bpp"
WiiSpriteGFX::                 INCBIN "gfx/overworld/wii.2bpp"
GoldTrophySpriteGFX::          INCBIN "gfx/overworld/gold_trophy.2bpp"
SilverTrophySpriteGFX::        INCBIN "gfx/overworld/silver_trophy.2bpp"
KrisSpriteGFX::                INCBIN "gfx/overworld/kris.2bpp"
KrisBikeSpriteGFX::            INCBIN "gfx/overworld/kris_bike.2bpp"
ChrisSurfSpriteGFX::           INCBIN "gfx/overworld/chris_surf.2bpp"
KrisSurfSpriteGFX::            INCBIN "gfx/overworld/kris_surf.2bpp"
BallCutFruitSpriteGFX::        INCBIN "gfx/overworld/ball_cut_fruit.2bpp"
BoulderRockFossilSpriteGFX::   INCBIN "gfx/overworld/boulder_rock_fossil.2bpp"
BookPaperPokedexSpriteGFX::    INCBIN "gfx/overworld/book_paper_pokedex.2bpp"


SECTION "Overworld Sprites 3", ROMX

AgathaSpriteGFX::              INCBIN "gfx/overworld/agatha.2bpp"
AnabelSpriteGFX::              INCBIN "gfx/overworld/anabel.2bpp"
AndySpriteGFX::                INCBIN "gfx/overworld/andy.2bpp"
ArcherSpriteGFX::              INCBIN "gfx/overworld/archer.2bpp"
ArianaSpriteGFX::              INCBIN "gfx/overworld/ariana.2bpp"
BlancheSpriteGFX::             INCBIN "gfx/overworld/blanche.2bpp"
BuckSpriteGFX::                INCBIN "gfx/overworld/buck.2bpp"
CaitlinSpriteGFX::             INCBIN "gfx/overworld/caitlin.2bpp"
CandelaSpriteGFX::             INCBIN "gfx/overworld/candela.2bpp"
CherylSpriteGFX::              INCBIN "gfx/overworld/cheryl.2bpp"
CynthiaSpriteGFX::             INCBIN "gfx/overworld/cynthia.2bpp"
DarachSpriteGFX::              INCBIN "gfx/overworld/darach.2bpp"
EusineSpriteGFX::              INCBIN "gfx/overworld/eusine.2bpp"
FlannerySpriteGFX::            INCBIN "gfx/overworld/flannery.2bpp"
GiovanniSpriteGFX::            INCBIN "gfx/overworld/giovanni.2bpp"
ImakuniSpriteGFX::             INCBIN "gfx/overworld/imakuni.2bpp"
IvySpriteGFX::                 INCBIN "gfx/overworld/ivy.2bpp"
JamesSpriteGFX::               INCBIN "gfx/overworld/james.2bpp"
JessieSpriteGFX::              INCBIN "gfx/overworld/jessie.2bpp"
LawrenceSpriteGFX::            INCBIN "gfx/overworld/lawrence.2bpp"
LeafSpriteGFX::                INCBIN "gfx/overworld/leaf.2bpp"
LoreleiSpriteGFX::             INCBIN "gfx/overworld/lorelei.2bpp"
LyraSpriteGFX::                INCBIN "gfx/overworld/lyra.2bpp"
MarleySpriteGFX::              INCBIN "gfx/overworld/marley.2bpp"
MatsumotoSpriteGFX::           INCBIN "gfx/overworld/matsumoto.2bpp"
MayleneSpriteGFX::             INCBIN "gfx/overworld/maylene.2bpp"
MiraSpriteGFX::                INCBIN "gfx/overworld/mira.2bpp"
PalmerSpriteGFX::              INCBIN "gfx/overworld/palmer.2bpp"
PetrelSpriteGFX::              INCBIN "gfx/overworld/petrel.2bpp"
ProtonSpriteGFX::              INCBIN "gfx/overworld/proton.2bpp"
RileySpriteGFX::               INCBIN "gfx/overworld/riley.2bpp"


SECTION "Overworld Sprites 4", ROMX

ArtistSpriteGFX::              INCBIN "gfx/overworld/artist.2bpp"
BakerSpriteGFX::               INCBIN "gfx/overworld/baker.2bpp"
BeautySpriteGFX::              INCBIN "gfx/overworld/beauty.2bpp"
BoarderSpriteGFX::             INCBIN "gfx/overworld/boarder.2bpp"
BreederSpriteGFX::             INCBIN "gfx/overworld/breeder.2bpp"
BugManiacSpriteGFX::           INCBIN "gfx/overworld/bug_maniac.2bpp"
ChildSpriteGFX::               INCBIN "gfx/overworld/child.2bpp"
CosplayerSpriteGFX::           INCBIN "gfx/overworld/cosplayer.2bpp"
CowgirlSpriteGFX::             INCBIN "gfx/overworld/cowgirl.2bpp"
DragonTamerSpriteGFX::         INCBIN "gfx/overworld/dragon_tamer.2bpp"
EngineerSpriteGFX::            INCBIN "gfx/overworld/engineer.2bpp"
HexManiacSpriteGFX::           INCBIN "gfx/overworld/hex_maniac.2bpp"
LadySpriteGFX::                INCBIN "gfx/overworld/lady.2bpp"
OfficerFSpriteGFX::            INCBIN "gfx/overworld/officer_f.2bpp"
RichBoySpriteGFX::             INCBIN "gfx/overworld/rich_boy.2bpp"
SilphEmployeeSpriteGFX::       INCBIN "gfx/overworld/silph_employee.2bpp"
SwimmingOfficerFSpriteGFX::    INCBIN "gfx/overworld/swimming_officer_f.2bpp"
SwimmingOfficerSpriteGFX::     INCBIN "gfx/overworld/swimming_officer.2bpp"
ArmoredMewtwoSpriteGFX::       INCBIN "gfx/overworld/armored_mewtwo.2bpp"
CelebiSpriteGFX::              INCBIN "gfx/overworld/celebi.2bpp"
EeveeSpriteGFX::               INCBIN "gfx/overworld/eevee.2bpp"
MewSpriteGFX::                 INCBIN "gfx/overworld/mew.2bpp"
BigGyaradosSpriteGFX::         INCBIN "gfx/overworld/big_gyarados.2bpp"
SlowpoketailSpriteGFX::        INCBIN "gfx/overworld/slowpoketail.2bpp"
WeirdTreeSpriteGFX::           INCBIN "gfx/overworld/weird_tree.2bpp"


SECTION "Overworld Sprites 5", ROMX

NurseSpriteGFX::               INCBIN "gfx/overworld/nurse.2bpp"
PISpriteGFX::                  INCBIN "gfx/overworld/pi.2bpp"
RoughneckSpriteGFX::           INCBIN "gfx/overworld/roughneck.2bpp"
SightseerMSpriteGFX::          INCBIN "gfx/overworld/sightseer_m.2bpp"
SkierSpriteGFX::               INCBIN "gfx/overworld/skier.2bpp"
SkylaSpriteGFX::               INCBIN "gfx/overworld/skyla.2bpp"
SparkSpriteGFX::               INCBIN "gfx/overworld/spark.2bpp"
StevenSpriteGFX::              INCBIN "gfx/overworld/steven.2bpp"
ValerieSpriteGFX::             INCBIN "gfx/overworld/valerie.2bpp"
KukuiSpriteGFX::               INCBIN "gfx/overworld/kukui.2bpp"
VeteranFSpriteGFX::            INCBIN "gfx/overworld/veteran_f.2bpp"
VeteranMSpriteGFX::            INCBIN "gfx/overworld/veteran_m.2bpp"
WalkerSpriteGFX::              INCBIN "gfx/overworld/walker.2bpp"
WestwoodSpriteGFX::            INCBIN "gfx/overworld/westwood.2bpp"
WillowSpriteGFX::              INCBIN "gfx/overworld/willow.2bpp"
YellowSpriteGFX::              INCBIN "gfx/overworld/yellow.2bpp"
ElectricFenceLeftSpriteGFX::   INCBIN "gfx/overworld/electric_fence_left.2bpp"
ElectricFenceRightSpriteGFX::  INCBIN "gfx/overworld/electric_fence_right.2bpp"
BlankSpriteGFX::               INCBIN "gfx/overworld/blank.2bpp"
