	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Rival@"
	db "#mon Prof.@"
	db "Elite Four@"
	db "<PKMN> Trainer@"
	db "Elite Four@"
	db "Elite Four@"
	db "Elite Four@"
	db "Champion@"
	db "Leader@"
	db "Leader@"
	db "Leader@"
	db "Scientist@"
	db "Leader@"
	db "Youngster@"
	db "Schoolboy@"
	db "Bird Keeper@"
	db "Lass@"
	db "Leader@"
	db "Ace Trainer@"
	db "Ace Trainer@"
	db "Beauty@"
	db "#Maniac@"
	db "Rocket@"
	db "Gentleman@"
	db "Skier@"
	db "Teacher@"
	db "Leader@"
	db "Bug Catcher@"
	db "Fisher@"
	db "Swimmer♂@"
	db "Swimmer♀@"
	db "Sailor@"
	db "Super Nerd@"
	db "Rival@"
	db "Guitarist@"
	db "Hiker@"
	db "Biker@"
	db "Leader@"
	db "Burglar@"
	db "Firebreather@"
	db "Juggler@"
	db "Black Belt@"
	db "Rocket@"
	db "Psychic@"
	db "Picnicker@"
	db "Camper@"
	db "Rocket@"
	db "Sage@"
	db "Medium@"
	db "Boarder@"
	db "#fan@"
	db "Kimono Girl@"
	db "Twins@"
	db "#fan@"
	db "<PKMN> Trainer@"
	db "Leader@"
	db "Officer@"
	db "Rocket@"
	db "Mystery Man@"
	db "Elder@"
	db "Rocket@"